### ISSUE TITLE
请问考虑兼容TDengine吗？

### ISSUE THREAD

**Issue by Aigoss** [ccfos/nightingale#1000]
请问考虑兼容TDengine吗？

**Comment by UlricQin** [comment]
从两个方面来看：

- 写：夜莺收到时序数据写到后端时序库，走的prometheus的remote write协议，TDEngine好像支持这个协议，所以，数据是可以写给TDEngine的
- 读，夜莺从时序库读取数据，走的是prometheus的querier接口，就是那些`/api/v1/query` `/api/v1/series`类的接口，没有这些接口就没法绘图。如果不支持这些接口，至少也要兼容支持 `/api/v1/query`接口，这样至少能配置报警

综上，不太清楚TDEngine现在支持这些prometheus协议的接口支持到了什么程度了，夜莺目前不会去适配其他时序库的接口协议
