### ISSUE TITLE
告警邮件通知 failed to close smtp connection

### ISSUE THREAD

**Issue by FengZh61** [ccfos/nightingale#1002]
版本

前端版本：5.5.1
后端版本：5.9.3

邮箱配置
![image](https://user-images.githubusercontent.com/98309003/176333348-ed2aef7f-00b4-4bc3-b9ae-f77e8cbc65e9.png)

InsecureSkipVerify = false 默认是true
为true的时候和为false的时候warnning情况一样

日志信息
![image](https://user-images.githubusercontent.com/98309003/176333511-8b53dc6f-e6bb-42fe-b683-7f7b8db1cd24.png)

告警邮箱可以正常接收到
![image](https://user-images.githubusercontent.com/98309003/176333615-be6d79c2-4952-4c16-ba55-fb705bb499d9.png)

**Comment by UlricQin** [comment]
不用关注，能正常收邮件就行
