### ISSUE TITLE
活跃告警聚合规则使用问题

### ISSUE THREAD

**Issue by FengZh61** [ccfos/nightingale#1005]
前端版本：5.5.1
后端版本：5.9.3

第一个问题
![image](https://user-images.githubusercontent.com/98309003/176407525-bb2b6d04-dd37-4775-9ceb-4ee5c031aca5.png)
![image](https://user-images.githubusercontent.com/98309003/176407599-984613e1-2aef-4780-9db6-0f1a5698239d.png)
这时他会提示是否公开，逻辑上公开就打开，不公开就关上，然后我公开再不公开就正常创建了
![image](https://user-images.githubusercontent.com/98309003/176408010-75aa9201-5cd3-4bed-9e67-09f311b9d270.png)
建议优化下这个逻辑

第二个问题

![image](https://user-images.githubusercontent.com/98309003/176408228-b3a25367-a042-43fb-9df1-5e61aa536281.png)
![image](https://user-images.githubusercontent.com/98309003/176408308-17f41cbb-b190-4adf-b387-65d34cbfd67b.png)
我的__name__聚合规则添加上了，但是实际显示出来的是Null
![image](https://user-images.githubusercontent.com/98309003/176408582-298c7b94-945b-4c7b-b8e8-36f6bf54233a.png)
我编辑聚合规则，删除__name__ 标签，提示：unsupported field: __name__，这个很奇怪，有时候可以添加上标签，有时候又不可以。
我试了一下告警中其他的标签，也是同样的问题。

**Comment by UlricQin** [comment]
第一个问题可以优化一下，辛苦 @jsers 看看
第二个问题是你的用法问题，field只有有限的field可以被支持，还可以配置tagkey，比如这么写：`tagkey:__name__` 官方文档有个链接，是某个用户做的分享，可以看看：https://blog.csdn.net/woshi_1245/article/details/125218828

**Comment by FengZh61** [comment]
> 第一个问题可以优化一下，辛苦 @jsers 看看 第二个问题是你的用法问题，field只有有限的field可以被支持，还可以配置tagkey，比如这么写：`tagkey:__name__` 官方文档有个链接，是某个用户做的分享，可以看看：https://blog.csdn.net/woshi_1245/article/details/125218828
![image](https://user-images.githubusercontent.com/98309003/176571862-2b689e38-f6d6-4878-8d38-be6a73ef0ac0.png)
我在原来的规则上修改，已经改成tagkey了，保存的时候还是提示unsupported field: __name__，也辛苦看一下吧！

**Comment by UlricQin** [comment]
打开开发者工具，看请求发的payload是什么，后端返回的是什么

**Comment by FengZh61** [comment]
> 打开浏览器开发者工具，看请求发的payload是什么，后端返回的是什么



> 打开浏览器开发者工具，看请求发的payload是什么，后端返回的是什么
field:rule_name::tagkey:__name__  修改原来的规则再保存

Playload
{name: "test", id: 7, rule: "field:rule_name::tagkey:__name__", cate: 1}
cate: 1
id: 7
name: "test"
rule: "field:rule_name::tagkey:__name__"

response

{"err":"unsupported field: __name__"}


正常添加规则
Playload
{name: "umm1", id: 9, rule: "tagkey:hostname", cate: 1}
cate: 1
id: 9
name: "umm1"
rule: "tagkey:hostname"

response
{"err":""}

**Comment by FengZh61** [comment]
> > 打开浏览器开发者工具，看请求发的payload是什么，后端返回的是什么
> 
> > 打开浏览器开发者工具，看请求发的payload是什么，后端返回的是什么
> > field:rule_name::tagkey:**name**  修改原来的规则再保存
> 
> Playload {name: "test", id: 7, rule: "field:rule_name::tagkey:**name**", cate: 1} cate: 1 id: 7 name: "test" rule: "field:rule_name::tagkey:**name**"
> 
> response
> 
> {"err":"unsupported field: **name**"}
> 
> 正常添加规则 Playload {name: "umm1", id: 9, rule: "tagkey:hostname", cate: 1} cate: 1 id: 9 name: "umm1" rule: "tagkey:hostname"
> 
> response {"err":""}



> > 打开浏览器开发者工具，看请求发的payload是什么，后端返回的是什么
> 
> > 打开浏览器开发者工具，看请求发的payload是什么，后端返回的是什么
> > field:rule_name::tagkey:**name**  修改原来的规则再保存
> 
> Playload {name: "test", id: 7, rule: "field:rule_name::tagkey:**name**", cate: 1} cate: 1 id: 7 name: "test" rule: "field:rule_name::tagkey:**name**"
> 
> response
> 
> {"err":"unsupported field: **name**"}
> 
> 正常添加规则 Playload {name: "umm1", id: 9, rule: "tagkey:hostname", cate: 1} cate: 1 id: 9 name: "umm1" rule: "tagkey:hostname"
> 
> response {"err":""}
![Dingtalk_20220701100842](https://user-images.githubusercontent.com/98309003/176809429-79ba0085-52f1-4acb-996b-2bd0ca7348d1.jpg)
![Dingtalk_20220701100842](https://user-images.githubusercontent.com/98309003/176809429-79ba0085-52f1-4acb-996b-2bd0ca7348d1.jpg)

**Comment by UlricQin** [comment]
不符合预期，我回头看看代码

**Comment by UlricQin** [comment]
代码看了没问题，你是不是老版本？先升级一下吧
<img width="1512" alt="image" src="https://user-images.githubusercontent.com/2769466/176979915-648f212c-8d36-47fa-9c16-3a28c8db4239.png">

**Comment by UlricQin** [comment]
你把后端用main分支最新代码编译测试，前端 https://github.com/n9e/fe-v5/releases/tag/v5.6.0 用这个版本

**Comment by FengZh61** [comment]
> 



> 代码看了没问题，代码位置在这里：https://github.com/ccfos/nightingale/blob/main/src/models/alert_aggr_view.go#L65 ，你确定你用的5.9.3的后端么，是不是部署了多个实例，有的升级了有的没升级？
> 
> 我测试也没问题 <img alt="image" width="1512" src="https://user-images.githubusercontent.com/2769466/176979915-648f212c-8d36-47fa-9c16-3a28c8db4239.png">

部署的单个实例，前端版本：5.5.1，后端版本：5.9.3，我重新编译测试一下

**Comment by FengZh61** [comment]
> 你把后端用main分支最新代码编译测试，前端 https://github.com/n9e/fe-v5/releases/tag/v5.6.0 用这个版本

使用5.6.0前端，可以正常添加聚合规则，辛苦继续关注是否公开的逻辑问题~

**Comment by UlricQin** [comment]
公开的规则修改问题已修复
