### ISSUE TITLE
建议：监控大盘

### ISSUE THREAD

**Issue by bbaobelief** [ccfos/nightingale#1006]
**What would you like to be added**:
1.图表支持快速查看大图，现在虽然有个分享但是不够直观，建议在右上角新增个🔍
2.查看大图支持调整Legend，以前版本是可以单独调整的。
![image](https://user-images.githubusercontent.com/3918461/176619045-3dd91b66-be26-4714-b17b-ed56db163f09.png)

![image](https://user-images.githubusercontent.com/3918461/176618947-24e0ec95-0bce-4750-9675-c141467c4e1f.png)

**Comment by UlricQin** [comment]
去 github.com/n9e/fe-v5 提哈
