### ISSUE TITLE
prometheus exporter动态发现的配置管理

### ISSUE THREAD

**Issue by laijinhang** [ccfos/nightingale#1007]
**What would you like to be added**:
希望 夜莺页面中新增用于管理exporter信息（如ip、port、labels、采集时间：1s、15s、30s、60s等、属于哪个server的标识）的功能

webapi组件 给前端和第三方提供用于管理的接口
server组件 获取属于它的exporter列表的接口
prometheus通过配置http_sd_configs的url指向到对应server组件的接口，获取要采集的列表

**Why is this needed**:
方便prometheus exporter的管理，比如有机器上线和下线，能够自动对上线的进行采集，清理已下线的

**Comment by UlricQin** [comment]
短期没计划。欢迎提供设计方案和PR
