### ISSUE TITLE
支持动态阀值告警吗

### ISSUE THREAD

**Issue by joeluodongjiu** [ccfos/nightingale#1008]
目前一些开源的告警系统都太鸡肋了，一般只支持静态阀值告警，很容易产出误报，漏报的情况，不知道夜莺有考虑支持动态阀值告警吗

**Comment by UlricQin** [comment]
静态阈值为啥会漏报呢？

夜莺开源版本也不支持动态阈值，商业版本才支持，动态基线的方式，如果有兴趣可以联系我微信：18612185520，我们的官网：https://flashcat.cloud/

**Comment by joeluodongjiu** [comment]
您的邮件我已经收到啦，我会尽快查看的O(∩_∩)O~
