### ISSUE TITLE
关于导入grafana大盘后，切换视图类型的问题

### ISSUE THREAD

**Issue by FengZh61** [ccfos/nightingale#1009]
Grafana v8.2.5 (b57a137acd)

向夜莺导入window视图

因为视图不匹配，在夜莺显示的视图是unknow
编辑视图，切换视图类型
![image](https://user-images.githubusercontent.com/98309003/176851049-0e70e7e0-8eae-475f-be3c-fea9709331c3.png)
如果切换除蜂窝图以外的视图就会直接闪退关闭编辑页面
![image](https://user-images.githubusercontent.com/98309003/176851390-43075521-1081-458b-b87c-16653b048e7b.png)

如果先切换到蜂窝图，再切换到其他类型的视图，就不会闪退关闭编辑页面

**Comment by UlricQin** [comment]
@jsers 瞧瞧？

**Comment by jsers** [comment]
是一个 bug，可以先手动添加下，下个版本修复

ulricqin ***@***.***> 于2022年7月2日周六 07:51写道：

**Comment by jsers** [comment]
@FengZh61 @UlricQin 新版已经修复
