### ISSUE TITLE
告警规则不生效

### ISSUE THREAD

**Issue by sourceliex** [ccfos/nightingale#1010]
配置了钉钉告警， 但是不生效
1. 查看server.log没有任何日志输出
2. sql语句已验证过， 无任何异常
3. 出现的问题是， 不论怎么配置规则， 都不会进行触发

**Comment by sourceliex** [comment]
版本 v5.8.0, 二进制安装， docker安装 v5.9.0也是同样的情况。

**Comment by laijinhang** [comment]
server.log需要设置debug，设成debug，重启后看一下日志

**Comment by UlricQin** [comment]
n9e.github.io 通读教程
