### ISSUE TITLE
支持pushgateway接口

### ISSUE THREAD

**Issue by thislyc** [ccfos/nightingale#1011]
**What would you like to be added**:
是否考虑支持pushgateway接口
**Why is this needed**:
之前我看readme中有提到 有一个todo是支持pushgateway接口的，现在为什么取消了，如果支持的话，n9e可以直接替代现有的pushgateway不用再搭一个prometheus来pull了

**Comment by UlricQin** [comment]
没有遇到需求，你这边有这个场景么？来个PR？
