### ISSUE TITLE
WARNING writer/writer.go:43 example timeseries:labels:<name:"__name__" value:"target_up" >

### ISSUE THREAD

**Issue by FengZh61** [ccfos/nightingale#1020]
前端版本：5.6.0
后端版本：5.9.4

对接自建的Prometheus数据源，配置文件中均修改了read/write地址
自行在数据库target表中添加了监控对象，同时Prometheus也有对应的lable

![image](https://user-images.githubusercontent.com/98309003/177505301-4d152aef-782a-4315-a9a5-d977f7de4598.png)
按ident告警一切正常。

今天突然发现日志中有n9e server向Prometheus写数据的情况，我没有通过n9e server接收agent的数据，同时也没有agent上报，之前测试过categraf、grafana，均已停用。
正常情况下应该是agent上报给n9e server 然后server在写入时序数据库，没想明白哪里出问题了。

日志截图如下：
![image](https://user-images.githubusercontent.com/98309003/177506091-bc7734ab-3969-4499-9508-f3c782ef0037.png)

还有，请注意这个时间间隔是10s，我在配置文件中配置的Nodata间隔是30s，默认的配置，辛苦看下这个是正常现象吗？

**Comment by UlricQin** [comment]
n9e-server有个逻辑，就是会自动生成target_up指标，如果某个ident在频繁上报数据，就会设置target_up=1，如果某个ident不再上报数据了，target_up=0，你的这个场景，应该禁用这个行为，不过很遗憾，现在还没有办法做禁用。后面的版本可以考虑支持禁用。不过只是报错，不影响整体逻辑

**Comment by FengZh61** [comment]
> n9e-server有个逻辑，就是会自动生成target_up指标，如果某个ident在频繁上报数据，就会设置target_up=1，如果某个ident不再上报数据了，target_up=0，你的这个场景，应该禁用这个行为，不过很遗憾，现在还没有办法做禁用。后面的版本可以考虑支持禁用。不过只是报错，不影响整体逻辑

我把server.conf中的[[Writers]]注释了，这个写操作就没了，感谢解答~
