### ISSUE TITLE
告警屏蔽BUG

### ISSUE THREAD

**Issue by tripitakav** [ccfos/nightingale#1024]
![image](https://user-images.githubusercontent.com/73687556/177520707-ff16144d-967d-4798-b6ea-fbc8f3c657f7.png)
如图所示新建两个告警规则只是阀值和标题不同，当大于0的rule 触发后活跃告警里点击屏蔽后会造成大于1的告警无法生成
![image](https://user-images.githubusercontent.com/73687556/177520997-946034ba-c19c-4e5e-bb58-f5a61856a664.png)

建议增加前端屏蔽自动增加alertname label，后端mute的时候也传入event rule name
![image](https://user-images.githubusercontent.com/73687556/177521157-f4ef4057-693b-4c43-a369-a24962cf16fa.png)
![image](https://user-images.githubusercontent.com/73687556/177521245-d8ce46d0-353f-4235-8c79-60b574e76595.png)
#1025

**Comment by bbaobelief** [comment]
加告警规则的时候 自定义 **附加标签** 就行。

**Comment by 710leo** [comment]
> 加告警规则的时候 自定义 **附加标签** 就行。

+1
