### ISSUE TITLE
5.8 屏蔽事件问题

### ISSUE THREAD

**Issue by Ohimma** [ccfos/nightingale#1028]
### Relevant server.conf | webapi.conf

```toml
no
```

### Relevant logs

```text
no
```

### System info

CentOS Linux release 7.7.1908 (Core)、n9e-5.8.0

### Steps to reproduce

第一个问题：
1. 10:28 报警出现，用户点击屏蔽，进入屏蔽流程，屏蔽时间7天
2. 10:30 报警又出现，用户又开始屏蔽
3. 屏蔽住了
(有时要屏蔽两次，有时要屏蔽三次)

第二个问题：
1. 我是超级管理员，报警触发后进入事件详情页面
2. 点击屏蔽后，业务组默认选择了之前进入过屏蔽规则的业务组，而不是事件详情所在的业务组

### Expected behavior

第一个问题：
1. 期望屏蔽直接生效，不要重复点击屏蔽

第二个问题：
1. 希望把事件详情的业务组信息 带入到 屏蔽页面 

### Actual behavior

和预期行为相反

**Comment by 710leo** [comment]
感谢反馈：） 问题已修复，可以等下一个版本升级一下

**Comment by 710leo** [comment]
@Ohimma  刚才回复的是第二个问题，第一个问题辛苦提供下相关的截图吧

**Comment by UlricQin** [comment]
你的屏蔽规则配置了5个条件，但是告警事件里只有4个标签？

**Comment by Ohimma** [comment]
type==kvm只是在报警信息通知时被隐藏了，原始报警信息是有的

**Comment by UlricQin** [comment]
我review了一下代码，没有看到问题
