### ISSUE TITLE
116.85.64.82ip是否不再维护，下载不了以前的包了

### ISSUE THREAD

**Issue by jlbluluai** [ccfos/nightingale#1033]

**Comment by UlricQin** [comment]
是的，现在都是v5.9.5版本了，这个ip的包实在是太老了

**Comment by jlbluluai** [comment]
能否问一下 之前版本里的probe模块涉及的组件采集这些是不是已经没了 现在版本里似乎没有找到

**Comment by UlricQin** [comment]
新的采集器是 categraf ：https://github.com/flashcatcloud/categraf
