### ISSUE TITLE
夜莺告警模块是如何和通知脚本交互的？

### ISSUE THREAD

**Issue by tianchao001** [ccfos/nightingale#1037]
想问下，夜莺的告警通知调用逻辑是怎样的？ 看文档里说 script/notify.py 是用来做通知的，想进一步了解下   是否 自己重写这个脚本后，在页面配置飞书或者钉钉通知  就可以调用到这个脚本？ 如果重写，应该遵循什么规范来接受传参？

**Comment by 710leo** [comment]
可以看下 FAQ 第 24 个问题 https://www.gitlink.org.cn/ccfos/nightingale/wiki

**Comment by UlricQin** [comment]
https://n9e.github.io/docs/usage/notify/
