### ISSUE TITLE
夜莺V5怎么监控同名的不同进程

### ISSUE THREAD

**Issue by Quintonwong** [ccfos/nightingale#1040]
之前夜莺v3内置的进程监控是支持监控同名的不同进程，只要配置/proc/<pid>/cmdline的关键字就好。categraf的procstat插件可以监控进程，但区分同名的不同进程目前只有pid的方式，显示pid的方式对运维来说不太直观，v5还能有其他方法比较直观监控多个python或java进程吗

**Comment by UlricQin** [comment]
categraf也支持cmdline
