### ISSUE TITLE
recording_rule.go 193行,实际没有prod字段

### ISSUE THREAD

**Issue by shengjian-tech** [ccfos/nightingale#1048]
### Relevant server.conf | webapi.conf

```toml
-
```

### Relevant logs

```text
-
```

### System info

-

### Steps to reproduce

https://github.com/ccfos/nightingale/blob/main/src/models/recording_rule.go#L193
```session := DB().Where("disabled = ? and prod = ?", 0, "")```
数据库也没有 prod 字段

### Expected behavior

```session := DB().Where("disabled = ? and prod = ?", 0, "")```  
修改为
 ```session := DB().Where("disabled = ? ", 0)```

### Actual behavior

```session := DB().Where("disabled = ? and prod = ?", 0, "")```

**Comment by UlricQin** [comment]
3ks 已修改
