### ISSUE TITLE
open-faclon agent上报后的一些疑惑

### ISSUE THREAD

**Issue by chenginger** [ccfos/nightingale#1049]
公司之前使用open-faclon作为监控.现在接入夜莺.将open-faclon的数据通过transfer往夜莺写入.遇到如下问题
1、推送的数据在5分钟之内不会出现掉底.
openfalcon16:21未推送数据
![image](https://user-images.githubusercontent.com/42002616/178662259-022053d6-83e8-4ed3-a1ae-04a2f33a7879.png)
但是Prometheus沿用了上一个节点的数据
![image](https://user-images.githubusercontent.com/42002616/178662201-a531a7a0-f56a-4f5e-a4de-31ef332ea97a.png)

找到原因:
因为Prometheus瞬时向量机制:
如果是距离当前时间戳 1 个小时的数据直观看来肯定不能纳入到我们的返回结果里面。 所以 Prometheus 通过一个指定的时间窗口来过滤数据 (通过启动参数 --query.lookback-delta 指定，默认 5min)。
解决方式:
-query.lookback-delta设置为1mi.大盘图展示正常
导致问题:
因为每分钟上报导致监控监控很难触发.实时查询触发点不确定.

想问下是否有遇到这种问题.好像用remote write的方式才会有.如果export每分钟采集不会有该问题？

**Comment by UlricQin** [comment]
应该都会遇到这个问题，不管是remote write还是exporter。因为在prometheus的生态里，监控数据上报是没有固定的interval的，open-falcon有个step字段，会告诉服务端上报频率是多少，但是在prometheus生态里没有这个东西，所以prometheus服务端并不清楚你会按照什么频率上报，client侧完全不按照固定频率上报，prometheus也可以接受。所以，prometheus返回数据给UI层，其实是使用了一个算法，按照指定的step参数(prometheus的/api/v1/query支持传入step参数)来返回的，这个说起来比较细了，可以查一下资料，在这个issue里分享一下你的学习心得:)

**Comment by UlricQin** [comment]
嗯，刚才我说错了，我想表达的就是query_range是支持step的，相当于频率这个信息，是查询的时候指定的，而非像open-falcon那样，是上报的时候指定的。这俩软件不是一个设计逻辑。

监控这个场景，一旦某个指标有问题，一般就会一直有问题，所以使用上一个值我倒是觉得问题不大，再配合持续时长，一定程度上也可以规避一些问题。
