### ISSUE TITLE
报警邮件通知的问题

### ISSUE THREAD

**Issue by tianchao001** [ccfos/nightingale#1050]
报警被触发后发送邮件，n9e server ERROR.log 报错：
ERROR sender/email.go:49 email_sender: failed to dial smtp: dial tcp: lookup smtp.xxx.xxx.xx : no such host
看报错应该是到该域名的网络或者域名解析问题，于是我尝试排查，用telnet 尝试链接上述域名配置的端口 发现是通的，同时 nslookup解析结果也是正常的cname记录及相关a记录。
目前看 网络层是没问题的，但为什么server 还是会报这个错误呢？

**Comment by UlricQin** [comment]
server不会自己实现网络协议栈，也是依赖操作系统这套机制，所以，跟server没关系，你需要再尝试其他思路解决
