### ISSUE TITLE
微信公众号上的文章有个小问题

### ISSUE THREAD

**Issue by snail2sky** [ccfos/nightingale#1051]
**What would you like to be added**:
一个词语有点小问题，也可能是我理解有问题，图如下：

![image](https://user-images.githubusercontent.com/49757958/178693420-bf25e3e3-8315-47a6-9bc1-79e32f436a4b.png)

- 采集的频率，应该是一定时间段内采集的次数，当时间一定时，采集的频率越大，采集的次数也就越多，因此，应该是：**查看的时间越大，采集的频率越小(采集的间隔越大)**
- 大佬有空可以斟酌下，小问题
**Why is this needed**:

**Comment by UlricQin** [comment]
👍🏻
