### ISSUE TITLE
influx多值数据查询问题

### ISSUE THREAD

**Issue by tianchao001** [ccfos/nightingale#1055]
使用categraf 采集器 exec插件执行influx数据格式shell脚本  --test 数据输出正常，但上报到夜莺server端后 查询 缺少了一个metric数据，详细如下：
exec脚本内容：
#!/bin/bash
echo "influx_test_status,test_label=test1,test_label2=test2 field1=3,field2=4"

categraf --test --inputs exec 输出内容：
15:14:20 influx_test_status_field1 agent_hostname=10.134.73.161 env=n9e region=tx-bj test_label2=test2 test_label=test1 3
15:14:20 influx_test_status_field2 agent_hostname=10.134.73.161 env=n9e region=tx-bj test_label2=test2 test_label=test1 4

夜莺server查询 只能查到 influx_test_status_field2  查不到 influx_test_status_field1的数据
想确认下  这种多值的情况下 夜莺的设计是只接受一个值吗

**Comment by beviniy** [comment]
我本地测试了一下是正常的
<img width="649" alt="image" src="https://user-images.githubusercontent.com/2903090/179188669-adaaba92-dd05-44cb-9329-9a839ac5faf6.png">

**Comment by xiaoziv** [comment]
我这边本地测试是正常的，建议自己再排查一下
<img width="649" alt="image" src="https://user-images.githubusercontent.com/72858153/179188940-f650a009-df12-487b-bcbf-7ce50543d022.png">
