### ISSUE TITLE
关于夜莺Standard角色的权限范围问题

### ISSUE THREAD

**Issue by tianchao001** [ccfos/nightingale#1058]
目前看 夜莺的Standard角色包含了 管理业务组与业务 团队的权限，有没有可能移除这两个权限呢？ 理由如下：
1 在实际生产场景中，Standard 可能会授权给各个业务部门的SRE或者负责人，以确保他们可以创建自己关心的监控大盘 和监控告警 等配置。
2  由于夜莺的业务团队  业务组功能在实际应用时会涉及到公司各业务部门与资产的划分，应该具备权威性，不能任由各个业务部门自己就可创建，应当由监控系统管理员统一监管，确保分组的准确性。
3 上述两个原因决定了  既要保证各个业务相关同学的告警配置权限 又必须保证团队分组的准确性，所以  这两类权限全部放在Standard角色中可能不太合适。

补充： 
   guest角色只读 给到 工程能力不强的运营同学 是有必要的，他们只关心指标，不关心配置。 同时他们也不具备准确的配置告警配置能力。 在此场景下  3个角色 admin需要确保具备全局的管理权限，guest需要确保一些同学可以看到指标又不会误配置指标，那么剩下的 一个角色 Standard  就需要既要能配置告警 又不会干扰团队分组。

**Comment by UlricQin** [comment]
不同公司的管理方式其实是不同的，角色也是可以自行配置的，可以直接通过修改role和role_operation表的内容来控制不同角色的能力
