### ISSUE TITLE
夜莺自带告警通知

### ISSUE THREAD

**Issue by wangdada11** [ccfos/nightingale#1064]
夜莺自带的告警通知，能否按照告警级别或者某些规则合并成一条消息进行通知呢？同一时间多条告警通知无法合并到一起，逐条告警通知显得有点杂乱繁琐。

**Comment by wangdada11** [comment]
每个报警都是独立发送，传的json也是如此。不知道怎么合并，这很苦恼

**Comment by UlricQin** [comment]
告警合并功能在设计了
