### ISSUE TITLE
夜莺V5监控大盘数据出现数据不同步

### ISSUE THREAD

**Issue by Quintonwong** [ccfos/nightingale#1067]
1、
![image](https://user-images.githubusercontent.com/29274981/180423189-ba16bba2-1eeb-4594-87b9-a58c940670de.png)
![image](https://user-images.githubusercontent.com/29274981/180423479-90b51291-a3c0-435e-b502-ca41bccdc544.png)

2、我最开始从5.6.2安装，经过好几次的升级，升级到5.8.0就出现这个问题了，然后我继续升到5.9.4还是有问题，升级到5.9.6也是一样。用了linux_by_categraf自带的监控大盘，categraf版本0.2.3
3、夜莺服务端是单节点部署直接跑的，监控的机器大概80台左右，请问我要怎么排查呢

**Comment by UlricQin** [comment]
1. 确认机器时间一致
2. 查看浏览器开发者工具，看request和response找线索

**Comment by Quintonwong** [comment]
找到原因了，停掉一半的agent就准了，再次开起来就不同步，服务端资源利用率都很低，大概80台agent和各种exporter，存储是普罗米修斯，存储层需要调优吗

**Comment by UlricQin** [comment]
看看prometheus的日志找找线索，百度一下看看prometheus有哪些重要监控指标，看看这些指标是否正常。有的公司用夜莺监控了几千台机器也没有出现你这个问题
