### ISSUE TITLE
指标count统计结果显示不稳定

### ISSUE THREAD

**Issue by zhaoge77** [ccfos/nightingale#1069]
### Relevant server.conf | webapi.conf

```toml
无
```

### Relevant logs

```text
基于某个metrics name(system_load1)进行count时结果存在波动
```

### System info

n9e 5.9.6, n9e-fe 5.6.0, categraf 0.2.3以上

### Steps to reproduce

1.在监控大盘里查看监控机器数时发现显示有时不一样
2.在即时查询里对该promql进行查询时显示如截图
3.
...

### Expected behavior

预期行为应该是一个稳定的值

### Actual behavior

![image](https://user-images.githubusercontent.com/7973070/180646640-dc5af8e3-906a-4edf-866d-5ff7ac225540.png)

**Comment by UlricQin** [comment]
机器时间是否一致？可以考虑用这个promql来统计：

`count(max_over_time(target_up[120s])==1)`
