### ISSUE TITLE
自愈功能

### ISSUE THREAD

**Issue by strongit** [ccfos/nightingale#1071]
**What would you like to be added**:
告警规则新增自愈脚本选择
**Why is this needed**:

<img width="636" alt="image" src="https://user-images.githubusercontent.com/11691213/180917767-eba0acbd-fb44-4258-9967-a6edcddb3f53.png">

**Comment by songhehe** [comment]
这个本来就支持，你看文档的ibex，就是自愈脚本的执行

**Comment by UlricQin** [comment]
回调地址写成 `${ibex}/23` 就表示执行ID为23的脚本，那个告警自愈的视频里有讲解，目前没有计划做更深度的支持
