### ISSUE TITLE
夜莺看板没有像grafana instant query功能？

### ISSUE THREAD

**Issue by xinxin415415** [ccfos/nightingale#1075]
在夜莺看板中PromQL查询目前是不是只有range的方式，能否支持instant的方式？

**Comment by UlricQin** [comment]
> 在夜莺看板中PromQL查询目前是不是只有range的方式，能否支持instant的方式？
> 
> 

是的，什么场景必须要支持instant query呢？举几个例子？

**Comment by xinxin415415** [comment]
监控Oracle数据库中阻塞信息，例如TX行锁，应该要instant query，如果使用range方式那么不是会出来n多行重新的信息吗

**Comment by UlricQin** [comment]
> 监控Oracle数据库中阻塞信息，例如TX行锁，应该要instant query，如果使用range方式那么不是会出来n多行重新的信息吗

不是出来n多行，是每个时间线出来n个点，如果要使用stat图，会只出来最后一个点

**Comment by xinxin415415** [comment]
使用stat图是可以展示最后一个点，因为我想展示更多的信息，只能使用table

**Comment by UlricQin** [comment]
@jsers 编辑图表的时候，chart可以配置单独的时间范围，那个时间范围增加1分钟和2分钟的范围，这个做完了就把这个issue关掉吧

**Comment by UlricQin** [comment]
新版本已经支持单个图表1、2分钟范围
