### ISSUE TITLE
docker创建容器categraf版本过低

### ISSUE THREAD

**Issue by findyou** [ccfos/nightingale#1078]
### Relevant server.conf | webapi.conf

```toml
categraf:
    image: "flashcatcloud/categraf:v0.1.9"

建议升级至v0.2.4
```

### Relevant logs

```text
categraf:
    image: "flashcatcloud/categraf:v0.1.9"

13:48:55 http_response_response_time agent_hostname=Test@13.x.238 method=GET target=https://www.baidu.com 0.584147413
13:48:55 http_response_result_code agent_hostname=Test@13.x.238 method=GET target=https://www.baidu.com 0
```

### System info

categraf:v0.1.9

### Steps to reproduce

1.  下载git源码，docker-compose up -d创建容器
2.  文件categraf/input.http_response/http_response.toml, 在targets添加https://www.baidu.com
3.  执行测试  ./categraf -test -inputs http_response

### Expected behavior

13:48:55 http_response_response_time agent_hostname=Test@13.x.238 method=GET target=https://www.baidu.com 0.584147413
13:48:55 http_response_result_code agent_hostname=Test@13.x.238 method=GET target=https://www.baidu.com 0
13:48:55 http_response_cert_expire_timestamp agent_hostname=Test@13.x.238 method=GET target=https://www.baidu.com 1.691298961e+09
13:48:55 http_response_response_code agent_hostname=Test@13.x.238 method=GET target=https://www.baidu.com 200

### Actual behavior

13:48:55 http_response_response_time agent_hostname=Test@13.x.238 method=GET target=https://www.baidu.com 0.584147413
13:48:55 http_response_result_code agent_hostname=Test@13.x.238 method=GET target=https://www.baidu.com 0

**Comment by kongfei605** [comment]
这个PR https://github.com/ccfos/nightingale/pull/1079/files已经修改使用最新版本的n9e和categraf了
