### ISSUE TITLE
helm chart 方式安装

### ISSUE THREAD

**Issue by dotheright** [ccfos/nightingale#1080]
**What would you like to be added**:
helm chart 方式安装

**Why is this needed**:
现在很多云原生的应用都是使用helm chart 方式安装的， 夜莺现在还没有这种安装方式

**Comment by laiwei** [comment]
- Nightingale helm chart，可以参考： https://github.com/flashcatcloud/n9e-helm
- 在rancher中一键安装Nightingale，可以参考：https://mp.weixin.qq.com/s/PHy4KNrcO5I6jALtbcbBSw

上述关于 Nightingale 安装使用的文档，都可以在 https://n9e.github.io 查阅得到。

@dotheright
