### ISSUE TITLE
历史告警 翻页翻不了

### ISSUE THREAD

**Issue by Ohimma** [ccfos/nightingale#1081]
### Relevant server.conf | webapi.conf

```toml
no
```

### Relevant logs

```text
no
```

### System info

5.8.0

### Steps to reproduce

点击翻页无响应

### Expected behavior

查看下一页

### Actual behavior

没响应

**Comment by 710leo** [comment]
@Ohimma 新版本没有这个问题，可以升级下版本

**Comment by Ohimma** [comment]
好的
