### ISSUE TITLE
在监控大盘里变量选择关键字搜索的对象时，搜索输出的对象选择框能持久化

### ISSUE THREAD

**Issue by blankleee** [ccfos/nightingale#1083]
**What would you like to be added**:
在监控大盘里，变量选择关键字搜索的对象时，搜索输出的对象选择框能持久化
![image](https://user-images.githubusercontent.com/65880739/182321161-f9bf8037-2172-493c-8abf-70e3b04f87bb.png)

**Why is this needed**:
在监控大盘里面，一个变量下有很多个对象时，很多时候要输入关键字去搜索选择，但是搜索选择时只能选择一个对象，如果我要选择这个关键字的多个对象时，就变得异常烦恼

**Comment by UlricQin** [comment]
大盘变量支持multi选项，勾选了就支持多选了。但是这需要每个图表的promql的配合，promql就需要用 `=~` 而不能用 `=`

**Comment by blankleee** [comment]
> 大盘变量支持multi选项，勾选了就支持多选了。但是这需要每个图表的promql的配合，promql就需要用 `=~` 而不能用 `=`

我的意思是， 前端在搜索完之后，我选择了一个对象， 搜索效果就不见了， 想选择第二个的时候要重新搜索，这样有点不方便。
