### ISSUE TITLE
是否有计划增强权限隔离或者说租户的能力

### ISSUE THREAD

**Issue by lsy1990** [ccfos/nightingale#1089]
1.设置业务组可以管理的namespace，
2.那么相应的运维团队就只能查询，该namespace的数据

**Comment by lsy1990** [comment]
我看了下，现在业务组有label，但是那个是对ident 元素打标签，
对于k8s，来讲，namespace类的filter 可能是更实际的方式

**Comment by lsy1990** [comment]
比设置业务组,region=k8s-3.11   namespace=xxxx  
or  region=vm  ident=*,*,*,*

**Comment by UlricQin** [comment]
没有计划增强权限和数据隔离机制。像即时查询这种，用户自由写promql，完全没法限制
