### ISSUE TITLE
夜莺支持对接cas server

### ISSUE THREAD

**Issue by UlricQin** [ccfos/nightingale#1093]
对于sso登录，夜莺目前支持oidc，希望能支持对接cas server。有些公司已经有了cas server了，夜莺要是能直接对接的话，对于公司层面的单点登录更加统一一些

oidc 的代码：src/pkg/oidcc/oidc.go
前端调用oidc的接口是：`/auth/redirect` 和 `/auth/callback`

要支持cas，首先要仿照 oidc.go 写一个逻辑与 cas  server 交互；其次是提供 `/auth/redirect/cas` 和 `/auth/callback/cas` 接口给JavaScript使用

**Comment by freedomkk-qfeng** [comment]
这个需求我认领了

**Comment by lsy1990** [comment]
@UlricQin 我搞过sso登录，是上海派拉的：）跟cas类似，如果有需要，也可问我@freedomkk-qfeng

**Comment by xxy-cn** [comment]
大佬，按你的逻辑实现了一版，指点下？

**Comment by goodosoft** [comment]
> 

强烈支持，请问现在进度如何？
急需

**Comment by foursevenlove** [comment]
已提pr，麻烦review一下 @UlricQin

**Comment by UlricQin** [comment]
赞 @freedomkk-qfeng  一起看看？

**Comment by freedomkk-qfeng** [comment]
#1236 
[n9e/fe-v5 #209](https://github.com/n9e/fe-v5/pull/209)

这两个 pr 应该可以解决这个问题

**Comment by freedomkk-qfeng** [comment]
Todo: 优化发起重定向跳转的方案，实现后端跳转。从而支持提供给第三方嵌入的 SSO 发起链接

**Comment by tanxiao1990** [comment]
> Todo: 优化发起重定向跳转的方案，实现后端跳转。从而支持提供给第三方嵌入的 SSO 发起链接

此优化是否有进展？

**Comment by UlricQin** [comment]
> > Todo: 优化发起重定向跳转的方案，实现后端跳转。从而支持提供给第三方嵌入的 SSO 发起链接
> 
> 
> 
> 此优化是否有进展？

看起来还没有进展，估计忙别的事情去了😄

**Comment by UlricQin** [comment]
新版本已经支持了
