### ISSUE TITLE
按照官方文档中  grafana-agent示例配置daemonset后 会采集多次数据

### ISSUE THREAD

**Issue by SnowiceShen** [ccfos/nightingale#1096]
文档建议
对于采集 node_exporter/ kubelet/ cAdvisor等指标，每个节点上只运行一个grafana-agent实例的情况，推荐以daemonset运行
实际单个实例运行时已经可以收集完整数据
daemonset会造成  cadvisor 和  kubelet 数据重复采集
------------------------------------------
kind: ConfigMap
metadata:
  name: grafana-agent
  namespace: monitor
apiVersion: v1
data:
  agent.yaml: |
    server:
      log_level: info
    metrics:
      wal_directory: /tmp/grafana-agent-wal
      global:
        scrape_interval: 15s
        scrape_timeout: 10s
        external_labels:
          cluster: SH
      configs:
      - name: integrations
        remote_write:
        - url: http://172.xxx.xxx.xxx:19000/prometheus/v1/write
          basic_auth:
            username:
            password:
        scrape_configs:
        - job_name: 'integrations/kubernetes/cadvisor'
          scheme: https
          tls_config:
            ca_file: /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
            insecure_skip_verify: true
          bearer_token_file: /var/run/secrets/kubernetes.io/serviceaccount/token
          kubernetes_sd_configs:
          - role: node
          relabel_configs:
          - source_labels: [__meta_kubernetes_node_name]
            regex: (.+)
            target_label: __metrics_path__
            replacement: metrics/cadvisor
          - source_labels: [__meta_kubernetes_node_label_ident]
            regex: (.+)
            target_label: ident
        - job_name: integrations/kubernetes/kubelet
          scheme: https
          tls_config:
              ca_file: /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
              insecure_skip_verify: true
          bearer_token_file: /var/run/secrets/kubernetes.io/serviceaccount/token
          kubernetes_sd_configs:
          - role: node
          relabel_configs:
          - source_labels: [__meta_kubernetes_node_label_ident]
            regex: (.+)
            target_label: ident

**Comment by UlricQin** [comment]
Grafana-agent 的文档请参考 Grafana 官方文档。n9e.github.io 的 Grafana-agent 文档这是机翻搬运过来的。另外，对于cadvisor、kubelet、node-exporter 这种数据的采集，你要看relabel_configs，如果relabel_configs之后`__address__`是apiserver的地址，那就用deployment部署grafana-agent即可，如果`__address__`是连的localhost或127.0.0.1，那就用daemonset
