### ISSUE TITLE
即时查询-Graph视图下-Series 列显示问题

### ISSUE THREAD

**Issue by FengZh61** [ccfos/nightingale#1099]
前端版本：5.9.0
后端版本：v5.10.3-f18ed76593c27a40a6de5bbf9d4b733d62ec6c63

![image](https://user-images.githubusercontent.com/98309003/183839607-48f28caf-bf6b-4f41-a317-9b81b6f0561a.png)

Series 列不显示文本，鼠标悬浮上去只有一个小黑框，而且数据不支持点击选取查看，比如有2行数据，我想查看其中一个，现在这个情况是没有办法选取的

![image](https://user-images.githubusercontent.com/98309003/183840130-863656a9-1dd4-42d2-b3cf-8d7d04ce5d62.png)

这是分享后的视图，Series 列可以正常显示，但仍然不可用选取

我印象中这两个问题在之前的版本是正常的，不知道是不是记错了

**Comment by UlricQin** [comment]
https://github.com/n9e/fe-v5/releases/tag/v5.9.1
