### ISSUE TITLE
订阅规则选择时支持多选

### ISSUE THREAD

**Issue by wsxedcer** [ccfos/nightingale#1101]
前端版本：5.9.0
后端版本：v5.10.3-f18ed76593c27a40a6de5bbf9d4b733d62ec6c63

现在的通用报警规则是创建在一个公共业务组中，然后各个业务组通过订阅相关的规则发送报警，在创建订阅规则的时候每次只能选取一条，但是“订阅事件标签Key” 这个条件大部分情况下是一致的，希望能增加多选功能

**Comment by UlricQin** [comment]
你想订阅一批，是基于什么分类筛选出的这一批，就可以为这些规则打上附加标签，然后根据附加标签做订阅
