### ISSUE TITLE
添加recording规则没有生效，是我哪里配置有问题吗？

### ISSUE THREAD

**Issue by FengZh61** [ccfos/nightingale#1106]
promethues抓取exporter数据然后存储到vm中，然后夜莺分别配置了vm的read和write的url，之前配置了promethues的read和write的url，recording也没有生效！

前端版本：5.9.1
后端版本：v5.10.3-23d7e5a7de5d0ffea7ab941e9621ef7f53071775

server.conf

![image](https://user-images.githubusercontent.com/98309003/184271723-019d1946-2d65-4a88-b1c5-f80077165e84.png)

webapi.conf

![image](https://user-images.githubusercontent.com/98309003/184271788-51582016-4931-4953-a72c-7438ccab9b93.png)

![image](https://user-images.githubusercontent.com/98309003/184271831-f81b7e32-8be2-433d-ac21-ee94719d3181.png)

观察日志没有errorr

**Comment by xiaoziv** [comment]
看下nserver的ClusterName配置

**Comment by FengZh61** [comment]
> 看下nserver的ClusterName配置

nserver的ClusterName和nwebapi的ClusterName不一致，我改下试试~
