### ISSUE TITLE
前端页面白屏

### ISSUE THREAD

**Issue by leozz705** [ccfos/nightingale#1117]
出现在监控大盘：http探测相关（用categraf的http_response和prometheus的blackbox采集监控的域名）
展示部分域名监控的时候就会白屏：
前端版本：5.9.0
后端版本：v5.10.3
浏览器：edge
页面控制台报错如下：
![image](https://user-images.githubusercontent.com/78150430/185024060-4cfb3591-a99f-4e34-b402-b2c4a9ab0bfc.png)

**Comment by UlricQin** [comment]
重复了

**Comment by bruceforlearn** [comment]
我也是白屏。
![image](https://user-images.githubusercontent.com/29446582/190053778-0693767d-4c66-4b8b-8762-501001b39190.png)
