### ISSUE TITLE
告警级别关联通知媒介

### ISSUE THREAD

**Issue by bbaobelief** [ccfos/nightingale#1120]
请问 告警级别 能否支持关联 通知媒介。
比如不同级别只能选：
- S3 邮件，钉钉
- S2 邮件，钉钉，短信
- S1  邮件，钉钉，短信，电话

这些选项支持在webapi 配置中映射。

![image](https://user-images.githubusercontent.com/3918461/185101826-13e0cbbc-dbc6-46ad-b562-88e50191c911.png)
![image](https://user-images.githubusercontent.com/3918461/185101864-e4f7f714-c1c5-4926-806c-1df6a8ffb21f.png)

**Comment by UlricQin** [comment]
不支持。有些公司觉得固定的关联不够灵活，夜莺的设计就都给放开了，每个告警规则都可以单独配置发送渠道

**Comment by bbaobelief** [comment]
> 不支持。有些公司觉得固定的关联不够灵活，夜莺的设计就都给放开了，每个告警规则都可以单独配置发送渠道

可以做成在webapi按级别配置通道，默认不配置就显示所有。
我现在遇到个问题：因运营商审核限制，电话告警内容不能太多，用户接到电话告警一时半会无法定位具体的告警事件。
falcon以前只有P0才能配置电话，查找起来就很快。

**Comment by UlricQin** [comment]
那用户配置告警的时候，针对P1的告警就只勾选电话通知即可。

**Comment by bbaobelief** [comment]
> 那用户配置告警的时候，针对P1的告警就只勾选电话通知即可。

我们研发可以配置告警，他们的行为不太好规范。

**Comment by UlricQin** [comment]
产品会尽量给予足够的灵活性，每个公司如果有自己独特的规范，可以二开解决，不过个人观点，这个点，不值得二开。规范制定了大家遵守即可。就像线上操作红线，不遵守的是需要处罚的。而告警发送而言，不遵守规范也没啥大不了的
