### ISSUE TITLE
n9e server扩容后，对象列表显示集群不正确

### ISSUE THREAD

**Issue by tianchao001** [ccfos/nightingale#1121]
### Relevant server.conf | webapi.conf

```toml
n9e server 由1 扩为3个后，并且原来的1个server集群名称由default 改为现在3个集群的自定义命名  bj  eu  hf后，删除对象列表中所有主机，并重启categraf 让categraf重新注册到对应 server，此时 在对象列表中 重新注册上来的categraf所属集群名称仍然是default 并且状态为donw，但在即时查询页面 该主机状态为up 并且所属集群为bj。
```

### Relevant logs

```text
无报错日志，逻辑BUG
```

### System info

n9e.5.10.3

### Steps to reproduce

1  关闭全部对象的categraf
2  删除对象列表全部主机
3 修改webapi配置文件的集群名称与server名称
4  启动categraf 
5 查看对象列表
6  查询该主机的启动状态

### Expected behavior

对象列表中的所属集群 应该是修改后的，因为categraf已经重新注册了。

### Actual behavior

会发现 对象列表中上报的集群仍然是修改前的，并且状态为down

### Additional info

weiapi配置信息：
```
[[Clusters]]
!# Prometheus cluster name
Name = "qcloud-bj"
!# Prometheus APIs base url
Prom = "http://127.0.0.1:9090"
!# Basic auth username
BasicAuthUser = ""
!# Basic auth password
BasicAuthPass = ""
!# timeout settings, unit: ms
Timeout = 30000
DialTimeout = 3000
MaxIdleConnsPerHost = 100

[[Clusters]]
!#Prometheus cluster name
Name = "aws-eu"
!# Prometheus APIs base url
Prom = "http://10.161.xx.xx:9090"
!# Basic auth username
BasicAuthUser = ""
!# Basic auth password
BasicAuthPass = ""
!# timeout settings, unit: ms
Timeout = 30000
DialTimeout = 3000
MaxIdleConnsPerHost = 100

[[Clusters]]
!#Prometheus cluster name
Name = "hf-idc"
!# Prometheus APIs base url
Prom = "http://10.142.xx.xx:9090"
!# Basic auth username
BasicAuthUser = ""
!# Basic auth password
BasicAuthPass = ""
!# timeout settings, unit: ms
Timeout = 30000
DialTimeout = 3000
MaxIdleConnsPerHost = 100

[Ibex]
Address = "http://127.0.0.1:10090"
!# basic auth
BasicAuthUser = "ibex"
BasicAuthPass = "ibex"
!# unit: ms
Timeout = 3000
```
-----------------------------------------
三个server 集群相关配置信息：
```
!# debug, release
RunMode = "release"

!# my cluster name
ClusterName = "qcloud-bj"

!# Default busigroup Key name
!# do not change
BusiGroupLabelKey = "busigroup"

!# sleep x seconds, then start judge engine
EngineDelay = 120

DisableUsageReport = false

!# debug, release
RunMode = "release"

!# my cluster name
ClusterName = "aws-eu"

!# Default busigroup Key name
!# do not change
BusiGroupLabelKey = "busigroup"

!# sleep x seconds, then start judge engine
EngineDelay = 120

DisableUsageReport = false

!# debug, release
RunMode = "release"

!# my cluster name
ClusterName = "hf-idc"

!# Default busigroup Key name
!# do not change
BusiGroupLabelKey = "busigroup"

!# sleep x seconds, then start judge engine
EngineDelay = 120

DisableUsageReport = false
```

**Comment by UlricQin** [comment]
三个server.conf的ClusterName怎么配置的？
webapi.conf的Clusters部分怎么配置的？

issue模板让你贴配置你咋不贴呢。。

**Comment by tianchao001** [comment]
weiapi配置信息：
[[Clusters]]
# Prometheus cluster name
Name = "qcloud-bj"
# Prometheus APIs base url
Prom = "http://127.0.0.1:9090"
# Basic auth username
BasicAuthUser = ""
# Basic auth password
BasicAuthPass = ""
# timeout settings, unit: ms
Timeout = 30000
DialTimeout = 3000
MaxIdleConnsPerHost = 100

[[Clusters]]
#Prometheus cluster name
Name = "aws-eu"
# Prometheus APIs base url
Prom = "http://10.161.xx.xx:9090"
# Basic auth username
BasicAuthUser = ""
# Basic auth password
BasicAuthPass = ""
# timeout settings, unit: ms
Timeout = 30000
DialTimeout = 3000
MaxIdleConnsPerHost = 100

[[Clusters]]
#Prometheus cluster name
Name = "hf-idc"
# Prometheus APIs base url
Prom = "http://10.142.xx.xx:9090"
# Basic auth username
BasicAuthUser = ""
# Basic auth password
BasicAuthPass = ""
# timeout settings, unit: ms
Timeout = 30000
DialTimeout = 3000
MaxIdleConnsPerHost = 100

[Ibex]
Address = "http://127.0.0.1:10090"
# basic auth
BasicAuthUser = "ibex"
BasicAuthPass = "ibex"
# unit: ms
Timeout = 3000
-----------------------------------------
三个server 集群相关配置信息：

# debug, release
RunMode = "release"

# my cluster name
ClusterName = "qcloud-bj"

# Default busigroup Key name
# do not change
BusiGroupLabelKey = "busigroup"

# sleep x seconds, then start judge engine
EngineDelay = 120

DisableUsageReport = false

-----------------------------
# debug, release
RunMode = "release"

# my cluster name
ClusterName = "aws-eu"

# Default busigroup Key name
# do not change
BusiGroupLabelKey = "busigroup"

# sleep x seconds, then start judge engine
EngineDelay = 120

DisableUsageReport = false
----------------------------------
# debug, release
RunMode = "release"

# my cluster name
ClusterName = "hf-idc"

# Default busigroup Key name
# do not change
BusiGroupLabelKey = "busigroup"

# sleep x seconds, then start judge engine
EngineDelay = 120

DisableUsageReport = false

**Comment by tianchao001** [comment]
已补充信息

**Comment by UlricQin** [comment]
那不可能。webapi和server中都没有Default字样的配置，客户端主动注册上来，cluster却叫Default是不可能的。
实际原理是，监控数据发给n9e-server，n9e-server读取自己配置中的ClusterName，然后设置到监控对象里，然后写入DB。你再检查一下你的配置吧
