### ISSUE TITLE
关于监控大盘中的蜂窝图需要修改的地方

### ISSUE THREAD

**Issue by jwh5566** [ccfos/nightingale#1130]
**What would you like to be added**:
![9aad1271a9354b299f1d3cc0f0895ec](https://user-images.githubusercontent.com/7205703/186651401-d9f854d6-2e91-4436-a33c-3d26eadcc19f.jpg)

**Why is this needed**:
蜂窝图显示数值，没有什么意义，正常情况下 我觉得只显示label就可以，用来标识不同的应用
值的话可以用颜色来区分正常或者异常的情况

**Comment by jwh5566** [comment]
转到前端那边去了

**Comment by UlricQin** [comment]
ok，那这个先close了
