### ISSUE TITLE
n9e配置标签绑定和采集的数据冲突了

### ISSUE THREAD

**Issue by shichanglin5** [ccfos/nightingale#1132]
**What would you like to be added**:

在 n9e web 端根据 ident 绑定标签，但是由于这个标签在采集的数据中已有同名标签了，导致监控数据写入 prometheus 失败

**Why is this needed**:

在 prometheus 配置自定义标签，有两种策略：以采集的数据为准覆盖自定义标签 和 自动重命名以保留两者，避免由于标签冲突导致数据采集不到

n9e 可以支持这个配置吗

**Comment by UlricQin** [comment]
你是哪个版本

**Comment by shichanglin5** [comment]
5.9.2

**Comment by UlricQin** [comment]
最新版本应该是不会报错了
