### ISSUE TITLE
关于活跃告警设计疑问

### ISSUE THREAD

**Issue by chenginger** [ccfos/nightingale#1143]
server每次都删除活跃告警然后重新生成.为什么不进行更新呢？
1、这里会导致一个问题.有人在页面想删除或屏蔽活跃告警,但是几分钟内活跃告警已经进行多次重新生成点击删除或者屏蔽就会报错还是个空的错误.
2、如果想扩展认领告警或者直接手动恢复(可能出现问题但是一定时间内处理不了暂时先恢复)等功能想操作活跃告警就很容易出现上述1的问题

**Comment by UlricQin** [comment]
每生成一个事件，都会在历史告警中存档，现在的设计，活跃告警永远是跟随最新的那条历史告警。如果只是更新，就需要引入一个新的概念，姑且称之为alert，这个后面会单独做一个产品来解决告警闭环、聚合发送等问题，目前的夜莺设计会维持现状

**Comment by chenginger** [comment]
这块设计大概什么时候会迭代呢？@UlricQin
