### ISSUE TITLE
Categraf 客户端停掉后，server端的target_up等待四分钟后值才为0

### ISSUE THREAD

**Issue by lyitt1987** [ccfos/nightingale#1146]
1 客户端于11:08:53 停掉
2 管理界面即时查询target_up为1，直到11:13分target_up才为0
3 重新启动Categraf后，target_up值马上就恢复为1
请解惑，谢谢！

**Comment by UlricQin** [comment]
机器时间没有校准，所有的机器时间都要一致

**Comment by lyitt1987** [comment]
时间都一样的，如果是时间问题，那恢复的时候为什么就能立马生效呢

**Comment by lyitt1987** [comment]
我的安装方式是docker-compose

**Comment by UlricQin** [comment]
faq里搜索target_up
