### ISSUE TITLE
LDAP用户同步到夜莺用户管理数据异常

### ISSUE THREAD

**Issue by Hallen109** [ccfos/nightingale#1148]
前端版本：5.10.0
后端版本：v5.11.0-e7d2c45f9d27da6d7e914fd9fac75f548f64e5c2
问题：通过接口/api/n9e/users将LDAP用户提前同步到夜莺，用户登录之后，在用户管理页面出现了两个同名的用户，但是在数据库的users表里只有一条记录。

**Comment by UlricQin** [comment]
证据和线索太少，无解

**Comment by Hallen109** [comment]
已解决
