### ISSUE TITLE
ldap支持

### ISSUE THREAD

**Issue by jeromeji** [ccfos/nightingale#1149]
**What would you like to be added**:
ldap，用户管理
**Why is this needed**:
接入现有ldap

**Comment by FengZh61** [comment]
webapi.conf有具体的配置项，支持ldap接入。

**Comment by xulun2468** [comment]
> 
目前支持过滤组用户吗？在那个配置项设置呀？base-dn？

**Comment by xulun2468** [comment]
你好，同名的用户，貌似只会使用夜莺的账户，这个有配置限制只登入ldap用户吗？
