### ISSUE TITLE
老师，您好，请教一下，自己写告警自愈的http webhook脚本逻辑，参数是从哪获取的？

### ISSUE THREAD

**Issue by beginend2012** [ccfos/nightingale#1151]
### Relevant server.conf | webapi.conf

```toml
无
```

### Relevant logs

```text
无
```

### System info

无

### Steps to reproduce

无

### Expected behavior

![Uploading image.png…]()

### Actual behavior

无

### Additional info

![Uploading image.png…]()

**Comment by UlricQin** [comment]
通读文档就知道了

**Comment by UlricQin** [comment]
`nc -l 3456` 随便找个机器用nc监听一个端口，把这个地址配置到webhook里，当夜莺触发webhook的时候，就可以在nc里看到接收到的内容了。[Linux进阶知识](https://edu.51cto.com/course/31049.html)
