### ISSUE TITLE
如何删除快捷试图中的主机实例

### ISSUE THREAD

**Issue by MikelPan** [ccfos/nightingale#1173]
### Relevant server.conf | webapi.conf

```toml
收到异常告警
```

### Relevant logs

```text
收到异常告警
```

### System info

n9e 5.11.1 categraf 0.2.13 ubuntu 20.0.4 docker 20.10.17

### Steps to reproduce

收到异常告警

### Expected behavior

收到异常告警

### Actual behavior

收到异常告警

**Comment by UlricQin** [comment]
https://github.com/ccfos/nightingale/discussions 去这里提问
