### ISSUE TITLE
连接redis哨兵模式日志有异常报错

### ISSUE THREAD

**Issue by MoonStill** [ccfos/nightingale#1174]
### Relevant server.conf | webapi.conf

```toml
server.conf
...
[Redis]
# address, ip:port or ip1:port,ip2:port for cluster and sentinel(SentinelAddrs)
Address = "192.168.250.xx:26379,192.168.250.xx:26379,192.168.250.xx:26379"
Password = "p9xxxxxxxxxx"
DB = 0
# UseTLS = false
# TLSMinVersion = "1.2"
# standalone cluster sentinel
RedisType = "sentinel"
# Mastername for sentinel type
MasterName = "mymaster"
...
```

### Relevant logs

```text
n9e-server
Sep 29 17:27:35  n9e-server[3691872]: redis: 2022/09/29 17:27:35 pubsub.go:159: redis: discarding bad PubSub connection: read tcp 192.168.250.68:35822->192.168.250.68:26379: i/o timeout
Sep 29 17:27:38  n9e-server[3691872]: redis: 2022/09/29 17:27:38 pubsub.go:159: redis: discarding bad PubSub connection: read tcp 192.168.250.68:35858->192.168.250.68:26379: i/o timeout
Sep 29 17:27:41  n9e-server[3691872]: redis: 2022/09/29 17:27:41 pubsub.go:159: redis: discarding bad PubSub connection: read tcp 192.168.250.68:35862->192.168.250.68:26379: i/o timeout
```

### System info

n9e 5.12.0,ubuntu 20.04 

### Steps to reproduce

使用redis-sentinel 模式，自从更新到5.11.3后就有这个报错，后续又更新到5.12.0问题依然存在，5.11之前无此问题。
用standalone 模式没有问题。

### Expected behavior

预期使用redis-sentinel模式无问题

### Actual behavior

实际n9e 5.11.3/5.11.2使用redis-sentinel模式都有报错

**Comment by caixiaoliang** [comment]
+1
redis: 2022/10/09 16:06:12 pubsub.go:159: redis: discarding bad PubSub connection: read tcp 10.202.60.108:45850->10.202.60.108:26379: i/o timeout
redis: 2022/10/09 16:06:15 pubsub.go:159: redis: discarding bad PubSub connection: read tcp 10.202.60.108:45864->10.202.60.108:26379: i/o timeout
redis: 2022/10/09 16:06:18 pubsub.go:159: redis: discarding bad PubSub connection: read tcp 10.202.60.108:45876->10.202.60.108:26379: i/o timeout
redis: 2022/10/09 16:06:21 pubsub.go:159: redis: discarding bad PubSub connection: read tcp 10.202.60.108:45896->10.202.60.108:26379: i/o timeout
redis: 2022/10/09 16:06:24 pubsub.go:159: redis: discarding bad PubSub connection: read tcp 10.202.60.108:45906->10.202.60.108:26379: i/o timeout
redis: 2022/10/09 16:06:27 pubsub.go:159: redis: discarding bad PubSub connection: read tcp 10.202.60.108:45918->10.202.60.108:26379: i/o timeout
redis: 2022/10/09 16:06:30 pubsub.go:159: redis: discarding bad PubSub connection: read tcp 10.202.60.108:45948->10.202.60.108:26379: i/o timeout

**Comment by tanxiao1990** [comment]
https://github.com/go-redis/redis/pull/2176
