### ISSUE TITLE
 http://116.85.64.82/n9e-3.8.0.tar.gz 地址不可用了

### ISSUE THREAD

**Issue by kk456852** [ccfos/nightingale#1175]
### Relevant server.conf | webapi.conf

```toml
http://116.85.64.82/n9e-3.8.0.tar.gz 地址不可用了
```

### Relevant logs

```text
http://116.85.64.82/n9e-3.8.0.tar.gz 地址不可用了
```

### System info

linux

### Steps to reproduce

 http://116.85.64.82/n9e-3.8.0.tar.gz 地址不可用了

### Expected behavior

 http://116.85.64.82/n9e-3.8.0.tar.gz 地址不可用了

### Actual behavior

 http://116.85.64.82/n9e-3.8.0.tar.gz 地址不可用了

### Additional info

 http://116.85.64.82/n9e-3.8.0.tar.gz 地址不可用了

**Comment by UlricQin** [comment]
现在已经v5了，v3已经不维护了，如果还需要的话可以自己clone代码下来切到对应分支自行编译：https://github.com/flashcatcloud/nightingale
