### ISSUE TITLE
屏蔽规则无法创建

### ISSUE THREAD

**Issue by MethTo** [ccfos/nightingale#1177]
### Relevant server.conf | webapi.conf

```toml
暂时忽略conf提交
```

### Relevant logs

```text
server.log以及webapi.log没有日志打印
打开chrome浏览器的网页检查，报错如下：
TypeError: e.cluster.join is not a function
    at onFinish (operateForm.tsx:142:31)
    at onFinish (Form.js:73:11)
    at useForm.js:829:11
（匿名）	@	useForm.js:834
Promise.then（异步）		
submit	@	useForm.js:826
onSubmit	@	Form.js:125
je	@	react-dom.production.min.js:52
Le	@	react-dom.production.min.js:52
（匿名）	@	react-dom.production.min.js:53
po	@	react-dom.production.min.js:53
yo	@	react-dom.production.min.js:101
（匿名）	@	react-dom.production.min.js:113
ke	@	react-dom.production.min.js:292
（匿名）	@	react-dom.production.min.js:50
wo	@	react-dom.production.min.js:50
Bn	@	react-dom.production.min.js:75
Un	@	react-dom.production.min.js:74
t.unstable_runWithPriority	@	scheduler.production.min.js:18
Ri	@	react-dom.production.min.js:122
xe	@	react-dom.production.min.js:292
Hn	@	react-dom.production.min.js:73
```

### System info

n9e-v5.10.0-linux / CentOS Linux release 7.4.1708 (Core)

### Steps to reproduce

1.出现告警时，点击活跃告警
2.点击具体告警右侧的屏蔽按钮，进入屏蔽页面
3.填写屏蔽原因后，点击创建按钮，无任何反馈和响应
4.将全部的标签删除，仅剩一条根据IP过滤。再次提交，仍然失败。

5.退出。从告警管理 -> 屏蔽规则 进入
6.点击新增屏蔽规则
7.添加相关的规则，屏蔽原因，点击创建，创建成功。

### Expected behavior

实际操作时，希望可以直接从活跃告警侧直接进入屏蔽管理。

### Actual behavior

直接从活跃告警进入屏蔽规则的web页面，点击创建无任何反馈和响应。
重启后，直接从告警进入屏蔽，还是无任何反馈和响应。页面报错相同的js问题

**Comment by UlricQin** [comment]
升级到最新版本试试，我在这个版本测试没问题：

前端版本：5.11.1
后端版本：v5.11.3-537d5d2386aa93533beb79ae887422bdca910d9c
