### ISSUE TITLE
是否有服务树模块代码呢

### ISSUE THREAD

**Issue by debug-LiXiwen** [ccfos/nightingale#1189]
**Why is this needed**: 请问该项目有服务树的设计吗

**Comment by UlricQin** [comment]
v3 v4 的老版本里有，老版本在这里：https://github.com/flashcatcloud/nightingale 新版本砍掉了

**Comment by debug-LiXiwen** [comment]
> v3 v4 的老版本里有，老版本在这里：https://github.com/flashcatcloud/nightingale 新版本砍掉了
想请教下是新版本是采用了什么方案来替代的服务树呢

**Comment by UlricQin** [comment]
一维的业务组+多维的标签
