### ISSUE TITLE
是否支持以下图表样式？

### ISSUE THREAD

**Issue by starwuleo** [ccfos/nightingale#1206]
nightingale的table样式，是否支持横向加列的方式？如下：
![image](https://user-images.githubusercontent.com/61398926/196623466-f444eebf-4360-46c8-8924-95fdb28ba41c.png)

**Comment by UlricQin** [comment]
支持，可以导入这个大盘参考一下：https://github.com/flashcatcloud/categraf/blob/main/inputs/http_response/dashboard.json   另外这类咨询类问题去 Discussions 提问：https://github.com/ccfos/nightingale/discussions
