### ISSUE TITLE
主机标签解绑小概率失败

### ISSUE THREAD

**Issue by jiangnanora** [ccfos/nightingale#1214]
版本如下：
       前端版本：5.13.2
       后端版本：v5.13.1-b893483d26ccce68c381b717f3551d5da96ed622

主机标签解绑失败：
![image](https://user-images.githubusercontent.com/20857328/196902363-af285af6-f14b-4169-aa68-dbff57fec647.png)

**Comment by UlricQin** [comment]
没有日志，没有请求的截图，没法查，bad issue
