### ISSUE TITLE
建议下钻和指标数据关联

### ISSUE THREAD

**Issue by masterjyq** [ccfos/nightingale#1218]
最好点击不同的指标数据实现传递不同的参数给下钻链接的URL，这样就可以看每条数据的详情，参数可以取指标的 label
![image](https://user-images.githubusercontent.com/29848365/197088252-3fd089aa-5d41-46bb-b7ca-eefee347dee0.png)

**Comment by UlricQin** [comment]
@jsers 这个需求提的好，可以考虑下
