### ISSUE TITLE
编译时报错

### ISSUE THREAD

**Issue by CyshallChan** [ccfos/nightingale#1219]
### Relevant server.conf | webapi.conf

```toml
无
```

### Relevant logs

```text
go build -gcflags="all=-N -l" -ldflags="-X 'github.com/didi/nightingale/v5/src/pkg/version.VERSION="v5.13.1-b893483d26ccce68c381b717f3551d5da96ed622"'" -o n9e ./src
# github.com/didi/nightingale/v5/src
panic: unexpected 32-bit segment

goroutine 1 [running]:
cmd/link/internal/ld.machoCombineDwarf(0x10512d9c8?, 0x1400000e0f8?, 0x140004fe000, {0x14002dec370?, 0x1?}, {0x14004ee2120, 0x53})
        /usr/local/go/src/cmd/link/internal/ld/macho_combine_dwarf.go:218 +0xfb4
cmd/link/internal/ld.(*Link).hostlink(0x14000100000)
        /usr/local/go/src/cmd/link/internal/ld/lib.go:1830 +0x4540
cmd/link/internal/ld.Main(_, {0x10, 0x20, 0x1, 0x1f, 0x1e, 0x7c00000, {0x105064576, 0x14}, {0x105067ee1, ...}, ...})
        /usr/local/go/src/cmd/link/internal/ld/main.go:378 +0x1444
main.main()
        /usr/local/go/src/cmd/link/main.go:72 +0xd98
make: *** [build-debug] Error 2
```

### System info

MacBook Pro M1 Pro，Mac os 12.6

### Steps to reproduce

go build -ldflags "-w -s -X github.com/didi/nightingale/v5/src/pkg/version.VERSION=$(RELEASE_VERSION)" -o $(SERVER_BIN) ./src
去除-ldflags的-w -s选项，然后编译。

### Expected behavior

正常编译

### Actual behavior

编译报错

### Additional info

go build的时候ldflags必须添加-s 和 -w选项不然就报错。

**Comment by UlricQin** [comment]
我们的Makefile中给的编译方式就是带有 `-s -w`的，你干嘛要删除？你的考虑是啥？

**Comment by CyshallChan** [comment]
> 

当然是为了保留调试信息调试呀。

**Comment by CyshallChan** [comment]
> 我们的Makefile中给的编译方式就是带有 `-s -w`的，你干嘛要删除？你的考虑是啥？

当然是为了保留调试信息调试呀。

**Comment by CyshallChan** [comment]
> 我们的Makefile中给的编译方式就是带有 `-s -w`的，你干嘛要删除？你的考虑是啥？

@UlricQin 当然是为了保留调试信息调试呀。

**Comment by UlricQin** [comment]
牛逼，但这不是夜莺的问题，这是你自己的环境问题，需要自行解决

```bash
[root@ulric-dev-10-206-16-10 nightingale]# RELEASE_VERSION=x.y.z
[root@ulric-dev-10-206-16-10 nightingale]# echo $RELEASE_VERSION
x.y.z
[root@ulric-dev-10-206-16-10 nightingale]# SERVER_BIN=n9e-new
[root@ulric-dev-10-206-16-10 nightingale]# go build -ldflags "-X github.com/didi/nightingale/v5/src/pkg/version.VERSION=$RELEASE_VERSION" -o $SERVER_BIN ./src
[root@ulric-dev-10-206-16-10 nightingale]# ls -l n9e-new
-rwxr-xr-x 1 root root 45515888 10月 21 16:23 n9e-new
```

**Comment by CyshallChan** [comment]
最后补充下吧，v5.13.1不支持mac os 12.6，M1系列的MacBook Pro下保留编译信息编译。

**Comment by UlricQin** [comment]
ulric@localhost nightingale % ls *n9e*
n9e-fe-5.13.1.tar.gz
ulric@localhost nightingale % go build -ldflags "-X github.com/didi/nightingale/v5/src/pkg/version.VERSION="v5.13.1-5d4acb6cc3a40e72d06a4cfbdac37b365fc1afe6"" -o n9e ./src
ulric@localhost nightingale % ls *n9e*                                                                                                                                     
n9e                  n9e-fe-5.13.1.tar.gz
ulric@localhost nightingale % go version
go version go1.18.4 darwin/arm64

<img width="586" alt="image" src="https://user-images.githubusercontent.com/2769466/197439223-fd715e7f-554d-4c43-893c-d1ea675d648c.png">

**Comment by CyshallChan** [comment]
> ```
> ulric@localhost nightingale % ls *n9e*
> n9e-fe-5.13.1.tar.gz
> ulric@localhost nightingale % go build -ldflags "-X github.com/didi/nightingale/v5/src/pkg/version.VERSION="v5.13.1-5d4acb6cc3a40e72d06a4cfbdac37b365fc1afe6"" -o n9e ./src
> ulric@localhost nightingale % ls *n9e*                                                                                                                                     
> n9e                  n9e-fe-5.13.1.tar.gz
> ulric@localhost nightingale % go version
> go version go1.18.4 darwin/arm64
> ```
> 
> 
>      
>   
> 
> <img alt="image" width="586" src="https://user-images.githubusercontent.com/2769466/197439223-fd715e7f-554d-4c43-893c-d1ea675d648c.png">

@UlricQin  啊，那为啥我不行，能看看你的.zshrc文件不？
