### ISSUE TITLE
即时查询bug

### ISSUE THREAD

**Issue by bbaobelief** [ccfos/nightingale#1222]
### Relevant server.conf | webapi.conf

```toml
前端版本：5.13.1
后端版本：v5.13.0-445d03e0969fa519aa5ceb0ecc2b46e6231db05f
```

### Relevant logs

```text
1
```

### System info

前端版本：5.13.1 后端版本：v5.13.0-445d03e0969fa519aa5ceb0ecc2b46e6231db05f

### Steps to reproduce

1.
2.
3.
...

### Expected behavior

1

### Actual behavior

1

### Additional info

语法有问题，但夜莺能查询
`sum_over_time(sum(cpu_usage_idle{ident="txxxxer01.bj"})[1d])`
![image](https://user-images.githubusercontent.com/3918461/197159665-75dd9f66-8ef9-4c2c-a04e-8ba7869ae897.png)
![image](https://user-images.githubusercontent.com/3918461/197159925-50480b8e-abfa-4459-bb3d-0ced94d1632a.png)

**Comment by UlricQin** [comment]
夜莺查询数据只是proxy，之所以能返回，是因为后端时序库可以返回
