### ISSUE TITLE
快捷视图，过滤后全选，选择的内容非过滤后的内容

### ISSUE THREAD

**Issue by shenghuofei** [ccfos/nightingale#1225]
### Relevant server.conf | webapi.conf

```toml
配置正常
```

### Relevant logs

```text
chrome 请求可以看到是所有的机器
```

### System info

n9e 5.13.1

### Steps to reproduce

1. 
<img width="239" alt="image" src="https://user-images.githubusercontent.com/5562615/197750657-0ccc2a64-f379-4be8-a925-6fff6e543299.png">

2.如图是过滤后的机器列表，点全选，选中的机器并不是过滤后的这些
3.
...

### Expected behavior

过滤后，全选时应该选中过滤后的列表

### Actual behavior

过滤后，全选时应该选中过滤后的列表

**Comment by UlricQin** [comment]
怎么判断不是过滤后的全部？拉取指标列表的接口，传的参数是什么

**Comment by shenghuofei** [comment]
> 
![Uploading image.png…]()

过滤后的机器8台，请求参数host=后面的参数很明显不是过滤后的机器，而且很明显就是所有的机器。
可以在搜索框输入过滤内容，然后点全选，看下请求参数和右边的图表

**Comment by UlricQin** [comment]
https://github.com/n9e/fe-v5/releases/tag/v5.14.3 这个版本修复了
