### ISSUE TITLE
监控视图-即时查询-Graph小bug

### ISSUE THREAD

**Issue by FengZh61** [ccfos/nightingale#1231]
前端 5.14.1
后端 5.14.0

![1666835722399](https://user-images.githubusercontent.com/98309003/198173593-db159e9a-9d2e-4e50-9cb5-12dc46ae5682.jpg)

![image](https://user-images.githubusercontent.com/98309003/198196064-543d7a3c-a0b5-4473-a9a3-ba4513cfe55c.png)

编辑promql 在label中的变量会穿透到下面的按钮，另外新版本的菜单是变了吗？有动画了？

需要鼠标悬在 label那里才会穿透过来 挪开就不会了

**Comment by UlricQin** [comment]
https://github.com/n9e/fe-v5/releases/tag/v5.14.3 这个版本修复了
