### ISSUE TITLE
导入监控大屏报错

### ISSUE THREAD

**Issue by FengZh61** [ccfos/nightingale#1233]
前端版本：5.13.0
后端版本：v5.13.0-445d03e0969fa519aa5ceb0ecc2b46e6231db05f

我之前新导入的一个大盘，然后删除了，再导入就报错了
重启也不行
我在最近几次的更新也没注意到有这个问题。
![image](https://user-images.githubusercontent.com/98309003/198222918-589b9fea-6a39-432f-80a4-f43de09c0be0.png)

2022/10/27 15:48:50 /home/runner/work/nightingale/nightingale/src/models/common.go:33 Error 1054: Unknown column 'public' in 'field list'
[0.248ms] [rows:0] INSERT INTO `board` (`group_id`,`name`,`tags`,`create_at`,`create_by`,`update_at`,`update_by`,`public`) VALUES (1,'ElasticSearch - 模板','Prometheus ElasticSearch ES',1666856930,'root',1666856930,'root',0)

这是webapi的日志

我在5.14.0版本新增、删除都没有问题，不知道是不是有啥隐藏的问题。

**Comment by jsers** [comment]
看着像是后端升级没有添加 public 字段

FengZh61 ***@***.***> 于2022年10月27日周四 15:51写道：

**Comment by FengZh61** [comment]
> 

找到问题了，我翻了一下初始化的sql，我在升级的过程中可能忘记更新sql了。
