### ISSUE TITLE
是否支持Opentelemetry导出

### ISSUE THREAD

**Issue by teaey** [ccfos/nightingale#1234]
**What would you like to be added**:

**Why is this needed**:

**Comment by UlricQin** [comment]
n9e-webapi 和 n9e-server 这俩模块都暴露了 `/metrics` 接口

**Comment by teaey** [comment]
> n9e-webapi 和 n9e-server 这俩模块都暴露了 `/metrics` 接口

采集端如果通过OTel的metrics，这部分集成是否有最佳实践？

**Comment by UlricQin** [comment]
看不懂你想问什么
