### ISSUE TITLE
n9e快捷视图中可以一键生成promql语句

### ISSUE THREAD

**Issue by wangteng0906** [ccfos/nightingale#1235]
**What would you like to be added**:
快捷视图中可以一键生成promql语句
**Why is this needed**:
这样可以在快捷视图中选择计算函数，聚合函数以及维度，选择好之后如果能一键生成promql语句那就再好不过了。

**Comment by jsers** [comment]
看上去是个不错的提议，后面版本考虑支持下

wangteng0906 ***@***.***> 于2022年10月28日周五 16:47写道：

**Comment by jsers** [comment]
v6 正式版已经支持
