### ISSUE TITLE
container in docker-compose has different timezone

### ISSUE THREAD

**Issue by Jason4XuTao** [ccfos/nightingale#1239]
1.  some container(agentd/categraf/ibex/prometheus) have wrong timezone
[root@n01bastion01 docker]# docker-compose exec nserver date +"%Z %z"
CST +0800
[root@n01bastion01 docker]# docker-compose exec agentd date +"%Z %z"
Asia +0000
[root@n01bastion01 docker]# docker-compose exec categraf date +"%Z %z"
Asia +0000
[root@n01bastion01 docker]# docker-compose exec ibex date +"%Z %z"
Asia +0000
[root@n01bastion01 docker]# docker-compose exec mysql date +"%Z %z"
CST +0800
[root@n01bastion01 docker]# docker-compose exec nwebapi date +"%Z %z"
CST +0800
[root@n01bastion01 docker]# docker-compose exec prometheus date +"%Z %z"
UTC +0000
[root@n01bastion01 docker]# docker-compose exec redis date +"%Z %z"
CST +0800

I tried to use volume to change timezone of containers, but not work.

2. some container(nserver) has the right timezone, but application in the container has wrong timezone.
{"log":"2022-10-31 14:06:03.383050 INFO engine/logger.go:19 event(ae44444241b7a26ce99d9cff365144c0 triggered) consume: rule_id=3 [__name__=mem_available_percent app=gitlab ident=categraf01 rulename=机器负载-内存较高，请关注 source=categraf]8.84286@1667196363 \n","stream":"stdout","time":"2022-10-31T06:06:03.383259255Z"}

I have no idea how to change application timezone to ensure correct log timestamp.

**Comment by kongfei605** [comment]
Image contains timezone info in directory /usr/share/zoneinfo,  and docker compose file set env “TZ=Asia/Shanghai" , this will be read by golang application. Other applications could try this way, too.
Image of categraf will add tzdata soon.

**Comment by UlricQin** [comment]
新版本的 n9e-server 有个配置，ForceUserServerTS = true，如果设置为true，就表示用n9e-server的服务端时间，直接忽略客户端时间，一定程度上可以规避时区的问题

**Comment by kongfei605** [comment]
> Image contains timezone info in directory /usr/share/zoneinfo, and docker compose file set env “TZ=Asia/Shanghai" , this will be read by golang application. Other applications could try this way, too. Image of categraf will add tzdata soon.

 categraf:v0.2.18-amd64 iamge contains tzdata now
