### ISSUE TITLE
屏蔽规则增加周期性屏蔽

### ISSUE THREAD

**Issue by shawnloong** [ccfos/nightingale#1282]
屏蔽规则可以增加周期性屏蔽，如早上晚上22:00至凌晨05:00

**Comment by laiwei** [comment]
@shawnloong 你可以在告警策略设置的时候，通过设置生效时间来达到这个目的。

**Comment by shawnloong** [comment]
多个周期时间段，跨天之类的

**Comment by shawnloong** [comment]
> @shawnloong 你可以在告警策略设置的时候，通过设置生效时间来达到这个目的。

比如每天凌晨1-3点维护，指定item,告警策略是全局的

**Comment by 710leo** [comment]
v6 版本已支持
