### ISSUE TITLE
告警策略，支持告警值单位配置

### ISSUE THREAD

**Issue by GitHamburg** [ccfos/nightingale#1287]
PromQL语法中可能会有*100、/1024等换算，监控数据和告警值具备对应的单位含义
**What would you like to be added**:
支持告警值单位配置
**Why is this needed**:
告警信息中的告警值带上单位，含义更加明确

**Comment by wushengwusheng** [comment]
同意，强烈建议加单位

**Comment by UlricQin** [comment]
陈旧需求无PR关闭。

在备注或者标题里写单位就可以了，新版也可以在自定义字段里写。
