### ISSUE TITLE
可否做数据转换模块

### ISSUE THREAD

**Issue by Shane-Meng** [ccfos/nightingale#1288]
**数据转换模块**:

**我的设备很弱，不支持再安装采集器**:

我服务于一家微型的做农业物联网的公司，公司现在有一个需求，希望用类似Prometheus或者夜莺类的平台，监控所有的端点的状态，由于这些设备的计算能力都很弱，且网络连接不稳定。现在不想再安装expoter增加设备的负载。设备内置的应用会提供一些状态数据给到服务器端。最优解：请问有可能将此类设备的状态信息，从mysql转换到夜莺平台么？次优解：如不能，可否提供API，让开发看看能不能改下内置程序，将这些状态信息再追加一套送到夜莺？

**Comment by laiwei** [comment]
@Shane-Meng 可以了解一下[ flashcat.cloud 北极星组件](https://flashcat.cloud/product/polaris/) ，支持将MySQL的数据转为实时的时序数据，并加以展示和报警。

**Comment by Shane-Meng** [comment]
好的，谢谢🙏
