### ISSUE TITLE
是否支持企业微信号来告警啊

### ISSUE THREAD

**Issue by hubeixulu** [ccfos/nightingale#1309]
目前用的版本是5.14.1
在告警配置里面找到的通知选项，都是各种机器人，但是我们公司的企业微信群不支持自己创建机器人，IT那边给了企业微信号，但是没有找到这个选项啊

**Comment by UlricQin** [comment]
只有企业微信号还不够，还得让IT的人给你们创建企业微信的app，拿到corpid、agentid、secret之类的，这个事才能干
