### ISSUE TITLE
飞书告警消息模板支持 ”消息卡片“ 模式，能够使用 ”lark_md“ 消息格式

### ISSUE THREAD

**Issue by ixiaoyi93** [ccfos/nightingale#1327]
**What would you like to be added**:
飞书告警消息模板支持 ”消息卡片“ 模式，能够使用 ”lark_md“ 消息格式。

**Why is this needed**:
飞书 V2 报警模板，能够根据告警的状态（类似于钉钉和企业微信告警模板里的功能）实现不同的 title color。偏于区分告警的状态，更加方便运维以及业务人员关注告警信息。

**Comment by jicki** [comment]
emmmm 其实我有实现这个功能.  我可以整理一下提一个 pr
