### ISSUE TITLE
服务器双网卡，如何指定所监控的网卡？

### ISSUE THREAD

**Issue by jiangshilin** [ccfos/nightingale#1334]
服务器双网卡，安装文档中的方案，采用docker-compose做了all in one部署，net_bytes_recv等网络指标显示的是eth0的值，我需要另一块网卡的流量数据，请问如何操作？

**Comment by kongfei605** [comment]
编辑 docker/categraf/conf/input.net/net.toml 。 采集配置找categraf对应的插件就可以。
