### ISSUE TITLE
夜莺三方登录获取用户电话信息BUG

### ISSUE THREAD

**Issue by hiflycat** [ccfos/nightingale#1344]
### Relevant server.conf | webapi.conf

```toml
xxx
```

### Relevant logs

```text
xxx
```

### System info

all

### Steps to reproduce

1. 三方登录这里，如果三方sso没有传电话号码，每次登录都会把电话更新为空，如果手动在系统里面更新，再次登录就会更更新空
2.
3.
...

### Expected behavior

在三方登录这里加个判断信息是否为空

### Actual behavior

<img width="919" alt="image" src="https://user-images.githubusercontent.com/25202901/210730892-9ea6d709-d112-4216-8396-d90b79e09b09.png">

**Comment by UlricQin** [comment]
改了一下代码，已提交main分支

**Comment by hiflycat** [comment]
> 改了一下代码，已提交main分支

看了下代码，oauth 和cas那里应该也是一样的

**Comment by UlricQin** [comment]
嗯，刚都改了
