### ISSUE TITLE
添加附加标签后，告警里只显示该附加标签及规则名称

### ISSUE THREAD

**Issue by Jason4XuTao** [ccfos/nightingale#1346]
### Relevant server.conf | webapi.conf

```toml
告警规则里，如果添加了附加标签，生成的告警就没有其它标签了，只有添加的附加标签和rulename

我使用的是docker compose，具体版本如下：
前端版本：5.13.0
后端版本：v5.13.0-445d03e0969fa519aa5ceb0ecc2b46e6231db05f
```

### Relevant logs

```text
检查规则对应的告警
```

### System info

n9e 5.13.0

### Steps to reproduce

1. 为告警规则添加附加标签
2.检查对应规则的新告警
3.
...

### Expected behavior

除了新添加的附加标签，还应该保留原来的所有标签及值

### Actual behavior

只有附加标签和规则名称标签

**Comment by 710leo** [comment]
@Jason4XuTao  提供下相关的截图吧，告警曲线在即时查询页面的截图，告警的详情页截图，告警规则的截图

**Comment by Jason4XuTao** [comment]
![告警规则](https://user-images.githubusercontent.com/7019288/211235782-7798b35b-4291-4afc-97dc-7116aa46042c.png)
![告警-附加标签和未附加标签对比](https://user-images.githubusercontent.com/7019288/211235803-b2d20843-e871-4523-8d95-ea23f30b5e4e.png)
![规则-附加标签](https://user-images.githubusercontent.com/7019288/211235814-6fd48789-4697-45e9-8e10-043c36d83a36.png)
![规则-未附加标签](https://user-images.githubusercontent.com/7019288/211235825-d32348e3-90a2-490d-bd2d-0deacd3d84d5.png)

**Comment by 710leo** [comment]
@Jason4XuTao 可以先升级到最新版本，然后再看下是否还存在问题
