### ISSUE TITLE
无法取消已勾选的业务组

### ISSUE THREAD

**Issue by liuxin638507** [ccfos/nightingale#1349]
### Relevant server.conf | webapi.conf

```toml
docker-compose默认配置
```

### Relevant logs

```text
docker-compose默认配置
```

### System info

n9e server 5.14.4

### Steps to reproduce

无法取消已选择的业务组，再次点击还是当前业务组，查看不了所有节点信息
![d0c2732f3525443f0822afaaae7582b](https://user-images.githubusercontent.com/32058132/211282303-1da09565-c153-4b9d-b01b-e5b6ba9efd2e.png)

### Expected behavior

docker-compose默认配置

### Actual behavior

docker-compose默认配置

**Comment by UlricQin** [comment]
已提到 github.com/n9e/fe-v5
