### ISSUE TITLE
编辑告警规则时，每编辑一次都在浏览器新增加一个标签打开，多次编辑后浏览器打开一大堆标签！

### ISSUE THREAD

**Issue by hel2o** [ccfos/nightingale#1356]
**What would you like to be added**:
建议还是在一个页面里操作的好，这样太影响使用了
**Why is this needed**:
浏览器标签太多，多次编辑后

![7626f15d91683c325f37a28322ff234](https://user-images.githubusercontent.com/14226648/212226517-935ca9cf-58e5-4057-92e4-87a69c66fa4e.png)

**Comment by rt005744** [comment]
是的，影响体验了
