### ISSUE TITLE
数据标签变化时，会出现误告警

### ISSUE THREAD

**Issue by MethTo** [ccfos/nightingale#1366]
### Relevant server.conf | webapi.conf

```toml
不涉及
```

### Relevant logs

```text
无异常日志
```

### System info

n9e 5.14.4/5.10.0 均复现该问题 系统：CentOS Linux release 7.9.2009 (Core)

### Steps to reproduce

1.配置告警规则 test
![image](https://user-images.githubusercontent.com/34958405/215373493-3b513001-4e48-4a0d-bc84-e252f7c82b36.png)
![image](https://user-images.githubusercontent.com/34958405/215373511-0cc269e3-59da-4069-a0ad-bf6aafa307f8.png)

2.构造异常数据,触发告警条件时，采集数据的key有不同的标签
![image](https://user-images.githubusercontent.com/34958405/215374050-3af819a0-fb51-4f42-9108-10442b0d6abe.png)
![image](https://user-images.githubusercontent.com/34958405/215374076-b021fdd5-93e2-4323-a6cf-b4b11d7e2f71.png)

3.此时立刻恢复数据为正常的标签以及值
4.触发告警。本次告警由单个数据点触发，且3min后告警自动恢复
![image](https://user-images.githubusercontent.com/34958405/215374383-488c2639-2d8d-4629-a30f-f961ce991f85.png)

### Expected behavior

标签不同的数据，虽然在图中会显示为两条线，但是单个数据点不应该触发告警。

### Actual behavior

单个数据点会触发告警

**Comment by UlricQin** [comment]
符合预期，prometheus也是这个行为。关键逻辑跟下面两个行为有关：

1，告警引擎的逻辑是，根据用户配置的promql查数据，查到了，就产生告警，查到几条就产生几个event，如果后面对应的event查不到了，就恢复
2，prometheus里的数据，如果只有一个点，并且prometheus的启动参数query.lookback-delta没有做额外调整（默认5分钟），5分钟内发起查询，永远都是返回对应的那个点

这里提到了类似的问题：https://time.geekbang.org/column/article/623851

**Comment by MethTo** [comment]
> 符合预期，prometheus也是这个行为。关键逻辑跟下面两个行为有关：
> 
> 1，告警引擎的逻辑是，根据用户配置的promql查数据，查到了，就产生告警，查到几条就产生几个event，如果后面对应的event查不到了，就恢复 2，prometheus里的数据，如果只有一个点，并且prometheus的启动参数query.lookback-delta没有做额外调整（默认5分钟），5分钟内发起查询，永远都是返回对应的那个点
> 
> 这里提到了类似的问题：https://time.geekbang.org/column/article/623851

感谢回复。

这里补充一下： [VM文档](https://docs.victoriametrics.com/keyConcepts.html#instant-query)
如果使用VictoriaMetrics，可以在查询接口处使用step参数修改默认的时间。例如我这里改成3min
<img width="836" alt="image" src="https://user-images.githubusercontent.com/34958405/215410434-9806b9f0-5fde-49d0-80c2-3bfa274a7c6a.png">
目前n9e这里的查询接口貌似只能用默认的，有需要改的可以在这里加一个step参数试试
![image](https://user-images.githubusercontent.com/34958405/215410902-b435a183-1811-423b-b41b-26894c513def.png)
