### ISSUE TITLE
nightingale后期是否支持告警相关的优化？比如说告警的降噪和抑制？

### ISSUE THREAD

**Issue by Shuimo03** [ccfos/nightingale#1367]
**What would you like to be added**:

**Why is this needed**:

**Comment by jicki** [comment]
emmmmm 需要~

**Comment by laiwei** [comment]
告警的聚合降噪、抑制、排班、协同，目前是以SaaS的形式提供的： https://flashcat.cloud/product/flashcat-duty/

**Comment by Shuimo03** [comment]
好的，十分感谢！
