### ISSUE TITLE
关于告警规则预案链接无法获取到labels标签

### ISSUE THREAD

**Issue by walingcc** [ccfos/nightingale#1375]
![image](https://user-images.githubusercontent.com/37326329/218365512-e176b6a2-3ea2-4f41-a0a0-30b6b844f4f7.png)
请问下，告警规则里面的预案链接是固定写死的链接吗？我无法获取到{{$labels.group_name}}标签

**Comment by tanxiao1990** [comment]
预计V6版本会支持变量
