### ISSUE TITLE
【前端建议】菜单自动伸缩

### ISSUE THREAD

**Issue by nondevops** [ccfos/nightingale#1378]
现象：
1、当前v5.15.0版本，打开导航菜单，在点击多个导航菜单后，会出现流水式下拉展示，看上去非常臃肿。
2、每一个菜单展开后，父级菜单比如告警管理太不明显，不熟悉的人还以为不能点告警管理这几个字后缩回去呢。
<img width="189" alt="image" src="https://user-images.githubusercontent.com/12181410/218907209-ca31d78f-86aa-4876-affe-5e366740301d.png">

建议：
菜单打开后能自动伸缩，当前只展示一个独立模块的菜单，其他菜单全部缩回去。
菜单展开后，对菜单的父级目录进行着重标记，让所有人知道可以缩回去。

**Comment by UlricQin** [comment]
再有两三周就发布v6的beta版本了，到时候一并解决这个菜单的问题，提供一个更好的设计
