### ISSUE TITLE
建议告警规则附加标签，支持表达式

### ISSUE THREAD

**Issue by masterjyq** [ccfos/nightingale#1379]
建议告警规则的附加标签和规则备注一样， 支持表达式， 效果如下
配置
![image](https://user-images.githubusercontent.com/29848365/218908868-54398930-edfb-4220-8018-0b7cf2ea1893.png)
效果
![image](https://user-images.githubusercontent.com/29848365/218909110-f9cac9b2-a44d-45d7-90fb-e784ab9294f2.png)

**Comment by UlricQin** [comment]
这个需求感觉不强，什么场景需要这个能力？promql也支持做label_replace之类的，另外如果只是针对通知的消息的话，tpl里也可以做拼接

**Comment by masterjyq** [comment]
> 这个需求感觉不强，什么场景需要这个能力？promql也支持做label_replace之类的，另外如果只是针对通知的消息的话，tpl里也可以做拼接

主要是针对告警信息使用webhhok 推送第三方，指标数据都需要一些标准的字段

**Comment by UlricQin** [comment]
你们用的什么第三方？正常来讲都是这类第三方系统来适配监控，比如pagerDuty bigpanda都是主动去适配监控系统。如果还没有办法适配的则需要加一个adapter。另外，这种对接一般不止是标签的问题，还需要其他多个字段的调整，还是需要在某个地方加入更多适配逻辑

**Comment by masterjyq** [comment]
POD， Deployment， 这些对象的 PromQL 出来的tag 没有统一标识字段，比如当前告警对象是什么类型， 告警对象的名称是什么， POD 的 promeQL 中 pod_name 标签表示当前对象名称， Deployment 的promQL 中 deployment 标签表示当前对象名称，不易于管理，在 adapter中针对不同的告警对象取不同的标签很麻烦，添加固定的标签后，我在adapter中取固定的标签就可以了， 我这边是有将告警对象的类型和名称提取为单独字段的需求， 针对这个做了改造，如果这个需求不太通用那可以不用考虑了。

这个功能需求也是源自于以前Prometheus 的告警是这样配置的
![image](https://user-images.githubusercontent.com/29848365/219531817-900b009a-7c89-45bd-a1ae-51502bdbfe16.png)

**Comment by UlricQin** [comment]
我知道你这个需求的出发点了

**Comment by masterjyq** [comment]
V6 版本添加了此功能

**Comment by foreverrice** [comment]
> V6 版本添加了此功能

哈喽，我正好在用这个功能，但是prometheus的labels通过{{$labels.proj}}去加标签变量，proj='',并没有拿到我在prometheus的labels变量
