### ISSUE TITLE
使用docker一键部署5.15版本，如果categraf采集器停止工作，prometheus 仍然会有延后的数据，导致告警延迟，大约延迟4min

### ISSUE THREAD

**Issue by alexg9781** [ccfos/nightingale#1380]
### Relevant server.conf | webapi.conf

```toml
v5.15 版本源码中默认配置 nightingale-main/docker/n9eetc/
```

### Relevant logs

```text
docker categraf logs   # 注册成功后，先关闭，待webapi上显示down后，开启categraf再立即关闭

2023/02/15 16:34:09 agent.go:47: I! [*agent.MetricsAgent] started
2023/02/15 16:34:09 agent.go:50: I! agent started
2023/02/15 16:34:13 main.go:106: I! received signal: terminated
2023/02/15 16:34:13 agent.go:54: I! agent stopping
2023/02/15 16:34:13 agent.go:62: I! [*agent.MetricsAgent] stopped
2023/02/15 16:34:13 agent.go:65: I! agent stopped
2023/02/15 16:34:13 main.go:121: I! exited
```

### System info

CentOS Linux release 7.9.2009 (Core)，docker version 23.0.1

### Steps to reproduce

1. git clone https://github.com/ccfos/nightingale.git
2. docker-compose -f nightingale-main/docker/docker-compose.yaml up -d
3. 登录webapi大盘,待 categraf01 机器 UP
4. 关闭采集器 docker stop  categraf
5. webapi 中选择 监控看图 -- 即时查询 输入查询 `target_up{ident="categraf01"}[1m]`
6. 发现Prometheus中在categraf采集器停止工作后，仍然有相关数据，大约延迟4min后数据发生变化
...

### Expected behavior

采集器机器停止后，Prometheus应该立即或延迟几秒钟数据有变化 
查询语句 `target_up{ident="categraf01"}[1m]`

### Actual behavior

4min后数据才有相应变化

**Comment by tanxiao1990** [comment]
docker\n9eetc\server.conf

[NoData]
Metric = "target_up"
# unit: second
Interval = 120

代表至少120秒没有收到数据，target_up值才会变为0
