### ISSUE TITLE
建议：告警屏蔽-删除屏蔽原因字段

### ISSUE THREAD

**Issue by bbaobelief** [ccfos/nightingale#1383]
前端版本：5.15.0
后端版本：v5.15.0-87899cbedbc7bfcfff61052ebeed945a57a418d2

告警屏蔽，规则备注和屏蔽原因 有点重复,每次写原因都需要写两次，建议 保留规则备注 改成 textarea
![image](https://user-images.githubusercontent.com/3918461/219992754-5c6e44d6-0539-435c-93b4-d89a30f98abf.png)

**Comment by jicki** [comment]
可以改修改为 非必填 应该就好了

**Comment by 710leo** [comment]
v6 版本已改成非必填项
