### ISSUE TITLE
管理页面删除监控对象后，告警依然会触发

### ISSUE THREAD

**Issue by allenz92** [ccfos/nightingale#1387]
### Relevant server.conf | webapi.conf

```toml
不涉及
```

### Relevant logs

```text
不涉及
```

### System info

v5.13.1-b893483d26ccce68c381b717f3551d5da96ed622

### Steps to reproduce

1. 被监控对象上kill categraf 进程
2. 服务端删除监控对象【在target_up变为0之前删除】
3. 观察告警，依然在继续

### Expected behavior

不触发相关告警

### Actual behavior

触发相关告警

**Comment by UlricQin** [comment]
v6版本来提供更好的失联告警机制

**Comment by 710leo** [comment]
v6 支持了 host 类型的机器失联告警
