### ISSUE TITLE
n9e-server remote-writer写入报错

### ISSUE THREAD

**Issue by pangpeng** [ccfos/nightingale#1391]
version:
Prometheus: v2.28.1
n9e:
前端版本：5.14.3
后端版本：v5.14.5

安装参考:
http://n9e.flashcat.cloud/docs/install/server/#%e7%bb%84%e4%bb%b6%e5%ae%89%e8%a3%85
我因9090被现有Prometheus占用,另起一个实例9091
server.conf,webapi.conf配置的9090改成9091

n9e-server 日志报错:
WARNING writer/writer.go:78 post to http://127.0.0.1:9091/api/v1/write got error: push data with remote write request got status code: 400, response body: out of bounds

n9e Prometheus 日志报错:
level=error ts=2023-02-22T07:28:14.065Z caller=write_handler.go:53 component=web msg="Out of order sample from remote write" err="out of bounds"

监控数据写入一点后,就无数据了
<img width="1426" alt="image" src="https://user-images.githubusercontent.com/8667405/220552560-f7bf98e1-ebaf-45e7-9fca-0c8511286fcc.png">

**Comment by 710leo** [comment]
@pangpeng  可以看下这个 https://github.com/ccfos/nightingale/discussions/1162
