### ISSUE TITLE
使用step参数后，改变时间范围，夜莺的采样点为7:00一直不变

### ISSUE THREAD

**Issue by lidageone** [ccfos/nightingale#1405]
### Relevant server.conf | webapi.conf

```toml
delta(disk_used{fstype!="UDF",ident="$ident",device="$device"}[24h])
step设置为86400，意味着1天采一个点
```

### Relevant logs

```text
无相关日志
```

### System info

5.14.3

### Steps to reproduce

1.夜莺step设置为86400 改变时间范围
![image](https://user-images.githubusercontent.com/22410073/222074427-c111f8a0-0dd9-40c0-ba32-018ad77c213d.png)

2.grafana step设置为86400，改变时间范围
![1677656224895](https://user-images.githubusercontent.com/22410073/222074607-47640627-917f-4882-94ff-820d603c5bd4.jpg)

### Expected behavior

夜莺和grafana的采样点保持一致，采样点都会随着时间改变

### Actual behavior

无论怎么改变时间范围，夜莺的采样点始终为7:00那个时刻的值
grafana的采样点会随着时间范围进行改变
![1677656224895](https://user-images.githubusercontent.com/22410073/222074980-16018623-c779-40e7-a29b-78595119c3ca.jpg)

**Comment by 710leo** [comment]
@jsers 可以看看哈
