### ISSUE TITLE
希望可以在表格中可以显示默认的时间这个字段，方便用户按照时间字段统计数据

### ISSUE THREAD

**Issue by lidageone** [ccfos/nightingale#1406]
**What would you like to be added**:
如下图，目前夜莺的表格不支持显示time这个label,而grafana是支持的
![image](https://user-images.githubusercontent.com/22410073/222079324-7f9dddcf-3aec-433b-adb6-142f97375dd4.png)
![image](https://user-images.githubusercontent.com/22410073/222079781-c3862649-d5c8-4835-b02e-d25777bf1e51.png)

**Why is this needed**:
时序数据库的time是一个比较重要的字段，用户做监控报表经常有按照时间统计数据的需求

**Comment by jsers** [comment]
现在表格的设计无法满足，目前表格会对所有时间点数据做统计后信息展示(last、sum、avg 等)，这时候已经没有详细的时间点信息了。
如果要支持需要有个新的展示形态，这个会放到后面 v6 某个中版本升级里面做吧，顺带还有其他的一些表格的需求到时候一起处理

**Comment by jsers** [comment]
v7 版本起在取值计算里新增了 ”原始值“，选择原始值后显示列里可选择 __ time__ 时间字段
