### ISSUE TITLE
The  dashboard shows spike fluctuations in the values, but after clicking edit, the spike fluctuations disappear.

### ISSUE THREAD

**Issue by nondevops** [ccfos/nightingale#1412]
### Relevant server.conf | webapi.conf

```toml
不涉及
```

### Relevant logs

```text
不涉及
```

### System info

CentOS Linux release 7.8.2003 (Core)

### Steps to reproduce

这是前端显示问题还是数据采集异常问题诶？第一个图是没编辑的图表，第二图是点击编辑之后的图表。第一个图有数据值波动，第二图点进去看又没有数据值波动。 
![7770b0e970993a4205cb2cb1547872c](https://user-images.githubusercontent.com/12181410/223135113-e527a5d3-0a8a-4f82-b4e1-9833113d91cd.png)
![0eacf9cf326e3d7b51fcfb6d164ab34](https://user-images.githubusercontent.com/12181410/223135140-0968ddb5-48a5-47e5-bf8d-958e56c99b95.png)
![1c6426583ef7f8ca549f86b020eb062](https://user-images.githubusercontent.com/12181410/223135191-5e870445-941b-4908-b428-a62151695c81.png)

### Expected behavior

不涉及

### Actual behavior

不涉及

**Comment by nondevops** [comment]
@

> 

可以的。

**Comment by UlricQin** [comment]
你看左侧的坐标，多个值都是0，这实际是计算机系统对float类型的值不严格准确导致的。不过我们在产品上尝试做一些规避，@jsers 看看是否有方案
