### ISSUE TITLE
时间序列图的 Legend 的 Table 模式下列支持是否展示

### ISSUE THREAD

**Issue by masterjyq** [ccfos/nightingale#1422]
当表格过小的时候, Max, Min, Avg, Sum 这列都展示会比较挤, 可以和Grafana类似,  添加配置, 是否展示这些列, 我这边已经基于v6 修改, 需要的话可以贡献代码.
配置方式:
![image](https://user-images.githubusercontent.com/29848365/224881659-a4c961ea-6a74-43b3-b83c-feb7ee18130d.png)
效果:
![image](https://user-images.githubusercontent.com/29848365/224879407-001f9a4d-2ac8-4cf9-a4e6-ed288f02aaf8.png)

**Comment by UlricQin** [comment]
👍🏻

**Comment by jsers** [comment]
可以搞成一个选项 Legend values，默认就全选吧兼容下现有的模式
欢迎共享代码

**Comment by masterjyq** [comment]
> 可以搞成一个选项 Legend values，默认就全选吧兼容下现有的模式 欢迎贡献代码

这种方式可行吗？ 默认是空， 空的话就展示全部
![image](https://user-images.githubusercontent.com/29848365/224925861-c890164f-c620-4cd8-bec7-83e45e49501b.png)

**Comment by masterjyq** [comment]
参考了，表格里面图表样式的设计
![image](https://user-images.githubusercontent.com/29848365/224936889-d3fcdc12-4bd7-41ed-90ba-e205497af244.png)

**Comment by masterjyq** [comment]
Merged: [https://github.com/n9e/fe/pull/1](https://github.com/n9e/fe/pull/1)
