### ISSUE TITLE
希望v6将web和write端口分开

### ISSUE THREAD

**Issue by itlaborer** [ccfos/nightingale#1423]
### Relevant server.conf | webapi.conf

```toml
v6将web和server合并到同一个n9e中，这是好事，但没必要把端口合并在一起
1.功能方面，一个只是做为网页展示用，另一个是做为客户端调用接口用来写数据
2.安全方面，在需要对公网显示大屏时，同时也会端口被调用写垃圾数据的风险
```

### Relevant logs

```text
无
```

### System info

n9e v6

### Steps to reproduce

无

### Expected behavior

无

### Actual behavior

无

**Comment by 710leo** [comment]
@itlaborer  v6.0.0-beta.1 已支持通过配置将 server 接口关闭
