### ISSUE TITLE
新加的Iframe组件, 参数可以添加开始时间和结束时间参数

### ISSUE THREAD

**Issue by masterjyq** [ccfos/nightingale#1431]
之前我自己开发了一个Link 组件, 作用和现在的Iframe基本一致, 为了和Grafana 联动, 把开始时间和结束也作为变量, 在URL中替换,  传了过去.
效果:
展示近30分钟的数据
![image](https://user-images.githubusercontent.com/29848365/225802266-2363e596-b2ed-4a99-8908-045cd9a32053.png)
展示近15分钟的数据
![image](https://user-images.githubusercontent.com/29848365/225802195-cb1ba833-2444-4f7a-9a78-4c4ed4c94afc.png)

**Comment by UlricQin** [comment]
👍🏻 @jsers 看看

**Comment by UlricQin** [comment]
@masterjyq 可以考虑来个pr？

**Comment by masterjyq** [comment]
> @masterjyq 可以考虑来个pr？

OK, 我整理一下

**Comment by jsers** [comment]
你之前是怎么处理的，现在是支持添加大盘变量的
关于时间其实是也是一种变量，后面是准备添加两个内置变量 $__from 和 $__to
这里会存在一个问题就是怎么适配那些嵌入进来的地址支持的时间值格式

Talon ***@***.***> 于2023年3月17日周五 13:02写道：

**Comment by masterjyq** [comment]
>
我处理目前只支持了时间戳格式,  添加了 _start,  _startms,  _end, _endms  分别支持秒和毫秒

**Comment by jsers** [comment]
要不这样处理
![image](https://user-images.githubusercontent.com/7424634/225836553-8b4a347d-6a68-4116-82f4-0097fe05fab8.png)

最后 date foramt 先不搞了，不支持 : 感觉意义不大

**Comment by jsers** [comment]
或者改下格式，时间值格式冒号应该比下划线更加常用一些，用下划线来分割参数就行了
${__from}
${__from_date_iso}
${__from_date_seconds}
${__from_date_YYYY-MM-DD HH:mm:ss}

**Comment by masterjyq** [comment]
ok , 我搞一下, 提一下PR
