### ISSUE TITLE
夜莺对接VictoriaMetrics集群

### ISSUE THREAD

**Issue by liufangpeng** [ccfos/nightingale#1433]
首先部署的是VictoriaMetrics集群。
在夜莺的server.conf和webapi.conf上面配置VictoriaMetrics的地址是
1、Nginx做过负载之后的地址：端口
2、配置一个库的地址：端口
3、配置三个库的地址：端口
应该是配置哪一个呢这个配置不太清楚

**Comment by 710leo** [comment]
@liufangpeng  看下这个视频教程，你就明白了 https://flashcat.cloud/media/?type=夜莺监控&source=aHR0cHM6Ly9kb3dubG9hZC5mbGFzaGNhdC5jbG91ZC9uOWUtMDctdXNpbmctbXVsdGktdHNkYi12MS5tcDQ=

**Comment by liufangpeng** [comment]
还是有点不明白，如果我部署一套VictoriaMetrics集群三个实例。对接夜莺server、webapi的话需要把三个实例的写入端口和读取端口做一个负载之后在夜莺里配置吗

**Comment by liufangpeng** [comment]
同时咨询一下Redis和Mysql主要存储的什么数据

**Comment by allenz92** [comment]
> 首先部署的是VictoriaMetrics集群。 在夜莺的server.conf和webapi.conf上面配置VictoriaMetrics的地址是 1、Nginx做过负载之后的地址：端口 2、配置一个库的地址：端口 3、配置三个库的地址：端口 应该是配置哪一个呢这个配置不太清楚

第一种即可

**Comment by 710leo** [comment]
> 还是有点不明白，如果我部署一套VictoriaMetrics集群三个实例。对接夜莺server、webapi的话需要把三个实例的写入端口和读取端口做一个负载之后在夜莺里配置吗

是的

**Comment by yueqianlong** [comment]
> @liufangpeng 看下这个视频教程，你就明白了 [https://flashcat.cloud/media/?type=夜莺监控&source=aHR0cHM6Ly9kb3dubG9hZC5mbGFzaGNhdC5jbG91ZC9uOWUtMDctdXNpbmctbXVsdGktdHNkYi12MS5tcDQ=](https://flashcat.cloud/media/?type=%E5%A4%9C%E8%8E%BA%E7%9B%91%E6%8E%A7&source=aHR0cHM6Ly9kb3dubG9hZC5mbGFzaGNhdC5jbG91ZC9uOWUtMDctdXNpbmctbXVsdGktdHNkYi12MS5tcDQ=)

视频里多个时序库webapi.conf的[[Clusters]] 和server.conf的[[readers]]配置了，server.conf里的ClusterName和writers怎么配呢？
![image](https://user-images.githubusercontent.com/86765439/227863584-5463b068-5c22-44d7-8e82-bc793fb82ea7.png)
