### ISSUE TITLE
关于采集器与n9e版本对应关系

### ISSUE THREAD

**Issue by 1725785880** [ccfos/nightingale#1434]
**What would you like to be added**:
希望每次Releases的时候，能在文档里注明Categraf(当然也可能是其他采集器)版本与n9e版本之间的对应关系，或者说是内部测试推荐使用的版本
**Why is this needed**:
在使用n9e5.x的时候，一切正常，将n9e升级到6.x，数据库也换成对应的6.x版本，categraf版本没有更换，发现categraf并没有正确上传ident标签，导致对象列表显示异常，通过数据库直接增加target后显示的状态是不正确的。所以希望每次releases的时候能够同时提供n9e/categraf推荐版本。谢谢

**Comment by UlricQin** [comment]
嗯，如果有不兼容升级，后面发版的时候说明一下。6.x确实需要依赖最新版本的categraf，建议是v0.2.35
