### ISSUE TITLE
希望能兼容腾讯云TDSQL-C Mysql

### ISSUE THREAD

**Issue by liangjaden** [ccfos/nightingale#1436]
部署项目时，用了腾讯云TDSQL-C Mysql作为外置数据库，容器nightingale-nserver 启动失败，报错如下：
2023/03/20 16:52:06 �[31;1m/home/runner/work/nightingale/nightingale/src/models/target.go:82 �[35;1mError 1064: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'cluster = ?' at line 1
�[0m�[33m[0.998ms] �[34;1m[rows:0]�[0m SELECT count(*) as total,max(update_at) as last_updated FROM target WHERE cluster = 'Default'
failed to sync targets: failed to exec TargetStatistics: Error 1064: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'cluster = ?' at line 1

经与腾讯云客服沟通，确认是cluster字段被腾讯云占用导致，客服建议如下：
![image](https://user-images.githubusercontent.com/54787532/226566381-dd822824-2881-40de-bfbc-dc89dd37e7ff.png)

**Comment by 710leo** [comment]
@liangjaden  感谢反馈，看这个是 v5 版本的，v5 后续就停止开发新功能了，只修复问题，推荐你安装 v6 版本哈，v6 版本现在已经进入稳定阶段了

**Comment by UlricQin** [comment]
helm应该还没有支持到6.x，可以先用二进制方式部署测试

**Comment by liangjaden** [comment]
好的~谢谢

**Comment by 710leo** [comment]
> 2023-03-28 15:08:49.102623 WARNING naming/heartbeat.go:120 heartbeat with cluster err:Error 1064: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'cluster = ? and datasource_id=?' at line 1
> 
> V6也是不兼容腾讯云 的TDSQL-C Mysql呢 @UlricQin @710leo

这块我们兼容下
