### ISSUE TITLE
全局回调地址收到的请求是空的

### ISSUE THREAD

**Issue by lizeyun** [ccfos/nightingale#1438]
系统设置-回调地址如下
![image](https://user-images.githubusercontent.com/19726385/226835687-2bf8dfc8-8f78-41de-b44b-6aa92ee65956.png)
收到的请求打印body 为空：

每个告警里面单独配置 回调地址则正常收到告警请求

**Comment by lizeyun** [comment]
![image](https://user-images.githubusercontent.com/19726385/226835946-aefe30ff-01b0-4e34-85a8-cd6bda1b16de.png)

**Comment by 710leo** [comment]
感谢反馈，我们看下

**Comment by 710leo** [comment]
已 fix, 见 https://github.com/ccfos/nightingale/commit/aac135c498d9e046099dc861cc17afdb43d0116d
