### ISSUE TITLE
告警规则中的变量是怎么使用的

### ISSUE THREAD

**Issue by hello2dj** [ccfos/nightingale#1439]
![48E4135F-274D-4f37-A9CC-383B765C9665](https://user-images.githubusercontent.com/10645383/227093395-c5c95983-d883-41d1-9f04-0fe2766bb1f2.png)

**Comment by 710leo** [comment]
@hello2dj 告警规则中 promql 是不支持写变量的，你是在哪里看到能写变量的呢？

**Comment by hello2dj** [comment]
> @hello2dj 告警规则中 promql 是不支持写变量的，你是在哪里看到能写变量的呢？

https://github.com/flashcatcloud/categraf  里面 linux 监控的内置告警规则

**Comment by 710leo** [comment]
@hello2dj 详细的链接可以贴下，找了下没找到你截图里的配置

**Comment by hello2dj** [comment]
![10E8AB5F-8553-4262-BC6F-5B1D7BADD03F](https://user-images.githubusercontent.com/10645383/227237784-488b95b3-91ae-4782-9575-aff2ce61d2b4.png)

@710leo 抱歉搞错了，是这里的  https://github.com/ccfos/nightingale/blob/main/integrations/linux/alerts/linux_by_exporter.json
