### ISSUE TITLE
n9e 6 版本数据库问题

### ISSUE THREAD

**Issue by ZTfred** [ccfos/nightingale#1441]
### Relevant server.conf | webapi.conf

```toml
DSN="root:****@2021@tcp(192.168.5.74:3306)/n9e_v6?charset=utf8mb4&parseTime=True&loc=Local&allowNativePasswords=true"
```

### Relevant logs

```text
2023/03/23 23:17:10 ESC[35m/home/runner/work/nightingale/nightingale/pkg/ormx/ormx.go:45
ESC[0mESC[31m[error] ESC[0mfailed to initialize database, got error Error 1045: Access denied for user 'root'@'192.168.7.209' (using password: YES)
2023/03/23 23:17:10 main.go:36: failed to initialize: Error 1045: Access denied for user 'root'@'192.168.7.209' (using password: YES)
```

### System info

n9e-v6.0.0-beta.5

### Steps to reproduce

最新的版本下，数据库密码如果包含有@符号，会匹配错误，无法正常连接数据库

### Expected behavior

连接数据库失败

### Actual behavior

如何避免这个现象

**Comment by 1725785880** [comment]
@ZTfred 有没有可能是您的密码真的不对？
以下是我的2次连接串儿，测试正常：
DSN = "n9eV6:n9e@V6*123@tcp(192.168.137.101:3306)/n9e_v6?charset=utf8mb4&parseTime=True&loc=Local&allowNativePasswords=true"

DSN = "n9eV6:n9e@2021@tcp(192.168.137.101:3306)/n9e_v6?charset=utf8mb4&parseTime=True&loc=Local&allowNativePasswords=true"

mysql版本：Server version: 8.0.31 MySQL Community Server - GPL

**Comment by ZTfred** [comment]
v6 版本下，categraf数据怎么直接接入n9e呢，尝试写到n9e的17000端口上，失败了

**Comment by ZTfred** [comment]
![image](https://user-images.githubusercontent.com/53425107/229340388-5b563311-aea8-4ab1-a232-a279d4768497.png)
我看要开启心跳，categraf已经开启了，后面n9e上需要添加哪种数据源呢？还是看不到数据
