### ISSUE TITLE
客户端失联告警没有自定义标签

### ISSUE THREAD

**Issue by xusiwang** [ccfos/nightingale#1451]
### Relevant server.conf | webapi.conf

```toml
规则标题: 服务器失联
触发时值: 2510509
监控对象: yskj-MW34-SP0-00
监控指标: [name=target_miss ident=yskj-MW34-SP0-00 rulename=服务器失联]
```

### Relevant logs

```text
监控指标中没有在对象列表里定义的标签，导致没法在订阅中根据标签发送到不同的群组中
```

### System info

n9e v6.0.0-ga.1

### Steps to reproduce

1.在对象列表中给某台服务器添加group=uat标签
2.添加告警规则服务器失联，配置规则host  全部机器
3.添加告警订阅，订阅服务器失联这条告警，并根据订阅事件标签选择group=uat，重新定义告警接收组
4.关闭收集客户端，模拟服务器掉线情况，重新定义的告警接受组没接收到告警消息

...

### Expected behavior

重新定义的告警接受组正常接收告警消息

### Actual behavior

重新定义的告警接受组没接收到告警消息

**Comment by 710leo** [comment]
fix at https://github.com/ccfos/nightingale/commit/b142a5726e719f5078150ffafa6cec718726de79
