### ISSUE TITLE
分享时序指标报错

### ISSUE THREAD

**Issue by yn197** [ccfos/nightingale#1458]
### Relevant server.conf | webapi.conf

```toml
Error 1054: Unknown column 'datasource_id' in 'field list'
```

### Relevant logs

```text
Error 1054: Unknown column 'datasource_id' in 'field list'
```

### System info

6.0.0-ga.2

### Steps to reproduce

1.功能:时序指标既时查询分享报错
2.
3.
...

### Expected behavior

无

### Actual behavior

无

**Comment by FengZh61** [comment]
数据库表缺少字段，是不是升级过程中漏了某些alter SQL？
