### ISSUE TITLE
OIDC 中 s.Attributes.Username 为啥是一个固定值

### ISSUE THREAD

**Issue by jicki** [ccfos/nightingale#1460]
### Relevant server.conf | webapi.conf

```toml
none
```

### Relevant logs

```text
none
```

### System info

v6-ga2

### Steps to reproduce

none

### Expected behavior

OIDC
s.Attributes.Username  可配置

### Actual behavior

s.Attributes.Username = "sub"

### Additional info

https://github.com/ccfos/nightingale/blob/ee167ce0ba45c15b01db940939733f5d94afbf21/pkg/oidcx/oidc.go#L73

**Comment by 710leo** [comment]
@jicki  固定值 遇到什么问题了吗

**Comment by jicki** [comment]
> 
就是想配置 username  然后发现无法是用这个属性

**Comment by jicki** [comment]
> > 
> 
> 就是想配置 username 然后发现无法是用这个属性

这个属性，如果修改为 变量值，会引发其他得问题吗？ 类似于 oauth2 的写发

**Comment by UlricQin** [comment]
这个应该可以做成可配置的

**Comment by 710leo** [comment]
已支持   https://github.com/ccfos/nightingale/commit/caa23fbba18d1bacbf03a99ffe837edac4286245
