### ISSUE TITLE
如何提交一些新特性的代码？

### ISSUE THREAD

**Issue by kuluce** [ccfos/nightingale#1465]
**如何提交一些新特性的代码？比如添加添加了install子命令，可以添加server、webapi服务**:

**Why is this needed**:
方便程序进行安装

**Comment by UlricQin** [comment]
共享开源项目，比较简单，一般有两个步骤：
1，提issue，说明问题，解决方案，以及为什么这么做，如果其他人有异议会在这个issue讨论
2，提PR，关联issue，提供解决方案

**Comment by kuluce** [comment]
了解谢谢
