### ISSUE TITLE
监控K8S服务器硬盘，怎么去重

### ISSUE THREAD

**Issue by lyitt1987** [ccfos/nightingale#1468]
![image](https://user-images.githubusercontent.com/35764082/230536523-6b05a61a-f5f6-4408-a14e-08d1c0af4ca6.png)
如图，当满足条件告警的时候，同一个硬盘因为挂载路径不一样，会出现两次甚至多次，这种情况怎么去重

**Comment by UlricQin** [comment]
我觉得你这个需求不合理，不过你可以通过 by 语句去重，具体可以google一下”promql group by“ 😄

**Comment by jicki** [comment]
你这个 metrics  path 是不相同得呀

或者 你直接把 path 排除了
```
max by (device, fstype, ident, mode) (100-disk_used_percent{device=~"sd.*", ident="172.20.1.89"}) < 50
```

**Comment by lyitt1987** [comment]
> 
虽然path不一样，但是都是同一个硬盘，而且没有分区
![image](https://user-images.githubusercontent.com/35764082/230568625-b9d17bcc-6d3e-4171-b6bd-c1622a2a4e07.png)

**Comment by lyitt1987** [comment]
> 我觉得你这个需求不合理，不过你可以通过 by 语句去重，具体可以google一下”promql group by“ 😄

是，你是考虑不通分区的情况下，去重就会出现结果不对吗，

**Comment by jicki** [comment]
> > 我觉得你这个需求不合理，不过你可以通过 by 语句去重，具体可以google一下”promql group by“ smile
> 
> 是，你是考虑不通分区的情况下，去重就会出现结果不对吗，

emmmm 我不是发了 一个 promql 给你嘛？ 你拿去测试一下呀

**Comment by lyitt1987** [comment]
> > > 我觉得你这个需求不合理，不过你可以通过 by 语句去重，具体可以google一下”promql group by“ smile
> > 
> > 
> > 是，你是考虑不通分区的情况下，去重就会出现结果不对吗，
> 
> emmmm 我不是发了 一个 promql 给你嘛？ 你拿去测试一下呀
嗯，已经测试了，符合我的需求，谢谢！
