### ISSUE TITLE
n9e 6x版本es数据源绘图适配

### ISSUE THREAD

**Issue by helopng** [ccfos/nightingale#1469]
希望适配es数据源的绘图, 可以像kibana的dashboard那样支持任意字段Order By数据展示

**Comment by helopng** [comment]
参考我这的es6如下:
![Dingtalk_20230407171158](https://user-images.githubusercontent.com/34534054/230583279-77526f92-be86-40ba-a61c-e0680d25e139.jpg)
![Dingtalk_20230407171215](https://user-images.githubusercontent.com/34534054/230583327-5c6893d1-6a41-4b2b-9b07-2b87b9d054f1.jpg)

**Comment by jicki** [comment]
这个真得棒棒，很需要

**Comment by jsers** [comment]
下周发布的 ga.4 版本支持下这个

**Comment by 710leo** [comment]
最新版本已支持
