### ISSUE TITLE
如何做告警升级？

### ISSUE THREAD

**Issue by xiaoyaolaotou** [ccfos/nightingale#1470]
比如当前磁盘告警80%发给某某，30分钟还未处理升级动作，发给leader。有相关文档之类的嘛？

**Comment by UlricQin** [comment]
夜莺本身支持的不太好，建议使用 FlashDuty 来搞这个事情：https://flashcat.cloud/blog/flashduty-intro/

**Comment by xiaoyaolaotou** [comment]
这是收费的




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "ccfos/nightingale"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年4月8日(星期六) 下午2:30
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [ccfos/nightingale] 如何做告警升级？ (Issue #1470)





 
夜莺本身支持的不太好，建议使用 FlashDuty 来搞这个事情：https://flashcat.cloud/blog/flashduty-intro/

**Comment by UlricQin** [comment]
> 这是收费的
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "ccfos/nightingale" ***@***.***&gt;; 发送时间:&nbsp;2023年4月8日(星期六) 下午2:30 ***@***.***&gt;; ***@***.******@***.***&gt;; 主题:&nbsp;Re: [ccfos/nightingale] 如何做告警升级？ (Issue #1470) 夜莺本身支持的不太好，建议使用 FlashDuty 来搞这个事情：https://flashcat.cloud/blog/flashduty-intro/ — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: ***@***.***&gt;

FlashDuty有免费的套餐，免费的套餐就具备告警升级的能力。另外，觉得有价值付费也挺好，这样才能合作共赢嘛。养家糊口都做不到的话，更无法为爱发电了 😄
