### ISSUE TITLE
夜莺自愈脚本调用夜莺内的参数

### ISSUE THREAD

**Issue by liufangpeng** [ccfos/nightingale#1471]
现在遇到了一个场景问题，目前我们打算用夜莺对接一个工单系统，打算用自愈脚本去调用API创建工单，但是目前的问题是我想要实现创建工单的内容是夜莺的告警信息，我该使用什么参数获取夜莺的告警信息，怎么样在夜莺自愈脚本功能中使用

**Comment by UlricQin** [comment]
你这个需求应该使用webhook实现，在webhook的逻辑里调用工单系统的api创建工单

**Comment by liufangpeng** [comment]
目前创建工单的功能已经通过自愈脚本实现了
`#!/bin/bash
# e.g.
curl --location 'xxx' \
--header 'authtoken: xxx' \
--header 'Content-Type: application/x-www-form-urlencoded' \
--data-urlencode 'input_data={
    "request": {
        "subject": "云盘-办公环境-HTTP探测失败！",
        "description": "云盘-办公环境-HTTP探测失败！URL=xxx 大盘地址=xxx" 告警信息=    ,
        "requester": {
            "id": "3601"
        }
    }
}'`

**Comment by UlricQin** [comment]
告警自愈脚本拿不到太多信息，需要用webhook的方式

**Comment by liufangpeng** [comment]
那这个webhook具体需要怎么实现呢

**Comment by UlricQin** [comment]
告警规则里不是有个回调地址的配置么？你需要写个http服务，提供一个http接口，然后把这个接口地址配置到告警规则的回调地址里，然后告警之后监控系统就会调用这个接口，把告警详情塞到http request中传给这个接口，这个接口拿到告警信息，就可以想干啥就干啥了，你的场景的话，就是调用工单系统的接口创建工单。
