### ISSUE TITLE
Alarm Management -- Data Source Type

### ISSUE THREAD

**Issue by simplelearn01** [ccfos/nightingale#1472]
目前版本，告警管理-数据源类型只能选择prometheus作为数据来源，下个版本会新增其他数据源吗，如 elastic 告警数据源

**Comment by UlricQin** [comment]
v6.0.0.ga.3 是可以添加es作为数据源的

**Comment by simplelearn01** [comment]
![image](https://user-images.githubusercontent.com/40163563/230816649-1c7fb29b-118a-4537-931c-05c448fdd4ac.png)
![image](https://user-images.githubusercontent.com/40163563/230816692-d8aaf75b-a902-4aaa-b096-3d0c516c78b5.png)
![image](https://user-images.githubusercontent.com/40163563/230817219-58015f1e-0a79-4984-b3a5-2949705c7fd0.png)

当前版本类型是v6.0.0.ga.3， 告警数据源类型目前只能看到prometheus, 需要怎么操作才能选择数据源类型为elastic

**Comment by UlricQin** [comment]
开源版本可以支持es的可视化，还做不了告警，es的告警是单独的一个商业化插件
