### ISSUE TITLE
Does the v6 version support integration with the Loki data source

### ISSUE THREAD

**Issue by zhangyiwang-001** [ccfos/nightingale#1473]
目前有相关的业务日志监控，使用了最新的v6版本的夜莺系统，如何把loki相关的数据源集成到夜莺管理页面上，形成相关告警

**Comment by jicki** [comment]
> 目前有相关的业务日志监控，使用了最新的v6版本的夜莺系统，如何把loki相关的数据源集成到夜莺管理页面上，形成相关告警

https://flashcat.cloud/blog/host-ilo-monitoring/

看一下这个 博客

**Comment by 710leo** [comment]
最新版本已支持
