### ISSUE TITLE
在n9e中使用$__range不支持

### ISSUE THREAD

**Issue by Xfireman** [ccfos/nightingale#1474]
sum_over_time(probe_success{instance="http://test.test.com/apm/health",job="http-health"}[$__range]) / count_over_time(probe_success{instance="http://test.test.com/apm/health",job="http-health"}[$__range])*100
在promQL中使用如下查询语句，提示不支持。
请问在nghtingale中，是否支持$__range，或者使用什么变量来替换？

bad_data: 1:45: parse error: missing unit character in duration

n9e-v5.15.0-87899cbedbc7bfcfff61052ebeed945a57a418d2

**Comment by UlricQin** [comment]
@jsers 咱们应该有计划做这个支持？

**Comment by jsers** [comment]
有计划，v6 正式版会支持一些内置变量，其中包括 $__range

**Comment by Xfireman** [comment]
好的，感谢。
