### ISSUE TITLE
v6 es 索引不按顺序排列

### ISSUE THREAD

**Issue by ojbkxiongdei** [ccfos/nightingale#1478]
# 部署方式
helm n9e ga3

# 问题
遇到设置es作为日志源，索引 日期不按顺序排列，不好找对应的日期查看日志，希望能有排序。
如下图
![n9e](https://user-images.githubusercontent.com/55149555/231681612-c84d29c8-6e31-474c-a19d-e6506b1daf31.png)

**Comment by 710leo** [comment]
最新版本已支持
