### ISSUE TITLE
n9e ga4.1试用es绘图逻辑问题

### ISSUE THREAD

**Issue by helopng** [ccfos/nightingale#1484]
各位下午好:

试用es绘图逻辑问题这里以mysql慢查询举例, 在kibana里绘图我想展示关键字段例如SQL, Query_time, Database, User 点击split rows选要展示的字段名然后Order By Query_time, 排序出慢查询的TOP 10

这样一个逻辑在夜莺中好像有一丝丝偏差,  **数值提取**应该是我想要的SQL, Querytime这些具体字段,但是这里只能选择count max sum这几个.

然后如果按照kibana的逻辑来看, 后面是直接Order By某个字段,例如我这里是Query_time, 所以后面的Group By, Order By应是平级, 可以任选其中一个来分组或排序

kibana截图:
![Dingtalk_20230417153020](https://user-images.githubusercontent.com/34534054/232439641-43c7f1d6-a63d-4bbc-860a-1f12ac7b155b.jpg)
![Dingtalk_20230417153414](https://user-images.githubusercontent.com/34534054/232439668-9e7a4ee4-5bf0-4ec2-88ea-47a465e4ac29.jpg)
夜莺截图:
![Dingtalk_20230417171207](https://user-images.githubusercontent.com/34534054/232439966-db860549-bb33-42fd-8534-638b063e8771.jpg)

**Comment by UlricQin** [comment]
@jsers 给瞧瞧？

**Comment by jsers** [comment]
@helopng 
能看到 kibana 里面 request body 吗？
比较好奇他是怎么处理和 groupBy 平级的 sortBy 里面的，是类似这样的吗？
```
sort: [{
  query_time: {order : "asc", "mode" : "max"}
}]
```

**Comment by helopng** [comment]
> 
是不是这个
{
    "index": "logstash-mysql-slowlog_*",
    "ignore_unavailable": true,
    "preference": 1681784755436
}
{
    "aggs": {
        "2": {
            "terms": {
                "field": "sql.keyword",
                "size": 20,
                "order": {
                    "2-orderAgg": "desc"
                }
            },
            "aggs": {
                "3": {
                    "terms": {
                        "field": "query_time",
                        "size": 20,
                        "order": {
                            "3-orderAgg": "desc"
                        }
                    },
                    "aggs": {
                        "4": {
                            "terms": {
                                "field": "database.keyword",
                                "size": 20,
                                "order": {
                                    "4-orderAgg": "desc"
                                }
                            },
                            "aggs": {
                                "5": {
                                    "terms": {
                                        "field": "user.keyword",
                                        "size": 20,
                                        "order": {
                                            "5-orderAgg": "desc"
                                        }
                                    },
                                    "aggs": {
                                        "5-orderAgg": {
                                            "max": {
                                                "field": "query_time"
                                            }
                                        }
                                    }
                                },
                                "4-orderAgg": {
                                    "max": {
                                        "field": "query_time"
                                    }
                                }
                            }
                        },
                        "3-orderAgg": {
                            "max": {
                                "field": "query_time"
                            }
                        }
                    }
                },
                "2-orderAgg": {
                    "max": {
                        "field": "query_time"
                    }
                }
            }
        }
    },
    "size": 0,
    "_source": {
        "excludes": []
    },
    "stored_fields": [
        "*"
    ],
    "script_fields": {},
    "docvalue_fields": [
        {
            "field": "@timestamp",
            "format": "date_time"
        }
    ],
    "query": {
        "bool": {
            "must": [
                {
                    "match_all": {}
                },
                {
                    "range": {
                        "@timestamp": {
                            "gte": 1681784053623,
                            "lte": 1681784953623,
                            "format": "epoch_millis"
                        }
                    }
                }
            ],
            "filter": [],
            "should": [],
            "must_not": []
        }
    },
    "timeout": "30000ms"
}

**Comment by helopng** [comment]
我没表达清楚, 就是现在夜莺的Group By +是固定的, 点击高级才会出来Order By, 我意思是这里把两个做成平级, 外面再放一个Order by +, 用户可以任选一个查询结果. 

或者还是因为**数据提取**那里选不了想要的字段, 导致后面什么By也查不出数据......

**Comment by jsers** [comment]
@helopng 
看着 DSL 没什么问题
orderBy 结构上来说就是 groupBy(terms aggr) 里面的
数据提取(avg / max ...) 也是支持字段的，选不了字段是因为只能选择 float / double / integer / long 类型的字段

**Comment by helopng** [comment]
好的, 我再研究研究
