### ISSUE TITLE
 如何只使用一套夜莺来支持victoriametrcs多租户呢？

### ISSUE THREAD

**Issue by luzejia** [ccfos/nightingale#1491]
我的场景：

一个victoriametrics集群里为不同的部门配置了不同的租户，每个租户使用不同的租户id来进行数据写入与查询，如：
```
查询：
http://xxx:port/select/0/xxxxx
http://xxx:port/select/1/xxxxx

写入：
http://xxx:port/insert/0/xxxxx
http://xxx:port/insert/1/xxxxx
```

这种情况下如何使用一套夜莺来对接多租户模式下的victoriametrics呢？如果每个租户都去部署一套夜莺，那运维难度太大。

**Comment by UlricQin** [comment]
每个租户可以配置成一个数据源，比如：

```
http://10.206.0.13:8481/select/1/prometheus
```

数据源的 url 里带有租户id

**Comment by luzejia** [comment]
> 每个租户可以配置成一个数据源，比如：
> 
> ```
> http://10.206.0.13:8481/select/1/prometheus
> ```
> 
> 数据源的 url 里带有租户id

嗨，你好，但是夜莺支持为每个登陆用户指定数据源url吗？

**Comment by laiwei** [comment]
> > 每个租户可以配置成一个数据源，比如：
> > ```
> > http://10.206.0.13:8481/select/1/prometheus
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 数据源的 url 里带有租户id
> 
> 嗨，你好，但是夜莺支持为每个登陆用户指定数据源url吗？因为每个登陆的用户其属于某个带有租户id的vm url的，在做即时查询和告警的时候，也需要其使用相应的vm url。

夜莺暂不支持数据源的隔离功能，所有人都可以看到所有的数据源。 @luzejia

**Comment by luzejia** [comment]
> > > 每个租户可以配置成一个数据源，比如：
> > > ```
> > > http://10.206.0.13:8481/select/1/prometheus
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > 数据源的 url 里带有租户id
> > 
> > 
> > 嗨，你好，但是夜莺支持为每个登陆用户指定数据源url吗？因为每个登陆的用户其属于某个带有租户id的vm url的，在做即时查询和告警的时候，也需要其使用相应的vm url。
> 
> 夜莺暂不支持数据源的隔离功能，所有人都可以看到所有的数据源。 @luzejia

好的，谢谢！
