### ISSUE TITLE
v6版本数据源接入vm的时候报错

### ISSUE THREAD

**Issue by luzejia** [ccfos/nightingale#1494]
### Relevant server.conf | webapi.conf

```toml
webapi.conf
```

### Relevant logs

```text
webapi
```

### System info

v6.0.0-ga.4.0.1-d39d4cb91df44bee90bc2870f9d5145bed01839f

### Steps to reproduce

1.新增数据源使用vmselect的地址

### Expected behavior

应该能够添加成功

### Actual behavior

<img width="1432" alt="image" src="https://user-images.githubusercontent.com/52991866/233338795-9ea1e47e-a0b6-44bd-94d9-380c8c467250.png">

**Comment by idcdog** [comment]
更新最新的ga5版本即可解决该问题, 可以测试下.

**Comment by luzejia** [comment]
> 更新最新的ga5版本即可解决该问题, 可以测试下.

收到！我测试下

**Comment by luzejia** [comment]
> 更新最新的ga5版本即可解决该问题, 可以测试下.

新版本已修复，测试正常
