### ISSUE TITLE
我想自己编译 arm的版本，但是ADD http://download.flashcat.cloud/wait /wait 这个文件源代码没有，能否提供谢谢。

### ISSUE THREAD

**Issue by wanminny** [ccfos/nightingale#1507]
**What would you like to be added**:

**Why is this needed**:
我想自己编译 arm的版本，但是ADD http://download.flashcat.cloud/wait /wait 这个文件源代码没有，能否提供谢谢。

**Comment by kongfei605** [comment]
可以参考下这个pr的修改 https://github.com/ccfos/nightingale/pull/1506
