### ISSUE TITLE
v6基础设施页面可以加一列IP地址吗

### ISSUE THREAD

**Issue by helopng** [ccfos/nightingale#1509]
你好,

v6基础设施这里显示主机名, 监控页面是从labels=n9e-172.1.1.2 显示的, 两边看着对应不起来,

所以基础设施页面可以加一列IP地址吗?

![no_ip](https://user-images.githubusercontent.com/34534054/234743085-1bd6f781-cab7-42c0-8a84-ed9d42b27154.jpg)

**Comment by samgang** [comment]
对象列表里显示跟 Categraf 的设置有关
- `hostname=""`：对象列表里显示**主机名**
- `hostname="xx"`：对象列表里显示**设置的内容**
- `hostname="$ip"`：对象列表里显示**ip**
- `hostname="$hostname-$ip"`：对象列表里显示**主机名-ip**
