### ISSUE TITLE
Suggestions for V6 and subsequent versions

### ISSUE THREAD

**Issue by samgang** [ccfos/nightingale#1510]
V6 及其以后的版本的一些建议

1. 配置文件和页面配置上示例配置采用服务的常见端口，比如 3306，6379等，方便新用户快速上手，用户可根据实际参考修改
2. 页面配置包含密码的进行加密
3. 在 n9e 里增加数据库的初始化，避免在升级小版本时因为改了表结构而造成某些页面的错误显示

新的安装过程
1. 正常安装依赖环境包，如MySQL，redis
4. 正常配置 `config.tml`
5. 去掉 `n9e.sql` 里数据库的创建，使用二进制部署的大多都不会使用 root，会单独分一个库和用户名
6. 初始化和运行
```shell
./n9e --install # 根据 config.tml 进行数据库的初始化，不手动进行数据库的执行，
./n9e # 运行
```

- 小版本之间无大的表结构变化升级时可直接运行，当运行 `./n9e --install ` 提示错误，避免再次初始化。
- 小版本之间有大的表结构变化升级时可运行 `./n9e --migrate ` 进行表结构修复。同时进行风险提示。
- 大版本之间进行升级可运行 `./n9e --migrate ` 进行表结构修复。同时进行风险提示。
- 如果版本之间表结构相差大，可升级到某一个版本的逐级升级方式。
**Why is this needed**:

**Comment by UlricQin** [comment]
大都已做修改
