### ISSUE TITLE
Suggest allowing custom alarm severity levels

### ISSUE THREAD

**Issue by bbaobelief** [ccfos/nightingale#1529]
现在的告警级别有
- 一级报警
- 二级报警
- 三级报警

希望可以通过配置文件支持定义更多级别
- 致命 | 0
- 严重 | 1
- 警告 | 2
- 提醒 | 3
- 通知 | 4

**Comment by 106848748** [comment]
现有的告警系统都有5级，现在要切到n9e上来，全都要改和规划，脑壳痛，正常点的都是5级啊

**Comment by 106848748** [comment]
我的临时解决方案：
1. n9e配置全局的webhook，所有的告警发送都是走自己的代码
2. 所以告警配置里的通知渠道就没有用，全部屏蔽，新增告警级别的5个
3. webhook接收到的告警信息里面有notify_channels字段，从里面选一个最高级别的

**Comment by UlricQin** [comment]
未有计划。如果觉得内置级别不合适，可以自行使用附加标签和自定义字段来定义级别信息。
