### ISSUE TITLE
夜莺配置告警备注时候URL发出来多了一些字符

### ISSUE THREAD

**Issue by a33151** [ccfos/nightingale#1530]
### Relevant 

感谢抽空查看， 我在配置告警备注时候想加入一些变量能直接跳转到grafana，但是发现 有& 符号后会被增加关键字 apm;  我配置的备注地址是： 
```

 https://aaa.aaa.com/d/xxxxx/su-zhu-ji-ji-chu-jian-kong?orgId=1&refresh=5s&var-ident={{$labels.ident}}
```

发出来的信息如下：
```

https://aaa.aaa.com/d/xxxxx/su-zhu-ji-ji-chu-jian-kong?orgId=1&amp;refresh=5s&amp;var-ident=xxxxhost
```

请问是需要如何配置才能去掉这个 apm; 字符

另外也建议规则备注支持换行，不然数据比较多的时候就一整行看起来有点痛苦
### System info

版本 5.15

**Comment by ysyneu** [comment]
@a33151 是指告警推送到IM之类的渠道，渲染备注信息有问题？

**Comment by UlricQin** [comment]
这是被IM转义了，不想被转义的话，定义模板的时候加个 unescaped 就可以了，比如 `{{$RunbookUrl | unescaped}}`

**Comment by a33151** [comment]
感谢协助 通过修改模板 ,已经能正确显示
```
规则名称: {{.RuleName}}
{{if .RuleNote}}
{{.RuleNote | unescaped }}{{end}}

```
