### ISSUE TITLE
订阅规则，希望支持原生标签筛选，而不仅仅是告警事件的标签

### ISSUE THREAD

**Issue by myselfghost** [ccfos/nightingale#1531]
**What would you like to be added**:
订阅规则，希望支持原生标签筛选，就是原生Metric 里面的label。

**Why is this needed**:

灵活性更强。订阅的时候，很可能我关心的不是告警规则本身，我只心对象。这个时候我就需要根据原生Metric 里面的label来筛选订阅。

**场景1**：
**前提条件**，现在运维人员已经配置了一个规则：磁盘大于80%告警，通知到运维组。这里是对全部instance对象生效的。
**需求**，现在有一个开发人员，对于告警规则“磁盘大于80%告警”里面的部分对象（原生标签可以区分,比如L=XX）感兴趣需要订阅，这个时候订阅规则就需要根据原生标签来筛选。既，我关心这一个告警规则，并且是部分监控对象。

**虽然**： 完成上述的需求，可以再添加一个“磁盘大于80%告警，并且label等于XX” 的告警规则来实现，但是这样是不合逻辑，不优雅的。1. 事实上，告警规则只需要“磁盘大于80%告警” 一个规则就够了，只是通知订阅的时候需要筛选2次而已。2. 多个相似的“磁盘大于80%告警”的告警规则会增加服务器的计算负担。

**场景2**：
**前提条件**，现在运维人员已经配置了N个规则,CPU、磁盘、内存等等相关的告警，通知到运维组。这里是对全部instance对象生效的。
**需求**，现在有一个开发人员，感兴趣需要订阅的条件是： 1.  告警事件标签G=DBA，2 . 原生标签L=XX 。既，我关心部分告警规则，并且是部分监控对象。

**Comment by myselfghost** [comment]
alert-mutes 也存在一样的情况

**Comment by 710leo** [comment]
@myselfghost  时序数据的标签在产生告警事件的时候，会加到告警事件标签中，你的需求现在应该就能满足
