### ISSUE TITLE
前端BUG: 屏蔽规则 运算符为IN，标签Value会聚成一团

### ISSUE THREAD

**Issue by LinZhenLin** [ccfos/nightingale#1532]
### Relevant server.conf | webapi.conf

```toml
无
```

### Relevant logs

```text
无
```

### System info

n9e 6.0.0-ga.6

### Steps to reproduce

1. 在编辑完 屏蔽规则后，再次打开屏蔽规则即可稳定触发
2. 屏蔽规则包含了了in 运算符，且value 有多个时

### Expected behavior

n9e v5.15版本效果
![](https://raw.githubusercontent.com/LinZhenLin/cloudimage/main/data/20230510152724.png)

### Actual behavior

n9e v6 ga.6版本效果
![](https://raw.githubusercontent.com/LinZhenLin/cloudimage/main/data/20230510152854.png)

**Comment by jsers** [comment]
正式版已经修复
