### ISSUE TITLE
建议将报警规则中的级别写入到标签中，方便订阅

### ISSUE THREAD

**Issue by cys-jason** [ccfos/nightingale#1533]
场景：比如某个管理人员，只关心S1级别的报警，想通过订阅报警实现。
实现：希望在报警标签中自动写入报警级别。

**Comment by UlricQin** [comment]
后面订阅规则、屏蔽规则，计划支持根据属性筛选事件，属性中可以选择级别

**Comment by myselfghost** [comment]
> 后面订阅规则、屏蔽规则，计划支持根据属性筛选事件，属性中可以选择级别

属性其实不就是用label 来表示吗？ 应该一切皆是label 啊

**Comment by 710leo** [comment]
订阅规则、屏蔽规则，已支持根据事件等级筛选
