### ISSUE TITLE
为什么PromClientMap的Del方法里不删除WriterClients

### ISSUE THREAD

**Issue by wpliang** [ccfos/nightingale#1537]
**What would you like to be added**:
在**prom/clientprom/client.go**中
type PromClientMap struct {
	sync.RWMutex
	ctx           *ctx.Context
	heartbeat     aconf.HeartbeatConfig
	ReaderClients map[int64]prom.API
	WriterClients map[int64]prom.WriterType
}
...
func (pc *PromClientMap) Del(datasourceId int64) {
	pc.Lock()
	defer pc.Unlock()
	delete(pc.ReaderClients, datasourceId)
}
这里的Del方法只清理了ReaderClients，而WriterClients并没有清理，WriterClients会不会内存泄漏？
**Why is this needed**:
func (pc *PromClientMap) Del(datasourceId int64) {
	pc.Lock()
	defer pc.Unlock()
	delete(pc.ReaderClients, datasourceId)
	delete(pc.WriterClients, datasourceId)
}
加上清理WriterClients代码

不知道是不是有别的考虑，这里没有清理WriterClients？

**Comment by 710leo** [comment]
感谢反馈，最新代码已经加了哈
