### ISSUE TITLE
n9e 大盘点分享后的图表，排序错误

### ISSUE THREAD

**Issue by shenghuofei** [ccfos/nightingale#1538]
### Relevant server.conf | webapi.conf

```toml
前端版本：5.15.0
后端版本：v5.15.0-87899cbedbc7bfcfff61052ebeed945a57a418d2
```

### Relevant logs

```text
webapi
```

### System info

前端版本：5.15.0 后端版本：v5.15.0-87899cbedbc7bfcfff61052ebeed945a57a418d2

### Steps to reproduce

1.在大盘选择一个图表，然后点击分享
2.在分享后的页面点击排序功能，如下图：
<img width="1452" alt="image" src="https://github.com/ccfos/nightingale/assets/5562615/e8d5c583-212c-4022-b224-0510b0ad62b8">

3.可以看到8.+k的排在了后面，感觉是按字典序排的，应该按数字排才符合预期
...

### Expected behavior

应该按数字排序而不是按字典排序

### Actual behavior

按字典序排序的

**Comment by shenghuofei** [comment]
另外这里的求和应该也有问题

**Comment by jsers** [comment]
v6 版本已修复，v5 后面找时间修复下该 bug

**Comment by shenghuofei** [comment]
修复了辛苦回复下issue

**Comment by UlricQin** [comment]
> 修复了辛苦回复下issue

v6最新版本是 v6.0.0.ga.7，已经非常稳定了，如果没有额外束缚，建议升级 v6 了

**Comment by shenghuofei** [comment]
找时间测试下看看，没有问题可以尝试升级

**Comment by shenghuofei** [comment]
> v6 版本已修复，v5 后面找时间修复下该 bug

这个大概什么时候可以修复呢？

**Comment by jsers** [comment]
修复代码提交了，着急的话可以先拿前端代码自己打包更新下
https://github.com/n9e/fe-v5


shenghuofei ***@***.***> 于2023年5月31日周三 11:32写道：
