### ISSUE TITLE
高级设置单位中bits和bytes显示差不多，并没有8/10倍关系

### ISSUE THREAD

**Issue by zzlyzq** [ccfos/nightingale#1540]
### Relevant server.conf | webapi.conf

```toml
不需要
```

### Relevant logs

```text
不需要
```

### System info

前端版本：6.0.0-ga.6 后端版本：v6.0.0-ga.6-b62762b2e6d61d3e234636a26f0c88111c2cd840

### Steps to reproduce

1. 在配置redis dashboard流量过程中
2. 高级选项，调整bits/bytes的时候，显示的数值差不多，没有8倍或者10倍的关系

### Expected behavior

bytes和bits应该有8倍/10倍关系

### Actual behavior

数值差不多

### Additional info

![截图_选择区域_20230519154942](https://github.com/ccfos/nightingale/assets/1989900/5fdae665-1337-4aed-ad68-f4ad88f20a5f)
![截图_选择区域_20230519154920](https://github.com/ccfos/nightingale/assets/1989900/c0291b8e-32a2-46e2-8353-869a9ecb8052)

**Comment by jsers** [comment]
单位 bits和bytes 不会改变数值，只是显示单位的区别，选择你查询的指标值对应的单位即可

Jacky ***@***.***> 于2023年5月19日周五 15:55写道：
