### ISSUE TITLE
v6通知脚本支持基于通知媒介来配置

### ISSUE THREAD

**Issue by luxiangqing** [ccfos/nightingale#1541]
目前看通知脚本是全局配置的，所有告警都会推送到这个脚本，发送模板不太好定义，建议基于通知媒介的维度来配置通知脚本，这样可以很方便的对接多个第三方告警通道，比如短信、电话、企业微信等，而且可以基于通知媒介来配置告警的模板，zabbix的通知脚本好像就是这么做的

**Comment by UlricQin** [comment]
现在的逻辑是拆成了不同的方法，对应不同的通知媒介，完全没问题，你可以看一下视频号SRETalk的最新视频讲解

**Comment by luxiangqing** [comment]
> 现在的逻辑是拆成了不同的方法，对应不同的通知媒介，完全没问题，你可以看一下视频号SRETalk的最新视频讲解

感谢指导，看了一下视频，已经明白了

**Comment by lyitt1987** [comment]
> > 现在的逻辑是拆成了不同的方法，对应不同的通知媒介，完全没问题，你可以看一下视频号SRETalk的最新视频讲解
> 
> 感谢指导，看了一下视频，已经明白了

请问V6版本短信告警你是怎么配的，我按照V5版本那样用notify.py，结果不行
![image](https://github.com/ccfos/nightingale/assets/35764082/a3d2dcfb-1a88-4dfa-bc1f-71248b56e6eb)
