### ISSUE TITLE
采集端上报数据如何对接

### ISSUE THREAD

**Issue by luxiangqing** [ccfos/nightingale#1542]
如果自己实现采集端，上报数据是直接写到promethus的remote write接口还是写到夜莺的接口比较好，主要考虑后续升级，接口这边不用频繁更新

**Comment by 710leo** [comment]
如果实现的采集端采集的是主机相关的指标，希望主机出现在机器列表页面，可以上报给夜莺的接口
如果是非机器相关的指标，上报给哪个都可以，写数据的接口基本不会改变了，即时改变，也会向前兼容
