### ISSUE TITLE
告警模版发送，如何发送ClusterName 或者DataSource

### ISSUE THREAD

**Issue by lyitt1987** [ccfos/nightingale#1547]
如图，当我想知道告警是从哪个机房或者云发送，V5版本告警模版可以添加 [.Cluster]，
![image](https://github.com/ccfos/nightingale/assets/35764082/de573689-3f5b-4c26-846a-023741167c39)

V6 告警模版[.ClusterName] 或者[.DataSource] 都不行，请问有其他参数吗
![image](https://github.com/ccfos/nightingale/assets/35764082/45a4abdc-1c49-4951-93a4-fb7cc43c68c4)

**Comment by UlricQin** [comment]
升级到最新版，试试 {{.Cluster}}

**Comment by lyitt1987** [comment]
> 升级到最新版，试试 {{.Cluster}}

嗯， 升级后就正常了，可以直接用 {{.Cluster}}
