### ISSUE TITLE
How can the timestamp be made precise to milliseconds

### ISSUE THREAD

**Issue by xucheng217** [ccfos/nightingale#1551]
### Relevant server.conf | webapi.conf

```toml
默认配置
```

### Relevant logs

```text
test_xxx{ident="xxx"}
0 @1685009553
0 @1685009555
0 @1685009556
0 @1685009557
```

### System info

telegraf 1.25收集

### Steps to reproduce

无

### Expected behavior

时间戳精确到毫秒

### Actual behavior

无

**Comment by UlricQin** [comment]
telegraf提供prometheus remote write的output，这个方式下时间戳是毫秒的
