### ISSUE TITLE
v6.0.0版本 telegraf采集，显示 unknown

### ISSUE THREAD

**Issue by wwwsky86** [ccfos/nightingale#1552]
categraf 采集的数据，可以正常显示
telegraf 采集的数据，显示为 unknown
![image](https://github.com/ccfos/nightingale/assets/10069198/e8eb7338-07ea-4731-bb1e-8d14e6ae318e)

telegraf版本
<img width="413" alt="image" src="https://github.com/ccfos/nightingale/assets/10069198/20451d23-ee69-4c00-9179-a70be4a94d15">

<img width="1226" alt="image" src="https://github.com/ccfos/nightingale/assets/10069198/9614eaf0-34c7-402d-ac7d-b6eee8d32172">

抓包看，数据是正常POST 进来了的

**Comment by wwwsky86** [comment]
换用：categraf 就可以正常显示
![image](https://github.com/ccfos/nightingale/assets/10069198/3b91f406-978d-4d44-a319-07bce8f75f28)

**Comment by UlricQin** [comment]
https://flashcat.cloud/docs/content/flashcat-monitor/nightingale-v6/faq/target-anomaly/
