### ISSUE TITLE
关于n9e-v6.0.0-ga.8 接入ES8.6.2版本的数据报错

### ISSUE THREAD

**Issue by zengshuaishuai** [ccfos/nightingale#1553]
![8431685347477_ pic](https://github.com/ccfos/nightingale/assets/47208027/0f12d64e-567b-498e-bf1e-e352eda9225a)
我将ES的数据接入夜莺平台 在日志分析页面里面选择查询某个索引下面的日志 提示报错。报错信息如上图所示

**Comment by UlricQin** [comment]
提一下报错请求的 http request 和 http response

**Comment by Primeyang** [comment]
日志分析，选择完毕数据源和索引直接查询就会报这个错误，数据可以查询出来，图表无展示

**Comment by jicki** [comment]
这个问题～我有咨询过
是 因为 在 8 版本中 date_histogram 已经 aggregation 官方的说明 ,https://www.elastic.co/guide/en/elasticsearch/reference/current/search-aggregations-bucket-datehistogram-aggregation.html#calendar_intervals

**Comment by jicki** [comment]
> 贴一下报错请求的 http request 和 http response

什么时候会支持 Es 8 版本吗？

**Comment by 710leo** [comment]
最新版本已兼容
