### ISSUE TITLE
Quick View and PromQL Builder support Chinese metric names

### ISSUE THREAD

**Issue by hzwwww** [ccfos/nightingale#1555]
**What would you like to be added**:
快捷视图、promql builder支持中文指标
**Why is this needed**:
数据中心的监控数据都是中文指标，希望将n9e能应用到数据中心领域

**Comment by UlricQin** [comment]
指标进入时序库了没？在即时查询里查一下子，我看看数据长什么样？快捷视图报错了？报什么错？
