### ISSUE TITLE
Does it support sending alerts for data source connection anomalies

### ISSUE THREAD

**Issue by DongWei-4** [ccfos/nightingale#1569]
**What would you like to be added**:
当配置的数据源连接异常时，发送告警
**Why is this needed**:
使用v6版本，夜莺的17000/metrics中没有关于数据源的指标，也没有找到怎么配置数据源连接异常的告警

**Comment by kamjin1996** [comment]
告警规则的触发，本身就要依赖数据源查询的，这没法整吧

**Comment by UlricQin** [comment]
好问题

**Comment by DongWei-4** [comment]
> 告警规则的触发，本身就要依赖数据源查询的，这没法整吧

意思是，当配置的数据源地址，查询访问出错时，发送告警。比如配置了Prometheus的地址，当Prometheus服务访问不了

**Comment by DongWei-4** [comment]
@kamjin1996 

意思是，当配置的数据源地址，查询访问出错时，发送告警。比如配置了Prometheus的地址，当Prometheus服务访问不了时发送告警

**Comment by jicki** [comment]
就是增加一个 数据源探测 的 metrics

**Comment by 710leo** [comment]
针对每一个数据源，可以配置一个 http 探测，然后配置一个告警规则，探测失败了就发告警
对于告警规则执行时候，查询数据源失败的情况，最新版本的 n9e 增加了自监控指标 n9e_alert_rule_eval_error_total，可以采集下这个自监控指标，写入到专门存自监控指标的时序库，然后配置一条 `increase(n9e_alert_rule_eval_error_total[1m]) > 0` 的告警规则，这样就可以发现查询数据源失败的情况
