### ISSUE TITLE
新增loki数据源出错

### ISSUE THREAD

**Issue by yuchengao0721** [ccfos/nightingale#1580]
### Relevant server.conf | webapi.conf

```toml
与此无关
```

### Relevant logs

```text
post http://n9e:30002/api/n9e/datasource/upsert

响应
{
    "error": "request url:http://loki:3100/loki/api/v1/labels?end=2&start=1 failed code:400"
}
```

### System info

前端版本：6.0.0-ga.11 后端版本：v6.0.0-ga.11-067b3f91a741368e727132060d46c109457a6493
grafana/loki:2.8.2

### Steps to reproduce

添加loki数据源
【系统设置】-【数据源】-【Prometheus】
http://loki:3100/loki

### Expected behavior

添加成功

### Actual behavior

接口报错：
{
    "error": "request url:http://loki:3100/loki/api/v1/labels?end=2&start=1 failed code:400"
}

### Additional info

实际上我请求http://loki:3100/loki/api/v1/labels即可成功，想知道后面的参数对于新增一个loki数据源的校验是否是必须的
我接入grafana是正常的，它们的测试接口入参是 ?start=1687253358516000000&end=1687253958516000000

**Comment by 710leo** [comment]
最新版本已修复
