### ISSUE TITLE
MYSQL从库告警和恢复有差异

### ISSUE THREAD

**Issue by lyitt1987** [ccfos/nightingale#1582]
如图，从库停掉后，会收到从库挂了和同步异常告警信息，但是在没启动从库的情况下，过一会收到同步异常恢复信息
请问此情况如何避免？
![image](https://github.com/ccfos/nightingale/assets/35764082/a5f9f6c0-0851-4935-99ce-481444f158de)

**Comment by UlricQin** [comment]
告警规则的promql贴一下

**Comment by lyitt1987** [comment]
> 告警规则的promql贴一下

mysql_slave_status_master_server_id > 0 and ON (ident) (mysql_slave_status_slave_io_running == 0 or mysql_slave_status_slave_sql_running == 0)

**Comment by UlricQin** [comment]
应该是查不到数据了，所以就报恢复了。和prometheus一个逻辑，可以参考 faq：https://flashcat.cloud/docs/content/flashcat-monitor/nightingale-v6/faq/alerting-logic/

**Comment by lyitt1987** [comment]
> 应该是查不到数据了，所以就报恢复了。和prometheus一个逻辑，可以参考 faq：https://flashcat.cloud/docs/content/flashcat-monitor/nightingale-v6/faq/alerting-logic/

对，mysql进程停了就查不到数据，但是却发送从库状态恢复的恢复信息，所以这种情况是无法避免了，对吧

**Comment by UlricQin** [comment]
对，查不到数据就会报恢复

**Comment by shardingHe** [comment]
我觉得这样场景应该适合设置告警屏蔽事件
