### ISSUE TITLE
请问http_response 配置的url有特殊字符如何处理，谢谢！

### ISSUE THREAD

**Issue by lyitt1987** [ccfos/nightingale#1583]
categraf错误日志如下：
E! failed to load configuration of plugin: local.http_response error: toml: line 98 (last key "instances.targets"): invalid escape in string '\&'

**Comment by kongfei605** [comment]
原配置贴一下？

**Comment by lyitt1987** [comment]
> 原配置贴一下？

http://192.168.1.80/takeout?key=qwe\&userId=ewq

**Comment by kongfei605** [comment]
> > 原配置贴一下？
> 
> [http://192.168.1.80/takeout?key=qwe\&userId=ewq](http://192.168.1.80/takeout?key=qwe%5C&userId=ewq)

直接贴到配置文件就好，不用转义 &
