### ISSUE TITLE
Alert rules that exceed the maximum alert count limit are not displayed on the active alerts page

### ISSUE THREAD

**Issue by idcdog** [ccfos/nightingale#1587]
### Relevant server.conf | webapi.conf

```toml
无
```

### Relevant logs

```text
无
```

### System info

n9e-v6.ga12

### Steps to reproduce

告警规则设置如下, 设置了最多告警三次
![image](https://github.com/ccfos/nightingale/assets/18034474/fe20a011-b4c5-479c-8af8-e220732429de)

告警后,一直没有恢复, 但是从活跃告警页面已经看不到告警了

![image](https://github.com/ccfos/nightingale/assets/18034474/b02a75ac-9971-46e9-b11c-8dbb5665b305)

首次触发 2023年 06月 27日 星期二 00:03:55 CST
最后一次触发 2023年 06月 27日 星期二 02:04:26 CST
在今天16点的时候查看, 活跃告警页面是看不到了
![image](https://github.com/ccfos/nightingale/assets/18034474/4c804f67-69e6-4e16-836c-a53f56fca946)

但是如果我把时间拉到一天, 则是可以看到的
![image](https://github.com/ccfos/nightingale/assets/18034474/c2af3b3c-394c-4dd5-aa4a-37848b9d75db)

### Expected behavior

1. 即便设置了告警策略最大报警三次, 如果规则仍然是触发的状态, 此处还是应该显示在活跃告警中
2. 对于上述场景, 数据库中的trigger_time应该更新为最近一次检查的时间戳, 而不是最后一次告警的时候的时间戳

### Actual behavior

1. 最后一次告警超过了页面选择的时间范围后就不显示
2. 数据库中的trigger_time显示为了最后一次告警的时候的时间戳, 而不是最后检查的时间戳

### Additional info

论坛问题帖子: https://answer.flashcat.cloud/questions/10010000000002726

**Comment by 710leo** [comment]
最新版本已解决此问题
