### ISSUE TITLE
关于心跳和机器失联告警的一些疑问

### ISSUE THREAD

**Issue by qifenggang** [ccfos/nightingale#1589]
### Relevant server.conf | webapi.conf

```toml
无
```

### Relevant logs

```text
无
```

### System info

CentOS Linux release 7.9.2009 (Core)

### Steps to reproduce

n9e版本：v6.0.0-ga.7.0.2
1、机器失联的告警是通过GetHostAnomalyPoint函数来判断的吗 ？
2、看这个具体的逻辑是根据mysql target表中update_at这个字段和当前时间对比来判断的机器是否失联的
3、心跳上报之后好像没有更新update_at这个字段，是不是心跳上报的时候更新update_at 会更合适
个人理解，希望能指正。

### Expected behavior

机器失联告警根据心跳判断

### Actual behavior

根据mysql表里面判断

**Comment by UlricQin** [comment]
update_at 我印象里是在收到监控数据的时候更新的，不是根据heartbeat更新的。因为只有categraf有心跳机制，如果用了其他agent，就不好弄了。所以是在收到监控数据的时候做更新

**Comment by qifenggang** [comment]
> update_at 我印象里是在收到监控数据的时候更新的，不是根据heartbeat更新的。因为只有categraf有心跳机制，如果用了其他agent，就不好弄了。所以是在收到监控数据的时候做更新

是的，不过这个上报数据建个比心跳间隔大，建议在heartbeat的时候增加一下rt.IdentSet.MSet(items) ，这样机器失联的 告警会及时点

**Comment by UlricQin** [comment]
这是个好建议，可以搞
