### ISSUE TITLE
调整告警规则生效时间

### ISSUE THREAD

**Issue by 710leo** [ccfos/nightingale#1590]
详情见 https://answer.flashcat.cloud/questions/10010000000002683

**Comment by SunnyBoy-WYH** [comment]
想问一下，如果配置的时间段是8:00-8:00，链接中提到的屏蔽规则的之前优化点是认为【这种8:00-8:00时间配置是完整的一天，而不是0时长】？因为我看代码，两者时间相等，直接认为告警事件match上mute规则了

**Comment by 710leo** [comment]
@SunnyBoy-WYH 是的
