### ISSUE TITLE
elasticsearch7.17.10接入后字段名称显示异常

### ISSUE THREAD

**Issue by hunter-luo** [ccfos/nightingale#1593]
### Relevant server.conf | webapi.conf

```toml
无
```

### Relevant logs

```text
夜莺接入elasticsearch 后，查看日志。
索引的字段名称应该显示为：kubernetes.pod.name 但是在夜莺实际显示的是：pod.name 夜莺这边少了kubernetes这段。
用kibana查看就是正常的。
```

### System info

n9e  6.0 ga 11

### Steps to reproduce

![image](https://github.com/ccfos/nightingale/assets/138017478/eec3a6f0-c9bc-4091-93b2-e8d9afa215ef)
![image](https://github.com/ccfos/nightingale/assets/138017478/d11d2bf8-0344-4197-a0c4-94f2504d948b)

### Expected behavior

kubernetes.pod.name

### Actual behavior

pod.name

### Additional info

data:
  filebeat.yml: |-
    filebeat.inputs:
    - type: container
      paths:
        - /var/log/containers/*.log
      processors:
        - add_kubernetes_metadata:
            default_indexers.enabled: true
            default_matchers.enabled: true
            host: ${NODE_NAME}
            matchers:
            - logs_path:
                logs_path: "/var/log/containers/"

**Comment by jsers** [comment]
最新版本已修复
