### ISSUE TITLE
告警规则上报自愈脚本信息过少

### ISSUE THREAD

**Issue by foreverrice** [ccfos/nightingale#1596]
**What would you like to be added**:
告警规则上报自愈脚本，需要像webhook中上报的信息
**Why is this needed**:
自愈脚本处理至少需要知道告警上报的一些信息，比如ruleName、几级报警、附加标签中看出是哪个集群机器，告警时是表等等，此时自愈脚本才好根据条件去执行

**Comment by UlricQin** [comment]
支持这个建议，这个也是一直想搞的，只是受限于人力一直没做，产品上是需要支持这个能力的
