### ISSUE TITLE
Install the Python 'requests' package in the Nightingale Docker image

### ISSUE THREAD

**Issue by wknb** [ccfos/nightingale#1610]
**What would you like to be added**:
在夜莺的dockerfile中安装requests包
**Why is this needed**:
因为v6版本的夜莺支持在线配置python脚本来对接外部通知方式，外部通知方式一般都需要用到requests包，如果镜像没有打的话，每次更新版本都需要手动安装一下，做不到开箱即用。

**Comment by UlricQin** [comment]
需要修改的 Dockerfile 文件在这里：https://github.com/ccfos/nightingale/tree/main/docker

- [Dockerfile.goreleaser](https://github.com/ccfos/nightingale/blob/main/docker/Dockerfile.goreleaser)
- [Dockerfile.goreleaser.arm64](https://github.com/ccfos/nightingale/blob/main/docker/Dockerfile.goreleaser.arm64)

来个 PR?

**Comment by UlricQin** [comment]
新版本应该支持了我记得，可以测试下

**Comment by RUST911** [comment]
> **What would you like to be added**: 在夜莺的dockerfile中安装requests包 **Why is this needed**: 因为v6版本的夜莺支持在线配置python脚本来对接外部通知方式，外部通知方式一般都需要用到requests包，如果镜像没有打的话，每次更新版本都需要手动安装一下，做不到开箱即用。

我升级到6.0.2版本还是不支持。请问咱们手动安装的支持方法是怎么实现的

**Comment by RUST911** [comment]
> 新版本v6.0.2应该支持了我记得，可以测试下

请问我在自定义脚本里使用了阿里云的短信sdk，但是报错：
ERROR sender/plugin.go:92 event_script_notify_fail: exec script ./.notify_scriptt occur error: exit status 1, output: Traceback (most recent call last):
  File "/app/./.notify_scriptt", line 5, in <module>
    from aliyunsdkcore.client import AcsClient
ModuleNotFoundError: No module named 'aliyunsdkcore'
请问这种应该怎么处理，在哪pip install吗

**Comment by UlricQin** [comment]
> > 新版本v6.0.2应该支持了我记得，可以测试下
> 
> 请问我在自定义脚本里使用了阿里云的短信sdk，但是报错： ERROR sender/plugin.go:92 event_script_notify_fail: exec script ./.notify_scriptt occur error: exit status 1, output: Traceback (most recent call last): File "/app/./.notify_scriptt", line 5, in from aliyunsdkcore.client import AcsClient ModuleNotFoundError: No module named 'aliyunsdkcore' 请问这种应该怎么处理，在哪pip install吗

你的问题和 requests 包没关系，我看你单独提了 issue
