### ISSUE TITLE
v6.0.0.ga.13告警规则数据源展示优化

### ISSUE THREAD

**Issue by peterwoo1224** [ccfos/nightingale#1614]
**What would you like to be added**:
告警规则页面的数据源展示过长，下方拖拽条太细不太容易拖动，能否优化下
![image](https://github.com/ccfos/nightingale/assets/24648358/208c9124-46f4-4ebb-8036-52ddbce13730)

**Why is this needed**:
展示优化或者拖拽条放大

**Comment by jsers** [comment]
ga.14 版本对告警规则表格展示做了优化，可以升级看看
