### ISSUE TITLE
v6.0.0-ga.6 日志分析，索引查询，日志timestamp显示UTC时间，如何显示为CST

### ISSUE THREAD

**Issue by fanghanyun** [ccfos/nightingale#1615]
### Relevant server.conf | webapi.conf

```toml
v6.0.0-ga.6 日志分析，索引查询，日志timestamp显示UTC时间，如何显示为CST
```

### Relevant logs

```text
v6.0.0-ga.6 日志分析，索引查询，日志timestamp显示UTC时间，如何显示为CST
```

### System info

v6.0.0-ga.6-b62762b2e6d61d3e234636a26f0c88111c2cd840

### Steps to reproduce

v6.0.0-ga.6 日志分析，索引查询，日志timestamp显示UTC时间，如何显示为CST

### Expected behavior

v6.0.0-ga.6 日志分析，索引查询，日志timestamp显示UTC时间，如何显示为CST

### Actual behavior

v6.0.0-ga.6 日志分析，索引查询，日志timestamp显示UTC时间，如何显示为CST

**Comment by UlricQin** [comment]
争取本周解决这个问题。

**Comment by 710leo** [comment]
最新版本已优化此问题，可以到下载页面下载最新版本 https://flashcat.cloud/download/nightingale/
