### ISSUE TITLE
docker-compose 部署之后，发现端口全没有暴漏出来

### ISSUE THREAD

**Issue by Yuaninga** [ccfos/nightingale#1658]
### Relevant server.conf | webapi.conf

```toml
no，just use docker-compose up -d.
```

### Relevant logs

```text
~ docker logs n9e

[INFO  wait] --------------------------------------------------------
[INFO  wait]  docker-compose-wait 2.11.0
[INFO  wait] ---------------------------
[DEBUG wait] Starting with configuration:
[DEBUG wait]  - Hosts to be waiting for: [127.0.0.1:3306, 127.0.0.1:6379]
[DEBUG wait]  - Paths to be waiting for: []
[DEBUG wait]  - Timeout before failure: 30 seconds
[DEBUG wait]  - TCP connection timeout before retry: 5 seconds
[DEBUG wait]  - Sleeping time before checking for hosts/paths availability: 0 seconds
[DEBUG wait]  - Sleeping time once all hosts/paths are available: 0 seconds
[DEBUG wait]  - Sleeping time between retries: 1 seconds
[DEBUG wait] --------------------------------------------------------
[INFO  wait] Checking availability of host [127.0.0.1:3306]
[INFO  wait] Host [127.0.0.1:3306] not yet available...
[INFO  wait] Host [127.0.0.1:3306] not yet available...
[INFO  wait] Host [127.0.0.1:3306] is now available!
[INFO  wait] --------------------------------------------------------
[INFO  wait] Checking availability of host [ 127.0.0.1:6379]
[INFO  wait] Host [ 127.0.0.1:6379] is now available!
[INFO  wait] --------------------------------------------------------
[INFO  wait] docker-compose-wait - Everything's fine, the application can now start!
[INFO  wait] --------------------------------------------------------
runner.cwd: /app
runner.hostname: n9e
runner.fd_limits: (soft=1048576, hard=1048576)
runner.vm_limits: (soft=unlimited, hard=unlimited)
2023-08-02 16:08:10.095691 INFO memsto/busi_group_cache.go:110 timer: sync busi groups done, cost: 5ms, number: 1
2023-08-02 16:08:10.101774 INFO memsto/target_cache.go:169 timer: sync targets done, cost: 5ms, number: 1
2023-08-02 16:08:10.112337 INFO memsto/datasource_cache.go:109 timer: sync datasources done, cost: 10ms, number: 0
2023-08-02 16:08:10.113155 INFO memsto/alert_mute_cache.go:145 timer: sync mutes done, cost: 0ms, number: 0
2023-08-02 16:08:10.113866 INFO memsto/alert_rule_cache.go:135 timer: sync rules done, cost: 0ms, number: 0
2023-08-02 16:08:10.121195 INFO memsto/user_cache.go:171 timer: sync users done, cost: 0ms, number: 1
2023-08-02 16:08:10.133184 INFO memsto/user_group_cache.go:162 timer: sync user groups done, cost: 11ms, number: 1
2023-08-02 16:08:10.134123 INFO memsto/alert_subscribe_cache.go:170 timer: sync subscribes done, cost: 0ms, number: 0
2023-08-02 16:08:10.134725 INFO memsto/recording_rule_cache.go:136 timer: sync recording rules done, cost: 0ms, number: 0
2023-08-02 16:08:10.137926 DEBUG models/notify_tpl.go:220 no tpl files under /app/etc/template, use default tpl
2023-08-02 16:08:10.153167 INFO naming/hashring.go:39 hash ring 99999999 rebuild [192.168.65.3:17000]
2023-08-02 16:08:10.153538 WARNING sender/email.go:108 SMTP configurations invalid
http server listening on: 0.0.0.0:17000
2023-08-02 16:08:19.104206 INFO memsto/target_cache.go:169 timer: sync targets done, cost: 1ms, number: 1
```

### System info

no

### Steps to reproduce

1. docker compose up -d

docker-compose up -d               
[+] Building 2.8s (12/12) FINISHED                                                                                                                          
 => [internal] load build definition from Dockerfile                                                                                                   0.0s
 => => transferring dockerfile: 224B                                                                                                                   0.0s
 => [internal] load .dockerignore                                                                                                                      0.0s
 => => transferring context: 109B                                                                                                                      0.0s
 => [internal] load metadata for docker.io/library/python:3-slim                                                                                       2.1s
 => http://download.flashcat.cloud/wait                                                                                                                0.1s
 => [1/6] FROM docker.io/library/python:3-slim@sha256:36b544be6e796eb5caa0bf1ab75a17d2e20211cad7f66f04f6f5c9eeda930ef5                                 0.0s
 => [internal] load build context                                                                                                                      0.5s
 => => transferring context: 35.68MB                                                                                                                   0.5s
 => CACHED [2/6] WORKDIR /app                                                                                                                          0.0s
 => CACHED [3/6] ADD n9e /app                                                                                                                          0.0s
 => CACHED [4/6] ADD http://download.flashcat.cloud/wait /wait                                                                                         0.0s
 => CACHED [5/6] RUN chmod +x /wait                                                                                                                    0.0s
 => CACHED [6/6] RUN chmod +x n9e                                                                                                                      0.0s
 => exporting to image                                                                                                                                 0.0s
 => => exporting layers                                                                                                                                0.0s
 => => writing image sha256:4ce8d62d2ce8b1ff54fbd40c23a4688cb7ce481a51a58b1893088a11ed606a42                                                           0.0s
 => => naming to docker.io/library/docker-web                                                                                                          0.0s

Use 'docker scan' to run Snyk tests against images to find vulnerabilities and learn how to fix them
[+] Running 8/8
 ⠿ Network docker_default  Created                                                                                                                     0.1s
 ⠿ Container docker-web-1  Started                                                                                                                     1.3s
 ⠿ Container mysql         Started                                                                                                                     0.8s
 ⠿ Container redis         Started                                                                                                                     0.8s
 ⠿ Container prometheus    Started                                                                                                                     0.8s
 ⠿ Container ibex          Started                                                                                                                     0.8s
 ⠿ Container n9e           Started                                                                                                                     1.0s
 ⠿ Container categraf      Started                                                                                                                     1.2s

### Expected behavior

> docker ps               
CONTAINER ID   IMAGE                              COMMAND                  CREATED         STATUS          PORTS                      NAMES
13178b2c63a6   flashcatcloud/categraf:latest      "/entrypoint.sh"         7 minutes ago   Up 7 minutes                               categraf
b5029a4f0d90   flashcatcloud/nightingale:latest   "sh -c '/wait && /ap…"   7 minutes ago   Up 24 seconds   0.0.0.0:17000->17000/tcp   n9e
782b5c53f7b7   ulric2019/ibex:0.3                 "sh -c '/wait && /ap…"   7 minutes ago   Up 7 minutes                               ibex
e8ce08b674c5   mysql:5.7                          "docker-entrypoint.s…"   7 minutes ago   Up 7 minutes                               mysql
df3a28f4fe1d   prom/prometheus                    "/bin/prometheus --c…"   7 minutes ago   Up 7 minutes                               prometheus
b61edc363d0d   redis:6.2                          "docker-entrypoint.s…"   7 minutes ago   Up 7 minutes                               redis

### Actual behavior

> docker ps
CONTAINER ID   IMAGE                              COMMAND                  CREATED          STATUS          PORTS     NAMES
b9692f48ee98   flashcatcloud/categraf:latest      "/entrypoint.sh"         11 seconds ago   Up 9 seconds              categraf
f4f33f6116c1   flashcatcloud/nightingale:latest   "sh -c '/wait && /ap…"   11 seconds ago   Up 9 seconds              n9e
fccc358f94b1   ulric2019/ibex:0.3                 "sh -c '/wait && /ap…"   11 seconds ago   Up 9 seconds              ibex
b409c69401f2   mysql:5.7                          "docker-entrypoint.s…"   11 seconds ago   Up 10 seconds             mysql
b86a4a62b499   prom/prometheus                    "/bin/prometheus --c…"   11 seconds ago   Up 10 seconds             prometheus
7e8abbcb78fc   redis:6.2                          "docker-entrypoint.s…"   11 seconds ago   Up 10 seconds             redis

### Additional info

查看了下是新改版之后，使用 network_mode: host 时，容器将共享主机的网络命名空间，这意味着容器将直接使用主机的网络栈，而无需进行端口映射或网络地址转换。之前的端口映射都去掉了，所以现在没有对外暴漏出对应端口。

**Comment by Yuaninga** [comment]
使用的是目前的v6.0.0 版本，mac，linux都实验过，无法出现端口。
<img width="1149" alt="image" src="https://github.com/ccfos/nightingale/assets/64267484/f5f18695-1a47-41ee-b051-d351d2fc8515">

**Comment by UlricQin** [comment]
默认用的 host network

**Comment by xcxinng** [comment]
使用host网络不需要暴露端口了的，而且看n9e日志 这不是正常起来了吗😃
