### ISSUE TITLE
Suggestion: Add Dropdown Box Filtering for Legends

### ISSUE THREAD

**Issue by bbaobelief** [ccfos/nightingale#1662]
**Legend 现在只支持表格和列表，但是开启之后太占地方。**
![image](https://github.com/ccfos/nightingale/assets/3918461/ee58c739-1c5d-4ff3-8df4-e21e860ca6d0)
**希望可以在图表右上角 下拉选择**
![image](https://github.com/n9e/fe/assets/3918461/082ec578-01e2-4244-b17f-0dab88a9a1ac)

**Comment by jsers** [comment]
后面版本会优化 Legend
但是不会考虑在标题栏通过下拉选择器，这种方式体验也不是很好，选择的值回填到选择框里面空间也不够会被省略处理
目前设想的优化方案是 Legend 默认只显示（1-2 行信息）然后通过展开一个浮层来展示完整的信息

zheng ***@***.***> 于2023年8月4日周五 16:43写道：

**Comment by jsers** [comment]
新版本已经支持自定义 legend 容器的高度
