### ISSUE TITLE
关于通知媒介建议

### ISSUE THREAD

**Issue by liuxin638507** [ccfos/nightingale#1669]
对于通知媒介，比如告警
目前是针对单用户配置，可对这个用户单独配置（很好）

但是单独创建一个用户作为告警不太合理（而且这个告警用户不需要登录），建议新增选项配置，把所有需要告警的都列出来（最后可自定义显示别名，xxx项目告警：toekn值），如用户管理界面一样管理已配置了的列表：作为自定义告警通知选项，团队可选择性关联已配置好的告警列表

**Comment by UlricQin** [comment]
计划在v7版本考虑这块的设计

**Comment by UlricQin** [comment]
核心提交者内部对了一下，这个设计和目前创建虚拟账号（如果担心安全，可以考虑设置一个没有任何权限的角色，专门给这类虚拟用户使用。虚拟用户的密码设置的巨复杂，以防泄露，反正这些虚拟用户并不会登陆系统）的设计差别不大，暂不做改动。v7版本可能会考虑设计通知媒介管理，不止管理token，还要支持加签密钥等
