### ISSUE TITLE
是否支持级联告警配置

### ISSUE THREAD

**Issue by liuxin638507** [ccfos/nightingale#1670]
添加了categraf一个采集器，下面有不同的服务，假设采集了mysql的相关指标，配置了mysql的告警规则
现在采集器某些原因没采集到数据（网络和主机异常，负载临时压力大等等），导致这个采集器下的所有告警规则都告警，无法判断是采集器除了问题还是其他服务挂了

是否支持告警某一个服务前，先判断采集器的状态或者依赖的上层服务是否正常，
采集器状态正常就报对应采集配置的服务，
如果采集器本身不正常，这个采集器下所有的都别告警了，只需要发送一条采集器异常

**Comment by kongfei605** [comment]
categraf 自身有self_metrics 监控（查文档打开一下），会有个categraf_info的指标，可以判断categraf状态。 根据这个指标来写promql就能实现你的目标

**Comment by UlricQin** [comment]
比如disk_free>5这个告警规则，如果agent有问题，数据无法上报，告警引擎查不到disk_free的数据，是不会告警的
