### ISSUE TITLE
Dashboard Full-Screen Issue

### ISSUE THREAD

**Issue by samgang** [ccfos/nightingale#1671]
### Relevant server.conf | webapi.conf

```toml
no
```

### Relevant logs

```text
no
```

### System info

v6.0.1

### Steps to reproduce

1.监控仪表盘
2.点击仪表盘名称，进行预览，点击全屏
![image](https://github.com/ccfos/nightingale/assets/16316300/58121d6d-d5ae-4f89-9eba-0e777ac8c706)
问题：右上角这些按钮选项是不是应该全部消失？
建议参考 GRAFANA的全屏展示

3.退出全屏，直接回到仪表盘列表了
问题：退出全屏不应该还在当前列表吗，又不是退出该仪表盘？
建议参考 GRAFANA的全屏展示
...

### Expected behavior

如上

### Actual behavior

如上

**Comment by 710leo** [comment]
最新版本已修复此问题
