### ISSUE TITLE
Adding multiple contacts of the same type, only one is effective after saving

### ISSUE THREAD

**Issue by liuxin638507** [ccfos/nightingale#1673]
### Relevant server.conf | webapi.conf

```toml
可以选择填多个钉钉，但是保存后只有最后一个输入的钉钉联系方式，是bug还是就是唯一设置？
如果是唯一设置，第一次输入完毕后，就不应该再显示已经填过的联系方式的可选项
```

### Relevant logs

```text
提示成功，同类型联系方式但是只有一个生效
```

### System info

centos7.9 n9e: 6.0.2

### Steps to reproduce

![image](https://github.com/ccfos/nightingale/assets/32058132/f1231fee-e209-4585-8672-5d188d6a926c)

### Expected behavior

-

### Actual behavior

-

### Additional info

-

**Comment by jsers** [comment]
Fixed in v6.0.3
