### ISSUE TITLE
The subscription rule for business groups is not effective

### ISSUE THREAD

**Issue by liuxin638507** [ccfos/nightingale#1674]
### Relevant server.conf | webapi.conf

```toml
-
```

### Relevant logs

```text
-
```

### System info

centos7.9 n9e: 6.0.2

### Steps to reproduce

已添加钉钉告警用户，所属业务组，但是告警的时候并没有发送对应业务组告警通知到钉钉
用户：
![image](https://github.com/ccfos/nightingale/assets/32058132/d654ddcf-599d-4ab2-bf0b-8f09c5793580)
业务组：
![image](https://github.com/ccfos/nightingale/assets/32058132/97d0b060-81fa-44d2-8c71-99c2f4a190b4)
机器列表
![image](https://github.com/ccfos/nightingale/assets/32058132/a6f5c8d3-b3c8-4e38-931e-94b20ff2079f)
订阅规则：
这儿也有一个改进的地方：监控类型metris和hosts不能都勾选吗，创建规则的时候还单独选择，导致订阅规则里面2条几乎完全一样
![image](https://github.com/ccfos/nightingale/assets/32058132/2b8aebc4-8f94-4567-9eba-9f75caa73672)
![image](https://github.com/ccfos/nightingale/assets/32058132/1082a059-d884-4dc1-9f1a-8662a196f932)

### Expected behavior

-

### Actual behavior

-

**Comment by 710leo** [comment]
<img width="717" alt="image" src="https://github.com/ccfos/nightingale/assets/2169271/1bd97300-95ee-4542-9525-74d23d4bd7bd">
<img width="146" alt="image" src="https://github.com/ccfos/nightingale/assets/2169271/ce5567bc-4a2d-478d-ba83-97e8c0ac40cd">    

没生效的原因是 业务组名称没匹配上

**Comment by liuxin638507** [comment]
这是选择的两个业务组，一个公共服务组和yim组，是in包含关系



---原始邮件---
发件人: "Yening ***@***.***&gt;
发送时间: 2023年8月15日(周二) 中午11:33
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [ccfos/nightingale] 订阅规则订阅业务组不生效 (Issue #1674)




       
没生效的原因是 业务组名称没匹配上
