### ISSUE TITLE
Built-in dashboard - Collection instructions No Data

### ISSUE THREAD

**Issue by liuxin638507** [ccfos/nightingale#1676]
### Relevant server.conf | webapi.conf

```toml
Click Dashboard --> Built-in dashboard, select a category, after viewing the dashboard, click the collection description again, there will be No Data blank, select another category again, return to the previously viewed category collection description or refresh the browser to display
```

### Relevant logs

```text
-
```

### System info

centos7.9 n9e: 6.0.2

### Steps to reproduce

![image](https://github.com/ccfos/nightingale/assets/32058132/7e187e09-9032-4711-86fb-3ecb6f53739d)

![image](https://github.com/ccfos/nightingale/assets/32058132/128cc5bc-9403-4fe2-90be-8f5fd3817ac0)

### Expected behavior

-

### Actual behavior

-

**Comment by UlricQin** [comment]
下个版本就有了，现在可以先参考：https://github.com/ccfos/nightingale/tree/main/integrations/ElasticSearch/markdown 

PS：后面有些插件可能不会有README，特别是有些插件是社区的人贡献的，贡献者可能就没有提供README。需要社区一起来完善。完善方法就是编写 integrations 下面每个插件的 markdown 下的 README.md
