### ISSUE TITLE
告警规则选择多个集群的时候，在告警规则页面无法通过集群搜索出来这条规则

### ISSUE THREAD

**Issue by Guwenqiang** [ccfos/nightingale#1678]
前端版本：5.15.0
后端版本：v5.15.0-87899cbedbc7bfcfff61052ebeed945a57a418d2

为一条告警配置了多个集群
![image](https://github.com/ccfos/nightingale/assets/42791612/51e98716-de22-4d6f-8c29-d912e80267b7)

集群方式筛选，无法找到对应规则
![image](https://github.com/ccfos/nightingale/assets/42791612/01f25e1d-52d5-4b17-894a-6f2f22496810)

**Comment by UlricQin** [comment]
v6我测试没问题，升级到v6即可解决
