### ISSUE TITLE
Bug:使用pg作为数据源，告警管理下的订阅规则和屏蔽规则JSON转换异常

### ISSUE THREAD

**Issue by qihang-sun** [ccfos/nightingale#1682]
### Relevant server.conf | webapi.conf

```toml
DBType = "postgres"
```

### Relevant logs

```text
failed to sync alert subscribes: failed to exec AlertSubscribeGetsAll: sql: Scan error on column index 9, name "tags": Failed to unmarshal JSONB value:[{"func":"==","key":"1","value":"1"},{"func":"==","key":"2","value":"2"}]
```

### System info

n9e 6.0.0

### Steps to reproduce

复现步骤：数据源从MySQL切换到PgSQL后，查询、新增订阅规则和屏蔽规则报错
fix-bug:将结构体AlertSubscribe和结构体AlertMute的Tags的类型由ormx.JSONArr改为ormx.JSONObj，问题消失

### Expected behavior

正常新增和查询

### Actual behavior

新增查询报错

**Comment by tanxiao1990** [comment]
贴一下表结构信息

**Comment by qihang-sun** [comment]
> 贴一下表结构信息

MySQL表结构：create table alert_subscribe
(
    id                bigint unsigned auto_increment
        primary key,
    name              varchar(255)  default '' not null,
    disabled          tinyint(1)    default 0  not null comment '0:enabled 1:disabled',
    group_id          bigint        default 0  not null comment 'busi group id',
    prod              varchar(255)  default '' not null,
    cate              varchar(128)             not null,
    datasource_ids    varchar(255)  default '' not null comment 'datasource ids',
    cluster           varchar(128)             not null,
    rule_id           bigint        default 0  not null,
    severities        varchar(32)   default '' not null,
    tags              varchar(4096) default '' not null comment 'json,map,tagkey->regexp|value',
    redefine_severity tinyint(1)    default 0  null comment 'is redefine severity?',
    new_severity      tinyint(1)               not null comment '0:Emergency 1:Warning 2:Notice',
    redefine_channels tinyint(1)    default 0  null comment 'is redefine channels?',
    new_channels      varchar(255)  default '' not null comment 'split by space: sms voice email dingtalk wecom',
    user_group_ids    varchar(250)             not null comment 'split by space 1 34 5, notify cc to user_group_ids',
    webhooks          text                     not null,
    extra_config      text                     not null,
    redefine_webhooks tinyint(1)    default 0  null,
    for_duration      bigint        default 0  not null,
    create_at         bigint        default 0  not null,
    create_by         varchar(64)   default '' not null,
    update_at         bigint        default 0  not null,
    update_by         varchar(64)   default '' not null
);

**Comment by qihang-sun** [comment]
> 贴一下表结构信息

PgSQL表结构：create table alert_subscribe
(
    id                bigserial
        primary key,
    name              varchar(255)  default ''::character varying not null,
    disabled          smallint      default 0                     not null,
    group_id          bigint        default 0                     not null,
    prod              varchar(255)  default ''::character varying not null,
    cate              varchar(128)                                not null,
    datasource_ids    varchar(255)  default ''::character varying not null,
    cluster           varchar(128)                                not null,
    rule_id           bigint        default 0                     not null,
    tags              varchar(4096) default ''::character varying not null,
    redefine_severity smallint      default 0,
    new_severity      smallint                                    not null,
    redefine_channels smallint      default 0,
    new_channels      varchar(255)  default ''::character varying not null,
    user_group_ids    varchar(250)                                not null,
    webhooks          text                                        not null,
    redefine_webhooks smallint      default 0,
    for_duration      bigint        default 0                     not null,
    create_at         bigint        default 0                     not null,
    create_by         varchar(64)   default ''::character varying not null,
    update_at         bigint        default 0                     not null,
    update_by         varchar(64)   default ''::character varying not null,
    extra_config      text                                        not null,
    severities        varchar(32)   default ''::character varying not null
);

**Comment by tanxiao1990** [comment]
在pg里面把  tags 从varchar(4096)改为  jsonb

**Comment by tanxiao1990** [comment]
busi_groups字段也手工改一下 jsonb类型，后续代码里修复

**Comment by tanxiao1990** [comment]
参考语句：
ALTER TABLE alert_subscribe ALTER COLUMN busi_groups TYPE jsonb USING busi_groups::jsonb::jsonb;
ALTER TABLE alert_subscribe ALTER COLUMN busi_groups SET DEFAULT '[]';

**Comment by qihang-sun** [comment]
> 参考语句： ALTER TABLE alert_subscribe ALTER COLUMN busi_groups TYPE jsonb USING busi_groups::jsonb::jsonb; ALTER TABLE alert_subscribe ALTER COLUMN busi_groups SET DEFAULT '[]';
👌

**Comment by yanyanguo** [comment]
@qihang-sun 目前使用夜莺想用pgsql替代msql，咨询下大佬mysql的数据表结构是如何转换到pgsql的  默认的那个sql文件用网上的工具转完语法不太对
