### ISSUE TITLE
Add a 'Duration of Alert' column to active alerts

### ISSUE THREAD

**Issue by wthahaha** [ccfos/nightingale#1688]
**What would you like to be added**:
在活跃告警页面，增加告警持续时间展示
**Why is this needed**:
便于相关方知晓故障持续时间，为后续事项推进提供直观的依据

**Comment by UlricQin** [comment]
这个可以有，算法可以是：告警持续时间=当前时间-首次告警时间。展示的时候，字段名字可以是：距离首次告警，比如：
```
距离首次告警：1h3m2s
```

**Comment by idcdog** [comment]
如果使用钉钉模板, 可以这么写
```
**发送时间**: {{timestamp}}
 
{{$time_duration := sub now.Unix .FirstTriggerTime }}{{if .IsRecovered}}{{$time_duration = sub .LastEvalTime .FirstTriggerTime }}{{end}}**持续时长**: {{humanizeDurationInterface $time_duration}}
 
**首次触发时间**: {{timeformat .FirstTriggerTime}}

```

**Comment by wthahaha** [comment]
> 这个可以有，算法可以是：告警持续时间=当前时间-首次告警时间。展示的时候，字段名字可以是：距离首次告警，比如：
> 
> ```
> 距离首次告警：1h3m2s
> ```

大佬们，这个功能未来会添加么？

**Comment by UlricQin** [comment]
> > 这个可以有，算法可以是：告警持续时间=当前时间-首次告警时间。展示的时候，字段名字可以是：距离首次告警，比如：
> > ```
> > 距离首次告警：1h3m2s
> > ```
> 
> 大佬们，这个功能未来会添加么？

你的楼上不是已经给了答案
