### ISSUE TITLE
Alert mutes

### ISSUE THREAD

**Issue by liuqian1990** [ccfos/nightingale#1705]
![image](https://github.com/ccfos/nightingale/assets/8868514/085f5401-1521-4b11-9e05-b7938b4752b4)
设置的告警沉默不行效

**Comment by UlricQin** [comment]
要注意告警屏蔽规则只对相同业务组下的告警规则生效

**Comment by liuqian1990** [comment]
多谢，了解了

**Comment by liuqian1990** [comment]
看了是已经加了业务组的，现在就一个业务组

**Comment by UlricQin** [comment]
> 要注意告警屏蔽规则只对相同业务组下的告警规则生效

这只是最常见的错误。其他的还需要检查配置。多检查几遍大概率就发现问题了。

**Comment by idcdog** [comment]
检查一下屏蔽规则中是否包含了
rulename 这个key， 我这里也发现了屏蔽不生效的问题
对比了一下异常和正常的屏蔽规则，发现似乎是早期版本中使用 rule_name 作为屏蔽条件（会导致无法屏蔽告警）
而新版本中（v6.6.1）中使用rulename作为屏蔽条件
目前已经不确认这个差异点是在什么时候引入的了, 我这里检查rule_name这个屏蔽条件的规则是在23年10月11日创建的

综上：
如果发现自己屏蔽告警没生效，检查屏蔽条件中是否有引用”rule_name“这个标签，修改为rulename即可
如果懒得一个个在界面检查， 直接到数据库alert_mute表中检查

select * from alert_mute where  tags like "%rule_name%"\G;
