### ISSUE TITLE
The level suppression within the alert rules of metrics is not functioning effectively

### ISSUE THREAD

**Issue by lldd123** [ccfos/nightingale#1709]
### Relevant server.conf | webapi.conf

```toml
..
```

### Relevant logs

```text
..
```

### System info

前端版本：v6.0.2 后端版本：v6.0.2-4fb4154e30e3ee502f35af18f8d42bb572d7ff53

### Steps to reproduce

1.新建一条告警规则
2.添加两个metric告警条件,级别分别设置为S1和S2,打开级别一直
3.触发两个告警条件

### Expected behavior

预期:只接收S1级别的告警

### Actual behavior

但告警抑制并不生效,S1和S2的告警都会发出来

**Comment by shardingHe** [comment]
To achieve high-level alert suppression of lower-level alerts, it is not the right way to configure two separate rules in the current version. Instead, you may configure multiple conditions within a single alert rule. For example, when configuring an alert rule of "Metric" type, you will notice an icon with a plus sign next to the "Queries" section.

**Comment by lldd123** [comment]
![image](https://github.com/ccfos/nightingale/assets/144794412/e48e7da6-a6e4-4b27-a223-a65fd0b77fc7)

我的配置如图,是在一个告警中,配置了多个不同级别的告警规则,但级别抑制并不生效

**Comment by 710leo** [comment]
级别抑制生效的前提条件是，告警事件的 metricName 和 labels 必须都相同才可以
