### ISSUE TITLE
Dashboard chart table configuration shows problems

### ISSUE THREAD

**Issue by sipufeng** [ccfos/nightingale#1719]
### Relevant server.conf | webapi.conf

```toml
none
```

### Relevant logs

```text
none
```

### System info

前端版本：v6.1.0 后端版本：v6.1.0-4a358f5cffdbdb6934ebeb11efe2018966b878ea

### Steps to reproduce

1.添加图片
2.图表类型为表格
3.图表样式 -> 显示模式 :每行展示指定聚合维度的值；
4.图表样式 -> **默认排序列：无法选择**
5.左侧预览 -> 数据转换(beta) -> **字段管理: 字段显示异常，并且无法修改**

### Expected behavior

根据自定义标签展示聚合维度数据值

### Actual behavior

1. 标签无法选择
2. 字段管理处显示异常并且字段值不断刷新

![WeChatacc02ceaf82e378b00a9a00db784a921](https://github.com/ccfos/nightingale/assets/46118429/b8b82eac-d194-4162-ae07-65d68baba81a)

**Comment by UlricQin** [comment]
@jsers was it resolved?

**Comment by jsers** [comment]
fixed in v6.2.x

ulricqin ***@***.***> 于2023年10月11日周三 08:01写道：
