### ISSUE TITLE
5.x版本的docker-compose启动时容器Restarting状态

### ISSUE THREAD

**Issue by zaghost** [ccfos/nightingale#1720]
### Relevant server.conf | webapi.conf

```toml
默认
```

### Relevant logs

```text
2023/09/20 18:19:28 main.go:36: failed to initialize: dialector() not supported
```

### System info

n9e 5.11.1，docker-ce 24.0.2，docker-compose 1.29.2

### Steps to reproduce

1.使用5.10.0以上5.x版本的release包或源码中的docker-compose.yaml启动

### Expected behavior

容器能进入正常状态

### Actual behavior

ibex/nserver/nwebapi容器一直重启

### Additional info

docker-compose.yaml中
1）ibex使用的镜像ulric2019/ibex:0.3中，并没有/wait命令
2）nwebapi/nserver使用的镜像flashcatcloud/nightingale:latest，版本已经是6.x，和mysql:5.7不兼容

**Comment by UlricQin** [comment]
v5已经过了维护周期了。使用v6测试吧。测试方法：

```
git clone https://github.com/ccfos/nightingale.git
cd nightingale/docker
docker-compose up -d
```
