### ISSUE TITLE
订阅规则修改后保存提示缺少字段

### ISSUE THREAD

**Issue by lldd123** [ccfos/nightingale#1723]
### Relevant server.conf | webapi.conf

```toml
..
```

### Relevant logs

```text
..
```

### System info

前端版本：v6.0.2 后端版本：v6.0.2,数据库mysql 5.7

### Steps to reproduce

订阅规则点击编辑报错缺少字段(busi_groups) 

### Expected behavior

可以点击编辑按钮.对订阅规则进行保存

### Actual behavior

![image](https://github.com/ccfos/nightingale/assets/144794412/050c54cb-a67a-4411-bcda-e1cc8a06491f)

### Additional info

数据库中 alert_subscribe并没有busi_groups这个字段.但是在代码中alert_subscribe表的gorm对象中的确是有busi_groups字段
![image](https://github.com/ccfos/nightingale/assets/144794412/5a38c8bf-7224-40c2-9549-e2307f466fd0)

**Comment by 710leo** [comment]
升级到最新版本吧
