### ISSUE TITLE
upgrading from version 6.0.13ga to 6.2.0 via binary installation on n9e, the alert items from active alerts have vanished

### ISSUE THREAD

**Issue by lyitt1987** [ccfos/nightingale#1726]
升级方式，直接下载二进制版，停止n9e进程，把n9e执行文件覆盖旧版本n9e，然后启动
请问这是什么情况

**Comment by 710leo** [comment]
活跃告警目前只展示最近6个小时的新产生的告警，下个版本会修复这个问题

**Comment by lyitt1987** [comment]
那请问，下个版本什么时候发布？

**Comment by lyitt1987** [comment]
> 活跃告警目前只展示最近6个小时的新产生的告警，下个版本会修复这个问题

我已经升级到6.3.0，但是活跃告警的时间选择还是没有，请问6.3.0的这个功能是展示最近多长时间的？
![image](https://github.com/ccfos/nightingale/assets/35764082/f0f94168-b955-4a4a-9e93-62f3fd420ee9)
