### ISSUE TITLE
Requirement for alarm aggregation

### ISSUE THREAD

**Issue by qq732552048** [ccfos/nightingale#1731]
目前的告警聚合只有在web界面展示的时候支持，但是发出的邮件之类是不支持的。
类似于alertmanager的subject功能：
receivers:
- name: 'yunwei'
  email_configs:
  - to: 'yunwei_alarm@xx.cn'
    html: '{{ template "email.html" . }}'
    send_resolved: false
    headers:
      subject: " {{ .CommonLabels.alertname }} idc={{ .CommonLabels.idc }} role={{ .CommonLabels.role }}"

这样可以将多封相同类型的邮件进行合并，在出现批量故障的时候不会被海量的告警淹没。

**Comment by 710leo** [comment]
在专业版里是有支持的，可以到下载页面下载试用下 https://flashcat.cloud/download/nightingale/
