### ISSUE TITLE
Questions concerning the high availability of the Nightingale Alert Engine

### ISSUE THREAD

**Issue by luzejia** [ccfos/nightingale#1732]
# 夜莺的告警引擎高可用问题

2个n9e组成集群（使用相同的redis和mysql），然后当把另一个n9e关掉的时候，发现这里依旧会显示2个告警引擎，没有实时剔除

<img width="1272" alt="image" src="https://github.com/ccfos/nightingale/assets/52991866/bcec51e3-d262-4eab-9c53-b7cb5fc3003d">

**Comment by 710leo** [comment]
从截图看 17 的实例心跳已经停止了，过段时间会被清理

**Comment by luzejia** [comment]
> 从截图看 17 的实例心跳已经停止了，过段时间会被清理

谢谢
