### ISSUE TITLE
How to upgrade through Helm installation?

### ISSUE THREAD

**Issue by lyitt1987** [ccfos/nightingale#1735]
比如6.0.0升级为6.2.0。
我直接修改values.yaml文件镜像tag为6.2.0，然后用 helm upgrade 。。。,center pod并未更新。
那helm安装的n9e该如何升级呢

**Comment by kongfei605** [comment]
kubectl delete 对应pod 试试呢？

**Comment by lyitt1987** [comment]
> kubectl delete 对应pod 试试呢？

所以后面我直接修改pod容器的tag，然后就能升级了
