### ISSUE TITLE
Edge deployment, Prometheus error reported

### ISSUE THREAD

**Issue by lyitt1987** [ccfos/nightingale#1737]
level=error component=web msg="Out of order sample from remote write" err="out of bounds" series="{__name__=\"conntrack_ip_conntrack_count\", ident=\"ces-192.168.3.200\", servicetype=\"web\"}" timestamp=1697013226737

中心机房的n9e有对服务器有绑定标签 servicetype=web
edge也对加入到中心机房n9e后，也对服务器绑定相同标签 servicetype=web
请大佬解答，谢谢！

**Comment by aaluopy** [comment]
你在哪里找到的edge，我找了半天，硬是没找到。

**Comment by lyitt1987** [comment]
> 你在哪里找到的edge，我找了半天，硬是没找到。

下载压缩包比如https://github.com/ccfos/nightingale/releases/download/v6.3.0/n9e-v6.3.0-linux-amd64.tar.gz，解压后里面有edge，etc/edge/下面有edge的配置文件

**Comment by 710leo** [comment]
> level=error component=web msg="Out of order sample from remote write" err="out of bounds" series="{**name**="conntrack_ip_conntrack_count", ident="ces-192.168.3.200", servicetype="web"}" timestamp=1697013226737
> 
> 中心机房的n9e有对服务器有绑定标签 servicetype=web edge也对加入到中心机房n9e后，也对服务器绑定相同标签 servicetype=web 请大佬解答，谢谢！

没明白这个是什么问题，可以在详细描述下
