### ISSUE TITLE
helm 6.2.0 升级到 6.3.0 问题

### ISSUE THREAD

**Issue by lyitt1987** [ccfos/nightingale#1741]
目前发现的问题，如图
![image](https://github.com/ccfos/nightingale/assets/35764082/103fd8f5-9f44-4c81-880e-1f4b246ce1b7)

活跃告警也会因为查不到数据而恢复，实际告警项并未处理

**Comment by 710leo** [comment]
可以升级到 v6.3.1，在最新版本修复了此问题
