### ISSUE TITLE
dead lock when update `target` table 

### ISSUE THREAD

**Issue by nichtsen** [ccfos/nightingale#1742]
### Relevant server.conf | webapi.conf
- center
etc/config.yaml
```toml
[DB]
DBType = "mysql"
DSN = "mysql:mysql@tcp(127.0.0.1:3306)"
```
- categraf 
```toml
[[writers]]
url = "${edge_address}/prometheus/v1/write"
[heartbeat]
enable = true
url = "${edge_address}/v1/n9e/edge/heartbeat"
```
### Relevant logs
we can notice that both transaction update timestiamp to 1697261616, which indicate that two goroutines occured in
the same second
 
```text
LATEST DETECTED DEADLOCK
------------------------
2023-10-14 09:00:03 1400484461885440
*** (1) TRANSACTION:
TRANSACTION 32030556, ACTIVE 0 sec starting index read
mysql tables in use 1, locked 1
LOCK WAIT 6 lock struct(s), heap size 1128, 102 row lock(s), undo log entries 50
MySQL thread id xxxxxx, OS thread handle 140048207931136, query id 187547026 127.0.0.1 root updating
UPDATE `target` SET `update_at`=1697261616 WHERE ident in (......)
*** (2) TRANSACTION:
TRANSACTION 32423895, ACTIVE 0 sec fetching rows
mysql tables in use 1, locked 1
LOCK WAIT 3 lock struct(s), heap size 1128, 41 row lock(s), undo log entries 40
MySQL thread id 1213979, OS thread handle 140048267732736, query id 189558005 127.0.0.1 root updating
UPDATE `target` SET `update_at`=1697261616 WHERE ident in (......)
*** WE ROLL BACK TRANSACTION (1)...
```

### System info
Categraf + n9e-edge 
v6.3.1

### Steps to reproduce
1. deploy n9e v6 with center and edge mode
1. depoly many categrafs that  enable both heartbeat and writer and with interval = 10s

3. use a mysql client to check status
```sql
SHOW ENGINE INNODB STATUS
```
3 a dead lock would be detected around every 20 minutes

### Expected behavior

push gateway should update  column `target.update_at` in a manner that resist dead lock as edge node call  API to center

### Actual behavior
edge call api  "/v1/n9e/target-update" to update targets in its persist loop ,
the problem is centers has its own persist loop, that would case race issue in database level
https://github.com/ccfos/nightingale/blob/f93e2ad4b65f33d03d3a83802ab6268afdd25609/pushgw/idents/idents.go#L91-L99

**Comment by shardingHe** [comment]
Do you mind providing the complete deadlock logs? I guess it would seem like that.
```
*** (1) TRANSACTION:
...
*** (2) TRANSACTION:
...
```

**Comment by nichtsen** [comment]
> Do you mind providing the complete deadlock logs? I guess it would seem like that.
> 
> ```
> *** (1) TRANSACTION:
> ...
> *** (2) TRANSACTION:
> ...
> ```

updated

**Comment by shardingHe** [comment]
Thanks for your feedback. I have a hunch, but would you mind providing the logs for n9e-edge and n9e-center around the time when the anomaly occurred? 
My suspicion is that it's related to updating the target table data. Currently, the update statements are using secondary index( `UPDATE target SET update_at=11111 WHERE ident in (‘aa’)
` ), and the deadlock might have been caused by conflicting lock attempts between different transactions.

**Comment by nichtsen** [comment]
> Thanks for your feedback. I have a hunch, but would you mind providing the logs for n9e-edge and n9e-center around the time when the anomaly occurred? My suspicion is that it's related to updating the target table data. Currently, the update statements are using secondary index( `UPDATE target SET update_at=11111 WHERE ident in (‘aa’) ` ), and the deadlock might have been caused by conflicting lock attempts between different transactions.
sorry that the original log had lost after restart systemD. i solve the dead lock by just comment MSet() method when edge remote write (leave only heartbeat update the table), i hope offical team can find a more graceful solution when edge call API to update `target` table

**Comment by UlricQin** [comment]
升级到 7.3.4 新版本试试哈，如果尚未解决可以新提一个 issue，这个老 issue 先关闭了
