### ISSUE TITLE
日志级别设置为INFO时，在日志文件中会打印出 email sender 的用户名和密码等信息，涉及安全问题

### ISSUE THREAD

**Issue by swolfar** [ccfos/nightingale#1744]
**What would you like to be added**:
日志级别设置为INFO时，在日志文件中打印出 email sender 的用户名和密码等信息时，对密码进行脱敏处理
**Why is this needed**:
在审查日志的时候，会在日志文件中获取到邮箱的用户名，密码等信息，对邮箱的安全使用造成影响

**Comment by 710leo** [comment]
最新的代码，日志中不再打印密码了，发版之后，可以升级下
