### ISSUE TITLE
Even after the datasource is disabled, it can still be selected within the dashboard.

### ISSUE THREAD

**Issue by swolfar** [ccfos/nightingale#1745]
**What would you like to be added**:
在数据源被禁用后，仪表盘内不应该还有被禁用的数据源选项
**Why is this needed**:
保持数据的实时，准确

**Comment by masterjyq** [comment]
这个禁用是作用于告警规则的 all 数据源的, 数据源禁用后就不属于all 数据源了, 但是依然可以单独使用, 这个在某些场景还是挺有用的

**Comment by swolfar** [comment]
看禁用数据源是放到系统级配置的，若说要作用于告警，可以单独在告警那设置禁用数据源
