### ISSUE TITLE
Unable to create alert rule.

### ISSUE THREAD

**Issue by 1renwuruiming** [ccfos/nightingale#1746]
### Relevant server.conf | webapi.conf

```toml
Field 'extra_config' doesn't have a default value"
```

### Relevant logs

```text
Field 'extra_config' doesn't have a default value"
```

### System info

n9e 6.4.0

### Steps to reproduce

没有填写extra_config的位置

### Expected behavior

没有填写extra_config的位置

### Actual behavior

没有填写extra_config的位置

### Additional info

没有填写extra_config的位置

**Comment by 1renwuruiming** [comment]
![image](https://github.com/ccfos/nightingale/assets/36869664/68e8b251-cfeb-4b6d-b763-04cd0bd6de1f)
克隆内置的告警规则也同样提示一样的问题

**Comment by 1renwuruiming** [comment]
写错了，是6.3.4版本。我直接下载的最新版

**Comment by UlricQin** [comment]
我用docker-compose启动的最新版，测试没问题，你是用二进制部署的？用的什么版本数据库？

**Comment by 1renwuruiming** [comment]
我也是用docker-compose启动的，compose-file就是下载下来的
version: "3.7"

services:
  mysql:
    image: "mysql:8"
    container_name: mysql
    hostname: mysql
    restart: always
    environment:
      TZ: Asia/Shanghai
      MYSQL_ROOT_PASSWORD: QQMM987zxc
    volumes:
      - ./mysqldata:/var/lib/mysql/
      - ../initsql:/docker-entrypoint-initdb.d/
      - ./etc-mysql/my.cnf:/etc/my.cnf
    network_mode: host

  redis:
    image: "redis:6.2"
    container_name: redis
    hostname: redis
    restart: always
    environment:
      TZ: Asia/Shanghai
    network_mode: host

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    hostname: prometheus
    restart: always
    environment:
      TZ: Asia/Shanghai
    volumes:
      - ./etc-prometheus:/etc/prometheus
    network_mode: host
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
      - "--storage.tsdb.path=/prometheus"
      - "--web.console.libraries=/usr/share/prometheus/console_libraries"
      - "--web.console.templates=/usr/share/prometheus/consoles"
      - "--enable-feature=remote-write-receiver"
      - "--query.lookback-delta=2m"

  ibex:
    image: flashcatcloud/ibex:v0.5.0
    container_name: ibex
    hostname: ibex
    restart: always
    environment:
      GIN_MODE: release
      TZ: Asia/Shanghai
      WAIT_HOSTS: 127.0.0.1:3306
    volumes:
      - ./etc-ibex:/app/etc
    network_mode: host
    depends_on:
      - mysql
    command: >
      sh -c "/app/ibex server"

  n9e:
    image: flashcatcloud/nightingale:latest
    container_name: n9e
    hostname: n9e
    restart: always
    environment:
      GIN_MODE: release
      TZ: Asia/Shanghai
      WAIT_HOSTS: 127.0.0.1:3306, 127.0.0.1:6379
    volumes:
      - ./etc-nightingale:/app/etc
    network_mode: host
    depends_on:
      - mysql
      - redis
      - prometheus
    command: >
      sh -c "/app/n9e"

  categraf:
    image: "flashcatcloud/categraf:latest"
    container_name: "categraf"
    hostname: "categraf01"
    restart: always
    environment:
      TZ: Asia/Shanghai
      HOST_PROC: /hostfs/proc
      HOST_SYS: /hostfs/sys
      HOST_MOUNT_PREFIX: /hostfs
      WAIT_HOSTS: 127.0.0.1:17000, 127.0.0.1:20090
    volumes:
      - ./etc-categraf:/etc/categraf/conf
      - /:/hostfs
    network_mode: host
    depends_on:
      - n9e

**Comment by 1renwuruiming** [comment]
用的是compose-host-network目录下的composefile

**Comment by 1renwuruiming** [comment]
> ![image](https://user-images.githubusercontent.com/36869664/275718060-68e8b251-cfeb-4b6d-b763-04cd0bd6de1f.png) 克隆内置的告警规则也同样提示一样的问题

我想请问一下extra_config这个对应到页面上的哪个位置

**Comment by 1renwuruiming** [comment]
> > ![image](https://user-images.githubusercontent.com/36869664/275718060-68e8b251-cfeb-4b6d-b763-04cd0bd6de1f.png) 克隆内置的告警规则也同样提示一样的问题
> 
> 我想请问一下extra_config这个对应到页面上的哪个位置

@UlricQin

**Comment by 710leo** [comment]
可以执行 `docker pull mysql:8` 然后再试试

**Comment by 1renwuruiming** [comment]
好的，谢谢





  	
 武瑞铭 
弈人科技  
 电话：17521132084 
 ***@***.*** 
 地址：上海-天地科技广场 
	     
	   		 弈人科技  	 企业主页  		      
 信息安全声明：本邮件包含信息归发件人所在组织所有，发件人所在组织对该邮件拥有所有权利。
请接收者注意保密，未经发件人书面许可，不得向任何第三方组织和个人透露本邮件所含信息的全部或部分。以上声明仅适用于工作邮件。
Information Security Notice: The information contained in this mail is solely property of the sender's organization. 
 This mail communication is confidential. Recipients named above are obligated to maintain secrecy and are not permitted to disclose the contents of this communication to others.  ------------------------------------------------------------------
发件人：Yening ***@***.***>
日　期：2023年10月20日 11:35:20
***@***.***>
***@***.***>; ***@***.***>
主　题：Re: [ccfos/nightingale] 无法创建告警规则 (Issue #1746)

可以执行 docker pull mysql:8 然后再试试

**Comment by 1renwuruiming** [comment]
> 可以执行 `docker pull mysql:8` 然后再试试

![image](https://github.com/ccfos/nightingale/assets/36869664/499b1da1-36e3-495a-a5d5-cc35f22e3687)
当前使用的就是mysql8

**Comment by 710leo** [comment]
升级到最新版本再看看吧

**Comment by 1renwuruiming** [comment]
好的
 武瑞铭 
弈人科技 
 电话：17521132084 
 ***@***.*** 
 地址：上海-天地科技广场 
 <https://mail.aliyun.com/mail-pages/dingmail-signature/index.html?token=FB7AC33A2176ACBD876FA64033712EF949D0ACB4461B8FB9D8C7F0B0413E8BE11164813B38998FCAA9D8F5D22965CCC9 > 
 <https://h5.dingtalk.com/home/index.html?corpId=ding1b71bef9e2248b5735c2f4657eb6378f&token=9fa6e5da557acd258c1cca5e504c3d7c&from=emailSign >  弈人科技  企业主页  <https://h5.dingtalk.com/home/index.html?corpId=ding1b71bef9e2248b5735c2f4657eb6378f&token=9fa6e5da557acd258c1cca5e504c3d7c&from=emailSign >  <https://h5.dingtalk.com/home/index.html?corpId=ding1b71bef9e2248b5735c2f4657eb6378f&token=9fa6e5da557acd258c1cca5e504c3d7c&from=emailSign > 
信息安全声明：本邮件包含信息归发件人所在组织所有，发件人所在组织对该邮件拥有所有权利。
请接收者注意保密，未经发件人书面许可，不得向任何第三方组织和个人透露本邮件所含信息的全部或部分。以上声明仅适用于工作邮件。
Information Security Notice: The information contained in this mail is solely property of the sender's organization. 
This mail communication is confidential. Recipients named above are obligated to maintain secrecy and are not permitted to disclose the contents of this communication to others.
------------------------------------------------------------------
发件人：Yening Qin ***@***.***>
发送时间：2024年1月28日(星期日) 22:19
***@***.***>
***@***.***>; ***@***.***>
主　题：Re: [ccfos/nightingale] Unable to create alert rule. (Issue #1746)
升级到最新版本再看看吧
