### ISSUE TITLE
请问V6.3.4 活跃告警显示的是最近多长时间的

### ISSUE THREAD

**Issue by lyitt1987** [ccfos/nightingale#1749]
![image](https://github.com/ccfos/nightingale/assets/35764082/2a59048e-ff2a-4c38-870a-4097bf19ebc2)

因为现在没有时间范围可选，请告知，谢谢！

**Comment by 710leo** [comment]
展示的是所有的未恢复告警，没时间筛选了

**Comment by lyitt1987** [comment]
> 展示的是所有的未恢复告警，没时间筛选了

了解了，谢谢大佬解答
