### ISSUE TITLE
关于告警生效时间的配置

### ISSUE THREAD

**Issue by kiic-leung** [ccfos/nightingale#1750]
**What would you like to be added**:
请问告警生效时间能否支持多区间段配置，或者根据脚本运行的返回值来判断是否要告警？

**Why is this needed**:
我们的服务并非一直处于运行状态，比如非交易日、非交易时段这些进程会停掉； 因此需要支持一个自定义脚本去配置交易日判断、以及分别对应日盘夜盘的多时间区间段的配置

**Comment by UlricQin** [comment]
告警生效时间是可以支持多个区间的。但是开源版本确实很难自动化的适配交易日这个场景。可以考虑自定义通知脚本来做一些逻辑，SRETalk视频号有关于自定义脚本的使用介绍。或者采购商业版，商业版支持自定义交易日历，会比较方便

**Comment by lyitt1987** [comment]
> 告警生效时间是可以支持多个区间的。但是开源版本确实很难自动化的适配交易日这个场景。可以考虑自定义通知脚本来做一些逻辑，SRETalk视频号有关于自定义脚本的使用介绍。或者采购商业版，商业版支持自定义交易日历，会比较方便

好的，谢谢大佬解答！

**Comment by kiic-leung** [comment]
> 告警生效时间是可以支持多个区间的。但是开源版本确实很难自动化的适配交易日这个场景。可以考虑自定义通知脚本来做一些逻辑，SRETalk视频号有关于自定义脚本的使用介绍。或者采购商业版，商业版支持自定义交易日历，会比较方便

好的，谢谢
