### ISSUE TITLE
内置仪表盘【机器台账表格视图】详情跳转错误

### ISSUE THREAD

**Issue by samgang** [ccfos/nightingale#1752]
### Relevant server.conf | webapi.conf

```toml
no
```

### Relevant logs

```text
大盘不存在
```

### System info

v6.3.4-0b23ddffb2e7b8a5d68815da4f4d57bfc1662e67

### Steps to reproduce

1. 导入内置仪表盘【机器台账表格视图】
2. 查看监控仪表盘里的【机器台账表格视图】
3. 在机器列表中打开某一台机器的链接详情，出现大盘不存在

因为详情里写的是 http://localhost:17000/dashboards/linux-host-by-categraf?ident=localhost

导入 linux-host-by-categraf 的仪表盘后，打开的链接是 http://localhost:17000/dashboards/2

两个链接不一样且无法关联

### Expected behavior

可以正常打开

### Actual behavior

错误：大盘不存在

**Comment by 710leo** [comment]
感谢反馈，最新代码已修复哈，可以等待下次发版

**Comment by samgang** [comment]
> 感谢反馈，最新代码已修复哈，可以等待下次发版
在最新版本 v6.4.0 里发现已经可以正常跳转，但是跳转后的大盘确实不对的，始终 `ident=all`，另外 v6.3.1 升级至 v6.4.0 是否有额外操作的步骤，因为升级 后[机器台账表格视图]() 无法打开

**Comment by samgang** [comment]
> 感谢反馈，最新代码已修复哈，可以等待下次发版
在最新版本 v6.4.0 里发现已经可以正常跳转，但是跳转后的大盘确实不对的，始终 `ident=all`，另外 v6.3.1 升级至 v6.4.0 是否有额外操作的步骤，因为升级 后[机器台账表格视图]() 无法打开
