### ISSUE TITLE
Nightingale/v1/n9e called by a third-party system.

### ISSUE THREAD

**Issue by NEW7BEE** [ccfos/nightingale#1763]
使用webapi.conf中配置的BasicAuth，get请求没有问题，post、del会报错
![image](https://github.com/ccfos/nightingale/assets/30228162/b6d1ec34-420d-4fff-93b7-dc02aee18286)
看代码是验证权限了
![image](https://github.com/ccfos/nightingale/assets/30228162/c896defb-215f-464d-be47-66c7f8fa74a4)
换成 admin 的账号报 401

**Comment by 710leo** [comment]
v5 已经不维护了，升级到 v6 版本吧
