### ISSUE TITLE
Customize home page

### ISSUE THREAD

**Issue by myselfghost** [ccfos/nightingale#1766]
**What would you like to be added**:
允许自定义首页，最好是允许每个用户自定义自己的首页。
比如设置‘活跃告警’为首页，或者设置‘/dashboards’ 为首页。甚至允许用户设置任意具体的仪表盘为首页‘/dashboards/3’

**Why is this needed**:

对使用用户更优好。

**Comment by 710leo** [comment]
最新版本已支持
