### ISSUE TITLE
When data cannot be obtained, there is no alarm raised, which does not align with the concept of monitoring

### ISSUE THREAD

**Issue by jiangsheng6** [ccfos/nightingale#1770]
当采集器没有获取到数据的时候，如何设置报警，有老师帮解答一下吗
因为如果数据不存在或者没获取到的时候不报警的话，无法识别监控对象是否健康

**Comment by tanxiao1990** [comment]
https://flashcat.cloud/docs/content/flashcat-monitor/nightingale-v6/faq/target_up/

**Comment by tanxiao1990** [comment]
建议先通读官方文档

**Comment by jiangsheng6** [comment]
categraf并没有失联，而是由于某些原因采集不到监控目标的数据了，这种情况如何设置报警，能否通过promql表达式处理采集不到数据的情况

**Comment by kongfei605** [comment]
用absent 系列函数，比如  absent_over_time

**Comment by jiangsheng6** [comment]
fine
