### ISSUE TITLE
query data request timeout

### ISSUE THREAD

**Issue by blade83lee** [ccfos/nightingale#1771]
中心节点访问边缘节点数据源列表图标请求超时 （数据小于10 正常，大于50返回超时
**What would you like to be added**:
![5a79cd19dcdd3bf4b262abbba253426](https://github.com/ccfos/nightingale/assets/88416508/67c458bc-9d0d-4fde-a3ee-0c8b07bfc4ad)
![395da27f4f1c1e6ebdf983ef4762347](https://github.com/ccfos/nightingale/assets/88416508/aa5188ef-683a-40c1-b1dc-19edd44c63a6)

**Why is this needed**:

**Comment by blade83lee** [comment]
![1699350717362](https://github.com/ccfos/nightingale/assets/88416508/a7eb9a8a-fc84-430e-98f9-809db6de204d)
但是即时查询页面又只要 54ms，但是面板显示则超时

**Comment by blade83lee** [comment]
![企业微信截图_16993510011818](https://github.com/ccfos/nightingale/assets/88416508/d61ac301-212b-423b-ba8f-abfc3067d534)
加上[1m] 则超时

**Comment by tanxiao1990** [comment]
可以先查看一下8428  victoria-metrics的 日志，应该会有收获

**Comment by blade83lee** [comment]
关键是8428日志没有体现， n9e的日志也没有找到相关的错误提示

**Comment by UlricQin** [comment]
夜莺里有个数据源配置，你的的这个数据源配置详情页面截个图
