### ISSUE TITLE
Center 警告

### ISSUE THREAD

**Issue by lyitt1987** [ccfos/nightingale#1785]
警告信息如图
![image](https://github.com/ccfos/nightingale/assets/35764082/5d104e34-87c2-4f5b-9ec6-eac79aa02d8b)

请大佬解答，谢谢！

**Comment by 710leo** [comment]
可以看下这个 https://github.com/ccfos/nightingale/discussions/1162

**Comment by lyitt1987** [comment]
> 可以看下这个 #1162

你好，按照你给的这个连接配置后警告依旧存在
![image](https://github.com/ccfos/nightingale/assets/35764082/e8eb19a1-e5a5-4772-a88c-c53d311541f8)

![image](https://github.com/ccfos/nightingale/assets/35764082/a0d48da8-bf0a-48a0-935b-5e3be969b2b8)
