### ISSUE TITLE
The k8s scheduler is monitored through Prometheus agrnt, and after authentication, it requests the /metrics interface to return many metrics. However, in the n9e "real-time query," it was found that some metrics were not reported.

### ISSUE THREAD

**Issue by Turi-fly** [ccfos/nightingale#1787]
### Relevant server.conf | webapi.conf

```toml
监控k8s scheduler通过Prometheus agrnt采集，认证后请求/metrics接口返回很多指标，但在n9e“即时查询”中发现部分指标并没有上报
```

### Relevant logs

```text
监控k8s scheduler通过Prometheus agrnt采集，认证后请求/metrics接口返回很多指标，但在n9e“即时查询”中发现部分指标并没有上报
```

### System info

centos7.6

### Steps to reproduce

监控k8s scheduler通过Prometheus agrnt采集，认证后请求/metrics接口返回很多指标，但在n9e“即时查询”中发现部分指标并没有上报

### Expected behavior

![n9e1 pic](https://github.com/ccfos/nightingale/assets/29781274/b3070c4f-0562-4e61-a79d-8ace3cf1f005)
![n9e2 pic](https://github.com/ccfos/nightingale/assets/29781274/587db899-e3d2-484f-ad76-68a2c730ff99)
![n9e3 pic](https://github.com/ccfos/nightingale/assets/29781274/30ea75d5-44f3-4d0e-9457-d4fe3d08a31d)
![n9e4 pic](https://github.com/ccfos/nightingale/assets/29781274/c6b0ba25-4bee-4028-a416-42fc5abec5b4)
![n9e5 pic](https://github.com/ccfos/nightingale/assets/29781274/9600d4e8-fec1-4d2f-ae44-c8eca178eeba)

### Actual behavior

监控k8s scheduler通过Prometheus agrnt采集，认证后请求/metrics接口返回很多指标，但在n9e“即时查询”中发现部分指标并没有上报

**Comment by kongfei605** [comment]
source_labels 最后一项 用的是endpoint的port name？ 那应该采集不到才对
