### ISSUE TITLE
Does Nightingale Monitoring have the function of creating daily reports?夜莺监控有制作每日报表功能吗？

### ISSUE THREAD

**Issue by Badboyswxl** [ccfos/nightingale#1792]
I would like to know if Nightingale has the ability to automatically generate HTML for daily load, operation status, charts, data, and other information, and then send it to a designated email?

**Comment by Badboyswxl** [comment]
我想知道夜莺有将每日的负载、运行情况、图表、数据等信息自动制作成html然后发送到指定的邮箱功能吗？

**Comment by UlricQin** [comment]
没有哈
