### ISSUE TITLE
The data source is es, and when adding variables to the dashboard, it automatically adds .keyword, which makes it impossible to query the aggregated value.

### ISSUE THREAD

**Issue by zaipingy** [ccfos/nightingale#1795]
<img width="590" alt="image" src="https://github.com/ccfos/nightingale/assets/30775871/4963861a-1f71-48df-b17f-3be65197c08b">
<img width="498" alt="image" src="https://github.com/ccfos/nightingale/assets/30775871/61dc2fb5-1713-43c3-916f-626334a47e1a">

**Comment by jsers** [comment]
确实，下个版本查询条件里会去掉 .keyword

**Comment by UlricQin** [comment]
@jsers 改完了么？改完了 close  issue 哈

**Comment by jsers** [comment]
新版本已解决
