### ISSUE TITLE
About using zoom to select time in the dashboard

### ISSUE THREAD

**Issue by xiaqi1210** [ccfos/nightingale#1797]
### Relevant server.conf | webapi.conf

```toml
-
```

### Relevant logs

```text
-
```

### System info

n9e 6.6.2, n9e-fe 6.6.1

### Steps to reproduce

1. 仪表盘缩放行为改成"更新时间范围"
![image](https://github.com/ccfos/nightingale/assets/5163551/35dcbb44-e362-4d3c-aacb-e461f9af13f3)

2. 随便选择一个有数据的时间段(这里选择的是最近24小时)
![image](https://github.com/ccfos/nightingale/assets/5163551/01505521-ef4e-4ffc-a7f8-a8ef9fae634d)

3. 在某一个图表中通过缩放选择一个小的时间段
![image](https://github.com/ccfos/nightingale/assets/5163551/ee3f63ed-140d-44ce-8554-c9bcbb01a6e0)

4. 这个时候会发现右上角的全局时间也相应的修改了
![image](https://github.com/ccfos/nightingale/assets/5163551/402424b6-fcd4-4ef8-a13c-338ae8290875)

5. 刷新当前页面
6. 发现右上角的全局时间又回去了(变成最近24小时)
![image](https://github.com/ccfos/nightingale/assets/5163551/1ad46f52-89c7-44a4-8f39-1afb22c7da1b)

### Expected behavior

期望图表中缩放之后的时间范围选择在页面刷新后可以一直保持(实际场景上图表里有一些链接, 如果不能保持这个时间, 那么链过去的新页面也会出现时间范围还是之前范围的问题)

### Actual behavior

图表中缩放之后的时间范围在页面刷新后又回到之前的时间选择范围了

**Comment by xiaqi1210** [comment]
@710leo 大佬, 麻烦看一下我的问题

**Comment by 710leo** [comment]
最新版本已修复此问题
