### ISSUE TITLE
docker-compose installation mode keeps redirecting

### ISSUE THREAD

**Issue by wxxiong6** [ccfos/nightingale#1799]
http://localhost:17000/login?redirect=/login?redirect=/login?redirect=/login?redirect=/login?redirect=/login?redirect=/login?redirect=/login?redirect=/login?redirect=/login?redirect=/login?redirect=/login?redirect=/login?redirect=/login?redirect=/login?redirect=/login?redirect=/login?redirect=/login?redirect=/login?redirect=/login?redirect=/login?redirect=/login?redirect=/login?redirect=/login?redirect=/login?redirect=/login?redirect=/login?redirect=/login?redirect=/login?redirect=/login?redirect=/login?redirect=/login?redirect=/login?redirect=/login?redirect=/login?redirect=/login?redirect=/login?redirect=/login?redirect=/login?redirect=/login?redirect=/login?redirect=/login?redirect=/login?redirect=/login?redirect=/login?redirect=/login?redirect=/login?redirect=/login?redirect=/login?redirect=/login?redirect=/login?redirect=/login?redirect=/login?redirect=/login?redirect=/login?redirect=/login?redirect=/login?redirect=/login?redirect=/login?redirect=/login?redirect=/login?redirect=/login?redirect=/login?redirect=/login?redirect=/login?redirect=/login?redirect=/login?redirect=/login?redirect=/login?

**Comment by 710leo** [comment]
可以提供下相关的日志，我这里没复现

**Comment by evenhh** [comment]
I had the same problem on my mac with Arm chip
