### ISSUE TITLE
Redefined alert channel in subscription rules, custom alert channels cannot be used.

### ISSUE THREAD

**Issue by ljw0831** [ccfos/nightingale#1800]
### Relevant server.conf | webapi.conf

```toml
..
```

### Relevant logs

```text
..
```

### System info

前端版本：v6.6.2 后端版本：v6.6.1,数据库mysql 5.7

### Steps to reproduce

1.告警规则中不定义告警通道,或者选择自定义通道(不选择告警接受组)
2.在订阅规则中选则重新定义告警媒介,选择自定义的告警通道,或者沿用告警规则中的自定义通道
3.告警出发时,无法正常通过自定通道接收消息

### Expected behavior

订阅告警中使用自定义通道应都应该可以正常使用

### Actual behavior

订阅告警中只可以使用原来的通道, 自定义通道无法使用

### Additional info

![image](https://github.com/ccfos/nightingale/assets/27805615/b590c494-9ee5-4524-81c0-3d833acab0de)
在订阅告警中选择了自定义的通道
![image](https://github.com/ccfos/nightingale/assets/27805615/b91fb7bf-cafe-473d-91dc-9660addd3301)

在后台日志会报没有自定义通道的发送

**Comment by 710leo** [comment]
自定义通道，需要通过使用通知脚本自己来对接

**Comment by waney316** [comment]
> ### Relevant server.conf | webapi.conf
> ```toml
> ..
> ```
> 
> ### Relevant logs
> ```
> ..
> ```
> 
> ### System info
> 前端版本：v6.6.2 后端版本：v6.6.1,数据库mysql 5.7
> 
> ### Steps to reproduce
> 1.告警规则中不定义告警通道,或者选择自定义通道(不选择告警接受组) 2.在订阅规则中选则重新定义告警媒介,选择自定义的告警通道,或者沿用告警规则中的自定义通道 3.告警出发时,无法正常通过自定通道接收消息
> 
> ### Expected behavior
> 订阅告警中使用自定义通道应都应该可以正常使用
> 
> ### Actual behavior
> 订阅告警中只可以使用原来的通道, 自定义通道无法使用
> 
> ### Additional info
> ![image](https://private-user-images.githubusercontent.com/27805615/291536532-b590c494-9ee5-4524-81c0-3d833acab0de.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDM4MzgxNjUsIm5iZiI6MTcwMzgzNzg2NSwicGF0aCI6Ii8yNzgwNTYxNS8yOTE1MzY1MzItYjU5MGM0OTQtOWVlNS00NTI0LTgxYzAtM2Q4MzNhY2FiMGRlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyMzEyMjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjI5VDA4MTc0NVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTI5ODZlMjhkY2ZiNmRhMGQyY2MyYzdhNzVhMzhmNmExZjMxYmMxMThmNjg5YjMyMmZmNmQyMzRhODAzOGZiMGYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.PO-MtDwL8ZybccZeP0vwXutLebUAHTiD4MpyBAk9n5E) 在订阅告警中选择了自定义的通道 ![image](https://private-user-images.githubusercontent.com/27805615/291537785-b91fb7bf-cafe-473d-91dc-9660addd3301.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDM4MzgxNjUsIm5iZiI6MTcwMzgzNzg2NSwicGF0aCI6Ii8yNzgwNTYxNS8yOTE1Mzc3ODUtYjkxZmI3YmYtY2FmZS00NzNkLTkxZGMtOTY2MGFkZGQzMzAxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyMzEyMjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjI5VDA4MTc0NVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWFkZDk1NzFkMjEyMzZlODhiODYxODgwOWUwOWY2NjIzYjdhYTUxM2FkYjMwZTllYTNjZWEyM2MzMzE2MzFjMzMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.VyWGUi8Bk0jEzSqP1dTAtCbn1o7AVYdaMXNIHWJxn1M)
> 
> 在后台日志会报没有自定义通道的发送
遇到了同样的问题，设置了全局的webhook ，phone，在订阅规则里重新定义告警渠道，但是无法发出
