### ISSUE TITLE
db Migrate

### ISSUE THREAD

**Issue by halalala222** [ccfos/nightingale#1803]
`dts := []interface{}{&RecordingRule{}, &AlertRule{}, &AlertSubscribe{}, &AlertMute{},
		&TaskRecord{}, &ChartShare{}, &Target{}, &Configs{}, &Datasource{}, &NotifyTpl{}}`
doesn't match models in /models ()

1. using MigrateTables() in package migrate,some tale missing some fields like id or update_at
2. missing some table like notify_tpl ,user_group_menber eq

install release nightingale，we can find some sql in script sql in /docker/initsql there are the full table

**Comment by 710leo** [comment]
Some SQL is here: https://github.com/ccfos/nightingale/blob/main/docker/initsql/migrate.sql
Some tables don't need the "update_at" field, like user_group_member.
