### ISSUE TITLE
Why does local deployment still need to access github?

### ISSUE THREAD

**Issue by Liuweb** [ccfos/nightingale#1805]
I deployed in my local VM and got below ERROR, Why need to access GitHub to check the latest version?

2023-12-22 15:33:11.682653 ERROR version/version.go:40 get github version fail: Get "https://api.github.com/repos/ccfos/nightingale/releases/latest": dial tcp 20.27.177.116:443: i/o timeout

**What would you like to be added**:

**Why is this needed**:

**Comment by 710leo** [comment]
To alert users of a new release, a notification will appear here if the version is lower than the new.
<img width="318" alt="image" src="https://github.com/ccfos/nightingale/assets/2169271/dbe7a527-8fe9-4f40-81b9-855ec588e5dd">

**Comment by Liuweb** [comment]
I think you'd better set a switch that can be turned off.
