### ISSUE TITLE
Can we add machine management inside the infrastructure?

### ISSUE THREAD

**Issue by opcache** [ccfos/nightingale#1807]
基础设施里面可以增加机器管理吗？
建议增加机器管理，可以批量更新categraf端或ibex端，以及可以批量执行bash脚本
这样灵活性大大增加，否则机器多还要搞个其他工具批量执行脚本来更新agent端

**Comment by 710leo** [comment]
专业版的机器管理已支持批量升级 agent，有兴趣可以了解下 https://flashcat.cloud/product/flashcat-pro/
