### ISSUE TITLE
Can log analysis be performed using only Elasticsearch and Loki data sources?

### ISSUE THREAD

**Issue by opcache** [ccfos/nightingale#1809]
日志分析只能Elasticsearch和Loki数据源吗？
categraf采集做数据源是否可以？
categraf不是可以 All-in-One 的开源的 telemetry 数据采集器 吗？
怎么配置使用的？？有最佳实践文档吗？建议补充一下

**Comment by UlricQin** [comment]
categraf 的角色仅仅是采集器，不负责数据存储，无法作为数据源
