### ISSUE TITLE
The lines of the timing diagram cannot be displayed

### ISSUE THREAD

**Issue by huhaiand** [ccfos/nightingale#1826]
**What would you like to be added**:
如图所示，选择图表样式为时序图时只会显示最近的2个点，不会显示近期时间段内连续数据的线条。
**Why is this needed**:
![image](https://github.com/ccfos/nightingale/assets/156059126/a23d777e-8402-445f-88b0-10e8076d58cf)

**Comment by UlricQin** [comment]
issue timeout..
