### ISSUE TITLE
es 查询 选择索引 跟默认索引下 可选字段不一致

### ISSUE THREAD

**Issue by blackher** [ccfos/nightingale#1829]
![WechatIMG760](https://github.com/ccfos/nightingale/assets/12698390/7747aa77-b20e-4f0d-b59f-724b942b1e56)

![WechatIMG759](https://github.com/ccfos/nightingale/assets/12698390/be999949-31e8-40ac-8d26-1e4dcc517efa)

**Comment by 710leo** [comment]
fix at https://github.com/ccfos/nightingale/releases/tag/v6.7.3
