### ISSUE TITLE
A newbie here, how do I monitor a Huawei S5720 switch that has SNMP V2 enabled?

### ISSUE THREAD

**Issue by fljcn** [ccfos/nightingale#1832]
需要监控一台华为S5720交换机，已经开启snmp V2，通过snmpwalk也能查询到相关信息，不知在服务端categraf/conf/input.snmp/下，复制一份snmp.toml 改为snmp_5720.toml进行修改配置，还是到categraf/conf/input.switch_legacy/下，复制一份switch_legacy.tol改为switch_legacy_s5720进修配置，迷茫？？？
修改后，在前台还需要进行哪些配置？
有使用zabbix多年经验。

**Comment by 710leo** [comment]
https://flashcat.cloud/docs/content/flashcat-monitor/categraf/plugin/snmp/ 可以看下这个文档
