### ISSUE TITLE
ADD MYSQL TYPE OF  DATASOURCE 

### ISSUE THREAD

**Issue by superman-killig** [ccfos/nightingale#1841]
**What would you like to be added**:
MYSQL TYPE OF  DATASOURCE 
**Why is this needed**:
分析统计类型数据需求，主要是统计时间戳的对齐；如果能增加rules通知更好了

**Comment by UlricQin** [comment]
对 MySQL 的数据做告警规则管理，可以尝试 https://flashcat.cloud/product/flashduty/ 。夜莺开源版本暂无计划支持 MySQL Datasource

**Comment by yanming-zhang** [comment]
> 对 MySQL 的数据做告警规则管理，可以尝试 https://flashcat.cloud/product/flashduty/ 。夜莺开源版本暂无计划支持 MySQL Datasource

我在Flashduty中，怎么没有找到关于MySQL数据源的支持

**Comment by UlricQin** [comment]
<img width="1511" alt="image" src="https://github.com/user-attachments/assets/e50f39b9-78ae-4e88-b8ac-faa65712e7ec">
在监控管理里，先部署 monitedge 模块，然后添加数据源，然后配置告警规则即可
