### ISSUE TITLE
Time offset alarm parameter acquisition

### ISSUE THREAD

**Issue by liuxin638507** [ccfos/nightingale#1843]
每台上面再配置ntp的offset有点麻烦，请问时间偏移告警参数怎么获取，想通过这个偏差值大小进行告警条件配置处理，
![image](https://github.com/ccfos/nightingale/assets/32058132/4cabc739-eb75-4b3b-b7cd-19a5bb65e76a)

**Comment by 710leo** [comment]
时间偏移是 n9e 部署机器的时间和categraf部署机器的时间差值，告警规则配置可以看下这个文档的 host告警部分 https://flashcat.cloud/docs/content/flashcat-monitor/nightingale-v6/usage/alert/alert-rule/

**Comment by liuxin638507** [comment]
> 时间偏移是 n9e 部署机器的时间和categraf部署机器的时间差值，告警规则配置可以看下这个文档的 host告警部分 https://flashcat.cloud/docs/content/flashcat-monitor/nightingale-v6/usage/alert/alert-rule/

这个时间偏移的表达式怎么写？
