### ISSUE TITLE
The message field content will not automatically wrap.

### ISSUE THREAD

**Issue by simple11618** [ccfos/nightingale#1846]
<img width="810" alt="3349AF27-72D1-4967-9E87-851F8A9C984C" src="https://github.com/ccfos/nightingale/assets/47932617/6105c73b-6838-478b-b749-bc0dfafdf971">

日志分析-即时查询时，message字段内容不会自动换行，出现比较长的信息只能通过拉去滚动条，拉到后面又看不到前面，希望能加个换行功能，像ELK那样展示 会更方便

**Comment by simple11618** [comment]
![image](https://github.com/ccfos/nightingale/assets/47932617/bff6d5f3-9bc2-4f8b-9f85-55a7a298a772) 
![image](https://github.com/ccfos/nightingale/assets/47932617/15d8d511-a756-4236-8b59-d3de1ededf86)

升级到最新6.73版本，存在以下几个问题：
1、仅选择字段 message，右边message中字段 内容过长还是有滚动条
2、message中字段 内容展开 有时显示内容带滚动条，有时刷新 字段中内容为空

**Comment by jsers** [comment]
1. 现在的设计不会换行，后面会考虑添加一个新的展示模式，该模式下会自动换行
2. 不换行的前提下自然会出现滚动条，至于你说的内容为空上面例子和截图不能帮助我排查问题，请先检测该条日志是否确实 message 内容是空的
