### ISSUE TITLE
The number of processes and threads is inconsistent with what top shows.

### ISSUE THREAD

**Issue by molixiaoge** [ccfos/nightingale#1847]
1.开启processes_total 和 processes_total_threads 监控。然后查看机器top task进程数，和top -H线程数发现和实际显示的不一样。

![图片](https://github.com/ccfos/nightingale/assets/1323533/9295325f-253d-4812-b8dd-8ba14244c570)

top显示
![图片](https://github.com/ccfos/nightingale/assets/1323533/51b31ef6-06cf-4fdc-8382-cbacfc398abc)

**Comment by UlricQin** [comment]
issue 提错了地方，Nightingale 不做采集，你应该去 Categraf 或者 telegraf 或者 node-exporter 的 repo 提

**Comment by molixiaoge** [comment]
好的
