### ISSUE TITLE
Hello, I'm currently in the process of making a selection and I wanted to inquire about any upcoming plans to launch  tracing.

### ISSUE THREAD

**Issue by Changego** [ccfos/nightingale#1849]
**What would you like to be added**:
你们好，正在做选型，想请问下近期有计划上线链路追踪的功能吗？
**Why is this needed**:

**Comment by 710leo** [comment]
目前专业版里是有链路追踪的，可以了解下 https://flashcat.cloud/product/flashcat-pro/，开源版的排期还没确定
