### ISSUE TITLE
触发报警时，发送钉钉消息被艾特的人其实收不到提醒

### ISSUE THREAD

**Issue by zhaoshiyou** [ccfos/nightingale#1851]
### Relevant server.conf | webapi.conf

```toml
1
```

### Relevant logs

```text
1
```

### System info

v6.3.4

### Steps to reproduce

1.
2.
3.
...

### Expected behavior

我的系统版本是v6.3.4
触发报警时，发送钉钉消息被艾特的人其实没收到提醒。
1.确认过人员组织->用户管理的人员号码和钉钉群里面的人手机号码是一样
2.收到的钉钉报警消息里面被艾特的人能显示出来，但确实收不到提醒。
我猜可能是发送消息的时候是直接拼成起来 @张三 ，应该是把被艾特的人手机号码当作参数之一调用钉钉接口
![1706261546378](https://github.com/ccfos/nightingale/assets/39617281/b7f27b0d-ec37-4a31-9fed-18462d49fcc4)
![1706261643517](https://github.com/ccfos/nightingale/assets/39617281/94f38a0c-6d02-46d5-b6b6-7c6d443d661b)

### Actual behavior

1

### Additional info

1

**Comment by UlricQin** [comment]
既作为参数传了也作为内容拼了（如下图），之前是可以的，默认钉钉改逻辑了

<img width="455" alt="image" src="https://github.com/ccfos/nightingale/assets/2769466/c6f0f8f5-dff3-4dc4-ae73-82ddb23b74db">

**Comment by idcdog** [comment]
今天也发现类似问题了,感觉是钉钉告警推动收费后, 这一块的逻辑修改了,期待夜莺做一下更新适配
