### ISSUE TITLE
根据业务组，告警通知到关联的用户组问题

### ISSUE THREAD

**Issue by szy345** [ccfos/nightingale#1853]
### Your config.toml

```toml
无
```

### Relevant logs

```text
无
```

### System info

n9e : 6.1.0 

### Steps to reproduce

无

### Expected behavior

夜莺版本6.1.0

业务组对应告警组，告警组关联多个告警接受人。
比如飞书的群ID（webhookID），是配置在告警接受人里的，而不是配置在告警组里。当1个告警组里关联的人有多个不同的webhookID时候，本应推送到该告警组的消息，却推送到了多个告警组。

比如：
busi-A --> user-group-A --> user-A & user-B
busi-B --> user-group-B --> user-B

在飞书的群 user-group-A ，webhookID，配置在 user-A上，
在飞书的群 user-group-B ，webhookID，配置在 user-B上，
当busi-A，busi-B 使用同一个k8s（datasource相同），告警规则不同，就是业务组不同，
此时，busi-A 的告警会 同时发送到 user-group-A 和 user-group-B。

这个有办法解吗

### Actual behavior

无

### Additional info

<img width="485" alt="image" src="https://github.com/ccfos/nightingale/assets/14071421/1e147b1d-df11-46ce-9bac-0fffedf2b72a">

**Comment by 710leo** [comment]
针对你的情况，可以创建两个虚拟用户 virtual-A 和 virtual-B
virtual-A 关联user-group-A群里的token，加到 user-group-A 团队
virtual-B 关联user-group-B群里的token，加到 user-group-B 团队
就可以解决你的问题了

**Comment by szy345** [comment]
跟我现在的想法是一样了 。
