### ISSUE TITLE
n9e docs errors

### ISSUE THREAD

**Issue by shenhua19891109** [ccfos/nightingale#1854]
1、https://flashcat.cloud/docs/content/flashcat-monitor/nightingale-v6/usage/dashboard/dashboard/
![ec24690b1ff610d3508066952102f69a](https://github.com/ccfos/nightingale/assets/14866179/3b8d4069-2e17-4b8f-bfd6-0aca77d57f53)

2、https://flashcat.cloud/docs/content/flashcat-monitor/nightingale-v6/usage/alert/alert-rule/
![image](https://github.com/ccfos/nightingale/assets/14866179/bff16ec9-72f0-4ff4-846a-8eb32cd5fa0f)

**Comment by 710leo** [comment]
感谢反馈，已修正
