### ISSUE TITLE
业务组请求数量能否增加翻页或者调大上限

### ISSUE THREAD

**Issue by idcdog** [ccfos/nightingale#1864]
版本: v6.7.3

问题: 业务组页面加载的时候默认请求限制为200条，当业务组数量超过200个后， 带来两个问题
1. 类似于大盘查看、业务组管理等凡是涉及到业务组的页面， 都看不到200条之后的业务组数据，除非使用搜索功能
2. 当收到告警后， 在告警详情页面，点击"业务组"跳转时，会提示 
![image](https://github.com/ccfos/nightingale/assets/18034474/430baf39-e491-4511-93b3-cef005309426)

建议：
对于业务组增加翻页功能，但考虑到其他页面比如大盘查看， 告警规则处理等， 这个貌似比较复杂
或者
调大业务组默认请求上限，比如调整到1000之类的

**Comment by 710leo** [comment]
感谢反馈，我们优化下

**Comment by jsers** [comment]
v7 版本起该问题以及解决
