### ISSUE TITLE
屏蔽规则是否可以不填写标签

### ISSUE THREAD

**Issue by foreverrice** [ccfos/nightingale#1870]
![image](https://github.com/ccfos/nightingale/assets/33533816/31d689b3-e9b3-4f5a-ae5d-8c25194613d2)
有需求正巧只想根据业务组去屏蔽规则，但至少填写一个标签就很不方便
![image](https://github.com/ccfos/nightingale/assets/33533816/c81f18e7-3c40-4eeb-8412-2679979f684d)

**Comment by 710leo** [comment]
你不想填标签的话，想使用什么条件来过滤告警事件呢

**Comment by foreverrice** [comment]
> 你不想填标签的话，想使用什么条件来过滤告警事件呢

上面有业务组可以过滤对于业务来说已经够了

**Comment by UlricQin** [comment]
快要发布 v7 beta2 了，届时应该会做到不需要配置标签

**Comment by UlricQin** [comment]
可以试试 v7 beta2.0.1 标签不是必填了
