### ISSUE TITLE
希望告警自愈执行结果发送到告警通知。

### ISSUE THREAD

**Issue by feko2018** [ccfos/nightingale#1871]
希望可配置，告警自愈，在触发后，将脚本执行的最后结果发送到告警通知。

**Comment by UlricQin** [comment]
产品层面没有计划做这个。你可以考虑在脚本内部实现，把脚本内关键逻辑的输出发出来，脚本里能拿到接收人、通知媒介，所以理论上脚本自身可以干。

脚本如果一开始就挂了，没法执行后续逻辑，脚本里后面的发送逻辑确实就没法搞了。不过这种情况应该是对脚本充分测试，而不是在脚本出错的时候作为告警发出来。

本质上，这个需求不合理的点是：把业务逻辑和平台自身健康状态的信息混杂在一起了，极端情况下，10000个研发人员都在使用夜莺，都收到了某个告警，但是脚本调用的结果也发给这10000个人，他们就会很困惑，而脚本本身是否成功，以及确保脚本正确运行，是夜莺的平台维护人员的职责，不能把这个信息暴露给这么多普通接收者。
