### ISSUE TITLE
仪盘表全屏时建议不提示“按 ESC 键退出全屏模式”

### ISSUE THREAD

**Issue by hel2o** [ccfos/nightingale#1872]
在其它系统中有引入多个仪盘表时 首次或者后面再刷新页面时会有很多的提示，建议增加个开关可不显示这句话。
![image](https://github.com/ccfos/nightingale/assets/14226648/13975ba4-e12b-45f4-a3b5-7d1d09b3a480)

**Comment by jsers** [comment]
后面会改成只有点击全屏按钮后才会有这个提示，如果是通过链接直接访问的全屏仪表盘则不会弹这个提示

**Comment by hel2o** [comment]
> 后面会改成只有点击全屏按钮后才会有这个提示，如果是通过链接直接访问的全屏仪表盘则不会弹这个提示

请问最新版本V7.Beta2.0.1删除这个提示了吗？

**Comment by hel2o** [comment]
v7.0.0-beta.3 可正常使用
