### ISSUE TITLE
no configuration file provided: not found

### ISSUE THREAD

**Issue by 2777484478** [ccfos/nightingale#1877]
[root@dap2 ~]# cd nightingale/docker/
[root@dap2 docker]# docker-compose  up -d
no configuration file provided: not found
[root@dap2 docker]# ls
build.sh  compose-bridge  compose-host-network  compose-host-network-metric-log  compose-postgres  Dockerfile  Dockerfile.goreleaser  Dockerfile.goreleaser.arm64  initsql  migratesql

Can't find a suitable configuration file in this directory or any
parent. Are you in the right directory?
no docker-compose.yml, docker-compose.yaml?

**Comment by tanxiao1990** [comment]
cd  nightingale/docker/compose-bridge   or  compose-host-network  or compose-host-network-metric-log  or compose-postgres

**Comment by tanxiao1990** [comment]
different subdirectories correspond to different supporting components or network

**Comment by 2777484478** [comment]
tks
