### ISSUE TITLE
建议增加监控仪表盘对浏览器ctrl+f的搜索功能

### ISSUE THREAD

**Issue by zzlyzq** [ccfos/nightingale#1878]
**What would you like to be added**:
* 在监控仪表盘页面，增加对浏览器ctrl+f搜索框的搜索功能。目前无法搜索内容。
![image](https://github.com/ccfos/nightingale/assets/1989900/84fd7f72-ab75-4520-bb61-2cbf0445374f)

**Why is this needed**:
如果监控仪表盘存在大量图表的情况下，增加支持内容搜索功能，可以方便使用者快速定位到相关指标。

**Comment by UlricQin** [comment]
@jsers 看看哈

**Comment by jsers** [comment]
这应该是浏览器本身就支持的功能，我在 Chrome 里 ctrl + f (command +f) 的搜索是可以高亮匹配结果和定位到匹配结果的位置
