### ISSUE TITLE
是否支持通过公式计算端口实时流量？

### ISSUE THREAD

**Issue by zhangchi2217** [ccfos/nightingale#1887]
通过snmp获取到ifHCInOctets
大盘是否支持通过公式计算当前值与上一个值的运算结果？
公式？：8×[ifHCInOctets(T2时刻的值)－ifHCInOctets(T1时刻的值)]，

**Comment by UlricQin** [comment]
promql 天然就支持这个，用 rate 或 irate 函数即可
