### ISSUE TITLE
v7.0.0-beta1疑似心跳上报bug

### ISSUE THREAD

**Issue by idcdog** [ccfos/nightingale#1888]
### Your config.toml

```toml
-
```

### Relevant logs

```text
-
```

### System info

v7.0.0-beta.1

### Steps to reproduce

版本：v7.0.0-beta.1-ee613616caa5ada2813e83d8b03dd0d7b67c606a
架构： 中心机房 -- 边缘机房， n9e和n9e-edge的版本都是 v7.0.0-beta.1
现象：
n9e-edge日志中每隔几分钟就报错
2024-03-15 14:44:57.939069 ERROR idents/idents.go:100 failed to update targets:[x.x.x.x] update_ts: redis is nil
其中x.x.x.x是所有上报数据到n9e-edge的相关机器ip
只有部署了n9e-edge边缘机房有这个报错， 中心机房没有这个报错
排查：
尝试重启过n9e-edge， 也尝试重启过中心机房的n9e， 检查过中心机房的redis服务正常， 之前没有这个报错（至少beta 0没有见过这个错误）

目前影响：目前除了有日志打印报错外， 未发现其他影响，边缘机房节点的心跳上报也是正常的

### Expected behavior

-

### Actual behavior

-

**Comment by penggk** [comment]
解决了吗？

**Comment by 710leo** [comment]
最新版本的 edge 也依赖了 redis，主要是进行机器失联告警时会用到，可以在 edge.toml 中增加下 redis 的配置，然后部署一个 redis 实例

```
[Redis]
# address, ip:port or ip1:port,ip2:port for cluster and sentinel(SentinelAddrs)
Address = "127.0.0.1:6379"
# Username = ""
# Password = ""
# DB = 0
# UseTLS = false
# TLSMinVersion = "1.2"
# standalone cluster sentinel
RedisType = "standalone"
# Mastername for sentinel type
# MasterName = "mymaster"
# SentinelUsername = ""
# SentinelPassword = ""
```

**Comment by idcdog** [comment]
> 最新版本的 edge 也依赖了 redis，主要是进行机器失联告警时会用到，可以在 edge.toml 中增加下 redis 的配置，然后部署一个 redis 实例
> 
> ```
> [Redis]
> # address, ip:port or ip1:port,ip2:port for cluster and sentinel(SentinelAddrs)
> Address = "127.0.0.1:6379"
> # Username = ""
> # Password = ""
> # DB = 0
> # UseTLS = false
> # TLSMinVersion = "1.2"
> # standalone cluster sentinel
> RedisType = "standalone"
> # Mastername for sentinel type
> # MasterName = "mymaster"
> # SentinelUsername = ""
> # SentinelPassword = ""
> ```

参考这个方式部署了redis后问题解决
