### ISSUE TITLE
对于权限的精细化

### ISSUE THREAD

**Issue by xiaqi1210** [ccfos/nightingale#1895]
**What would you like to be added**:
希望有一种权限配置是不允许修改别人创建的仪表盘, 只允许修改自己创建的仪表盘
或者只允许同一个的业务团队里的人可以有修改权限

**Why is this needed**:
现在的权限粒度比较粗, 要不然就全都能改, 要不然就全部不能改, 但是实际上每个业务团队应该有自己的管理权限, 要不然可能仪表盘不小心被其他团队的人改了影响就比较大

**Comment by 710leo** [comment]
现在仪表盘的权限管理，是有细粒度的权限控制的，可以给不同业务团队创建自己的业务组，在自己的业务组下创建管理仪表盘，不同业务组之间的权限是隔离的

**Comment by Payton443** [comment]
在仪表盘内可以查看所有设备信息，而不是只能查看授权业务组设备信息，比如[IPMI by Categraf]
