### ISSUE TITLE
服务端能否支持SQLite数据库类型？

### ISSUE THREAD

**Issue by luckyao** [ccfos/nightingale#1917]
**What would you like to be added**:支持SQLite数据库作为配置数据的存储

**Why is this needed**: 因为夜莺服务端的数据库，主要存储告警规则，面板，告警事件等小量数据，目前看使用MySQL或者Postgresql都有点重。如果使用SQLite会减少部署的组件，后续维护成本也会降低。

**Comment by UlricQin** [comment]
从产品角度支持 SQLite 是应该的，给用户多一个选项，只是人力有限，短期排不上，只能靠社区力量了

**Comment by fm2022aa** [comment]
sqlite 服务多主不好搞了吧

**Comment by 710leo** [comment]
最新版本已支持
