### ISSUE TITLE
发布的版本包希望支持mac m1版本

### ISSUE THREAD

**Issue by wego-xuchang** [ccfos/nightingale#1922]
发布的版本包希望支持mac m1版本

**Comment by 710leo** [comment]
可以自行编译下，很方便，安装下 go 环境，在根目录直接 make 就可以了，会产生可执行的 n9e 二进制文件

**Comment by wego-xuchang** [comment]
目前我的把源代码拉下来打包解决此问题，我提这个的意思就是发布包的可以根据makefile中构建不同个os和处理器打包，对使用不同的用户跟我遇到问题一样又不懂go的有希望体验




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "ccfos/nightingale"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年4月22日(星期一) 上午10:42
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [ccfos/nightingale] 发布的版本包希望支持mac m1版本 (Issue #1922)





 
可以自行编译下，很方便，安装下 go 环境，在根目录直接 make 就可以了，会产生可执行的 n9e 二进制文件
