### ISSUE TITLE
告警详情页面不能匿名访问

### ISSUE THREAD

**Issue by shichanglin5** [ccfos/nightingale#1930]
<img width="773" alt="image" src="https://github.com/ccfos/nightingale/assets/48707349/87177e5a-7ef3-495b-9e9c-a28005dd0ae4">

这个匿名感觉不太友好，我开启匿名访问后，想要能够匿名访问告警详情页面，但现在发现不行，只能匿名访问这个接口
<img width="1463" alt="image" src="https://github.com/ccfos/nightingale/assets/48707349/ecc22794-0c7c-4565-b9a6-32a1b1859288">

访问页面还是需要登录，感觉很奇怪，那这个配置有啥用呢
<img width="1311" alt="image" src="https://github.com/ccfos/nightingale/assets/48707349/f93f0f36-4e93-4763-97d7-67a39255e68c">

**Comment by UlricQin** [comment]
可以打开chrome开发者工具，看看哪个接口报的错。

**Comment by shichanglin5** [comment]
这个应该是前端的问题，是不是前端项目检查没有token直接就跳登录页了，上面匿名访问配置只配置了后端接口，前端没有做相关处理？

**Comment by UlricQin** [comment]
这个有问题，我们看一下
