### ISSUE TITLE
夜莺前端有大量错误的pure

### ISSUE THREAD

**Issue by zhangchi2217** [ccfos/nightingale#1931]
错误如图，版本：v7.0.0-beta.2.0.1
![image](https://github.com/ccfos/nightingale/assets/110875942/e45ae08b-ec21-4932-8f46-45f5e265cad3)

**Comment by UlricQin** [comment]
可以参考这个排查：https://mp.weixin.qq.com/s/Ug9CJisF8l3RG9wQmnIxBw
