### ISSUE TITLE
用VictoriaMetrics替换prometheus但是找不到文档中的配置文件

### ISSUE THREAD

**Issue by zhangchi2217** [ccfos/nightingale#1933]
参考文章：https://flashcat.cloud/docs/content/flashcat-monitor/nightingale/install/victoriametrics/
夜莺版本：v7.0.0-beta.2.0.1
VictoriaMetrics：单机版
根据文档中是要配置server.conf及webapi.cof ，但是在n9e中没有找到配置文件，只有config.toml有writer的配置，reader和webapi没有找到所在位置。

**Comment by UlricQin** [comment]
看对应版本的文档，你用 v7 就看 v7 的文档

<img width="311" alt="image" src="https://github.com/ccfos/nightingale/assets/2769466/b3801f45-e751-474d-812b-d57511007261">
