### ISSUE TITLE
希望提供告警规则创建修改和删除的API

### ISSUE THREAD

**Issue by ChenShuai1981** [ccfos/nightingale#1935]
希望提供告警规则创建修改和删除的API以便可以动态维护告警规则

需求背景是我们有一个实时计算平台，上面运行了非常多的实时作业，每一个实时作业设置的告警规则都不相同，通过手动页面配置的话工作量太大，而且我们也不想让用户接触到夜莺和熟悉PromQL。所以我们希望夜莺能够对外提供维护告警规则的API，通过实时平台来集成夜莺，最直接的是REST API，如果能够封装Java Client SDK更好。

**Comment by UlricQin** [comment]
https://flashcat.cloud/docs/content/flashcat-monitor/nightingale-v6/api/api/
