### ISSUE TITLE
告警管理中的订阅规则无法换行管理

### ISSUE THREAD

**Issue by sunailong** [ccfos/nightingale#1937]
### Your config.toml

```toml
default toml
```

### Relevant logs

```text
无
```

### System info

n9e v7.0.0-beta.2.0.1

### Steps to reproduce

1. 部署n9e v7.0.0-beta.2.0.1
2. 启动后点击告警管理，找到订阅规则
3. 随便选择一个业务组，新增订阅规则
4. 找到订阅告警规则选项
5. 选择已创建的规则，若有多条订阅，超出浏览器宽度的部分不会显示，也无法编辑和管理
![1](https://github.com/ccfos/nightingale/assets/13182160/83f6812d-eaaf-450f-b734-c2a4dbc37b74)
![2](https://github.com/ccfos/nightingale/assets/13182160/32887b92-8759-4d8d-ae20-89677a7a9e43)

### Expected behavior

能够正常换行显示

### Actual behavior

不会自动换行且无法管理

**Comment by sunailong** [comment]
@UlricQin @jsers 业务组分级创建和管理也有一些不方便，每次在终端业务组创建时不会自动扩展，会新增一个
![image](https://github.com/ccfos/nightingale/assets/13182160/e67e926e-21dc-4b87-b402-aa2d451d37d4)

**Comment by UlricQin** [comment]
不知道你咋用的，我这没问题。我的版本是 v7.0.0.beta3

树形展示：
<img width="231" alt="image" src="https://github.com/ccfos/nightingale/assets/2769466/096702da-8850-4e1a-9b72-80b7b4065e25">


去【系统配置】-【站点设置】中把业务组展示模式改成列表：

<img width="460" alt="image" src="https://github.com/ccfos/nightingale/assets/2769466/aba515e7-74a5-4ff1-a787-00590ec2c7bc">

再回到业务组看到的效果：
<img width="204" alt="image" src="https://github.com/ccfos/nightingale/assets/2769466/495b295b-ef30-404e-b436-ac8e52777584">

都是符合预期的。当然，你不能单独创建一个 cloud-dev-monitor的同时还创建一个 cloud-dev，那就是多此一举了
