### ISSUE TITLE
能否支持告警模板和针对具体主机自定义宏参数

### ISSUE THREAD

**Issue by sunailong** [ccfos/nightingale#1938]
**What would you like to be added**:
1. 新增告警模板管理，
2. 支持单机的监控参数宏定义替换。
**Why is this needed**:
1. 可创建一个类似base linux 告警模板，业务组订阅该模板后可以自动生效模板内的所有监控项
2. 模板内的监控参数不一定适合所有设备，可以新增一个宏参数，在单机定义具体宏参数可以替换掉模板内的默认参数，提高灵活性

**Comment by UlricQin** [comment]
这块还没有细想，不过开源版本中大概率不会做这个事情。你这个思路很像是 zabbix 那种资产管理式的模式。但是 prometheus 生态，一切都是靠标签筛选，而且 prometheus 里并没有资产的概念，没有对资产归组的概念，没有资产关联模板的概念。

**Comment by sunailong** [comment]
明白了，多谢
