### ISSUE TITLE
页面报错load filed，查看网络有一个路径经常加载失败，无法找到目录

### ISSUE THREAD

**Issue by zhangchi2217** [ccfos/nightingale#1940]
n9e版本：v7.0.0-beta.2.0.1
失败路径：/api/n9e/board/5/pure

![pure_error](https://github.com/ccfos/nightingale/assets/110875942/95f56590-5f42-4f8e-8548-89d919c4de04)

请问如何找到这个路径，和解决这个报错呢？

**Comment by 710leo** [comment]
可以确认下你的电脑到 n9e 所在机器的网络，经过了哪些链路，看看是哪个环节失败了
