### ISSUE TITLE
华为云K8S环境部署的n9e无法获取到k8s的指标

### ISSUE THREAD

**Issue by lyitt1987** [ccfos/nightingale#1943]
n9e部署方式：helm
categraf是以 DaemonSet运行
由于华为云k8s启动的10250端口未绑定在127.0.0.1，helm部署的n9e categraf日志报错如图

![image](https://github.com/ccfos/nightingale/assets/35764082/923e1b83-2a40-43e3-b608-8df895c5e740)

请问，如何配置让categraf 获取到本机IP，谢谢！

**Comment by UlricQin** [comment]
去categraf的repo提问哈，问错地了
