### ISSUE TITLE
二进制方式部署边缘节点Edge时，启动后可以同步数据，但是前端无法访问

### ISSUE THREAD

**Issue by sunailong** [ccfos/nightingale#1951]
### Your config.toml

```toml
默认配置，仅修改了redis地址
启动路径/opt/n9e
启动方式：./n9e-edge -configs etc/edge

后端提示同步数据正常，仅前端无法访问。
```

### Relevant logs

```text
前端报错：404 page not found
后端报错：无
```

### System info

n9e v7.0.0-beta.3

### Steps to reproduce

1.解压压缩包
2.修改edge配置文件redis地址
3.进入/opt/n9e，使用命令启动服务
4.前端无法访问

### Expected behavior

正常访问页面

### Actual behavior

404 page not found

**Comment by 710leo** [comment]
n9e-edge 并不提供页面服务，是一个后端程序，n9e-plus 才会提供页面服务
