### ISSUE TITLE
API接口地址变化

### ISSUE THREAD

**Issue by fctee** [ccfos/nightingale#1953]
升级了夜莺最新版本测试，之前是v5版本，现在后端版本：v7.0.0-beta.2.0.1 
之前使用的告警屏蔽接口  /api/n9e/busi-group/x/alert-mutes 正常使用。新版本同样接口提交没有报错，但是前端没有添加成功
另外 请问 https://developer.flashcat.cloud/?nav=01HREXR2GG81GWSAW83GW73T1W 这个链接里面的API文档是否实时更新

**Comment by fctee** [comment]
问题已解决 ，文档中的 /v1/n9e/alert-mutes 告警屏蔽接口没法使用。使用旧接口成功

**Comment by 710leo** [comment]
/v1/n9e/alert-mutes 有增加字段，接口文档已更新
