### ISSUE TITLE
告警订阅执行发送时不要再发送告警规则下配置的webhook回调了

### ISSUE THREAD

**Issue by wadefelix** [ccfos/nightingale#1955]
我现在使用的6.5版本。（不知道后续版本（比如7.0版本）改过没）

我发现，在告警规则下配置回调webhook，告警发生时调用一次这webhook，这没问题。
但是这个告警规则被另一人通过告警订阅给订阅了，那么再给告警订阅规则发送告警通知时， 原告警规则下原始定义的webhook会被再调用一次。  这不符合我的预期。我觉得告警订阅执行时，就不能再执行告警规则线原始配置的告警通知和webhook了，   仅仅再给订阅人执行发送给它的通知便可。

**What would you like to be added**:

**Why is this needed**:

**Comment by 710leo** [comment]
感谢反馈，现在的逻辑是不太合理，后续这里我们调整下

**Comment by UlricQin** [comment]
7.3.4版本应该已经调整好了，可以升级测试，这个 issue 我先 close 了，有问题可以再 reopen
