### ISSUE TITLE
边缘机房添加数据源无效

### ISSUE THREAD

**Issue by Myifan610** [ccfos/nightingale#1957]
![image](https://github.com/ccfos/nightingale/assets/19645451/c12e7f8b-e79e-4939-8df2-e97473e64d09)

我部署了一个边缘端，添加数据源URL时只能添加中心端victoriametrics，完成后机器列表里面可以看到边缘机房机器

但是仪表盘和即使查询无法查看边缘机房机器的数据

请问是数据源URL的问题吗，如果边缘机房只允许出网流量，该如何添加边缘机房的victoriametrics？

**Comment by 710leo** [comment]
可以看下这个 [视频教程 ](https://flashcat.cloud/media/?type=夜莺监控&source=aHR0cHM6Ly9kb3dubG9hZC5mbGFzaGNhdC5jbG91ZC9uOWUtMDgtdXNpbmctbXVsdGktdHNkYi12Mi5tcDQ=  
)

**Comment by Myifan610** [comment]
视频里面5.14和现在7的东西好像完全不一样了，无法按里面的操作进行

**Comment by 710leo** [comment]
https://flashcat.cloud/docs/content/flashcat-monitor/nightingale-v7/integrations/datasource/ 可以看下这个文档，可以把边缘机房的时序库也添加到数据源中
