### ISSUE TITLE
categraf所在宿主机机器名相同,夜莺机器列表就不显示

### ISSUE THREAD

**Issue by taoyang987** [ccfos/nightingale#1964]
### Your config.toml

```toml
111
```

### Relevant logs

```text
111
```

### System info

n9e 7.0beta4

### Steps to reproduce

1.
2.
3.
...
1

### Expected behavior

111

### Actual behavior

111

### Additional info

数据传输回来正常,图表中能显示,但是ident(主机)下拉框列表不显示

**Comment by taoyang987** [comment]
![image](https://github.com/ccfos/nightingale/assets/872386/cb5b64c0-9ac8-49d3-ace0-704579526549)
在这里自定义,启动日志还是显示宿主机名,但是回传回去的内容就是自定义好的

**Comment by 710leo** [comment]
可以贴下详细的配置截图

**Comment by UlricQin** [comment]
1.不同的机器不能自定义相同的主机名
2.日志中的 runner.hostname 是原始主机名，不是自定义主机名
