### ISSUE TITLE
告警规则编辑时的新手模式能不能回归

### ISSUE THREAD

**Issue by Myifan610** [ccfos/nightingale#1970]
![1716956351374](https://github.com/ccfos/nightingale/assets/19645451/97a44b02-5132-4523-ab06-3d80b9611bd8)
这里原来好像是有新手模式的挺好用的

**Comment by 710leo** [comment]
之前的 新手模式 交互略复杂，就下线了

**Comment by UlricQin** [comment]
新手模式实际无法覆盖所有的 promql 的场景，也可以说是有 bug 很难修，另外社区基本不用这个功能，直接下线掉了。
