### ISSUE TITLE
Feat: 限制用戶的登入方式（例如強制用戶只能使用SSO登入）

### ISSUE THREAD

**Issue by chenyunda218** [ccfos/nightingale#1983]
場景：公司提供了SSO，基於安全性考慮希望強制所有或部分同事都只能透過SSO登入。
解決方案：為每個用戶新增一個field，記錄用戶能使用的登入方式。
待討論內容：
1. 需不需要全局設置可以配置限制
2. 記錄方式，Field類型。
3. 需不需要基於角色的限制配置

**Comment by 710leo** [comment]
已有的功能，就可以支持这个场景，需要強制使用sso登录的人
- 如果之前没在夜莺中创建过账号，那就只能通过sso登录
- 如果之前在夜莺中创建过账号，把这些人账号的密码，操作数据库设置为空就行了，设置之后，也只能通过sso登录了

**Comment by chenyunda218** [comment]
目前我們公司也是這樣執行的，將已存在的帳號的密碼設置為使用者不知道的隨機密碼。強制管理員使用SSO登入。
我不確定這樣是否正確的做法。
另一方面當用戶有設定密碼的權限時能夠為自己設定密碼突破限制，而又無法透過一般的方法分別出一個用戶是否能夠用密碼登入。當有員工離職時就不能只管理SSO系統，而同時要去管理n9e的用戶。
