### ISSUE TITLE
机器列表界面无法显示指标信息

### ISSUE THREAD

**Issue by ddl1228** [ccfos/nightingale#1996]
### Question and Steps to reproduce

机器列表界面，龙蜥操作系统Anolis 8.5.0-18.0.3无法显示指标信息，CentOS 7.9.2009操作系统可以显示，如下图，上面是CentOS操作系统，下面是龙蜥操作系统
![image](https://github.com/ccfos/nightingale/assets/69077200/4ab863a9-c6d9-4505-afdf-ceb9bc9b19f4)

### Relevant logs and configurations

```text
两台机器，除了操作系统不同，其他都一样
```

### Version

夜莺版本：v7.0.0-beta.11
Categraf版本：v0.3.70
操作系统1版本：Anolis 8.5.0-18.0.3
操作系统2版本：CentOS 7.9.2009

**Comment by UlricQin** [comment]
categraf的配置都一样？没法心跳理论上会有报错日志，可以贴出完整的categraf日志




秦晓辉
***@***.***

快猫星云
联合创始人
18612185520



------------------ 原始邮件 ------------------
发件人: ddl1228 ***@***.***&gt;
发送时间: 2024年6月14日 16:03
收件人: ccfos/nightingale ***@***.***&gt;
抄送: Subscribed ***@***.***&gt;
主题: Re: [ccfos/nightingale] 机器列表界面无法显示指标信息 (Issue #1996)





 
Question and Steps to reproduce
 
机器列表界面，龙蜥操作系统Anolis 8.5.0-18.0.3无法显示指标信息，CentOS 7.9.2009操作系统可以显示，如下图，上面是CentOS操作系统，下面是龙蜥操作系统
 image.png (view on web)
 
Relevant logs and configurations
 两台机器，除了操作系统不同，其他都一样  
Version
 
夜莺版本：v7.0.0-beta.11
 Categraf版本：v0.3.70
 操作系统1版本：Anolis 8.5.0-18.0.3
 操作系统2版本：CentOS 7.9.2009

**Comment by UlricQin** [comment]
看起来就是 heartbeat 的 enable 关掉了

**Comment by ddl1228** [comment]
再次确认了下，enable的值是true，并且是有心跳的，如下图
![image](https://github.com/ccfos/nightingale/assets/69077200/b920ff55-7ac8-4436-a1d6-7fb3e62ba814)

**Comment by UlricQin** [comment]
那个更新时间并不能说明heartbeat有效，只要有指标上报，那里就是绿的。这种情况要么就是categraf版本太低，要么就是heartbeat没开。

**Comment by ddl1228** [comment]
categraf版本是最新的，heartbeat也是打开的
[root@hq_sz_n9e_master_01 ~]# /usr/local/categraf/categraf -version
v0.3.70-beda1a1c68e37273f26697f374cc1e9085eb4d76
[root@hq_sz_n9e_master_01 ~]# grep heartbeat /usr/local/categraf/conf/config.toml -C 1

[heartbeat]
enable = true
--
# report os version cpu.util mem.util metadata
url = "http://127.0.0.1:17000/v1/n9e/heartbeat"

**Comment by UlricQin** [comment]
`enable = true` 下面怎么多了两个横线？

**Comment by kongfei605** [comment]
检查下url的ip和端口正确么？

**Comment by ddl1228** [comment]
> 你说两台机器的categraf配置都一样，那heartbeat地址都是配置的127.0.0.1？那这个sz的机器上也有n9e的进程？
> 
> 想不到其他可能性了，摸不到环境没法确认你的输入的信息的准确性。

是的，这两台机器上都单独部署了n9e，prometheus，redis和categraf，但是共用同一套mysql，目前可视化界面连的是hq_fs_n9e_master_01这台

**Comment by UlricQin** [comment]
你没有使用n9e-edge边缘模式，只用了n9e，多个n9e所用的redis要用一套




秦晓辉
***@***.***

快猫星云
联合创始人
18612185520



------------------ 原始邮件 ------------------
发件人: ddl1228 ***@***.***&gt;
发送时间: 2024年6月17日 09:52
收件人: ccfos/nightingale ***@***.***&gt;
抄送: ulricqin ***@***.***&gt;, Comment ***@***.***&gt;
主题: Re: [ccfos/nightingale] 机器列表界面无法显示指标信息 (Issue #1996)





  
你说两台机器的categraf配置都一样，那heartbeat地址都是配置的127.0.0.1？那这个sz的机器上也有n9e的进程？
 
想不到其他可能性了，摸不到环境没法确认你的输入的信息的准确性。
  
是的，这两台机器上都单独部署了n9e，prometheus，redis和categraf，但是共用同一套mysql，目前可视化界面连的是hq_fs_n9e_master_01这台

**Comment by ddl1228** [comment]
好的，不过之前我们使用V5版本的时候也是这样部署的就没有问题，最新版本是必须使用同一套redis了是吧？
