### ISSUE TITLE
Feat:  回调地址 中支持 获取变量

### ISSUE THREAD

**Issue by jicki** [ccfos/nightingale#1998]
**What would you like to be added**:

希望在回调地址中支持 变量, 如:

回调地址:
https://open.feishu.cn/open-apis/bot/v2/hook/b43e7bea-88fd-436e-3223-xdsfd233223?card=1&ats={{ $labels.id }} 

**Why is this needed**:
可以进行一些灵活的操作. 如我在创建服务的时候就把创建者 id 或者 name 添加到 labels 中. 在触发告警的时候可以直接获取到这个 id 或者 name 进行 @ 到负责人

**Comment by 710leo** [comment]
@jicki 欢迎贡献 pr 哈，可以参考下 rule_note 支持变量的实现
