### ISSUE TITLE
dashboard 如何显示label_values？

### ISSUE THREAD

**Issue by zhangchi2217** [ccfos/nightingale#2003]
### Question and Steps to reproduce

在大盘中想要通过主机IP显示data中的label，如何实现呢？

### Relevant logs and configurations

```text
在大盘中想要通过主机IP显示data中的label，如何实现呢？
```

### Version

v7.0.0-beta.11

**Comment by UlricQin** [comment]
看不懂你的问题。大盘变量的设置逻辑和Grafana类似，参考：https://flashcat.cloud/docs/content/flashcat-monitor/nightingale-v7/queries/dashboard/
