### ISSUE TITLE
右上角的时间范围能否被调用？

### ISSUE THREAD

**Issue by zhangchi2217** [ccfos/nightingale#2009]
### Question and Steps to reproduce

获取时间段bytes数据能都调用前端右上角的时间范围？
<img width="743" alt="image" src="https://github.com/ccfos/nightingale/assets/110875942/bdddbd82-4abe-436d-866b-e90d32f982cf">

### Relevant logs and configurations

```text
snmp_ap_hwWlanApEthportDwTraffic{ip="$ip"}[$__interval]
```

### Version

v7.0.0-beta.1

**Comment by UlricQin** [comment]
@jsers 帮看看呢

**Comment by jsers** [comment]
![image](https://github.com/ccfos/nightingale/assets/7424634/cb0a7b3f-8278-43e0-9f33-3dc0fa7f1a0a)
可以用 $__range 相关的变量

**Comment by jicki** [comment]
之前我有个想法.. 就是这个时间范围不能单独作用于一个 Panel ，只能作用于整个 dashboard . 我看 grafana 也不行.  哈哈。不知道能不能实现这个东西。

**Comment by jsers** [comment]
@jicki 
Panel 的每个 query 都可以设置单独的时间范围，内置的时间变量也会优先使用 query.time 的时间来解析

**Comment by jicki** [comment]
> @jicki Panel 的每个 query 都可以设置单独的时间范围，内置的时间变量也会优先使用 query.time 的时间来解析

啊～这个怎么设置呀。  比如我想设置 query   start_time = 2024-06-27 09:00:00    end_time = 2024-06-27 10:00:00 

这种如何可以配置呢

**Comment by jsers** [comment]
![image](https://github.com/ccfos/nightingale/assets/7424634/00235876-e7f8-419b-b19c-10a1d939f99a)

**Comment by jicki** [comment]
啊。原来如此。 太棒了
