### ISSUE TITLE
现在v7.0版本支持告警合并发送吗

### ISSUE THREAD

**Issue by wxswhh** [ccfos/nightingale#2010]
![8f03da58-1cc4-4c7c-95bd-8fbf171e26d6](https://github.com/ccfos/nightingale/assets/57620635/4b7da1ae-ee0f-4ac8-bc64-aba7ccd9da2a)

同一个指标的告警可以合并发送么。

**Comment by 710leo** [comment]
这个功能在开源里没有，在商业版本里是有的
