### ISSUE TITLE
活跃告警没有被清理

### ISSUE THREAD

**Issue by Jalright** [ccfos/nightingale#2013]
### Question and Steps to reproduce

![image](https://github.com/ccfos/nightingale/assets/5615974/184d30b0-82f8-4bee-b9db-1989b214e471)
活跃告警一直没有被清理，实际告警已经恢复，触发时间也不会被更新

### Relevant logs and configurations

```text
http://[n9e-server]/alert-cur-events
```

### Version

- v7.0.0-beta.11
- rockylinux 9 
- amd64

**Comment by 710leo** [comment]
@Jalright 可以贴下完整的告警规则配置

**Comment by Jalright** [comment]
@710leo 应该跟告警规则没有关系，所有告警规则都会，是因为我使用TiDB做为存储吗？   还是因为我部署了多个节点？ 
![image](https://github.com/user-attachments/assets/ddb13ee7-eb99-4ce1-8756-18392d302c38)
截图是我回复的时候截的，上面的告警已经发通知恢复了，实际情况也是恢复的，只是活跃告警还是一直都在。

**Comment by Jalright** [comment]
![image](https://github.com/user-attachments/assets/b13ba5e1-9da4-4b94-bf2b-8178f526bfb8)
@710leo 告警历史里面是有恢复记录的

**Comment by Jalright** [comment]
升级到**正式版本**之后就没有出现了！
