### ISSUE TITLE
本地如何运行夜莺后端

### ISSUE THREAD

**Issue by LionCastle** [ccfos/nightingale#2018]
1.准备了go环境、拉取了代码、加载了依赖
2.执行 go build ./cmd/center/main.go后 会生成mian.exe
3.我执行mian.exe,没有任何反应。
![1719454866828](https://github.com/ccfos/nightingale/assets/22554596/03b23e7b-921c-4e33-bdf9-6963354d63ad)

请问：本地如何启动运行呢？有文档可以参考吗

**Comment by UlricQin** [comment]
没有运行的截图，这是一个 bad issue。就在 Nightingale-main 目录里执行 `.\cmd\center\main.exe` 不可能没有任何输出

**Comment by LionCastle** [comment]
@UlricQin 你好，那我怎么在本地运行呢？有运行文档吗

**Comment by UlricQin** [comment]
开源软件一般都提供 Makefile 来编译，编译完成之后，就跟[二进制方式](https://flashcat.cloud/docs/content/flashcat-monitor/nightingale-v7/install/binary/)的运行方法一致。

1.确保配置文件都改好了，尤其是mysql、redis等的连接地址
2.确保网络通畅，执行 make 命令
3.启动夜莺即可 ./n9e
