### ISSUE TITLE
使用日志分析功能，选泽对应索引后，可选字段有的索引有展示、有的索引没展示

### ISSUE THREAD

**Issue by caojiaqiang** [ccfos/nightingale#2019]
### Question and Steps to reproduce

本地使用日志分析功能，选泽对应索引后，可选字段有的索引（.monitoring-es-6-2024.06.26）有展示
![1](https://github.com/ccfos/nightingale/assets/11900397/48a10446-fbb5-466b-a548-ad21cfcef304)
有的索引（ops_tlblog_all）又没展示
![2](https://github.com/ccfos/nightingale/assets/11900397/e2e9b236-2c8f-46d5-a8b0-bd98bd91cb14)

### Relevant logs and configurations
.monitoring-es-6-2024.06.26索引返回的mapping
![4](https://github.com/ccfos/nightingale/assets/11900397/d48b21a9-bc83-447d-8c2e-76de0673266f)

ops_tlblog_all索引返回的mapping
![3](https://github.com/ccfos/nightingale/assets/11900397/1a3747e8-79e1-4ca8-98f4-be9c9608688e)

```text

```

### Version

n9e版本：
6.5.0

ES版本：
6.8.0

本级操作系统；
mac m1

**Comment by jsers** [comment]
索引的 root 不合规，目前只支持 mappings.properties 或是旧版本的 mappings.doc.properties
