### ISSUE TITLE
部署了v7.0.0-beta.12.1版本，夜莺界面为什么看不到内置仪表盘，只有集成仪表盘

### ISSUE THREAD

**Issue by lixue323** [ccfos/nightingale#2021]
### Question and Steps to reproduce

![夜莺](https://github.com/ccfos/nightingale/assets/31582375/af00c76c-9d95-4fd7-8985-af893fe472bf)

### Relevant logs and configurations

```text
我想使用插件连接mysql，也在采集器input。mysql下配置好了。就是不知道如何在夜莺上展示
```

### Version

v7.0.0-beta.12.1

**Comment by jsers** [comment]
内置仪表盘已升级，新的地址在 "集成中心" >  "模板中心"
升级后 “模板中心” 包括了内置仪表盘和内置告警规则等
