### ISSUE TITLE
使用自己新增的通知媒介、通知模板和联系方式，发送告警消息的时候会报错 no sender channel: xxx

### ISSUE THREAD

**Issue by DuanxianshengGO** [ccfos/nightingale#2022]
### Question and Steps to reproduce

使用自己新增的通知媒介、通知模板和联系方式，发送告警消息的时候会报错 no sender channel: xxx

### Relevant logs and configurations

```text
DEBUG dispatch/dispatch.go:246 no sender for channel: feishuos
```

### Version

7.0

**Comment by UlricQin** [comment]
不用关心，那只是一个debug，表示的意思是：go 代码中没有内置实现相关的 channel 的发送逻辑，这是符合预期的，因为自定义的通知媒介一般是在自定义脚本里实现发送的
