### ISSUE TITLE
使用内置仪表盘功能

### ISSUE THREAD

**Issue by blackher** [ccfos/nightingale#2023]
### Question and Steps to reproduce

无法配置 页面为空
![WX20240703-095817](https://github.com/ccfos/nightingale/assets/12698390/8941078e-0f6d-4434-88da-ba371e91befc)
查看源码发现需要配置embedded-dashboards
![image](https://github.com/ccfos/nightingale/assets/12698390/46aa71f2-68da-4a1b-ad50-d3068b226480)

需要怎么配置

### Relevant logs and configurations

```text
mysql> select * from configs where ckey= "embedded-dashboards"\G;
Empty set (0.00 sec)

ERROR:
No query specified
```

### Version

v7.0.0-beta.12.1

**Comment by UlricQin** [comment]
用管理员登录试试

**Comment by blackher** [comment]
> 用管理员登录试试

应该是权限问题 修改/etc/ops.yaml 增加权限后可以了
