### ISSUE TITLE
恢复告警的 promql 表达式在哪配置

### ISSUE THREAD

**Issue by florajun** [ccfos/nightingale#2026]
### Question and Steps to reproduce

我在新版本的告警配置页面并没有找到恢复 promql 表达式的配置功能。而 v7 计划里面这一块已经打✔了。想请问下这块功能是否已发布

### Relevant logs and configurations

```text
无
```

### Version

V7-beta12.1

**Comment by UlricQin** [comment]
http://flashcat.cloud/blog/nightingale-release-v7.0.0.beta10/




秦晓辉
***@***.***

快猫星云
联合创始人
18612185520



------------------ 原始邮件 ------------------
发件人: florajun ***@***.***&gt;
发送时间: 2024年7月7日 09:31
收件人: ccfos/nightingale ***@***.***&gt;
抄送: Subscribed ***@***.***&gt;
主题: Re: [ccfos/nightingale] 恢复告警的 promql 表达式在哪配置 (Issue #2026)

**Comment by florajun** [comment]
谢谢,秦总

**Comment by florajun** [comment]
谢谢,秦总
