### ISSUE TITLE
Skip verify ssl doesn't work

### ISSUE THREAD

**Issue by chenyunda218** [ccfos/nightingale#2028]
我發現回調地址中的"跳過SSL驗證" 不起作用，並且在`nightingale/alert/sender/webhook.go` 中的 `sendWebhook` 中有一個// todo add skip verify。有甚麼特殊原因不去實現該功能嗎？如果沒有特別的原因我願意去實現該功能。

**Comment by 710leo** [comment]
@chenyunda218 没有特殊原因，应该是当时开发的时候，漏掉了，欢迎提 PR 实现。
