### ISSUE TITLE
v7.0.0-beta.13无法添加通过edge接入的不可外网访问的数据源

### ISSUE THREAD

**Issue by hrool** [ccfos/nightingale#2029]
### Question and Steps to reproduce

网络情况：   prometheus  <  n9e-edge  >  n9e
n9e的中心端没办法访问位于n9e-edge内网的prometheus的情况下，无法添加数据源，提示如下：

![图片](https://github.com/ccfos/nightingale/assets/18434071/68cc6ca4-7d19-4fce-a439-1b6cd5fd6612)

### Relevant logs and configurations

```text
no
```

### Version

v7.0.0-beta.13

**Comment by UlricQin** [comment]
嗯，现在的产品确实就是这么设计的。你的场景是什么？不需要在 n9e 中心端查看数据，仅想使用 n9e-edge 做告警？并且 n9e-edge 可以连通 n9e 进程？

**Comment by hrool** [comment]
内网的prometheus不允许提供对外网络连接的情况下，我以为只要n9e-edge部署在内网，n9e-edge可以访问内网的prometheus就不影响使用。
那如果产品这样设计的，只要我的prometheus没有直接暴露给n9e, 我就完全没法接入.

**Comment by UlricQin** [comment]
也能接入，用比较奇诡的方法。URL 配置为 n9e 可通的 Prometheus ，假的 Prometheus 就行，然后数据源配置里的那个内网 URL 设置为真实的时序库地址。但还有个前提，n9e-edge 需要能连通中心端 n9e，因为要从中心端拉取告警规则




秦晓辉
***@***.***

快猫星云
联合创始人
18612185520



------------------ 原始邮件 ------------------
发件人: rool ***@***.***&gt;
发送时间: 2024年7月9日 16:39
收件人: ccfos/nightingale ***@***.***&gt;
抄送: ulricqin ***@***.***&gt;, Comment ***@***.***&gt;
主题: Re: [ccfos/nightingale] v7.0.0-beta.13无法添加通过edge接入的不可外网访问的数据源 (Issue #2029)

**Comment by hrool** [comment]
明白，的确可以用这样的fake方法
