### ISSUE TITLE
v7.0.0-beta.13 监控仪表板 TopBar自定义 自定义全选值失效

### ISSUE THREAD

**Issue by aapelismith** [ccfos/nightingale#2033]
### Question and Steps to reproduce

v7.0.0-beta.13 监控仪表板 TopBar自定义 自定义全选值失效

### Relevant logs and configurations

```text
"sum(rate(kafka_topic_partition_current_offset{app=\"exporter-xxxxx\",project=\"xxxxx\",group=\"vvvv", topic=~\"all\"}[1m])) by (topic)"


topic 应当为 .*
```

### Version

v7.0.0-beta.13

**Comment by jsers** [comment]
下个版本会修复这个问题

**Comment by UlricQin** [comment]
新版本应该已经修复这个问题了，可以下载 7.3.4版本测试哈，这个issue先关闭了，如果还有问题可以到 github.com/n9e/fe 提 issue

**Comment by xiaqi1210** [comment]
> 新版本应该已经修复这个问题了，可以下载 7.3.4版本测试哈，这个issue先关闭了，如果还有问题可以到 github.com/n9e/fe 提 issue

这个是前端的问题还是后端问题, 我是前端独立部署的, 是需要升级前端, 还是前后端都要升级?
