### ISSUE TITLE
legend 引用变量 不生效

### ISSUE THREAD

**Issue by lujay** [ccfos/nightingale#2036]
### Question and Steps to reproduce

版本： v7 beta 13
浏览器： chrome 126.0.6478.127
![03fe380400d9db8ddd6c5df2742f284](https://github.com/user-attachments/assets/30a0615e-0c96-4253-97f9-391c3b3be1ce)
![image](https://github.com/user-attachments/assets/dc394b5d-9048-4640-afbe-daa6a3b109b0)
从grafana 导入 dashboard， 只有legend 引用变量 显示异常

### Relevant logs and configurations

```text
略
```

### Version

版本： v7 beta 13
浏览器： chrome 126.0.6478.127
cpu ： x86_64

**Comment by UlricQin** [comment]
这样看不出来，你把 promql 中的变量 application 、instance 等替换成某个确切的值，然后去即时查询页面查询，看看返回的内容中，有 application 标签么

**Comment by lujay** [comment]
![image](https://github.com/user-attachments/assets/bb8455fe-52c8-4526-a071-6108926440ae)
![image](https://github.com/user-attachments/assets/49cbe7f7-d4cd-4224-94ba-8fd1a0c68e72)
标签是有的

**Comment by lujay** [comment]
这个lengend 在grafana 里面正常能使用 导入后就失效了

**Comment by lujay** [comment]
![image](https://github.com/user-attachments/assets/ec4e58ae-2179-4854-8c67-e8739c342809)
dashboard 这边 添加变量，不能实时预览？结果

**Comment by UlricQin** [comment]
你的 promql 最外层加了 sum ，结果是没有 application 标签的，legend 自然就取不到值了
<img width="1266" alt="image" src="https://github.com/user-attachments/assets/c0bd9359-be4c-4dc7-9094-95ed79cea6a9">

**Comment by lujay** [comment]
![image](https://github.com/user-attachments/assets/b635cf5a-8b70-4a58-ad60-f636d980f5e3)
grafana 上面就正常
![image](https://github.com/user-attachments/assets/31db2031-5003-4797-a454-bd5d22edb362)

**Comment by UlricQin** [comment]
1. 变量的引用实际来自两个地方，一个是监控数据series，另一个是大盘变量
2. grafana 和 夜莺都支持引用 series 里的变量，通过 {{var}} 的方式
3. grafana 的 legend 支持引用大盘变量，夜莺的panel标题支持引用大盘变量
4. 你这个情况，可以在夜莺图表的标题里写 $application
