### ISSUE TITLE
v7.0.0-beta.13专业版 告警规则开启级别抑制告警恢复后低级别告警无法自动恢复

### ISSUE THREAD

**Issue by spublinux** [ccfos/nightingale#2037]
### Question and Steps to reproduce

v7.0.0-beta.13专业版 告警规则开启级别抑制告警恢复后低级别告警无法自动恢复

### Relevant logs and configurations

```text
v7.0.0-beta.13专业版 告警规则开启级别抑制告警恢复后低级别告警无法自动恢复
```

### Version

v7.0.0-beta.13

**Comment by 710leo** [comment]
@spublinux 最新版本已修复，可以升级下：）
