### ISSUE TITLE
单个用户是否支持设置多个飞书webhook

### ISSUE THREAD

**Issue by yanming-zhang** [ccfos/nightingale#2039]
### Question and Steps to reproduce

有这么一种场景需求：
一个用户需要同时接收多个飞书群的告警，但目前的情况是一个用户只能绑定一个飞书webhook地址，比如：
![image](https://github.com/user-attachments/assets/f4910a93-7416-4dd4-8ac4-2700a148525e)

### Relevant logs and configurations

```text
null
```

### Version

v7.0.0-beta.13

**Comment by UlricQin** [comment]
创建多个假用户，A 用户配置 a token，B 用户配置 b token。这些用户可以看做是虚拟机器人。和 ldap 中的用户不是一一对应

**Comment by yanming-zhang** [comment]
> 创建多个假用户，A 用户配置 a token，B 用户配置 b token。这些用户可以看做是虚拟机器人。和 ldap 中的用户不是一一对应

然后把这些假用户加到对应的团队里，也就意味同一个团队中的不同用户，可以收到来自多个不同webhook的告警消息？
