### ISSUE TITLE
告警规则支持匹配抑制

### ISSUE THREAD

**Issue by 18216499322** [ccfos/nightingale#2044]
比如说
flink_taskmanager_job_task_operator_pendingRecords{job_name='*'} > 200000
和
flink_taskmanager_job_task_operator_pendingRecords{job_name='abc'} > 100000
两个告警规则条件
告警事件命中了精准匹配的告警规则后，通配匹配的告警规则不再生效，即相同的指标名和labels只触发一个告警

**Comment by UlricQin** [comment]
现在的告警规则里就可以配置多个 promql，启用级别抑制。高级别抑制低级别，一级是最高的。如果某个 series 触发了一级告警，即便这个 series 同时触发了二级、三级告警，都不会发送二级、三级告警，只会发送一级告警
