### ISSUE TITLE
v7.0.0-beta.13 监控仪表板 在分组按钮上面点击添加图表，展示内容不全

### ISSUE THREAD

**Issue by aapelismith** [ccfos/nightingale#2050]
### Question and Steps to reproduce

v7.0.0-beta.13 监控仪表板 在分组按钮上面点击添加图表，展示内容不全, 会弹出一个空的Dialog
![image](https://github.com/user-attachments/assets/e67fbade-47f5-457c-9d03-8115520a4c35)

![image](https://github.com/user-attachments/assets/a659ab09-933e-47b1-9e82-c939f8aa6270)

### Relevant logs and configurations

```text
暂无
```

### Version

v7.0.0-beta.13

**Comment by jsers** [comment]
最新版本已修复
