### ISSUE TITLE
夜莺不兼容导入的Grafana面板中出现正则

### ISSUE THREAD

**Issue by aapelismith** [ccfos/nightingale#2053]
### Question and Steps to reproduce

如下图所示, 夜莺不兼容变量定义中出现正则而Grafana中是兼容的

![image](https://github.com/user-attachments/assets/2294651e-dc77-49b6-ab8b-526749cbcfab)

查询会变成下面的内容
![image](https://github.com/user-attachments/assets/ed418d4f-6fc8-4416-b2b9-5fea4917449b)

### Relevant logs and configurations

```text
暂无
```

### Version

v7.0.0-beta.14

**Comment by jsers** [comment]
这里是两个问题
1. metrics 目前确实是不支持正则匹配，下个版本我们支持下
2. 第二个截图 query: last_over_time() 这个显然不是 metrics 查询，这是 label values 的查询然后这里数据源里选择了 vm 则会通过 last_over_time 去查询 label values，目前我看 grafana 也是不支持 label values 的 metric 是正则的方式
