### ISSUE TITLE
企微推送，在企微群没有看到消息，夜莺也没有相关错误日志

### ISSUE THREAD

**Issue by lyc0221** [ccfos/nightingale#2057]
### Question and Steps to reproduce

按照企微推送配置教程 https://flashcat.cloud/docs/content/flashcat-monitor/nightingale-v7/monitor/notify-wecom/
最后发现企微群没有收到告警消息，具体配置如下
![image](https://github.com/user-attachments/assets/86b8bca3-ea59-45d7-bb02-8de7276a72c8)

![image](https://github.com/user-attachments/assets/d67f9a31-88f6-4bfe-966c-b43553a9de52)

![image](https://github.com/user-attachments/assets/b7fc5d51-6309-4512-80fe-31cf183204c5)

![image](https://github.com/user-attachments/assets/461cbc1f-2a9b-479e-99dc-40e1796eb7d9)

![image](https://github.com/user-attachments/assets/5be65ce8-ed88-456f-9fe2-3418fbba4116)

![image](https://github.com/user-attachments/assets/4a7efe45-af47-4a12-9af9-39dc826e6758)

### Relevant logs and configurations

```text
只有DEBUG.log有日志，ERROR.log没有日志
```

### Version

v7.0.0

**Comment by UlricQin** [comment]
https://flashcat.cloud/docs/content/flashcat-monitor/nightingale-v7/monitor/notify-wecom/ 这个文章写的很清楚了，你没有照做，反而自己新增了通知媒介
