### ISSUE TITLE
是否支持回调地址覆盖

### ISSUE THREAD

**Issue by yanming-zhang** [ccfos/nightingale#2058]
### Question and Steps to reproduce

情况是这样的，我配置了一个全局的回调地址：
![image](https://github.com/user-attachments/assets/15036ff4-15ad-4cf7-903e-bc0c60977902)

同时在配置告警规则的时候，也配置一个回调地址：
![image](https://github.com/user-attachments/assets/1799399d-9773-48f8-b9cf-4c4d4cec6502)

是否可以支持用这个回调地址覆盖全局的回调地址（最好是能提供一个开关按钮，让用户选择是否覆盖）？

### Relevant logs and configurations

```text
null
```

### Version

v7.0.0

**Comment by chenyunda218** [comment]
感覺是能設定啓不啓用全局的回調,無論有沒有局部的回調都能設置

**Comment by aapelismith** [comment]
![image](https://github.com/user-attachments/assets/a2dcdbf1-2e76-4ce2-96d0-ee3cf311a4ba)

借楼反馈个问题，全局回调地址配置上之后就再也删不掉了.

**Comment by aapelismith** [comment]
@yanming-zhang 你试试看
cc @alrs

**Comment by aapelismith** [comment]
@jsers

**Comment by yanming-zhang** [comment]
> @jsers

你可以把它的 启用 关闭掉

**Comment by yanming-zhang** [comment]
> @yanming-zhang 你试试看 cc @alrs

你可以把它的 启用 关闭掉

**Comment by YIwanT** [comment]
会覆盖的，会发两次，我测试了
