### ISSUE TITLE
通知模版dingtalk如何获取恢复时的数据而不是触发时值？

### ISSUE THREAD

**Issue by opsmeta** [ccfos/nightingale#2060]
### Question and Steps to reproduce

通知模版dingtalk如何获取恢复时的数据而不是触发时值？
{{if .AnnotationsJSON.recovery_value}}
 当前数据: {{formatDecimal .AnnotationsJSON.recovery_value 4}}
{{end}}
这个似乎不生效

### Relevant logs and configurations

```text
N/A
```

### Version

v7.0.0

**Comment by UlricQin** [comment]
https://flashcat.cloud/blog/nightingale-release-v7.0.0.beta10/
