### ISSUE TITLE
内置变量与自定义变量数据对比

### ISSUE THREAD

**Issue by HH17740639615** [ccfos/nightingale#2065]
### Question and Steps to reproduce

我使用exec插件获取自定义变量数据: server__bindwidth{server_code='tps41'} 
与内置变量 rate(net_bytes_sent{ident='tps41'}[1m])  两个变量皆有数据，且单位也一致，见图 。不知道为啥计算后无结果 
<img width="1126" alt="微信图片_20240730100347" src="https://github.com/user-attachments/assets/8b68dd27-162b-4a09-9990-f0fee6ceed14">

### Relevant logs and configurations

```text
日志正常, 就是查询无数据
```

### Version

夜莺版本: v7.0.0-17dbb3ec778f84aa8687ac4fda91b7370ba32c7c
操作系统: centos7
内核:  Linux 3.10.0-1160.90.1.el7.x86_64
CPU:   Intel(R) Xeon(R) CPU E5-2690 0 @ 2.90GHz

**Comment by UlricQin** [comment]
你需要再学习一下 promql，在 promql 里标签不同的指标不能直接计算，更详细可以再问问 GPT
