### ISSUE TITLE
告警指标无数据上报时不进行告警恢复

### ISSUE THREAD

**Issue by ximifei** [ccfos/nightingale#2068]
当触发指标触发告警后，后续指标如果没有上报数据将在默认5分钟后触发告警恢复。如何设置在没有数据上报后，将不进行告警恢复，直到下次指标数据上报后再进行告警恢复。

V7版本已经提供了recovery_promql这个注释，能否支持下通过recovery_promql去做无数据检测的情况

**Comment by UlricQin** [comment]
这个逻辑开源版本暂无改变的计划，要是动起来这块，动作比较大，你可以考虑使用 [FlashDuty](https://flashcat.cloud/product/flashduty/) 里的告警功能，会更强大一些
