### ISSUE TITLE
n9e启动时如果redis无法ping通则启动失败

### ISSUE THREAD

**Issue by spublinux** [ccfos/nightingale#2069]
### Question and Steps to reproduce

使用公有云的redis服务，即使6379可联通，但因redis禁ping，所以n9e启动失败。

### Relevant logs and configurations

```text
redis i/o timeout
```

### Version

n9e v7.0

**Comment by UlricQin** [comment]
确认是redis禁ping导致的？把夜莺代码里redis建连之后的ping检测代码删掉就好使了？




秦晓辉
***@***.***

快猫星云
联合创始人
18612185520



------------------ 原始邮件 ------------------
发件人: spublinux ***@***.***&gt;
发送时间: 2024年8月1日 14:57
收件人: ccfos/nightingale ***@***.***&gt;
抄送: Subscribed ***@***.***&gt;
主题: Re: [ccfos/nightingale] n9e启动时如果redis无法ping通则启动失败 (Issue #2069)





 
Question and Steps to reproduce
 
使用公有云的redis服务，即使6379可联通，但因redis禁ping，所以n9e启动失败。
 
Relevant logs and configurations
 redis i/o timeout  
Version
 
n9e v7.0
