### ISSUE TITLE
升级n9e到v7新建数据源报错：datasource表少了is_default字段

### ISSUE THREAD

**Issue by lifa1225** [ccfos/nightingale#2076]
### Question and Steps to reproduce

升级n9e到v7，添加数据源的时候报错，看日志发现是datasource表少了is_default字段，请问n9e“自动创建表结构”的功能是否漏了is_default字段？
<img width="715" alt="微信图片_20240802172116" src="https://github.com/user-attachments/assets/4134f4ca-1df7-4e1e-8e0f-6984631793c8">
![微信图片_20240802174204](https://github.com/user-attachments/assets/7c7e5635-cc6d-4ebd-8e5e-505dd2ce47b5)

### Relevant logs and configurations

```text
tip：我本地数据库用的是sqlite，执行：alter table datasource add is_default tinyint not null default 0;解决
```

### Version

v7，openEular，x86

**Comment by 710leo** [comment]
确认了下，是有自动加 is_default 字段的，可以检索下日志中的 migrate 关键字，看下是否是添加字段的时候报错了

**Comment by lifa1225** [comment]
> 确认了下，是有自动加 is_default 字段的，可以检索下日志中的 migrate 关键字，看下是否是添加字段的时候报错了

感谢回复！看了下有报错：
![微信截图_20240806105509](https://github.com/user-attachments/assets/b31050a1-7230-4ded-8e3d-8ecc25c798ae)

**Comment by sundayhk** [comment]
mysql
```
alter table datasource add column `is_default` tinyint(1) DEFAULT NULL COMMENT 'is default datasource' after `auth`,
```
