### ISSUE TITLE
回调地址是否可以用变量代替，会更直观一些

### ISSUE THREAD

**Issue by yanming-zhang** [ccfos/nightingale#2082]
### Question and Steps to reproduce

![image](https://github.com/user-attachments/assets/38a84713-7c97-4f4a-a5b7-7900dcc147c8)

### Relevant logs and configurations

```text
null
```

### Version

前端版本：v7.0.0
后端版本：v7.1.0-4764cc2419aa23efa48088b565652e50fdc35db0

**Comment by UlricQin** [comment]
回调地址这里，后面会抽出来单独管理，然后告警规则这里直接选择某个回调地址的名字即可。
