### ISSUE TITLE
mac os下执行n9e文件报错

### ISSUE THREAD

**Issue by sunzeJAVA** [ccfos/nightingale#2083]
### Question and Steps to reproduce

执行./n9e
控制台打印以下错误：
zsh: exec format error: ./n9e

### Relevant logs and configurations

```text
执行 nohup ./n9e &> n9e.log &
n9e.log中打印：
./n9e: ./n9e: cannot execute binary file
```

### Version

运行版本：n9e-v7.1.0-linux-arm64
macos版本：14.2 (23C64)
芯片：Apple M2 Pro

**Comment by chenyunda218** [comment]
有沒有重新在這台電腦上make build過？還是從別的電腦上複制過來的？

**Comment by chenyunda218** [comment]
看樣子像是直接下載release中的檔案，n9e-v7.1.0-linux-arm64不像是macos的版本，建議重新使用source code build一次。

**Comment by sunzeJAVA** [comment]
是的，直接在release下载的，我重新source code build一次试试

**Comment by sunzeJAVA** [comment]
重新make build，启动成功了，但是访问http://localhost:17000/出现404

**Comment by sunzeJAVA** [comment]
<img width="952" alt="image" src="https://github.com/user-attachments/assets/508eaa21-680d-4862-8ecd-84ebc131c6be">

**Comment by UlricQin** [comment]
使用 make 命令编译，会自动下载前端静态资源文件，然后打包进二进制，如果只是 go build 没有把前端文件打包进来，那就是 404
