### ISSUE TITLE
我使用snmp采集的几个端口汇聚相加不能相加

### ISSUE THREAD

**Issue by wangze-TIM** [ccfos/nightingale#2084]
### Question and Steps to reproduce

这个两个指标单独能在即时查询能查到
snmp_interface_ifHCInOctets{ifAlias="LKUP-CT1"}
snmp_interface_ifHCInOctets{ifAlias="LKUP-CT2"}

这个相加不能返回数据
snmp_interface_ifHCInOctets{ifAlias="LKUP-CT1"}+snmp_interface_ifHCInOctets{ifAlias="LKUP-CT2"}

### Relevant logs and configurations

```text
我看接口是正常返回的200
/api/n9e/proxy/2/api/v1/query?time=1723016671&query=snmp_interface_ifHCInOctets%7BifAlias%3D%22LKUP-CT1%22%7D%2Fsnmp_interface_ifHCInOctets%7BifAlias%3D%22LKUP-CT2%22%7D
{
    "status": "success",
    "data": {
        "resultType": "vector",
        "result": []
    },
    "stats": {
        "seriesFetched": "0",
        "executionTimeMsec": 0
    }
}
```

### Version

v7.1.0-4764cc2419aa23efa48088b565652e50fdc35db0   CentOS Linux release 7.9.2009 (Core)  amd64

**Comment by 710leo** [comment]
promql 中如果两个曲线的标签不同，是不能做运算的，可以看下这里的文档  https://prometheus.io/docs/prometheus/latest/querying/operators/ ，解决方案是通过一些函数将标签对齐
