### ISSUE TITLE
es集群即时查询报错

### ISSUE THREAD

**Issue by eryajf** [ccfos/nightingale#2087]
### Question and Steps to reproduce

添加了一个aws的opensearch，版本为2.13，进行即时查询是，切换到这个集群，就会出现报错：

```
Unexpected token '<', "<!doctype "... is not valid JSON
```

### Relevant logs and configurations

看起来是一个前端的报错：

<img width="935" alt="image" src="https://github.com/user-attachments/assets/56deb2aa-53f6-44dc-a176-9a194743bd76">

### Version

夜莺版本：v7.0.0
系统：CentOS 7.9
CPU架构：AMD

**Comment by jsers** [comment]
可以看下 network 感觉是接口请求失败了，导致返回的可能是一个 5xx 的 html 页面，html 去做 tojson 处理就是现在的错误消息

**Comment by eryajf** [comment]
<img width="788" alt="image" src="https://github.com/user-attachments/assets/d2c3b01e-38b1-4451-9af0-5dd5ed6ac0ef">


第一个请求是a集群，可正常获取索引列表。
第二个是切到这个异常的集群，很奇怪，为什么会出来这样的错误

**Comment by UlricQin** [comment]
从 Chrome 的请求中可以看到 urlpath、Payload 等信息，如果请求相同，一个集群好使一个不好使，这得研究这俩 es 集群的区别了。

**Comment by eryajf** [comment]
> 从 Chrome 的请求中可以看到 urlpath、Payload 等信息，如果请求相同，一个集群好使一个不好使，这得研究这俩 es 集群的区别了。

理论上来说的确如此，但我试了通过curl来获取索引列表，是能正常拿到的。这个我随后再深挖一下吧。

另外补充个小建议：貌似nightingale和categraf的issue都没有比较好地借助label来对问题进行归类，建议把这块儿做一下，以便于后来人更快速地找到自己的同类问题，以及更多开发者参与进来。

**Comment by UlricQin** [comment]
👌
