### ISSUE TITLE
Adding English Translations

### ISSUE THREAD

**Issue by venkatamutyala** [ccfos/nightingale#2089]
**What would you like to be added**:
English translations so that English speakers can use it.

**Why is this needed**:
Translation tools can only get us English speakers so far.

**Comment by 710leo** [comment]
<img width="1813" alt="image" src="https://github.com/user-attachments/assets/f0f48763-6e45-47e0-ae50-6bdf22a7e688">
@venkatamutyala Our product supports an English version. You can switch languages in the top right corner.

**Comment by venkatamutyala** [comment]
Thanks.
