### ISSUE TITLE
配置了回调地址，但没有收到请求

### ISSUE THREAD

**Issue by lyc0221** [ccfos/nightingale#2093]
### Question and Steps to reproduce

![image](https://github.com/user-attachments/assets/e89af677-dc8c-438a-85f1-3d12a8f389c6)
在通知设置界面，配置了回调地址，但是当触发了告警规则的时候，回调地址并没有接收到请求，是什么原因？

### Relevant logs and configurations

```text
无相关错误日志
```

### Version

前端版本：v7.0.0
后端版本：v7.0.0-17dbb3ec778f84aa8687ac4fda91b7370ba32c7c

**Comment by UlricQin** [comment]
<img width="1505" alt="image" src="https://github.com/user-attachments/assets/789d52f0-7291-44fb-aa96-a725bfb86fa9">
是否还有其他原因不知道，仅从这个图上来看，这个回调没启用

**Comment by lyc0221** [comment]
可以了，就是那个开启按钮没有打开
