### ISSUE TITLE
配置smtp后发送测试邮件失败

### ISSUE THREAD

**Issue by wuliwuli** [ccfos/nightingale#2100]
### Question and Steps to reproduce

正按文档配置完后，发送测试邮件，报错
我将insecureskipverify设置成false还是一样的报错

### Relevant logs and configurations

```text
email_send:failed to send: unencrypted connected
```

### Version

7.0.0

**Comment by UlricQin** [comment]
![image](https://github.com/user-attachments/assets/150ad07c-831c-47b2-87eb-c568bdfc3a82)
