### ISSUE TITLE
建议考虑uptimekuma的告警数量提醒小花招，在浏览器标签里面增加告警数量

### ISSUE THREAD

**Issue by zzlyzq** [ccfos/nightingale#2103]
作为全职网关，为了保障数百项服务稳定性，部署了包括夜莺在内的众多监控系统，其中夜莺是主力，还有uptime-kuma等。在日常的工作中，我发现尝尝打开uptime-kuma界面，对于告警数量可以直接看到，做到心中有数。毕竟有时候告警信息有时候来不及看。

**What would you like to be added**:

**Why is this needed**:
![image](https://github.com/user-attachments/assets/64d9ee2d-7790-44cc-a200-b3bd32d4af4b)

**Comment by UlricQin** [comment]
这个可以搞，不过优先级不高，本质是个巡检需求。通过浏览器的tab提示最大的问题是现代的浏览器都有tab颗粒度的内存释放能力，有可能夜莺的tab已经被释放掉了反而影响了巡检人员的注意力。一般在监控告警系统里，问题都是通过告警事件推送到某个通知媒介来提醒值班人员，事件驱动为主，上班时、下班时的巡检为辅。
