### ISSUE TITLE
v7.2.1告警无法自动恢复

### ISSUE THREAD

**Issue by spublinux** [ccfos/nightingale#2106]
### Question and Steps to reproduce

v7.0.0升级到v7.2.1，创建测试规则使其告警，告警后将规则阈值调整至可恢复的值，发现告警无法自动恢复。回滚到v7.0.0版本，问题不会出现

### Relevant logs and configurations

```text
cpu_usage_active >= 0.1 触发告警

cpu_usage_active >= 99.9 触发恢复告警
```

### Version

v7.2.1

**Comment by 710leo** [comment]
@spublinux 我们用 v7.2.1 没有复现，可以提供下详细的复现步骤，以及相关的截图

**Comment by spublinux** [comment]
补充：再次测试发现如果“留观时长（秒）”不设置为0既可复现。设置为0，恢复正常。
![alert-1](https://github.com/user-attachments/assets/e51d073a-6a20-4ab2-816a-49b5ac3e0aeb)

![alert-2](https://github.com/user-attachments/assets/b399b9c9-227d-4619-9dfe-8e8be27fd6a0)
![alert-3](https://github.com/user-attachments/assets/b08e5f56-c99e-459a-96ab-c4642605629f)

**Comment by hel2o** [comment]
> @spublinux 我们用 v7.2.1 没有复现，可以提供下详细的复现步骤，以及相关的截图

我的V7.2.1复现了，只要留观时长（秒）设置为非0  就不会发送恢复通知 永远不会恢复 即使实际上恢复了

**Comment by 710leo** [comment]
最新代码已经修复了，等发版之后可以升级下

**Comment by 710leo** [comment]
@hel2o @spublinux 最新版本已经修复了，可以升级下版本
