### ISSUE TITLE
仪表盘分享匿名访问无效

### ISSUE THREAD

**Issue by kankanai** [ccfos/nightingale#2114]
### Question and Steps to reproduce

设置公开且匿名访问，仍然需要登录才能看到图表
![image](https://github.com/user-attachments/assets/86a4e70f-2529-49b4-8b3d-65569509d8ad)
![image](https://github.com/user-attachments/assets/ec530955-8420-4e4a-8dd7-f5662f3f1136)

### Relevant logs and configurations

```text
控制台查看是有接口返回401状态
```

### Version

最新版本v7.2.1

**Comment by 710leo** [comment]
@kankanai 如果想打开匿名访问，这里的 PromQuerier 需要改为 true，才可以，可以检查下这里的配置
<img width="330" alt="image" src="https://github.com/user-attachments/assets/47e603bc-cb96-4201-a931-84ed6f417289">

**Comment by kankanai** [comment]
> @kankanai 如果想打开匿名访问，这里的 PromQuerier 需要改为 true，才可以，可以检查下这里的配置 <img alt="image" width="330" src="https://private-user-images.githubusercontent.com/2169271/359725704-47e603bc-cb96-4201-a931-84ed6f417289.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQyMDc4OTYsIm5iZiI6MTcyNDIwNzU5NiwicGF0aCI6Ii8yMTY5MjcxLzM1OTcyNTcwNC00N2U2MDNiYy1jYjk2LTQyMDEtYTkzMS04NGVkNmY0MTcyODkucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDgyMSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA4MjFUMDIzMzE2WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MDQ0MWIxNTNhOTIzMDc1MjIzYjg4OTU4Y2Y3OGU2ZTE0OTU5ZjZiM2UyZjFkNTk4ZWQ2ZWM4NWNlMjkzMGE2ZiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.z5ZpispahbXueyOHsE-nME7UlFuJu0KQzLHfUL5sOvM">

请问这个文件在哪里。。我是docker compose启动的

**Comment by kankanai** [comment]
> @kankanai 如果想打开匿名访问，这里的 PromQuerier 需要改为 true，才可以，可以检查下这里的配置 <img alt="image" width="330" src="https://private-user-images.githubusercontent.com/2169271/359725704-47e603bc-cb96-4201-a931-84ed6f417289.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQyMDgxODgsIm5iZiI6MTcyNDIwNzg4OCwicGF0aCI6Ii8yMTY5MjcxLzM1OTcyNTcwNC00N2U2MDNiYy1jYjk2LTQyMDEtYTkzMS04NGVkNmY0MTcyODkucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDgyMSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA4MjFUMDIzODA4WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9N2IzYTBlODQ2Mjc0ZGNmMjRlNjU3MmY4NjU4YjI0ZmU5Y2RiMWU5Nzg4NTRjMDFkYjQzMWI1ZjU3MTM0ZTQ3YSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.2uGpdBZlJnpmRr8SKiEXrN-Hv1RjEyqu1AJ1e6juEr8">

好像可以了，谢谢，还有两个问题想请教。
1.分享出去的页面的图表组件菜单包含“分享”，“排查”功能，如何隐藏，或者这个页面对应的代码文件在哪里呢，想自己修改。
2.想在页面监控里加一个图表，图表数据源来自mysql的sql语句，或者是自己实现的接口，没有找到，好像只支持Prometheus，Es，Loki这种数据源

**Comment by UlricQin** [comment]
1.可以通过关键字搜索找相关的代码
2.mysql数据源是商业版本的功能，暂未开放到开源版本
