### ISSUE TITLE
v7.2.1 无法发送告警

### ISSUE THREAD

**Issue by blade83lee** [ccfos/nightingale#2115]
在升级到v7.2.1 开始能正常告警， 但是运行几个小时后就无法发出告警，n9e-edge 出现崩溃情况提示错误如下：
![1724376146972](https://github.com/user-attachments/assets/ad031ea0-94f0-4666-85b3-13bd8676362f)
查看了 v7.2.1的源码
![企业微信截图_1724376281973](https://github.com/user-attachments/assets/7ddc7c2a-5e3a-4214-8d8f-27a772ab7924)
按道理，edge是不用去访问mysql数据库的
查看main的源码
![企业微信截图_17243763717599](https://github.com/user-attachments/assets/8d40014f-843d-4b09-824e-b2413e281804)
j加了新的判断。
所以能否打包出新的版本， 或者有手动解决的方式，先解决无法告警的问题

**Comment by 710leo** [comment]
@blade83lee 最新代码这个问题已经解决了，可以先自己用 make 编译一个新的二进制升级下
