### ISSUE TITLE
v.7.2.1 订阅规则无法使用通知脚本

### ISSUE THREAD

**Issue by blade83lee** [ccfos/nightingale#2116]
订阅规则
![企业微信截图_17243859168031](https://github.com/user-attachments/assets/759deebc-66f2-4a41-92c1-1c3cea252a3a)

**Comment by 710leo** [comment]
@blade83lee  如果启用了通知脚本，所有事件都给传给通知脚本，然后在 通知脚本 中自定义通知逻辑。在订阅的场景，你想使用通知脚本做什么事情呢

**Comment by blade83lee** [comment]
通知脚本做了一些获取第三方的信息，然后重新组合了 告警内容。所以订阅规则的 所涉及的告警规则是没设置通知媒介的。通知都在订阅里面设置。 在升级到v7.2.1之前 订阅规则是可以通过自定义通知脚本发送告警信息的

**Comment by blade83lee** [comment]
我增加 wecom  以及重新定义回调地址， 都有数据传出， 但是就是自定义的iaas渠道 没有消息发出， 如果我将iaas渠道放在告警规则里面， 可以正常发出

**Comment by UlricQin** [comment]
试试 7.3.4 版本应该可以了
