### ISSUE TITLE
文档中所说的接入数据源 腾讯云cls Jaeger数据源, 使用v7.2.1时并未找到

### ISSUE THREAD

**Issue by chenzhao1990** [ccfos/nightingale#2118]
### Question and Steps to reproduce

夜莺v7的官方文档中说已支持，但是实际使用时并未找到：
https://flashcat.cloud/docs/content/flashcat-monitor/nightingale-v7/usage/data_source/tx_cls/

### Relevant logs and configurations

```text
文档与实际使用不符
```

### Version

v7.2.1 二进制部署

**Comment by 710leo** [comment]
@chenzhao1990 这些是商业版本的功能，后面我们在文档上备注下
