### ISSUE TITLE
指标查询可以查到图，但告警没有被触发

### ISSUE THREAD

**Issue by 0xMadao** [ccfos/nightingale#2123]
### Question and Steps to reproduce

在告警规则详情页里，点`指标查询`，能出来图，但这个告警规则一直没触发。如下图:
<img width="1683" alt="截屏2024-08-27 16 42 23" src="https://github.com/user-attachments/assets/addafea1-7422-46df-a44b-11d3c87417b7">

### Relevant logs and configurations

```text
告警引擎没有报错
```

### Version

夜莺：v5

**Comment by HH17740639615** [comment]
看看n9e的目录下是否存在./.notify_scriptt 的隐藏文件，手动执行看看是否是缺少什么模块

**Comment by 0xMadao** [comment]
> 看看n9e的目录下是否存在./.notify_scriptt 的隐藏文件，手动执行看看是否是缺少什么模块

不是通知模块缺失，是引擎执行的时候，压根没查到数据。HandleVector是空的

**Comment by 710leo** [comment]
@0xMadao v5 版本已经过了维护期限了，可以参考此文档升级到 v7 版本 https://flashcat.cloud/docs/content/flashcat-monitor/nightingale-v7/install/upgrade/
