### ISSUE TITLE
夜莺使用调研，为什么突然嵌入这个链接，该怎么取消啊？

### ISSUE THREAD

**Issue by qianjiso** [ccfos/nightingale#2133]
### Question and Steps to reproduce

为什么右下角突然嵌入了一个按钮，是不是有后门代码啊？该怎么取消啊？

### Relevant logs and configurations

```text
无
```

### Version

版本 7.3.1

**Comment by 710leo** [comment]
增加调研入口是为了让用户更方便的提反馈建议，并不是后门
