### ISSUE TITLE
告警规则是否可以支持ES的报警

### ISSUE THREAD

**Issue by CHAIQ** [ccfos/nightingale#2141]
夜莺报警规则的数据源类型是否可以增加对ES的查询报警呢？有一些业务错误日志提交到ES，通过夜莺的告警规则页面输入ES查询条件等检索到一些数据发送报警通知

**Comment by UlricQin** [comment]
这是商业版的功能，开源版本暂未提供，后面我们会考虑是否把这个功能下放到开源版本。在还未下放之前，你可以使用 Flashduty 做日志告警，那个有免费套餐。
