### ISSUE TITLE
新版本对nginx监控采集缺失

### ISSUE THREAD

**Issue by adminshun** [ccfos/nightingale#2152]
### Question and Steps to reproduce

在对客户端安装nginx_exporter，并打开nginx_status模块，但在web端数据源中并没有检测到nginx的采集指数

### Relevant logs and configurations

```text
none
```

### Version

v7.3.1   CentOS Linux 7

**Comment by UlricQin** [comment]
夜莺不提供采集能力，只是查询tsdb中的数据，你要确保时序库中有数据。采集数据可以选择各类exporter，categraf，telegraf等等采集器都可以。只要数据进入时序库了，夜莺就可以看图告警，如果时序库里没数据，夜莺也无能为力。




秦晓辉
***@***.***

快猫星云
联合创始人
18612185520



------------------ 原始邮件 ------------------
发件人: adminshun ***@***.***&gt;
发送时间: 2024年9月7日 11:56
收件人: ccfos/nightingale ***@***.***&gt;
抄送: Subscribed ***@***.***&gt;
主题: Re: [ccfos/nightingale] 新版本对nginx监控采集缺失 (Issue #2152)





 
Question and Steps to reproduce
 
在对客户端安装nginx_exporter，并打开nginx_status模块，但在web端数据源中并没有检测到nginx的采集指数
 
Relevant logs and configurations
 none  
Version
 
v7.3.1   CentOS Linux 7

**Comment by adminshun** [comment]
夜莺的web端显示的nginx的指标类型只有nginx-up,别的指标类型都没有了，prometheus的配置是没有问题的

**Comment by UlricQin** [comment]
你去Prom里查查有没有ngx相关指标先




秦晓辉
***@***.***

快猫星云
联合创始人
18612185520



------------------ 原始邮件 ------------------
发件人: adminshun ***@***.***&gt;
发送时间: 2024年9月7日 16:47
收件人: ccfos/nightingale ***@***.***&gt;
抄送: ulricqin ***@***.***&gt;, Comment ***@***.***&gt;
主题: Re: [ccfos/nightingale] 新版本对nginx监控采集缺失 (Issue #2152)
