### ISSUE TITLE
Categraf 提供的http_response 插件问题反馈

### ISSUE THREAD

**Issue by l19891223j** [ccfos/nightingale#2155]
> * 方案1：使用 Categraf 提供的http_response 插件： https://github.com/flashcatcloud/categraf/tree/main/inputs/http_response
> * 方案2：使用 Flashcat 提供的网络拨测功能：[https://flashcat.cloud/docs/content/flashcat-monitor/n9e-pro/highlights/#拨测](https://flashcat.cloud/docs/content/flashcat-monitor/n9e-pro/highlights/#%E6%8B%A8%E6%B5%8B)

我这边遇到的问题是：
![图片](https://github.com/user-attachments/assets/a6de0336-84b9-402f-883b-8a06116a70ee)

接口监控告警用的categraf，使用钉钉webhook机器人，正常的url ，推送正常，如下：
![图片](https://github.com/user-attachments/assets/93283dfd-d58e-4cc9-a6e9-9802acb09dc9)
而加了传参的? = 的url，推送异常，不显示接口地址
![图片](https://github.com/user-attachments/assets/c96d2cd5-231d-44c1-a2f6-37708a95a1f5)

_Originally posted by @l19891223j in https://github.com/ccfos/nightingale/issues/1923#issuecomment-2337036528_

**Comment by UlricQin** [comment]
你的告警规则里的 promql 是怎么写的？其次你的其他通知媒介，比如短信、邮件的内容是否正常？如果其他通知媒介正常，那就是钉钉做了限制。

**Comment by l19891223j** [comment]
> 你的告警规则里的 promql 是怎么写的？其次你的其他通知媒介，比如短信、邮件的内容是否正常？如果其他通知媒介正常，那就是钉钉做了限制。

告警规则：
http_response_result_code{product="管理平台"} != 0
目前只试了钉钉的，我换个邮件媒介验证试试，多谢了

**Comment by l19891223j** [comment]
![图片](https://github.com/user-attachments/assets/bb79eb35-0f9a-4073-ae67-776585ae14a5)
通过python request检测的告警推送到钉钉群，是没有问题的

**Comment by l19891223j** [comment]
补充： 
告警规则
![图片](https://github.com/user-attachments/assets/c3d2620b-9d46-465c-9651-03265011df35)

从历史告警上看，这个target url 确实没有获取到：
![图片](https://github.com/user-attachments/assets/d54fd0f0-a0fe-4e7b-b3c7-267106b1cd12)
@UlricQin

**Comment by l19891223j** [comment]
**注：** 升级到最新的7.3.4 版本后，告警已经正常，但是告警恢复还是显示不出target
![588B84B2-1DE5-4653-AD4E-0C8C5A6D01AA](https://github.com/user-attachments/assets/21f9e688-a11d-48f8-9fef-f671fbce758e)
告警恢复不显示taget：
![AD2E3A77-41EB-4292-8F0B-B0F1666D6DFE](https://github.com/user-attachments/assets/0aeb2c84-7a3a-49d1-9628-9239e02050df)

邮件同样的问题
![图片](https://github.com/user-attachments/assets/db04f893-fb67-40ae-bc4f-8382d7983947)

**Comment by 710leo** [comment]
@l19891223j 这个问题最新版本已经修复了，可以升级下
