### ISSUE TITLE
BUG - 告警通知偶发性乱发

### ISSUE THREAD

**Issue by njqaaa** [ccfos/nightingale#2156]
### Question and Steps to reproduce

现象：告警详情中显示发送至webhook A，实际告警发送至了webhook B。
1. 通过告警详情的通知记录得出，告警发送的目标机器人与实际接收告警的机器人webhook是不一致的。 此处疑问：通知记录当前的用途仅仅是把告警通知组对应的webhook展现出来，有价值，但不多，尤其是我现在这种乱发的情况。
2. 告警创建/更新时间为 2024-09-06 12:24:05
![image](https://github.com/user-attachments/assets/e42197a3-5720-43cb-83b7-5dd9f86cca7c)
3. 20:13分的告警发送至错误群，21:25的告警发送至正确群。
4. 通知记录显示发送至https://open.feishu.cn/open-apis/bot/v2/hook/5e481a86-ce54-4831-9493-114b********与
https://open.feishu.cn/open-apis/bot/v2/hook/0177dc88-baf6-478f-bf6a-180d********，实际发送告警发送至https://open.feishu.cn/open-apis/bot/v2/hook/cb4d3aef-038f-4e05-9399-*********

此告警错误接收群（告警记录）
![image](https://github.com/user-attachments/assets/5c8a0e24-d7cd-4015-885d-9ec322f8bbe1)
此告警错误接收群webhook1
![image](https://github.com/user-attachments/assets/92398732-2bea-4fb4-b634-99e16eaeb757)
此告警错误接收群webhook2
![image](https://github.com/user-attachments/assets/a14e0edd-1099-4d9f-9553-bb90c2dabe5d)

此告警期望接收群（告警记录）
![image](https://github.com/user-attachments/assets/31e6ed2f-99a3-4086-963b-acb60284021f)
此告警期望接收群webhook1
![image](https://github.com/user-attachments/assets/a37ad6e8-1899-4135-bdf0-01ab33fc8a81)

夜莺告警详情
![image](https://github.com/user-attachments/assets/822f31e0-e5f2-418c-80e7-a9da8bcf5c17)
夜莺告警详情的通知记录
![image](https://github.com/user-attachments/assets/d12c36f4-de04-49cb-96d8-2680bae2a76c)

### Relevant logs and configurations

```text
当前属于偶发现象，什么情况会出现该问题？
```

### Version

7.3.1

**Comment by 710leo** [comment]
<img width="175" alt="image" src="https://github.com/user-attachments/assets/448c86a5-b874-4bab-bf6f-f566285a4263">   

@njqaaa 可以检查下，这个接收组中的人，是否配置了其他的token

**Comment by njqaaa** [comment]
@710leo 重新梳理了信息，帮忙看下

**Comment by njqaaa** [comment]
@UlricQin 大佬帮忙看下，是7.3.1的bug吗

**Comment by UlricQin** [comment]
理论上不会有这样的bug，如果有的话社区这么多用户也应该遇到了。你还需要再检查一下配置。另外可以再搞个钉钉机器人做对比测试。

**Comment by njqaaa** [comment]
> 理论上不会有这样的bug，如果有的话社区这么多用户也应该遇到了。你还需要再检查一下配置。另外可以再搞个钉钉机器人做对比测试。

我有十几个群，都遇到了这问题，每天总有几个告警发错群。
并且我这里严格控制P1和P2的，P1群里不可能出现P2告警。
另外如图，每个告警都有快捷方式跳转至告警详情页，详情页显示的通知token是正确的，但偶发会发错群

**Comment by njqaaa** [comment]
补充下，当前未使用告警订阅能力，所有的告警渠道都是ruleid直接控制

**Comment by njqaaa** [comment]
异常日志
![img_v3_02en_1f10b214-b693-4a40-9d41-141056f228ag](https://github.com/user-attachments/assets/87c0e7cf-b0ad-46c2-b6cc-b0ee0e5c6f4a)

feishucard模版- 获取ruleid以及alertid
![image](https://github.com/user-attachments/assets/c42b7a94-6c1f-45af-a04c-ed72b253bc77)

异常日志时间对应的上下文告警（关键字1）
![image](https://github.com/user-attachments/assets/a547990d-87a1-4357-8ec3-d25f5a8484d9)
异常日志时间对应的上下文告警（关键字2）
![image](https://github.com/user-attachments/assets/c5a9f112-fa62-4c8d-abc5-f9ca4dbc1c35)

ruleid对应的通知渠道
![image](https://github.com/user-attachments/assets/775bfa0c-0e4c-47c8-a23b-073ab2a6408d)

ruleid对应的告警规则
![image](https://github.com/user-attachments/assets/1ae77bbd-5d8f-48ea-b1ab-d85f63622b2c)



问题：
日志中体现了 1条告警中同时存在了2个的alertname，且alertname可能不同，这是哪里配置有问题而导致的吗？ 如何调整？

@UlricQin 请大佬解惑

**Comment by UlricQin** [comment]
仅凭这些打码的零散的截图看不出来啥。上次我说你配置个单独的钉钉机器人做对比，钉钉那边是否正常？如果没有配置订阅规则，只会看两个配置相关，一个是回调地址，一个是告警接收组：
1，如果回调地址是指向了一个飞书、钉钉、企微的机器人，那告警的时候无论如何都会发到这个机器人
2，如果告警接收组对应的人员的联系方式中包含飞书的token，那这些token对应的机器人，也会收到告警

**Comment by njqaaa** [comment]
@UlricQin 
你提出的偶发性时间的观点我是认可的。 之所以会使用”偶发性“，主要是没有去深入排查异常信息时刻的周边信息。

验证结果：钉钉未复现，飞书复现。

测试方式：
1. 新建2条告警规则，ruleid分别为2和6。 
2. 每条ruleid的通知媒介都选择了 feishucard以及dingTalk。 
3. 新建虚拟用户P1与P2，各自绑定飞书 token 与钉钉 token。
4. 新建团队P1与P2，P1绑定虚拟用户P1，P2绑定虚拟用户P2。

测试方式如下：
![image](https://github.com/user-attachments/assets/642c8646-3149-4903-8077-bebf9a2442bf)
![image](https://github.com/user-attachments/assets/109db35b-086d-4797-82cc-8ef4003f7573)

![image](https://github.com/user-attachments/assets/f1f00b9d-0a2f-4ae2-a9b1-ec193a8c9394)
![image](https://github.com/user-attachments/assets/14d8c2b0-b994-47a4-94da-6be7afb1a85e)


异常截图如下（飞书异常的2条消息，在钉钉中是满足预期的）：
<img width="1151" alt="image" src="https://github.com/user-attachments/assets/2898c865-2540-4445-a911-3f800cd70f81">
<img width="1152" alt="image" src="https://github.com/user-attachments/assets/96c10d3d-8ad2-4d7c-96fe-b419efa96bef">
<img width="1137" alt="image" src="https://github.com/user-attachments/assets/0bf74e4f-6ee2-4678-84bc-00964ca38621">
<img width="1112" alt="image" src="https://github.com/user-attachments/assets/22fa5fc3-f046-4243-a8e6-73398ebdf525">
<img width="1108" alt="image" src="https://github.com/user-attachments/assets/0a254999-1847-46e7-80f2-64e705fef265">


是否还需要其他信息补充？

**Comment by njqaaa** [comment]
异常通知主要如下情况
1. 明确为P2的告警发往了P1群
2. 告警标题与ruleName不一致

<img width="722" alt="image" src="https://github.com/user-attachments/assets/8db66b03-b78e-41e2-83e5-d048df0ae3bb">
<img width="746" alt="image" src="https://github.com/user-attachments/assets/9b3a51f1-88a6-4a60-b635-a881df5e6808">
<img width="762" alt="image" src="https://github.com/user-attachments/assets/1aec04fc-ce1a-4db2-82ab-b772ac358252">

通知模版：
![image](https://github.com/user-attachments/assets/71816a32-2d7f-4295-af22-b34860bc9e31)
![image](https://github.com/user-attachments/assets/711a8199-8434-4fa9-94f4-6437a9776468)

**Comment by UlricQin** [comment]
这些信息可以了，我让研发看一下

**Comment by 710leo** [comment]
@njqaaa 感想反馈，最新版本这个问题修复了，可以升级下

**Comment by njqaaa** [comment]
> @njqaaa 感想反馈，最新版本这个问题修复了，可以升级下

高效 👍🏻 

今天下午升级到7.4.1了，后续观察下，有问题再反馈。
