### ISSUE TITLE
target_miss 会报警不存在的机器

### ISSUE THREAD

**Issue by rayn316** [ccfos/nightingale#2157]
### Question and Steps to reproduce

经过
1. 主机名为validator-hk-lido-1的服务器改名后，重启了categraf, categraf会自动应用新主机名
2. 机器列表中也有新主机名，就把旧主机名的主机删除，并且机器列表中没有这个旧主机名称
3. 但是target_miss出现bug，会一直提示旧主机(validator-hk-lido-1)无法连接
4. 在查看机器列表没有这个主机名

尝试
1. 将其它服务器改为此名称，在夜莺机器列表中出现此名字后关闭categraf，然后删除此机器，过会告警会继续（失败）
2. 清空机器列表所有机器，确定没有任何机器了，然后让categraf接入（失败）

### Relevant logs and configurations

```text
告警内容

__name__ == target_miss
ident == validator-hk-lido-1
rulename == 无法连接categraf
user_group == 服务器
```
```


### Version

最开始安装时版本: v7.0.0-beta.13
后面升级到最新版本: v7.3.4

**Comment by 710leo** [comment]
可以贴一下相关的现场截图

**Comment by rayn316** [comment]
有报警，但是搜索不到
<img width="950" alt="image" src="https://github.com/user-attachments/assets/11f1e7ec-d779-40a8-bd22-4bfd4fb18088">
<img width="1148" alt="image" src="https://github.com/user-attachments/assets/76a6f323-9e39-437d-8b02-26a0e9ccc93d">

**Comment by rayn316** [comment]
我说怎么一直搜不到，跑到未归组机器里面了
