### ISSUE TITLE
机器台账表格视图中的机器列表点击详情404

### ISSUE THREAD

**Issue by showsmall** [ccfos/nightingale#2159]
### Question and Steps to reproduce

如下图：点击机器台账表格视图中的机器列表”详情“404
![image](https://github.com/user-attachments/assets/cfb186bb-216c-48c6-a0d9-90cd69f59463)
![image](https://github.com/user-attachments/assets/1acfec91-7857-402e-a038-662700e561b2)

### Relevant logs and configurations

```text
无，前端页面404
```

### Version

前端版本：v7.3.2
后端版本：v7.3.4-037152ad7206c926a327713283aceff1d4327ecf

**Comment by 710leo** [comment]
内置仪表盘放到模版中心之后，内置的机器详情仪表盘的地址发生了变化，可以编辑下表格图表，重新修改下表格中的链接

**Comment by showsmall** [comment]
> 内置仪表盘放到模版中心之后，内置的机器详情仪表盘的地址发生了变化，可以编辑下表格图表，重新修改下表格中的链接

![image](https://github.com/user-attachments/assets/3a7540f7-aa43-471b-be52-1289753ea479)
/dashboards-built-in/detail?__built-in-cate=Linux&__built-in-name=Linux%20Host%20by%20Categraf%20v2&ident=${__field.labels.ident}   请教您一下，这个地址应该怎么改呢？

**Comment by UlricQin** [comment]
可以尝试改成这个：/built-in-components/dashboard/detail?id=8849&ident=${__field.labels.ident} 这里的 `id=8849` 对应`集成中心-模板中心`里的Linux类别下的Linux Host by Categraf v2仪表盘。但是我的环境里这个仪表盘的id是8849，你的就未必了，你需要去`集成中心-模板中心`里找到Linux类别下的Linux Host by Categraf v2仪表盘，打开，看看url里的id是多少，对应的填在这里。

后面我们会想办法搞一个不变的唯一标识，来解决这类问题。
