### ISSUE TITLE
n9e-edge 边缘机房的数据源添加不成功

### ISSUE THREAD

**Issue by xutengfei0929** [ccfos/nightingale#2161]
<img width="749" alt="image" src="https://github.com/user-attachments/assets/3d71b118-b724-4a39-ac67-7cd52effb38b">

根据这个架构图，中心机房的 n9e 应该不需要连边缘机房的 prometheus ，但是我看文档 https://flashcat.cloud/docs/content/flashcat-monitor/nightingale-v7/install/edge/
<img width="844" alt="image" src="https://github.com/user-attachments/assets/f858c321-bdb7-47e0-a3af-69c31e1f1784">
 
这个意思是要在中心机房添加边缘机房的promethus，那岂不是要和边缘机房的promethus通信吗，如果网络不通的话是添加不成功的

**Comment by UlricQin** [comment]
是在中心添加。
如果想在中心端查询边缘TSDB的数据，那就需要通。
如果跟中心不通，只是希望能告警，那中心能否连通边缘TSDB就都无所谓了。但是，添加数据源还是要添加的，而且添加的时候会校验连通性，对于这种不连通但是仍然想添加的情况，目前的版本，可以写个假的能通的地址，然后在时序库内网地址那里配置真实的地址即可。后面我们会优化一下，即便不通也可以添加。
