### ISSUE TITLE
iframe内嵌grafana图表失败

### ISSUE THREAD

**Issue by Sailias666** [ccfos/nightingale#2167]
### Question and Steps to reproduce

添加 iframe 内嵌 grafana 的监控图，链接可以正常访问，但是图表报错了
![65868ccc5995073498dc700ee75b090](https://github.com/user-attachments/assets/6ed83c24-3b58-4359-88ef-d141611c4bb2)

### Relevant logs and configurations

```text
无效的数据源
```

### Version

v6.1.0

**Comment by jsers** [comment]
升级到最新版本已经修复该问题

**Comment by Sailias666** [comment]
好的，我先尝试一下，谢谢，有升级文档吗？目前版本是v6.1.0
