### ISSUE TITLE
边缘机房部署，中心机房没有边缘机房的机器列表显示

### ISSUE THREAD

**Issue by ghqzsong** [ccfos/nightingale#2177]
### Question and Steps to reproduce

<img width="848" alt="image" src="https://github.com/user-attachments/assets/db9deb1b-4cd2-4572-8c17-02d9dd155074">

### Relevant logs and configurations

```text
边缘机房接入：如图中region01的架构，边缘机房已增加了redis，现在vm中能正常得到categraf的数据，edge和中心机房也能正常通信，edge的告警引擎也能在中心机房看到，中心机房在增加了边缘机房的vm数据源之后，也可以查询监控数据

问题：n9e的web界面，机器列表，没有边缘机房的机器信息

错误日志：edge有错误日志，ERROR idents/idents.go:88 failed to update targets: unexpected status code: 401
```

### Version

n9e-v7.3.4
categraf-v0.3.78
victoria-metrics-linux-amd64-v1.103.0

**Comment by ghqzsong** [comment]
<img width="892" alt="image" src="https://github.com/user-attachments/assets/c123bbf4-5a1b-4e35-8d8d-889faa33c73d">
数据库中的target表，也没有边缘机房机器的信息

**Comment by ghqzsong** [comment]
n9e和n9e-edge配置文件的APIForService\ APIForAgent注释掉后，在n9e的web界面，可以看到edge机房的机器了

**Comment by 710leo** [comment]
@ghqzsong 最新版本这个问题已经修复了，可以升级到最新版本，注意 n9e-edge 和 n9e 中心模块需要一起升级

**Comment by ghqzsong** [comment]
好的👍
