### ISSUE TITLE
a-n9e-for-Postgres.sql 新版本Postgresql建表语句缺失

### ISSUE THREAD

**Issue by 751329612** [ccfos/nightingale#2188]
### Question and Steps to reproduce

builtin_payloads的component_id字段在Postgresql的sql文件中并不存在，是否还有其他字段也未有提交

### Relevant logs and configurations

```text
无
```

### Version

v7.0.0  postgres

**Comment by 710leo** [comment]
@751329612 可以参考 https://github.com/ccfos/nightingale/blob/main/docker/migratesql/migrate.sql 这个 mysql 的表结构修改语句，手动修改下 pg 的表结构
