### ISSUE TITLE
postgres数据库自定义sql监控

### ISSUE THREAD

**Issue by 352140532** [ccfos/nightingale#2192]
[[instances.metrics]]
 mesurement = "sessions"
 label_fields = [ "status", "type" ]
metric_fields = [ "value" ]
timeout = "3s"
request = '''
SELECT status, type, COUNT(*) as value FROM v$session GROUP BY status, type

请问下我自定义了一个查询，写到时序里面的数据标签里面没有outputaddress或者跟数据库相关的标识，请问该怎么才能加上。标签上只有busigroup跟ident，categraf运行不在数据库主机上。

**Comment by 352140532** [comment]
1

**Comment by UlricQin** [comment]
采集问题把 issue 提到 github.com/flashcatcloud/categraf 哈，提 issue 的时候，贴一下 `./categraf --test --inputs postgresql` 测试这个 postgresql 插件的 output
