### ISSUE TITLE
能否通过alertmanager触发的webhook，让 nightingale 配置的告警通道发出告警？

### ISSUE THREAD

**Issue by zhuchubo** [ccfos/nightingale#2193]
### Question and Steps to reproduce

helmCharts: nightingale-0.2.8
appVersion: 7.3.4
能否通过alertmanager触发的webhook，让 nightingale 配置的告警通道发出告警？因为 Prometheus 有一些自定义的 Prometehus 通过 Alertmanger 触发 webhook 进行告警发送，如果 webhook 可以通过 nightingale 的 api 进行告警分发，并记录告警日志。 我就可以把 nightingale 作为全公司的告警分发中心。

### Relevant logs and configurations

```text
能否通过alertmanager触发的webhook，让 nightingale 配置的告警通道发出告警？
```

### Version

7.3.4

**Comment by UlricQin** [comment]
无法做到。现在的设计是期望大家把Flashduty作为全公司的告警分发平台，无论是夜莺还是alertmanager还是zabbix还是各类云监控，全部接入Flashduty是最佳实践。




秦晓辉
***@***.***

快猫星云
联合创始人
18612185520



------------------ 原始邮件 ------------------
发件人: zhuchubo ***@***.***&gt;
发送时间: 2024年9月25日 13:41
收件人: ccfos/nightingale ***@***.***&gt;
抄送: Subscribed ***@***.***&gt;
主题: Re: [ccfos/nightingale] 能否通过alertmanager触发的webhook，让 nightingale 配置的告警通道发出告警？ (Issue #2193)

**Comment by zhuchubo** [comment]
感谢回复，如果期望可以使用 PrometehusRules 资源预设的告警规则，也是通过 webhook 接入 Flashduty 吗？

**Comment by UlricQin** [comment]
没懂你的意思。prometheus还是要搭配alertmanager的，alertmanager通过webhook调用Flashduty推事件




秦晓辉
***@***.***

快猫星云
联合创始人
18612185520



------------------ 原始邮件 ------------------
发件人: zhuchubo ***@***.***&gt;
发送时间: 2024年9月25日 14:25
收件人: ccfos/nightingale ***@***.***&gt;
抄送: ulricqin ***@***.***&gt;, Comment ***@***.***&gt;
主题: Re: [ccfos/nightingale] 能否通过alertmanager触发的webhook，让 nightingale 配置的告警通道发出告警？ (Issue #2193)

**Comment by zhuchubo** [comment]
明白了。我的使用场景里，只有 Prometehus-operator + n9e , 还有一些存量的告警规则是 PrometheusRules 资源。这么看，还是将 PrometheusRules 资源修改成 n9e 告警规则吧。谢谢！
