### ISSUE TITLE
v7.4.1 两个小瑕疵

### ISSUE THREAD

**Issue by wsfnk** [ccfos/nightingale#2194]
### Question and Steps to reproduce

version：v7.4.1-amd64 二进制模式部署
瑕疵1、机器列表>（用户标签 和 机器标签 处，机器标签并不会直接展示 categraf globle_labels 的标签）
瑕疵2、将机器更改 业务组时，输入栏 无法对业务组进行检索，如下图
![image](https://github.com/user-attachments/assets/978fa0a1-72a2-42e2-95a0-0d962c208026)
![image](https://github.com/user-attachments/assets/1a0afd27-4783-496c-9b1c-26525bb93e23)

### Relevant logs and configurations

```text
version：v7.4.1-amd64 二进制模式部署
```

### Version

version：v7.4.1-amd64 二进制模式部署

**Comment by 710leo** [comment]
@wsfnk 
第1点，categraf 下一个版本会支持
第2点，下一次发版会支持检索

**Comment by wsfnk** [comment]
好嘞
