### ISSUE TITLE
请对上报的消息（尤其是JSON格式）做编码处理

### ISSUE THREAD

**Issue by victoryxing126** [ccfos/nightingale#2222]
### Question and Steps to reproduce

请对上报的消息（尤其是JSON格式）做编码操作；比如转成STRING、然后Base64Encode一下；服务端在拿到数据后再Base64Decode；否则会被WAF等安防产品拦截，处理起来很麻烦

### Relevant logs and configurations

```text
请对上报的消息（尤其是JSON格式）做编码操作；比如转成STRING、然后Base64Encode一下；服务端在拿到数据后再Base64Decode；否则会被WAF等安防产品拦截，处理起来很麻烦
```

### Version

请对上报的消息（尤其是JSON格式）做编码操作；比如转成STRING、然后Base64Encode一下；服务端在拿到数据后再Base64Decode；否则会被WAF等安防产品拦截，处理起来很麻烦

**Comment by 710leo** [comment]
@victoryxing126 你这个说的是 categraf 采集器上报的监控数据格式？

**Comment by victoryxing126** [comment]
![image](https://github.com/user-attachments/assets/cfd83012-f808-4e24-be73-262aae053042)
就是类似这种上报请求体；过大的JSON结构会在WAF-LB-NG等网络转发过程中发生不可预知的错误。你们可以调研下神策、顶象等埋点上报交互时的数据结构。
