### ISSUE TITLE
反馈一个关于告警规则-规则配置的BUG

### ISSUE THREAD

**Issue by 13310241314** [ccfos/nightingale#2232]
### Question and Steps to reproduce

我在使用夜莺7.4.1以及7.5版本进行告警规则配置，在使用内置的“内存利用率比较高”该项告警规则时，尝试进行修改，发生了以下BUG信息。
在规则配置栏内，尝试利用Host进行主机或者业务组进行排除时，发现点击host按钮后会
导致metirc已经保存的告警规则丢失。导致metric和host无法共存，请问该现象是设计如此还是一个BUG呢，非常感谢。
![微信截图_20241022165113](https://github.com/user-attachments/assets/15a73bf1-421b-430b-b9b4-cf1b137f0fdc)

### Relevant logs and configurations

```text
暂无错误日志
```

### Version

7.4.1  and 7.5.0

**Comment by UlricQin** [comment]
这个是目前的设计如此

**Comment by 13310241314** [comment]
> 这个是目前的设计如此

那这样的话，如何实现对一个host的规则或者排除呢？

**Comment by UlricQin** [comment]
Prometheus 生态里，都是通过标签过滤，这需要你学习一下 promql 了。之前我写过几篇教程可以参考：https://flashcat.cloud/tags/promql/ 。后面夜莺会支持使用业务组来过滤机器，相当于脱离了 Prometheus 生态的玩法，估计年底或明年年初下放给开源版本

**Comment by 13310241314** [comment]
> Prometheus 生态里，都是通过标签过滤，这需要你学习一下 promql 了。之前我写过几篇教程可以参考：https://flashcat.cloud/tags/promql/ 。后面夜莺会支持使用业务组来过滤机器，相当于脱离了 Prometheus 生态的玩法，估计年底或明年年初下放给开源版本

明白了，感谢
