### ISSUE TITLE
支持 Prometheus 结果作为告警回调地址中的变量

### ISSUE THREAD

**Issue by monchcc** [ccfos/nightingale#2238]
# 支持 Prometheus 结果作为告警回调地址中的变量
在生产环境中，我们希望通过告警回调地址中使用变量来支持不同应用的定制化需求。变量的来源可以从 Prometheus 监控指标的查询结果中获得，这样可以实现对不同告警场景的灵活处理。

### 需求描述

当前的告警回调地址是静态的，无法动态适应不同应用的告警需求。我们希望在回调地址中能够引入变量，并且这些变量能够从 Prometheus 监控指标的结果中动态获取，从而实现以下功能：

基于 Prometheus 查询的监控结果，在告警回调时自动生成不同的告警地址。
支持自定义 Prometheus 查询语句，能够灵活提取所需监控指标。
对于不同的应用场景，可以根据具体的监控需求，自行定义不同的回调地址模式。

<img width="1220" alt="image" src="https://github.com/user-attachments/assets/284df8c6-fa9c-43b6-9100-83322b530f29">

**Comment by monchcc** [comment]
您发的是模版内容已经支持了变量，我这里提的需求是希望能够在http query上支持变量。

**Comment by monchcc** [comment]
> 这个功能在这个 PR #2001 已经支持了，如果是 [v7.0.0-beta.12](https://github.com/ccfos/nightingale/releases/tag/v7.0.0-beta.12) 之前的版本，升级下就可以了，在回调地址中配置变量的用法，可以参考这个文档 https://flashcat.cloud/docs/content/flashcat-monitor/nightingale-v6/faq/go-template/

您发的是模版内容已经支持了变量，我这里提的需求是希望能够在http query上支持变量。

**Comment by UlricQin** [comment]
> > 这个功能在这个 PR #2001 已经支持了，如果是 [v7.0.0-beta.12](https://github.com/ccfos/nightingale/releases/tag/v7.0.0-beta.12) 之前的版本，升级下就可以了，在回调地址中配置变量的用法，可以参考这个文档 https://flashcat.cloud/docs/content/flashcat-monitor/nightingale-v6/faq/go-template/
> 
> 您发的是模版内容已经支持了变量，我这里提的需求是希望能够在http query上支持变量。

一样的，都支持。`{{$labels.xxxx}}`
