### ISSUE TITLE
夜莺界面上怎么不支持绑定业务组标签了？

### ISSUE THREAD

**Issue by masterzht** [ccfos/nightingale#2249]
### Question and Steps to reproduce

之前机器列表是可以绑定业务组添加标签的，现在怎么没这个按钮了，我看现在是支持机器列表绑定多业务组了啊，是前端逻辑还没有设计好吗？

### Relevant logs and configurations

```text
无
```

### Version

v7.5.0

**Comment by UlricQin** [comment]
有意为之。业务组标签要附到机器上，如果机器挂到A和B两个业务组，意味着，机器要同时打上 busigroup=A 和 busigroup=B 的标签，但是 Prometheus 生态里是不允许同 key 标签的，所以这样做不被允许。

所以，新的方式下，机器如果想打 busigroup 这样的标签，只能手工打在特定的机器上了。业务组自动关联 busigroup 标签的逻辑下掉了。
