### ISSUE TITLE
告警规则不勾选告警接收组时，在订阅规则中配置告警接收组发送通知失败

### ISSUE THREAD

**Issue by sunyum** [ccfos/nightingale#2264]
### Question and Steps to reproduce

1. 创建一个告警规则不勾选告警接收组
2. 创建一个订阅规则，勾选告警接收组并指定指定钉钉通知
3. 此时告警触发后错误如下 Client.Timeout exceeded while awaiting headers
![image](https://github.com/user-attachments/assets/5bbc920e-c521-412f-9b77-428975f4a37e)

### Relevant logs and configurations

```text
无
```

### Version

7.6.0

**Comment by UlricQin** [comment]
大概率是你的网络问题，可以手工 curl 钉钉的 url 做测试

**Comment by sunyum** [comment]
不是网络的问题。 
1. 告警规则配置接收组后，告警规则和订阅规则的通知就都会发送
2. 告警规则接收组配置一个错误的钉钉hook，则告警规则通知失败，订阅规则通知发送成功

**Comment by UlricQin** [comment]
那个报错很明显，就是超时了，跟是否在告警规则中勾选业务组无关。

**Comment by sunyum** [comment]
> 那个报错很明显，就是超时了，跟是否在告警规则中勾选业务组无关。

那为什么告警规则勾选告警组后，就能通知成功呢？ 这个超时的错误只会出现在告警规则不勾选告警组时

**Comment by UlricQin** [comment]
> > 那个报错很明显，就是超时了，跟是否在告警规则中勾选业务组无关。
> 
> 那为什么告警规则勾选告警组后，就能通知成功呢？ 这个超时的错误只会出现在告警规则不勾选告警组时

我不勾选，仍然可以发，勾选了，也可以发。从原理上分析这是完全不相干的。

**Comment by UlricQin** [comment]
如果告警规则里配置了接收组，也配置了订阅，一切正常。如果告警规则没有选接收组，订阅规则里写了接收人也收不到，这是个问题，现象是通知详情里直接就是空的，这个需要看看 @710leo 
无论如何我都没有测试出超时，client.Timeout 99% 都是网络问题，超时跟产品逻辑无关 @sunyum

**Comment by sunyum** [comment]
离谱
