### ISSUE TITLE
全新环境最新版本v7.6 登录页面报错，不能正常打开登录页面

### ISSUE THREAD

**Issue by showsmall** [ccfos/nightingale#2272]
### Question and Steps to reproduce

antdChunk.a14eb74f.js:21 Uncaught ReferenceError: globalThis is not defined
    at antdChunk.a14eb74f.js:21

浏览器版本：版本 70.0.3538.110（正式版本） （32 位）

### Relevant logs and configurations

```text
antdChunk.a14eb74f.js:21 Uncaught ReferenceError: globalThis is not defined
    at antdChunk.a14eb74f.js:21

浏览器版本：版本 70.0.3538.110（正式版本） （32 位）
```

### Version

v7.6

**Comment by jsers** [comment]
未能复现这个问题，可能是浏览器版本太低导致，70 是6年前的版本了，建议升级后看下
