### ISSUE TITLE
v7小版本之间升级操作

### ISSUE THREAD

**Issue by showsmall** [ccfos/nightingale#2275]
### Question and Steps to reproduce

v7小版本之间升级操作是否为程序自动处理表结构的变化？

### Relevant logs and configurations

```text
v7小版本之间升级操作是否为程序自动处理表结构的变化？
```

### Version

v7小版本之间升级操作是否为程序自动处理表结构的变化？

**Comment by 710leo** [comment]
@showsmall v7 小版本升级的时候，会自动处理表结构的变化
