### ISSUE TITLE
建议 - 实现带图片的飞书报警通知

### ISSUE THREAD

**Issue by njqaaa** [ccfos/nightingale#2281]
期望效果类似下图（展示仅xx分钟该告警的趋势）：
![image](https://github.com/user-attachments/assets/7eb3bb51-1c6e-476b-aa0f-8e7dd1c84ac9)
参考：https://blog.csdn.net/wanger5354/article/details/118977432

开源版是否有计划落地该能力？

**Comment by UlricQin** [comment]
暂无计划~
