### ISSUE TITLE
查询promethues接口连接泄露

### ISSUE THREAD

**Issue by pjlzhy** [ccfos/nightingale#2283]
### Question and Steps to reproduce

添加promethues源后，持续查询，进程占用大量TCP连接
![image-20241113170332888](https://github.com/user-attachments/assets/36b2c25f-4258-43e6-94a0-fc0a6f34b5f1)
![image-20241113170420415](https://github.com/user-attachments/assets/9d2590c6-88e2-42c6-bd31-a46cacf77ef5)

原因是http调用时未close连接
![image-20241113165858256](https://github.com/user-attachments/assets/8179a4fd-fb65-4331-941b-a2c112097fba)

### Relevant logs and configurations

```text
server.go:3197: http: Accept error: accept tcp [::]:9090: accept4: too many open files; retrying in 1s
```

### Version

v7.6.0-04734b894019a6cd0fa348069f5512fea2c6f2e1

**Comment by 710leo** [comment]
@pjlzhy 感谢反馈，这里修复了 https://github.com/ccfos/nightingale/commit/c7117b94615d7751ec23e6fc360763ad0c26535b
