### ISSUE TITLE
升级至7.7版本后，Doris仪表盘找不到

### ISSUE THREAD

**Issue by jackjiali** [ccfos/nightingale#2303]
### Question and Steps to reproduce

7.7更新日志中显示：
doc: 增加 Doris 仪表盘和告警模板

但升级后发现，Doris告警模板是有的，仪表盘列表是空的，找不到。
integrations/Doris/dashboards/Doris_Overview.json 仪表盘文件是存在的，bug望修复。

### Relevant logs and configurations

```text
integrations/Doris/dashboards/Doris_Overview.json 仪表盘文件是存在的
```

### Version

7.7

**Comment by 710leo** [comment]
@jackjiali 之前的模板文件内容有点问题，没导入成功，可以先用这里的文件，手动导入下 https://github.com/ccfos/nightingale/blob/main/integrations/Doris/dashboards/Doris_Overview.json
