### ISSUE TITLE
使用n9e-v7.6.0-linux-amd64.tar.gz安装启动后，看到一条报错信息，不知道会有什么影响。

### ISSUE THREAD

**Issue by blurcat** [ccfos/nightingale#2306]
### Question and Steps to reproduce

 wget https://github.com/ccfos/nightingale/releases/download/v7.6.0/n9e-v7.6.0-linux-amd64.tar.gz
 tar xf n9e-v7.6.0-linux-amd64.tar.gz 
mysql -uroot -p < n9e.sql
nohup ./n9e &> n9e.log &
可以正常启动n9e，也可以正常访问到页面。只是不明白下面这条报错信息会不会潜在未知的错误。求解答。谢谢。

### Relevant logs and configurations

```text
tail -fn100 ERROR.log 使用tail查看到的错误日志内容，只有这一行报错信息，不知道会有什么影响。

2024-11-20 14:59:11.521928 ERROR ormx/ormx.go:67 /home/runner/work/nightingale/nightingale/models/target.go:570 sql: Scan error on column index 0, name "MAX(group_id)": converting NULL to int64 is unsupported
[1.678ms] [rows:1] SELECT MAX(group_id) FROM `target`
```

### Version

--n9e版本
V7.6.0

--使用的安装包
n9e-v7.6.0-linux-amd64.tar.gz

--操作系统
CentOS Linux release 7.9.2009 (Core)

-- 数据库
MariaDB [(none)]> select version();
+----------------+
| version()      |
+----------------+
| 5.5.68-MariaDB |
+----------------+

--CPU架构信息
Architecture:          x86_64
CPU op-mode(s):        32-bit, 64-bit
Byte Order:            Little Endian
CPU(s):                2
On-line CPU(s) list:   0,1
Thread(s) per core:    2
Core(s) per socket:    1
Socket(s):             1
NUMA node(s):          1
Vendor ID:             GenuineIntel
CPU family:            6
Model:                 85
Model name:            Intel Xeon Processor (Cascadelake)
Stepping:              6
CPU MHz:               2494.140
BogoMIPS:              4988.28
Hypervisor vendor:     KVM
Virtualization type:   full
L1d cache:             32K
L1i cache:             32K
L2 cache:              4096K
L3 cache:              16384K
NUMA node0 CPU(s):     0,1
Flags:                 fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ht syscall nx pdpe1gb rdtscp lm constant_tsc rep_good nopl xtopology cpuid tsc_known_freq pni pclmulqdq ssse3 fma cx16 pcid sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xsave avx f16c rdrand hypervisor lahf_lm abm 3dnowprefetch cpuid_fault invpcid_single pti ssbd ibrs ibpb fsgsbase bmi1 hle avx2 smep bmi2 erms invpcid rtm avx512f avx512dq rdseed adx smap clflushopt clwb avx512cd avx512bw avx512vl xsaveopt xsavec xgetbv1 arat pku ospke avx512_vnni

**Comment by UlricQin** [comment]
这个没事，7.7.0 开始应该就没这个 warning 了
