### ISSUE TITLE
夜莺二进制更新后，如何同步更新最新支持的监控模板？

### ISSUE THREAD

**Issue by zhanglangting** [ccfos/nightingale#2310]
### Question and Steps to reproduce

夜莺二进制更新后，如何同步更新最新支持的监控模板到“模板中心”？
比如7.7.0新发布Doris的模板名称、图标、采集说明、指标说明、仪表盘、告警规则这些。
谢谢！！！

### Relevant logs and configurations

```text
无
```

### Version

7.7.0

**Comment by 710leo** [comment]
每次更新，可以同时更新下 n9e 和 integration 目录

**Comment by zhanglangting** [comment]
👍👍👍同步更新 integrations 目录可以添加新监控的 采集说明、告警规则 了。
我在 integrations 目录看到新的 仪表盘 json，但似乎没有自动同步到模板中心，是否需要手动添加？
谢谢！！！

**Comment by UlricQin** [comment]
> 👍👍👍同步更新 integrations 目录可以添加新监控的 采集说明、告警规则 了。 我在 integrations 目录看到新的 仪表盘 json，但似乎没有自动同步到模板中心，是否需要手动添加？ 谢谢！！！

7.7.0 的 Doris 的仪表盘有点问题，用 [7.7.1](https://github.com/ccfos/nightingale/releases/tag/v7.7.1) 版本吧

**Comment by zhanglangting** [comment]
好的，谢谢！
