### ISSUE TITLE
订阅规则&业务组标签

### ISSUE THREAD

**Issue by gpfhaha** [ccfos/nightingale#2316]
版本v7.7.1
1.订阅规则中的订阅业务组不生效，使用标签订阅就是正常的，这是为什么？
![image](https://github.com/user-attachments/assets/3f5704ab-cf8c-4d17-bcf3-a88957c442f4)
是配置的问题，还是哪里的问题。。。。日志也没记录
2.业务组标签的相关功能是不是没有了，移动主机资源到对应业务组，没有办法自动打标了嘛，需要手动打标了么现在
![image](https://github.com/user-attachments/assets/7e91d8e8-686e-4df7-8213-be40ef8ed85e)
原本的业务组标签busigroup变成自定义标签了

**Comment by 710leo** [comment]
@gpfhaha 第 1 点，可以贴下告警事件详情页面截图；第 2 点，可以看下这个文章的说明 https://flashcat.cloud/blog/nightingale-support-multi-group/

**Comment by gpfhaha** [comment]
这是告警事件的详情，都没有看到业务组的信息，事件标签标签busigroup是升级之前的业务组标签

**Comment by 710leo** [comment]
<img width="811" alt="image" src="https://github.com/user-attachments/assets/2f5dd856-a6d4-41b6-b245-9a9234e019e8">
<img width="367" alt="image" src="https://github.com/user-attachments/assets/60120d28-d54e-4387-893e-4dd0cf516e67">


订阅规则这里的业务组，指的是告警规则所属的业务组的名称，不是告警事件中，busigroup 标签的值

**Comment by gpfhaha** [comment]
好的，感谢
