### ISSUE TITLE
告警条件使用变量配置问题

### ISSUE THREAD

**Issue by RockysGit** [ccfos/nightingale#2340]
**What would you like to be added**:
在配置和使用上我个人感觉变量配置应改属于全局，然后每个告警条件可以使用变量筛选对应的value，避免不必要的重复配置。
<img width="1661" alt="image" src="https://github.com/user-attachments/assets/90a9881d-c678-484b-86d0-af3034e197fb">

**Why is this needed**:

**Comment by RockysGit** [comment]
此外，在通过模版导入的时候，希望能够修改变量的值(可能在批量导入时会麻烦一些)。 更大程度上使用变量来提供方便
<img width="1237" alt="image" src="https://github.com/user-attachments/assets/9fceb32f-fa62-41b0-a3dc-9b88c6a4bbc1">

**Comment by 710leo** [comment]
@RockysGit 可以描述下你上述建议的具体的使用场景

**Comment by UlricQin** [comment]
枚举值是个很小众的场景，未来或许可以考虑和全局宏变量打通。这里带变量的告警规则，更多是为了把业务组的筛选能力集成到告警规则里。回头会写个最佳实践。

**Comment by RockysGit** [comment]
> 枚举值是个很小众的场景，未来或许可以考虑和全局宏变量打通。这里带变量的告警规则，更多是为了把业务组的筛选能力集成到告警规则里。回头会写个最佳实践。

好的，如果使用全局宏变量的话应该可以解决现在的问题。 
不仅仅是枚举值，因为我在使用上感觉，如果一个告警规则中是多个告警条件，每个告警条件都是单独的变量，那跟我直接把值写入promQL没什么区别。

**Comment by RockysGit** [comment]
> 此外，在通过模版导入的时候，希望能够修改变量的值(可能在批量导入时会麻烦一些)。 更大程度上使用变量来提供方便 <img alt="image" width="1237" src="https://private-user-images.githubusercontent.com/61232321/393196440-9fceb32f-fa62-41b0-a3dc-9b88c6a4bbc1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzM2NTY2OTQsIm5iZiI6MTczMzY1NjM5NCwicGF0aCI6Ii82MTIzMjMyMS8zOTMxOTY0NDAtOWZjZWIzMmYtZmE2Mi00MWIwLWEzZGMtOWI4OGM2YTRiYmMxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMDglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjA4VDExMTMxNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWY4YTdkMDUwODYyNDYwZDRjNjdkMjk4MjE4OGUyZWMyM2FmMGEyMDAxZDU1MDMzMjgwZjJhODU1YjZjNjRhYzImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.pz-bN9jAT6Oj1PavbQefzjZEW9rr7gVqIpU6cJCYc18">

@710leo https://github.com/ccfos/nightingale/issues/2258参考这个issue，现在beat版正在支持变量，但是在导入模版时还是修改json。因此我想是不是可以在导入模版的时候增加一个修改变量值的选项

**Comment by UlricQin** [comment]
模板变量的初衷并非是为了减少promql中的重复过滤条件（重复内容不是啥太大的问题），回头会写文章介绍这个功能




秦晓辉
***@***.***

快猫星云
联合创始人
18612185520



------------------ 原始邮件 ------------------
发件人: RockysGit ***@***.***&gt;
发送时间: 2024年12月8日 19:20
收件人: ccfos/nightingale ***@***.***&gt;
抄送: ulricqin ***@***.***&gt;, Comment ***@***.***&gt;
主题: Re: [ccfos/nightingale] 告警条件使用变量配置问题 (Issue #2340)





  
此外，在通过模版导入的时候，希望能够修改变量的值(可能在批量导入时会麻烦一些)。 更大程度上使用变量来提供方便 
  
@710leo #2258  参考这个issue，现在beat版正在支持变量，但是在导入模版时还是修改json。因此我想是不是可以在导入模版的时候增加一个修改变量值的选项

**Comment by RockysGit** [comment]
测试并阅读代码后，我想我应该了解这个功能的使用了。非常感谢
