### ISSUE TITLE
官方 v7.7.2 版本的镜像 无法使用sqlite

### ISSUE THREAD

**Issue by yeaze** [ccfos/nightingale#2348]
### Question and Steps to reproduce

下载了官方v7.7.2的镜像，配置文件中数据库改用了sqlite 相关的配置，启动后报错：

应该是使用的sqlite库需要用到CGO，但是镜像中的二进制编译的时候没有开启CGO。
其实可以使用这个库：github.com/glebarez/sqlite  纯go写的，无需cgo 

### Relevant logs and configurations

```text
failed to initialize database, got error Binary was compiled with 'CGO_ENABLED=0', go-sqlite3 requires cgo to work. This is a stub
2024-12-10 18:03:21.630152 DEBUG ormx/ormx.go:69 /home/runner/work/nightingale/nightingale/pkg/ormx/ormx.go:98
```
```


### Version

V7.7.2

**Comment by 710leo** [comment]
@yeaze 感谢反馈，使用了 github.com/glebarez/sqlite，最新版本里，问题已经解决了
