### ISSUE TITLE
告警恢复时回调地址不触发

### ISSUE THREAD

**Issue by 751329612** [ccfos/nightingale#2351]
### Question and Steps to reproduce

问题： 告警恢复时回调地址不触发，偶尔历史告警详情里显示通知渠道但是回调地址也未被调用。

![image](https://github.com/user-attachments/assets/333c55f8-2085-46fd-ae36-9aab891fce87)
![image](https://github.com/user-attachments/assets/5e5f19e5-c34d-4585-ba38-dbaa0dd005ea)

### Relevant logs and configurations

```text
无报错日志
```

### Version

版本：v7.7.2
数据库：瀚高
环境： arm64

**Comment by UlricQin** [comment]
日志里有没有报错

**Comment by 751329612** [comment]
没有报错



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年12月11日(周三) 晚上7:12
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [ccfos/nightingale] 告警恢复时回调地址不触发 (Issue #2351)




 
日志里有没有报错

**Comment by 751329612** [comment]
是categraf的linux指标告警，其他类型的没有尝试

**Comment by 751329612** [comment]
> 日志里有没有报错

刚才又测试了一下，用的v7.0.0-beta.5的版本，功能是正常的，v7.7.2就不行

**Comment by 710leo** [comment]
@751329612  你在日志里 grep 下 webhook 关键字，看看有什么日志输出

**Comment by UlricQin** [comment]
可以试试 v8.beta1 了，发版了

**Comment by 751329612** [comment]
好



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年12月13日(周五) 下午4:07
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [ccfos/nightingale] 告警恢复时回调地址不触发 (Issue #2351)




 
可以试试 v8.beta1 了，发版了

**Comment by 751329612** [comment]
v8.beta.1修复了

**Comment by zzlytq** [comment]
问题怎么解决的那？？
