### ISSUE TITLE
监控JVM，无法屏蔽pid标签（gather_per_pid = false）

### ISSUE THREAD

**Issue by rollingsunn** [ccfos/nightingale#2353]
### Question and Steps to reproduce

插件配置：input.procstat/procstat.toml
gather_per_pid = false
无法屏蔽 jvm 指标的pid 标签，会导致每次重启java进程之后，因为pid发生变化，导致jvm指标图不连贯。
（但是对 cpu、mem等进程信息，是可以屏蔽掉pid标签的）
![Uploading 121212.jpg…]()

### Relevant logs and configurations

```text
[[instances]]
 search_cmdline_substring = "xxx.jar"
 gather_total = true
 gather_per_pid = false
 gather_more_metrics = [
     "threads",
     "fd",
     "io",
     "uptime",
     "cpu",
     "mem",
     "limit",
     "jvm"
 ]
```

### Version

./categraf --version
v0.3.82-d0633717eafc21d8e303f7435454eec7ea6aae9f

**Comment by UlricQin** [comment]
可能是 Categraf 的bug，把这个 issue 提到 github.com/flashcatcloud/categraf 这个 repo 哈
