### ISSUE TITLE
【功能建议】关于仪表盘、告警规则和边缘节点部署的建议

### ISSUE THREAD

**Issue by wadeLouis** [ccfos/nightingale#2374]
### 仪表盘：
1. 建议增加表达式，如grafana的Expression 功能 。这个功能有助于log类型的仪表盘的一些运算。如果不好实现，日志的查询，希望能够开放es的_search API接口的body查询能力。
2. 建议增加transformation 转换功能。

### 告警规则
1. 多条告警组合计算希望能够增加，比如A-B/C等计算 
2. 告警规则导入，建议直接做成接入Prometheus数据源后，能够自动识别alerts列表，并可以选择性导入。

### 边缘节点的部署
建议增加本地缓存，etcd缓存以便替代redis的缓存 。

**Comment by UlricQin** [comment]
拆成多条 issue 讨论哈
