### ISSUE TITLE
新配置的规则，在历史告警种查看，没有触发webhook回调

### ISSUE THREAD

**Issue by Wangyxiang** [ccfos/nightingale#2401]
### Question and Steps to reproduce

我的通知设置中有一个已经启用的回调地址
![image](https://github.com/user-attachments/assets/74b31257-308f-4541-a78e-eef635c2c5bf)

我新增了一个规则，这个规则产生了一个告警，但是我点击通知记录的查看详情并没有看到规则通知记录
![image](https://github.com/user-attachments/assets/3493ad0d-7348-4805-9c92-229bf56f1c5b)

### Relevant logs and configurations

```text
我理解配置了规则，不是应该会往我这个回调中发送消息嘛
还是我哪里的配置有问题
```

### Version

我的n9e版本：v7.6.0

**Comment by 710leo** [comment]
@Wangyxiang 如果是修改规则产生的恢复事件，之前版本不会发出通知，这个在新版本去掉了，可以升级到最新版本

**Comment by Wangyxiang** [comment]
好的，那我遇到的应该就是这个问题，告警是在修改规则之前发出的，告警有触发回调，恢复没有触发回调
