### ISSUE TITLE
订阅规则、屏蔽规则、维护时间等使用问题

### ISSUE THREAD

**Issue by Guwenqiang** [ccfos/nightingale#908]
前端版本：5.1.2
后端版本：5.3.4

1、订阅规则、屏蔽规则：
现状：多个Prometheus时序库接入到n9e中，Prometheus中有很多一样特性的监控指标，这些指标也都是订阅给相同的一批人，目前我如果要配置一个订阅规则对所有Prometheus集群生效，我需要定义多条规则，一对一订阅集群规则
建议：是否可以考虑一条规则支持订阅多个Prometheus集群？屏蔽规则也是一样

2、维护时间：是否可以考虑增加一个类似zabbix维护时间的功能？指定周期性指定时间段内的指定告警静默

**Comment by UlricQin** [comment]
这个我们回头考虑一下，zabbix的屏蔽具体怎么做的？展开说说？也截个图看看？

**Comment by Guwenqiang** [comment]
zabbix是维护时间，如下图
![image](https://user-images.githubusercontent.com/42791612/163507577-ee04a66c-29fd-4a1d-bd93-5f4838da0b60.png)

关于订阅规则和屏蔽规则是基于n8e多集群概念，相关规则只能适用于对应的集群，如果希望一条规则适应多个集群，需要相同规则配置到多个集群内，个人认为这里可以优化

**Comment by isCoding** [comment]
我也有类似的需求, 在每天的某些时段, 机器执行复杂任务导致指标升高而触发报警, 希望这段时间是可以静默的

**Comment by 710leo** [comment]
v6 版本已支持
