### ISSUE TITLE
自动发现tsdb集群

### ISSUE THREAD

**Issue by IAOTW** [ccfos/nightingale#938]
**What would you like to be added**:
能否实现类似Prometheus的target那样，n9e-api可以自动发现tsdb集群，或加一个类似prometheus的reload接口，不用重启服务
**Why is this needed**:
目前在n9e-api中，tsdb集群相关的配置是写死的，自动发现tsdb的话则更灵活，或加一个reload接口，改完配置文件后可以不用重启服务

**Comment by UlricQin** [comment]
这个可以有，不过优先级较低，欢迎社区PR

**Comment by UlricQin** [comment]
陈旧issue批量close。数据源不会特别多，未有计划做此功能，如果实在太多，也可以考虑直接insert DB插入数据源。
