### ISSUE TITLE
监控大盘 关闭客户机鼠标无法正确显示

### ISSUE THREAD

**Issue by molixiaoge** [ccfos/nightingale#944]
**夜莺版本**:

    前端版本：5.3.0
    后端版本：5.7.0

**问题和复现方法**:

1台夜莺服务器，4台客户机，大盘监控内存鼠标是可以正常移动查看信息的。
但是关闭其中一台客户机后，大盘监控就无法查看后面的信息了，数据是有的，但是鼠标无法移动，卡在某个节点。

![图片](https://user-images.githubusercontent.com/1323533/168712802-d553a2bd-8494-44c7-ae43-de15ccab7939.png)

![图片](https://user-images.githubusercontent.com/1323533/168712854-fabf2a14-5cb4-42c0-9c76-3b00bb854a2e.png)

**Comment by molixiaoge** [comment]
浏览器使用的是火狐,使用chrome则没问题

**Comment by UlricQin** [comment]
n9e只针对chrome做了完全兼容，目前没有精力支持firefox
