### ISSUE TITLE
api接口备注和标签的统一更新

### ISSUE THREAD

**Issue by Ohimma** [ccfos/nightingale#947]
**What would you like to be added**:
1. api 删除 tags 只能完全匹配，可不可以模糊匹配 或 只提供key就行，或者可以支持修改key的值 
2. api  tags 和 notes 修改必须要调用两个url，可不可以支持一个PUT /targets 接口，可以批量update字段

**Why is this needed**:
目前想使用telegraf客户端，标签和备注通过cmdb获取，但是修改tags时只会增加，脚本获取不到上次的内容，也不好先删除之前的tag

**Comment by UlricQin** [comment]
从产品上看，可以做一个 PUT /v1/n9e/targets 接口，把tags、note给一并修改了，覆盖式修改，完全以传入的参数为准

**Comment by UlricQin** [comment]
陈旧需求关闭。

短期可以考虑直接更新DB。
