### ISSUE TITLE
告警抑制的支持

### ISSUE THREAD

**Issue by IAOTW** [ccfos/nightingale#956]
**What would you like to be added**:
例如这个：https://help.aliyun.com/document_detail/209508.htm?spm=a2c4g.11186623.0.0.18f35b78kuYkft#reference-2062585
**Why is this needed**:
例如网络异常时，会导致服务请求延迟过高或者核心链路服务异常，相关非核心服务也会产生异常。此时您最关注是快速处理严重度高、更核心的告警，其它告警延迟处理。为避免一次性发送所有告警通知，可以将它们抑制掉

**Comment by zero-element** [comment]
> 不会，我觉得这功能很鸡肋。远没有v5活跃告警的卡片聚合视图来得好用

但是对于告警通知而言，抑制还是很有价值的？底层故障可能会触发大量告警轰炸通知渠道，已有功能可以规避这个问题吗

**Comment by UlricQin** [comment]
> > 不会，我觉得这功能很鸡肋。远没有v5活跃告警的卡片聚合视图来得好用
> 
> 但是对于告警通知而言，抑制还是很有价值的？底层故障可能会触发大量告警轰炸通知渠道，已有功能可以规避这个问题吗

没有办法规避，底层的问题，影响了上层，上层的告警接收者收到告警我觉得挺好的，要不然，只是订阅上层告警的人，可能就不知道自己的服务出问题了
