### ISSUE TITLE
告警规则关闭“启用恢复通知”问题

### ISSUE THREAD

**Issue by Guwenqiang** [ccfos/nightingale#957]
**夜莺版本**:
前端版本：5.1.4
后端版本：5.4.0

**问题和复现方法**:
告警规则内关闭“启用恢复通知”
![image](https://user-images.githubusercontent.com/42791612/169803535-167abaa0-e951-4dd7-bf68-83d5e67243f7.png)
当前的活跃告警列表
![image](https://user-images.githubusercontent.com/42791612/169803675-4b1a7a46-9651-4282-a51c-c4b46494de03.png)
当前的历史告警列表
![image](https://user-images.githubusercontent.com/42791612/169803755-3f27b751-22f4-4e41-93b1-0c491ecdeab4.png)
alert_cur_event表数据
![image](https://user-images.githubusercontent.com/42791612/169819972-b15c3537-0543-489e-a559-7ab1f337e280.png)
![image](https://user-images.githubusercontent.com/42791612/169820006-22f90406-6429-4d90-89aa-24b44878cbd3.png)
PromQL查询了最近1h也没有数据返回，告警规则配置的是1m，说明告警规则已经恢复了，但为什么“活跃告警”控制台和对应表内还是有这个事件？如果我开启“启用恢复通知” 则一切正常
![image](https://user-images.githubusercontent.com/42791612/169820277-28de200e-92ce-486a-b7d0-28409d739bd7.png)

**Comment by UlricQin** [comment]
升级到最新版试试

**Comment by Guwenqiang** [comment]
升级新版本后问题得到解决，谢谢
