### ISSUE TITLE
server init fail: dialector() not supported 主程序无法通过docker-compose 部署

### ISSUE THREAD

**Issue by drscrewdriver** [ccfos/nightingale#970]
**夜莺版本**:
5.8.0

**问题和复现方法**:

docker-compose 启动不起来
报错 server init fail: dialector() not supported

**Comment by UlricQin** [comment]
拉取main分支上的代码试试，别用下载的tarball

git clone xxx
cd nightingale/docker
docker compose up -d

**Comment by JacZhoulang** [comment]
碰到同样的问题，不懂go，想用这个开源产品，最终楼主是怎么解决这个问题的呢？

**Comment by Coldfengzi** [comment]
> 碰到同样的问题，不懂go，想用这个开源产品，最终楼主是怎么解决这个问题的呢？

按文档操作不会有问题，自己docker-compose可能会出现，主要是配置文件中的etc目录在上一级，从git上复制下来，自己映射一下就好https://github.com/ccfos/nightingale/tree/main/etc
