### ISSUE TITLE
告警屏蔽能否细分下告警接收屏蔽和订阅接收屏蔽

### ISSUE THREAD

**Issue by AlbertCQY** [ccfos/nightingale#973]
告警接收组一般是运维人员，订阅接收组一般是开发/运营人员。当告警产生后，开发人员处理问题需要一段时间也有可能消极处理。运维人员需要跟踪并督促问题的解决。为防止运维人员疲于被告警打扰、告警麻木，需要对告警接收先屏蔽一段时间，但订阅接收告警不屏蔽。

**Comment by AlbertCQY** [comment]
尝试不设置告警项中的告警接收组。在订阅中分配告警接收组时发现没有选项选择所有标签，或者选择所有标签但排除某些标签。

**Comment by UlricQin** [comment]
屏蔽是针对事件屏蔽，不是针对接收者的屏蔽，上面的需求没有计划支持。你的需求实际是告警跟踪协同的需求，从系统边界角度来讲，这是一个通用需求，这类需求应该由一个单独的产品来处理，类似pagerduty这样的产品，同时对接夜莺、zabbix、cacti等多个监控系统。夜莺只要负责产出事件即可。不会做协同相关的事情
