### ISSUE TITLE
告警到飞书群机器人回调报错

### ISSUE THREAD

**Issue by Zhanben** [ccfos/nightingale#977]
**夜莺版本**:
v5.8.0

**问题和复现方法**
2022-06-09 15:45:10.151713 INFO engine/callback.go:39 event_callback(rule_id=1 url=https://open.feishu.cn/open-apis/bot/v2/hook/744d62b1-7471-4a07-9c28-a5bdd3b0000000) succ, resp: {"code":19002,"data":{},"msg":"params error, msg_type need"}, code: 200

**Comment by tanxiao1990** [comment]
飞书不是走callback（回调地址）配置，callback配置是针对ibex告警自愈或者其他自定义的第三方回调接口进行的调用。
建议你参考官方文档中的分享：
https://n9e.github.io/docs/prologue/share/   
https://mp.weixin.qq.com/s/ayVaQJ8mEacnyMkyqE_rJg

**Comment by tanxiao1990** [comment]
> **夜莺版本**: v5.8.0
> 
> **问题和复现方法** 2022-06-09 15:45:10.151713 INFO engine/callback.go:39 event_callback(rule_id=1 url=https://open.feishu.cn/open-apis/bot/v2/hook/744d62b1-7471-4a07-9c28-a5bdd3b0000000) succ, resp: {"code":19002,"data":{},"msg":"params error, msg_type need"}, code: 200


飞书不是走callback（回调地址）配置，callback配置是针对ibex告警自愈或者其他自定义的第三方回调接口进行的调用。
建议你参考官方文档中的分享，如何发送告警到钉钉机器人   发送到飞书与发送到钉钉是类似的。
https://n9e.github.io/docs/prologue/share/
https://mp.weixin.qq.com/s/ayVaQJ8mEacnyMkyqE_rJg

具体步骤大概有以下几步：
1、创建飞书相关用户，在更多联系方式的地方配置飞书机器人相关token
2、告警规则或订阅通知媒介选择飞书机器人
