### ISSUE TITLE
grafana大盘导入报错

### ISSUE THREAD

**Issue by GitHamburg** [ccfos/nightingale#979]
**夜莺版本**:
前端版本：5.5.0
后端版本：5.9.1

**问题和复现方法**:

1、kube-state-metrics-v2 https://grafana.com/grafana/dashboards/13332
导入报TypeError: undefined is not an object (evaluating 'a.thresholds.mode')

2、Kubernetes Pod Metrics https://grafana.com/grafana/dashboards/747   
Kubernetes / Kubelet https://grafana.com/grafana/dashboards/12123
可以导入，打开大盘空白，报错
Unhandled Promise Rejection: TypeError: undefined is not an object (evaluating 'e.match')

3、K8s / Storage / Volumes / Cluster https://grafana.com/grafana/dashboards/11454
K8s / Storage / Volumes / Namespace https://grafana.com/grafana/dashboards/11455
CoreDNS https://grafana.com/grafana/dashboards/5926
Kubernetes Deployment Statefulset Daemonset metrics https://grafana.com/grafana/dashboards/8588
很多控件不支持，大盘无法正常访问

**Comment by blankleee** [comment]
grafana里面的模板大盘涉及了很多变量需要手动去调整的，如果是n9e可以正常采集k8s的数据，手动建变量，建大盘就行了，虽然有点繁琐。

**Comment by jsers** [comment]
@blankleee 
https://github.com/n9e/fe-v5/releases/tag/v5.6.0
新版本修复了一些导入报错的问题
关于控件不支持问题现在的导入功能只能支持夜莺本身有的控件

**Comment by XiaoMuYi** [comment]
关于grafana模板导入到夜莺，控件不支持这块有什么规划么？

**Comment by jsers** [comment]
@XiaoMuYi 
grafana 的控件太多了，夜莺对这块的支持是一个持续漫长的过程，但是一些适合的控件未来版本肯定是会支持的
