### ISSUE TITLE
监控大盘刷新数据每次都不一致

### ISSUE THREAD

**Issue by blankleee** [ccfos/nightingale#980]
**夜莺版本**:
前端版本：5.4.0-ga.0
后端版本：5.8.0

**问题和复现方法**:
监控大盘5s刷新一次数据，但是图表每次展示的图都不一致。猜测是每次刷新取的时序点都不一致。
![2411ab6910b35a98e1bdeb70d1a09c1](https://user-images.githubusercontent.com/65880739/173560418-b710d2e6-ff43-4865-a31f-2d2de9f2819b.png)
![5355c022d93a6433df5810f8438be99](https://user-images.githubusercontent.com/65880739/173560441-c7827580-19b5-4d53-abcc-486edb6e69d0.png)
如图， 左边峰值一次是2.5刷新后一次是3

**Comment by UlricQin** [comment]
你这是看的多大区间的数据？夜莺其实没有对数据做处理，就是原封不动返回了 TSDB 的数据，夜莺只是一个 proxy

**Comment by blankleee** [comment]
> 你这是看的多大区间的数据？夜莺其实没有对数据做处理，就是原封不动返回了 TSDB 的数据，夜莺只是一个 proxy

一小时的区间，我看了下5分钟、15分钟的都挺正常的，一小时以后区间的变化比较大，整个图表都会变化。

**Comment by blankleee** [comment]
> > > 你这是看的多大区间的数据？夜莺其实没有对数据做处理，就是原封不动返回了 TSDB 的数据，夜莺只是一个 proxy
> > 
> > 
> > 一小时的区间，我看了下5分钟、15分钟的都挺正常的，一小时以后区间的变化比较大。
> 
> 这是prometheus的step的处理逻辑，可以百度一下，这个一两句话说不清楚，这个跟夜莺没关系，这个issue我就先关了

感觉跟step的关系不大，我看了一下prometheus的图确实是每次刷新取的时序点都不一样...比如这次是15、30、45。刷新之后就是16、31、46。我把图放到grafana里面就没有这种情况，估计grafana里面会做出图的数据处理，grafana里面的图看的舒服一点，每次刷新取的点都是一致的~建议你们可以优化一下这个点，现在测试的同学会反馈监控数据不准确 (笑哭

**Comment by UlricQin** [comment]
你说的15/30/45，是值时间戳，还是指值，我理解是时间戳？刷新之后，因为两次刷新动作间隔了1s，所以，时间戳就变成了16/31/46？

**Comment by blankleee** [comment]
> 你说的15/30/45，是时间戳，还是指值，我理解是时间戳？刷新之后，因为两次刷新动作间隔了1s，所以，时间戳就变成了16/31/46？

是时间戳，step=15时，15/30/45 刷新变成 16/31/46 这个取值我只是打个比方，实际上时间戳取值的变化应该是随机的，即下一次有可能是22、37、52。

**Comment by blankleee** [comment]
> 你说的15/30/45，是时间戳，还是指值，我理解是时间戳？刷新之后，因为两次刷新动作间隔了1s，所以，时间戳就变成了16/31/46？

我测试了一下，跟刷新的间隔没关系，每次刷新时间戳的取值好像都不一致

**Comment by UlricQin** [comment]
我知道了，每次不一样是必然的，因为每次都是获取的当前时间，即：把当前时间作为最后一个时间戳，其他时间依次做成15秒的间隔。

这个确实可以在前端做一个处理，就是根据step做一个对齐，查询的结束时间=当前时间戳-当前时间戳%step @jsers

**Comment by blankleee** [comment]
> 我知道了，每次不一样是必然的，因为每次都是获取的当前时间，即：把当前时间作为最后一个时间戳，其他时间依次做成15秒的间隔。
> 
> 这个确实可以在前端做一个处理，就是根据step做一个对齐，查询的结束时间=当前时间戳-当前时间戳%step @jsers

嗯，这样用户使用体验会比较好，虽然数据是没问题的，但是对于不知道的人来说会觉得数据不准确。（他们只会关心图上的数据

**Comment by jsers** [comment]
@blankleee 
新版本已修复
https://github.com/n9e/fe-v5/releases/tag/v5.6.0
