### ISSUE TITLE
支持快速屏蔽

### ISSUE THREAD

**Issue by bbaobelief** [ccfos/nightingale#981]
希望告警屏蔽支持url传参，通过请求url快速屏蔽监控
![image](https://user-images.githubusercontent.com/3918461/173777565-f4aeeb32-f1cb-4912-92a6-bda430acc6d5.png)

点击告警连接，可以快速屏蔽N分钟。
![image](https://user-images.githubusercontent.com/3918461/173777400-f4185728-a2ee-4c2d-9c12-506175568555.png)

**Comment by jsers** [comment]
v6 版本
可以参考告警事件快速屏蔽产生的链接
