### ISSUE TITLE
监控大盘手动刷新或自动刷新都会有报错

### ISSUE THREAD

**Issue by bangyongfeng** [ccfos/nightingale#982]
**夜莺版本**:
n9e-5.9.2

**问题和复现方法**:
安装了n9e-5.9.2后，导入监控大盘：linux_by_categraf 。手动刷新或自动刷新都会有报错。请帮忙排查下是什么问题导致的。

![图片](https://user-images.githubusercontent.com/38450169/173813667-b3747348-856c-45d5-b155-a7c05277d62e.png)

**Comment by bangyongfeng** [comment]
你好，我是用的管理员账户登陆的。目前用firefox 会有这个问题。360和chrome 没异常。
抓包如下：
![图片](https://user-images.githubusercontent.com/38450169/173974374-84a05435-e2a8-47aa-b5c0-d21dbeca2d1b.png)
![图片](https://user-images.githubusercontent.com/38450169/173974388-4902908e-9898-443e-9c7e-ec4d4729706b.png)

**Comment by jsers** [comment]
Firefox 会有这个报错，建议用 Chrome last 2 版本访问夜莺

bangyongfeng ***@***.***> 于2022年6月16日周四 09:54写道：

**Comment by bangyongfeng** [comment]
好的。非常感谢！
