### ISSUE TITLE
监控规则多集群生效

### ISSUE THREAD

**Issue by bbaobelief** [ccfos/nightingale#984]
希望生效集群这里支持**ALL**选项(或者**多选**)，后端支持1条监控规则覆盖多个集群
![image](https://user-images.githubusercontent.com/3918461/174218176-4ff0f876-7fc7-457f-9d0d-c0bf3c42c4a1.png)

**Comment by UlricQin** [comment]
新版已支持

**Comment by Ohimma** [comment]
是不是只需要在webapi.ini中增加Clusters，然后再web端生效集群选择all，就可以了。我这么操作了，但是感觉多集群没生效，是遗漏了哪的配置吗

**Comment by UlricQin** [comment]
每个时序库都要有对应的n9e-server，官方视频讲解了
