### ISSUE TITLE
k8s监控

### ISSUE THREAD

**Issue by liuflylove666** [ccfos/nightingale#985]
请问是否可以提供k8s的监控的最佳实践

**Comment by lsy1990** [comment]
分享下我目前的做法：
1.采用DS 部署，收集基础服务器指标，kubernetes 指标
2.采用Deployment 部署探针，收集kube_state_metrics ,重点来了，ident 一定用自定义，不要用ip hostname，因为这是一个集群指标，如果ident变化会导致kube_state_metrics 数据不稳定

**Comment by zxzixuanwang** [comment]
目前做法感觉就是，通过k8s 上一些业务指标 prometheus operator自动发现那一套来做，通过remote write 到victoriametrics。再者夜莺的基础监控存储也可以通过victoriametrics，将整套指标都存储在victoriametrics。指标查询通过victoriametrics，继而所有的告警规则就能统一配置了。

**Comment by a33151** [comment]
目前做法是 ：
1. 集群中部署 vmagent采集metrics 
2. remotewrite victormetrics.
3. 夜莺接入victormetrics

**Comment by UlricQin** [comment]
K8S监控已经具备了这个能力，Categraf可以直接拉取 `/metrics` 接口指标，也内嵌了prometheus agent mode代码支持服务发现，后面会在Flashcat的博客站点放出K8s监控手册：[https://flashcat.cloud/tags/kubernetes/](https://flashcat.cloud/tags/kubernetes/)

**Comment by K-free-N** [comment]
@zxzixuanwang 兄弟你好，我想问下这样做的话，夜莺上可以发现prometheus里自动发现的主机吗？
