### ISSUE TITLE
replace telegraf to categraf in docker_compose 

### ISSUE THREAD

**Issue by laiwei** [ccfos/nightingale#991]
**What would you like to be added**:

[There](https://github.com/ccfos/nightingale/blob/main/docker/docker-compose.yaml#L137) is still using telegraf as default collector, we should replace to categraf as same as https://github.com/flashcatcloud/n9e-helm

**Why is this needed**:

**Comment by tanxiao1990** [comment]
> **What would you like to be added**:
> 
> [There](https://github.com/ccfos/nightingale/blob/main/docker/docker-compose.yaml#L137) is still using telegraf as default collector, we should replace to categraf as same as https://github.com/flashcatcloud/n9e-helm
> 
> **Why is this needed**:

Hi, for this issue, I have submitted pr
你好，针对此问题，已提交相关PR。
