### ISSUE TITLE
监控大盘-下钻链接 支持传参

### ISSUE THREAD

**Issue by bbaobelief** [ccfos/nightingale#994]
**What would you like to be added**:
下钻链接 支持传参，比如传promql，ident等
**Why is this needed**:
**图1**是多个服务Goroutine汇总1条线，我希望通过下钻链接可以跳转到图3
![image](https://user-images.githubusercontent.com/3918461/175251921-477db6e3-055d-46a4-a614-adc58250ea89.png)

**图2**
![image](https://user-images.githubusercontent.com/3918461/175253114-4bd2afe9-8be0-440d-90f9-8b42acefd443.png)

**图3**可以携带参数生成详情图，展示多条线
![image](https://user-images.githubusercontent.com/3918461/175252336-79ad15b1-8915-4de4-b388-1498cf59c95c.png)

**Comment by UlricQin** [comment]
好想法，不过参数从哪里取呢？第一个图里，可能有多条线，每个线可能有多个标签

**Comment by bbaobelief** [comment]
> 好想法，不过参数从哪里取呢？第一个图里，可能有多条线，每个线可能有多个标签

只要下钻链接能配置参数，且支持变量就行
`http://n9e.com/chart/xxx?promql=event_gauge{ident=~"$ident", project="$project", event="runtime.NumGoroutine"}`

**Comment by UlricQin** [comment]
关键是变量从哪里取，从大盘变量？还是从图表里的series里

**Comment by bbaobelief** [comment]
或者可以支持查看大图自定义PromQL

小图查看总和，查看大图可以查看具体机器。

**Comment by 710leo** [comment]
@bbaobelief 这个需求 v6 版本里已支持哈
