### ISSUE TITLE
告警规则页面使用时发现的一个小问题

### ISSUE THREAD

**Issue by FengZh61** [ccfos/nightingale#996]
![image](https://user-images.githubusercontent.com/98309003/175472982-8d789d09-23cc-4777-b54f-c8b6e2a8968f.png)
刷新后第一次点击告警规则是这样，正常显示
![image](https://user-images.githubusercontent.com/98309003/175473166-257afc3e-70b0-41c4-a827-93a6501d10db.png)
再次点击就这样了
再切换别的菜单，再切换回来又恢复正常了。

**Comment by UlricQin** [comment]
版本是多少

**Comment by FengZh61** [comment]
> 版本是多少

前端版本：5.5.1
后端版本：5.9.2

**Comment by guguji5** [comment]
@FengZh61 收到，我们修改一下，感谢反馈

**Comment by guguji5** [comment]
@FengZh61 代码已提交，可以自己先build一个前端包用，不急的话可以等下一个release

**Comment by FengZh61** [comment]
> @FengZh61 代码已提交，可以自己先build一个前端包用，不急的话可以等下一个release

好的~辛苦
