### ISSUE TITLE
屏蔽规则运算符问题

### ISSUE THREAD

**Issue by Guwenqiang** [ccfos/nightingale#997]
前端版本：5.5.0
后端版本：5.8.0

某些情况下，比如有100个监控项，我希望屏蔽除__name__ = target_up外的所有告警，由于屏蔽规则运算符不支持!=，所以无法满足我的需求，请问可以考虑增加相关运算符吗？或者当前的版本，有其他方式可以实现我的需求吗？

**Comment by UlricQin** [comment]
当前版本有个正则方式 `=~` 想想有没有办法写个正则来表示这种情况，后面版本把 `!=` 加上

**Comment by Guwenqiang** [comment]
![image](https://user-images.githubusercontent.com/42791612/175495936-642e1fac-b7ee-4683-9523-71a4c7dc8dda.png)

**Comment by UlricQin** [comment]
已经额外支持了 `not in` `!~` `!=`
